import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_1a: [Question] = [
        .multipleChoice(
            id: "q1a_add_001",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Lisinopril is a -pril ACE inhibitor commonly used for hypertension and heart failure. Which brand name is associated with lisinopril?",
            options: ["Zestril/Prinivil", "Vasotec", "Altace", "Cozaar", "Diovan"],
            answer: "Zestril/Prinivil",
            explanation: "Lisinopril is marketed as Zestril/Prinivil. Learning the -pril class plus the brand name helps you recognize the same drug across different charts and question stems.",
            objective: .genericBrand,
            relatedDrugIds: ["d1"],
            tags: ["ACE Inhibitor", "brand", "Lisinopril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_002",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Zestril/Prinivil is a brand name for a first-line RAAS blocker used in hypertension. What is the generic name?",
            options: ["Lisinopril", "Enalapril", "Benazepril", "Losartan", "Olmesartan"],
            answer: "Lisinopril",
            explanation: "Zestril/Prinivil is lisinopril. Generic names stay consistent across settings, so anchoring the brand to the generic is high-yield.",
            objective: .brandGeneric,
            relatedDrugIds: ["d1"],
            tags: ["ACE Inhibitor", "generic", "Lisinopril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_003",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Enalapril is an ACE inhibitor (-pril) used for hypertension and heart failure. Which brand name matches enalapril?",
            options: ["Vasotec", "Lotensin", "Altace", "Benicar", "Avapro"],
            answer: "Vasotec",
            explanation: "Enalapril is sold as Vasotec. ACE inhibitors share class effects (cough, hyperkalemia, angioedema) and a pregnancy warning.",
            objective: .genericBrand,
            relatedDrugIds: ["d2"],
            tags: ["ACE Inhibitor", "brand", "Enalapril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_004",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Vasotec is the brand name of an ACE inhibitor often used in hypertension and heart failure. Which generic drug is Vasotec?",
            options: ["Enalapril", "Ramipril", "Lisinopril", "Valsartan", "Irbesartan"],
            answer: "Enalapril",
            explanation: "Vasotec = enalapril. Seeing a brand name should instantly trigger the class (-pril) and the shared monitoring needs (K+ and creatinine).",
            objective: .brandGeneric,
            relatedDrugIds: ["d2"],
            tags: ["ACE Inhibitor", "generic", "Enalapril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_005",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Ramipril is a -pril ACE inhibitor used for hypertension and sometimes cardiovascular risk reduction in high-risk patients. What is the brand name for ramipril?",
            options: ["Altace", "Vasotec", "Lotensin", "Diovan", "Cozaar"],
            answer: "Altace",
            explanation: "Ramipril is marketed as Altace. Many exam stems signal ramipril by mentioning both ACE inhibitor class and CV risk reduction.",
            objective: .genericBrand,
            relatedDrugIds: ["d3"],
            tags: ["ACE Inhibitor", "brand", "Ramipril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_006",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Altace is a brand-name ACE inhibitor used for hypertension and heart failure. What is the generic name for Altace?",
            options: ["Ramipril", "Benazepril", "Enalapril", "Losartan", "Olmesartan"],
            answer: "Ramipril",
            explanation: "Altace = ramipril. Remember: -pril drugs inhibit ACE, reducing angiotensin II and increasing bradykinin.",
            objective: .brandGeneric,
            relatedDrugIds: ["d3"],
            tags: ["ACE Inhibitor", "generic", "Ramipril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_007",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Benazepril is an ACE inhibitor frequently used to treat uncomplicated hypertension. Which brand name matches benazepril?",
            options: ["Lotensin", "Altace", "Vasotec", "Benicar", "Diovan"],
            answer: "Lotensin",
            explanation: "Benazepril = Lotensin. High-yield pearl: benazepril is also found in a fixed-dose combo with amlodipine (Lotrel).",
            objective: .genericBrand,
            relatedDrugIds: ["d4"],
            tags: ["ACE Inhibitor", "brand", "Benazepril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_008",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Lotensin is a brand-name ACE inhibitor. Which generic medication is sold as Lotensin?",
            options: ["Benazepril", "Lisinopril", "Ramipril", "Losartan", "Irbesartan"],
            answer: "Benazepril",
            explanation: "Lotensin = benazepril. ACE inhibitors are first-line for HTN, especially when renal protection is desired (proteinuria/diabetes).",
            objective: .brandGeneric,
            relatedDrugIds: ["d4"],
            tags: ["ACE Inhibitor", "generic", "Benazepril"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_009",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Losartan is an ARB (-sartan) that blocks the RAAS system and is commonly used for hypertension and diabetic nephropathy. What is the brand name for losartan?",
            options: ["Cozaar", "Diovan", "Avapro", "Benicar", "Lotensin"],
            answer: "Cozaar",
            explanation: "Losartan is marketed as Cozaar. ARBs share many benefits of ACE inhibitors but have much less bradykinin-related cough.",
            objective: .genericBrand,
            relatedDrugIds: ["d5"],
            tags: ["ARB", "brand", "Losartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_010",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Cozaar is a brand-name ARB used to treat hypertension. Which generic drug is Cozaar?",
            options: ["Losartan", "Valsartan", "Irbesartan", "Olmesartan", "Benazepril"],
            answer: "Losartan",
            explanation: "Cozaar = losartan. The -sartan suffix is your quick visual cue for the ARB class.",
            objective: .brandGeneric,
            relatedDrugIds: ["d5"],
            tags: ["ARB", "generic", "Losartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_011",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Valsartan is an ARB commonly used in hypertension and also in heart failure. Which brand name matches valsartan?",
            options: ["Diovan", "Cozaar", "Benicar", "Avapro", "Altace"],
            answer: "Diovan",
            explanation: "Valsartan = Diovan. Like other ARBs, it can increase potassium and creatinine, so labs matter after starting or titrating.",
            objective: .genericBrand,
            relatedDrugIds: ["d6"],
            tags: ["ARB", "brand", "Valsartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_012",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Diovan is a brand-name ARB used for hypertension and heart failure. What is the generic name for Diovan?",
            options: ["Valsartan", "Losartan", "Olmesartan", "Enalapril", "Benazepril"],
            answer: "Valsartan",
            explanation: "Diovan = valsartan. Seeing Diovan should prompt: ARB class, -sartan suffix, monitor potassium/creatinine.",
            objective: .brandGeneric,
            relatedDrugIds: ["d6"],
            tags: ["ARB", "generic", "Valsartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_013",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Irbesartan is an ARB often chosen for hypertension, especially when diabetic nephropathy is present. Which brand name matches irbesartan?",
            options: ["Avapro", "Benicar", "Cozaar", "Diovan", "Vasotec"],
            answer: "Avapro",
            explanation: "Irbesartan = Avapro. ARBs block angiotensin II signaling at the receptor, reducing vasoconstriction and aldosterone release.",
            objective: .genericBrand,
            relatedDrugIds: ["d7"],
            tags: ["ARB", "brand", "Irbesartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_014",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Avapro is the brand name for an ARB used to treat hypertension. Which generic drug is Avapro?",
            options: ["Irbesartan", "Olmesartan", "Valsartan", "Losartan", "Ramipril"],
            answer: "Irbesartan",
            explanation: "Avapro = irbesartan. Nephroprotection + BP control is the classic high-yield use for irbesartan.",
            objective: .brandGeneric,
            relatedDrugIds: ["d7"],
            tags: ["ARB", "generic", "Irbesartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_015",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Olmesartan is an ARB (-sartan) prescribed for hypertension. Which brand name matches olmesartan?",
            options: ["Benicar", "Avapro", "Diovan", "Cozaar", "Lotensin"],
            answer: "Benicar",
            explanation: "Olmesartan = Benicar. High-yield pearl: it has a rare but board-relevant adverse effect resembling malabsorption (sprue-like enteropathy).",
            objective: .genericBrand,
            relatedDrugIds: ["d8"],
            tags: ["ARB", "brand", "Olmesartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_016",
            subsectionId: "1a",
            difficulty: .easy,
            question: "Benicar is a brand-name ARB used for hypertension. What is the generic name for Benicar?",
            options: ["Olmesartan", "Irbesartan", "Valsartan", "Losartan", "Enalapril"],
            answer: "Olmesartan",
            explanation: "Benicar = olmesartan. The key class clue is the -sartan suffix and the shared monitoring (K+ and renal function).",
            objective: .brandGeneric,
            relatedDrugIds: ["d8"],
            tags: ["ARB", "generic", "Olmesartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_017",
            subsectionId: "1a",
            difficulty: .medium,
            question: "If you see a medication ending in -sartan (for example, losartan), what class is it AND what does it block?",
            options: ["ARB; blocks the angiotensin II (AT1) receptor", "ACE inhibitor; blocks conversion of angiotensin I to angiotensin II", "Beta blocker; blocks beta-1 receptors in the heart", "Thiazide diuretic; blocks the Na+/Cl- cotransporter in the DCT", "Calcium channel blocker; blocks L-type calcium channels"],
            answer: "ARB; blocks the angiotensin II (AT1) receptor",
            explanation: "The -sartan suffix identifies ARBs, which block angiotensin II signaling at the AT1 receptor. This decreases vasoconstriction and aldosterone release, lowering blood pressure.",
            objective: .classId,
            relatedDrugIds: ["d5"],
            tags: ["ARB", "mechanism", "suffix"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_018",
            subsectionId: "1a",
            difficulty: .medium,
            question: "ACE inhibitors such as lisinopril lower blood pressure by changing the RAAS system. Which option best describes their mechanism of action?",
            options: ["Inhibit ACE, decreasing angiotensin II and increasing bradykinin", "Block AT1 receptors to prevent angiotensin II binding", "Directly inhibit renin to prevent angiotensin I formation", "Block aldosterone receptors in the collecting duct", "Increase sodium excretion by blocking ENaC channels"],
            answer: "Inhibit ACE, decreasing angiotensin II and increasing bradykinin",
            explanation: "ACE inhibitors block angiotensin-converting enzyme, so angiotensin II falls and bradykinin rises. That bradykinin rise explains classic ACE-inhibitor cough and angioedema risk.",
            objective: .moa,
            relatedDrugIds: ["d1"],
            tags: ["ACE Inhibitor", "mechanism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_019",
            subsectionId: "1a",
            difficulty: .medium,
            question: "ARBs like valsartan and losartan lower blood pressure without increasing bradykinin. What is their primary target?",
            options: ["Angiotensin II type 1 (AT1) receptor", "Angiotensin-converting enzyme (ACE)", "Renin enzyme in the kidney", "Beta-2 receptor in the lungs", "L-type calcium channels in vascular smooth muscle"],
            answer: "Angiotensin II type 1 (AT1) receptor",
            explanation: "ARBs block angiotensin II from binding the AT1 receptor. Because they do not inhibit ACE, bradykinin does not build up (less cough than ACE inhibitors).",
            objective: .moa,
            relatedDrugIds: ["d6"],
            tags: ["ARB", "mechanism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_020",
            subsectionId: "1a",
            difficulty: .medium,
            question: "ACE is also called kininase II. When ACE is inhibited (for example with enalapril), levels of which peptide can rise and contribute to cough and angioedema?",
            options: ["Bradykinin", "Aldosterone", "Angiotensin II", "Epinephrine", "Vasopressin (ADH)"],
            answer: "Bradykinin",
            explanation: "ACE normally breaks down bradykinin. Blocking ACE increases bradykinin, which can cause a dry cough and, rarely, angioedema.",
            objective: .moa,
            relatedDrugIds: ["d2"],
            tags: ["ACE Inhibitor", "adverse effect", "bradykinin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_021",
            subsectionId: "1a",
            difficulty: .medium,
            question: "Both ACE inhibitors (-pril) and ARBs (-sartan) lower aldosterone. Which lab abnormality can occur with either class, especially if the patient is also taking potassium supplements?",
            options: ["Hyperkalemia", "Hypokalemia", "Hypernatremia", "Hypocalcemia", "Hypermagnesemia"],
            answer: "Hyperkalemia",
            explanation: "Less aldosterone means less potassium excretion in the collecting duct, so serum potassium can rise. This is a shared (ACEi + ARB) high-yield adverse effect.",
            objective: .adverseEffect,
            relatedDrugIds: ["d5"],
            tags: ["ACE Inhibitor", "ARB", "hyperkalemia"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_022",
            subsectionId: "1a",
            difficulty: .medium,
            question: "When starting or increasing the dose of a RAAS blocker like lisinopril or losartan, which monitoring plan is most important early on?",
            options: ["Check serum creatinine and potassium within 1-2 weeks", "Check INR weekly until stable", "Check liver enzymes (AST/ALT) every 48 hours", "Check thyroid function (TSH) every 2 weeks", "Check creatine kinase (CK) weekly"],
            answer: "Check serum creatinine and potassium within 1-2 weeks",
            explanation: "ACE inhibitors and ARBs can increase creatinine (via efferent arteriole dilation) and increase potassium (via lower aldosterone). Monitoring creatinine and potassium soon after initiation is the board-style safety step.",
            objective: .monitoring,
            relatedDrugIds: ["d1"],
            tags: ["monitoring", "ACE Inhibitor", "ARB"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_023",
            subsectionId: "1a",
            difficulty: .hard,
            question: "ACE inhibitors and ARBs carry a Black Box Warning for fetal toxicity. A patient discovers she is pregnant while taking valsartan. What is the best next step?",
            options: ["Stop valsartan promptly and switch to a pregnancy-safe antihypertensive", "Continue valsartan if blood pressure is controlled", "Increase the valsartan dose to prevent preeclampsia", "Add an ACE inhibitor for stronger RAAS blockade", "Hold valsartan only during the first trimester"],
            answer: "Stop valsartan promptly and switch to a pregnancy-safe antihypertensive",
            explanation: "RAAS blockers are contraindicated in pregnancy because they can cause fetal renal injury and oligohydramnios. The high-yield move is to discontinue as soon as pregnancy is detected.",
            objective: .contraindication,
            relatedDrugIds: ["d6"],
            tags: ["pregnancy", "black box", "ARB", "ACE Inhibitor"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_024",
            subsectionId: "1a",
            difficulty: .hard,
            question: "A patient with known bilateral renal artery stenosis needs hypertension treatment. Which option is most likely to cause an acute rise in creatinine by lowering intraglomerular pressure?",
            options: ["Lisinopril", "Amlodipine", "Hydrochlorothiazide", "Metoprolol", "Chlorthalidone"],
            answer: "Lisinopril",
            explanation: "ACE inhibitors (and ARBs) dilate the efferent arteriole, which can drop GFR in patients who depend on angiotensin II to maintain filtration pressure (classic example: bilateral renal artery stenosis).",
            objective: .contraindication,
            relatedDrugIds: ["d1"],
            tags: ["renal artery stenosis", "AKI risk", "ACE Inhibitor"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_025",
            subsectionId: "1a",
            difficulty: .medium,
            question: "ACE inhibitors and ARBs can slow progression of proteinuric kidney disease. Which renal hemodynamic change best explains the reduction in proteinuria?",
            options: ["Dilation of the efferent arteriole, lowering intraglomerular pressure", "Constriction of the afferent arteriole, lowering renal blood flow", "Increased aldosterone, increasing sodium retention", "Dilation of the afferent arteriole, raising intraglomerular pressure", "Direct blockade of sodium-glucose transport in the proximal tubule"],
            answer: "Dilation of the efferent arteriole, lowering intraglomerular pressure",
            explanation: "Angiotensin II preferentially constricts the efferent arteriole. Blocking RAAS dilates the efferent arteriole, decreasing intraglomerular pressure and reducing protein leakage (proteinuria).",
            objective: .moa,
            relatedDrugIds: ["d1"],
            tags: ["kidney", "proteinuria", "ACE Inhibitor", "ARB"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_026",
            subsectionId: "1a",
            difficulty: .medium,
            question: "A patient develops a nagging dry cough on an ACE inhibitor (a bradykinin effect). To maintain similar renal and blood-pressure benefits with a lower cough risk, which specific medication is the best substitute?",
            options: ["Losartan", "Enalapril", "Benazepril", "Ramipril", "Lisinopril"],
            answer: "Losartan",
            explanation: "Switching from an ACE inhibitor to an ARB (like losartan) preserves RAAS blockade while avoiding bradykinin accumulation, so cough is much less common.",
            objective: .indication,
            relatedDrugIds: ["d5"],
            tags: ["ARB", "ACE cough"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_027",
            subsectionId: "1a",
            difficulty: .hard,
            question: "ACE inhibitors (like ramipril) can rarely cause angioedema. Which symptom pattern should be treated as an emergency and requires immediate drug discontinuation?",
            options: ["Lip/tongue swelling with trouble breathing or swallowing", "Mild ankle swelling at the end of the day", "Occasional headache after the first dose", "Increased urination the first week of therapy", "Mild nausea after meals"],
            answer: "Lip/tongue swelling with trouble breathing or swallowing",
            explanation: "Angioedema is a potentially life-threatening airway emergency. If facial, lip, or tongue swelling occurs, stop the ACE inhibitor and seek urgent care.",
            objective: .adverseEffect,
            relatedDrugIds: ["d3"],
            tags: ["angioedema", "ACE Inhibitor"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_028",
            subsectionId: "1a",
            difficulty: .hard,
            question: "A student suggests combining an ACE inhibitor with an ARB for stronger blood-pressure control. Why is this generally avoided?",
            options: ["Higher risk of hyperkalemia and kidney injury without meaningful added benefit", "Because ARBs completely block bradykinin breakdown", "Because ACE inhibitors require IV administration when combined", "Because the combination causes severe hypokalemia", "Because ARBs become ineffective if taken with food"],
            answer: "Higher risk of hyperkalemia and kidney injury without meaningful added benefit",
            explanation: "Dual RAAS blockade (ACEi + ARB) increases adverse effects (hyperkalemia, hypotension, renal dysfunction) and is generally not recommended for routine use.",
            objective: .interaction,
            relatedDrugIds: ["d6"],
            tags: ["ACE Inhibitor", "ARB", "combination"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_029",
            subsectionId: "1a",
            difficulty: .hard,
            question: "A patient with heart failure is already taking spironolactone (a potassium-sparing diuretic). Adding lisinopril provides mortality benefit but increases the risk of which complication?",
            options: ["Hyperkalemia", "Hypokalemia", "Severe neutropenia", "QT prolongation", "Ototoxicity"],
            answer: "Hyperkalemia",
            explanation: "Spironolactone and ACE inhibitors both increase potassium (less aldosterone effect). Combining them is common in HF but requires careful potassium and renal monitoring.",
            objective: .interaction,
            relatedDrugIds: ["d1"],
            tags: ["hyperkalemia", "drug interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_030",
            subsectionId: "1a",
            difficulty: .hard,
            question: "A classic outpatient interaction is the 'triple whammy': ACE inhibitor or ARB + diuretic + NSAID. What is the major danger of this combination?",
            options: ["Acute kidney injury from reduced renal perfusion and altered arteriolar tone", "Severe hypoglycemia from increased insulin release", "Life-threatening hypercalcemia", "Irreversible hearing loss from ototoxicity", "Agranulocytosis from bone marrow suppression"],
            answer: "Acute kidney injury from reduced renal perfusion and altered arteriolar tone",
            explanation: "Diuretics lower volume, NSAIDs constrict the afferent arteriole, and ACEi/ARBs dilate the efferent arteriole. Together they can sharply reduce GFR and cause AKI.",
            objective: .interaction,
            relatedDrugIds: ["d5"],
            tags: ["AKI", "NSAID", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_031",
            subsectionId: "1a",
            difficulty: .hard,
            question: "ACE inhibitors and ARBs can raise lithium levels by decreasing renal lithium clearance. If a patient takes lithium and starts enalapril, what is the main risk?",
            options: ["Lithium toxicity (tremor, confusion, GI upset)", "Severe bleeding from elevated INR", "Serotonin syndrome", "Myasthenic crisis", "Torsades de pointes"],
            answer: "Lithium toxicity (tremor, confusion, GI upset)",
            explanation: "RAAS blockers can increase lithium concentrations. High yield: monitor lithium levels and watch for toxicity symptoms when starting or changing ACEi/ARB therapy.",
            objective: .interaction,
            relatedDrugIds: ["d2"],
            tags: ["lithium", "interaction", "ACE Inhibitor", "ARB"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_032",
            subsectionId: "1a",
            difficulty: .medium,
            question: "Enalapril has a high-yield formulation pearl: it is a prodrug converted to enalaprilat. What makes enalapril (Vasotec) stand out among many ACE inhibitors?",
            options: ["It has an IV form (enalaprilat) available for select situations", "It is the only ACE inhibitor safe in pregnancy", "It is a direct renin inhibitor rather than an ACE inhibitor", "It is primarily used to treat asthma", "It commonly causes hypokalemia"],
            answer: "It has an IV form (enalaprilat) available for select situations",
            explanation: "Enalapril is converted to enalaprilat, and enalaprilat can be given IV. This pearl helps you recognize enalapril in hospital/ED pharmacology contexts.",
            objective: .pearl,
            relatedDrugIds: ["d2"],
            tags: ["enalaprilat", "ACE Inhibitor", "formulation"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_033",
            subsectionId: "1a",
            difficulty: .medium,
            question: "Lotrel is a common fixed-dose combination used for hypertension that pairs a calcium channel blocker with an ACE inhibitor. Which ACE inhibitor is the one found in Lotrel?",
            options: ["Benazepril", "Enalapril", "Ramipril", "Lisinopril", "Valsartan"],
            answer: "Benazepril",
            explanation: "Lotrel = amlodipine + benazepril. Recognizing common combination products helps you quickly identify drug classes and anticipate shared adverse effects.",
            objective: .pearl,
            relatedDrugIds: ["d4"],
            tags: ["benazepril", "combination"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_034",
            subsectionId: "1a",
            difficulty: .medium,
            question: "Losartan has a unique clinical pearl compared with many other ARBs. What does its 'uricosuric effect' mean?",
            options: ["It can lower serum uric acid by increasing urate excretion", "It can raise serum uric acid by decreasing urate excretion", "It prevents uric acid stones by alkalinizing urine", "It directly inhibits xanthine oxidase", "It blocks urate reabsorption in the gut"],
            answer: "It can lower serum uric acid by increasing urate excretion",
            explanation: "Losartan can promote uric acid excretion (uricosuric), which can be a nice bonus in patients with hypertension plus gout or hyperuricemia.",
            objective: .pearl,
            relatedDrugIds: ["d5"],
            tags: ["losartan", "uric acid"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_035",
            subsectionId: "1a",
            difficulty: .medium,
            question: "A patient with type 2 diabetes has hypertension and albuminuria (diabetic nephropathy). Which ARB from this module is a common nephroprotective choice?",
            options: ["Irbesartan", "Olmesartan", "Valsartan", "Benazepril", "Amlodipine"],
            answer: "Irbesartan",
            explanation: "Irbesartan is a go-to ARB for hypertension with diabetic nephropathy because RAAS blockade lowers intraglomerular pressure and reduces proteinuria.",
            objective: .indication,
            relatedDrugIds: ["d7"],
            tags: ["diabetic nephropathy", "ARB"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_036",
            subsectionId: "1a",
            difficulty: .medium,
            question: "Valsartan is an ARB used to treat hypertension. It also has a high-yield cardiology indication beyond simple BP control. Which option best fits?",
            options: ["Heart failure with reduced ejection fraction (HFrEF)", "Acute bacterial pneumonia", "Atrial fibrillation rhythm conversion", "Migraine abortive therapy", "Benign prostatic hyperplasia"],
            answer: "Heart failure with reduced ejection fraction (HFrEF)",
            explanation: "Several RAAS blockers are core heart failure therapies. Valsartan is an ARB with a strong HF role (monitor for hypotension, hyperkalemia, and renal function changes).",
            objective: .indication,
            relatedDrugIds: ["d6"],
            tags: ["heart failure", "ARB"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_037",
            subsectionId: "1a",
            difficulty: .medium,
            question: "In your Top 300 list, one ACE inhibitor has a clinical pearl of 'cardiovascular risk reduction in high-risk patients' in addition to treating hypertension. Which drug is it?",
            options: ["Ramipril", "Benazepril", "Enalapril", "Olmesartan", "Irbesartan"],
            answer: "Ramipril",
            explanation: "Ramipril is the ACE inhibitor most classically linked to CV risk reduction pearls in high-risk patients. Remember it as an ACE inhibitor (-pril) with typical class monitoring (K+ and creatinine).",
            objective: .pearl,
            relatedDrugIds: ["d3"],
            tags: ["ramipril", "CV risk reduction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_038",
            subsectionId: "1a",
            difficulty: .hard,
            question: "A patient on olmesartan develops months of chronic diarrhea, weight loss, and negative infectious testing. You suspect ARB-associated sprue-like enteropathy. What is the best management step?",
            options: ["Discontinue olmesartan and choose a different antihypertensive", "Increase the olmesartan dose to overcome tolerance", "Add an ACE inhibitor to counteract the adverse effect", "Continue the drug and treat with antidiarrheals only", "Give broad-spectrum antibiotics for 14 days"],
            answer: "Discontinue olmesartan and choose a different antihypertensive",
            explanation: "Olmesartan can rarely cause sprue-like enteropathy. The high-yield fix is to stop the offending drug; symptoms typically improve after discontinuation.",
            objective: .adverseEffect,
            relatedDrugIds: ["d8"],
            tags: ["olmesartan", "enteropathy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_039",
            subsectionId: "1a",
            difficulty: .medium,
            question: "By reducing angiotensin II signaling, ACE inhibitors and ARBs decrease aldosterone. Which physiologic effect of lower aldosterone helps lower blood pressure?",
            options: ["Less sodium and water retention (more sodium excretion)", "More sodium and water retention (less sodium excretion)", "Direct relaxation of bronchial smooth muscle", "Direct blockade of cardiac sodium channels", "Increased secretion of insulin from pancreatic beta cells"],
            answer: "Less sodium and water retention (more sodium excretion)",
            explanation: "Aldosterone promotes sodium reabsorption (and potassium excretion). Lower aldosterone means less sodium/water retention, lowering volume and blood pressure.",
            objective: .moa,
            relatedDrugIds: ["d5"],
            tags: ["aldosterone", "RAAS", "mechanism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1a_add_040",
            subsectionId: "1a",
            difficulty: .medium,
            question: "A learner thinks switching from lisinopril to another ACE inhibitor (like benazepril) will eliminate the dry cough. Why is this strategy usually ineffective?",
            options: ["The cough is a class effect of ACE inhibition due to bradykinin, so another ACE inhibitor can still cause it", "Benazepril has a higher risk of cough because it is an ARB", "ACE inhibitor cough is caused by histamine release from mast cells", "The cough occurs only when the drug is taken at night", "Switching within the class always fixes the cough in most patients"],
            answer: "The cough is a class effect of ACE inhibition due to bradykinin, so another ACE inhibitor can still cause it",
            explanation: "ACE inhibitor cough is driven by bradykinin accumulation, a mechanism shared by the entire ACE inhibitor class. The usual fix is switching classes to an ARB.",
            objective: .adverseEffect,
            relatedDrugIds: ["d1"],
            tags: ["ACE Inhibitor", "class effect", "cough"],
            source: .curated
        )
    ]
}
