import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_10e: [Question] = [
        // MARK: - Latanoprost (d295) — first-line glaucoma
        .multipleChoice(id: "q10e_c_001", subsectionId: "10e", difficulty: .easy,
            question: "Xalatan is a prostaglandin analog used as first-line therapy for open-angle glaucoma. What is the generic name of Xalatan?",
            options: ["Latanoprost", "Bimatoprost", "Timolol", "Dorzolamide", "Brimonidine"],
            answer: "Latanoprost",
            explanation: "Xalatan is the brand name for latanoprost, a prostaglandin analog that lowers intraocular pressure.",
            objective: .brandGeneric, relatedDrugIds: ["d295"], tags: ["10e", "latanoprost", "brand->generic"]),
        .multipleChoice(id: "q10e_c_002", subsectionId: "10e", difficulty: .easy,
            question: "A patient needs to start first-line treatment for open-angle glaucoma with a once-daily eye drop at bedtime. Which class best describes latanoprost?",
            options: ["Prostaglandin analog", "Beta-blocker", "Carbonic anhydrase inhibitor", "Alpha-2 agonist", "Antihistamine"],
            answer: "Prostaglandin analog",
            explanation: "Latanoprost is a prostaglandin analog, the most commonly used first-line class for open-angle glaucoma.",
            objective: .classId, relatedDrugIds: ["d295"], tags: ["10e", "latanoprost", "class"]),
        .multipleChoice(id: "q10e_c_003", subsectionId: "10e", difficulty: .medium,
            question: "A patient using latanoprost asks why her brown eye seems to be getting darker. Which adverse effect is most likely?",
            options: ["Iris pigmentation change", "Corneal ulceration", "Severe bradycardia", "Orange-red urine", "Hearing loss"],
            answer: "Iris pigmentation change",
            explanation: "Latanoprost can cause permanent iris pigmentation change, especially in eyes with mixed-color irides.",
            objective: .adverseEffect, relatedDrugIds: ["d295"], tags: ["10e", "latanoprost", "iris-color"]),
        .multipleChoice(id: "q10e_c_004", subsectionId: "10e", difficulty: .medium,
            question: "When should latanoprost eye drops be administered for glaucoma?",
            options: ["Once daily in the evening", "Three times daily with meals", "Every 2 hours while awake", "Once weekly on Mondays", "Only when eye pressure feels high"],
            answer: "Once daily in the evening",
            explanation: "Latanoprost is used once daily in the evening for optimal IOP reduction.",
            objective: .dosing, relatedDrugIds: ["d295"], tags: ["10e", "latanoprost", "dosing"]),
        .multipleChoice(id: "q10e_c_005", subsectionId: "10e", difficulty: .medium,
            question: "Latanoprost lowers intraocular pressure primarily by which mechanism?",
            options: ["Increasing uveoscleral outflow of aqueous humor", "Blocking beta receptors to reduce aqueous production", "Inhibiting carbonic anhydrase in the ciliary body", "Constricting the pupil to open the trabecular meshwork", "Blocking histamine receptors in the conjunctiva"],
            answer: "Increasing uveoscleral outflow of aqueous humor",
            explanation: "Prostaglandin analogs like latanoprost lower IOP primarily by increasing uveoscleral outflow.",
            objective: .moa, relatedDrugIds: ["d295"], tags: ["10e", "latanoprost", "moa"]),

        // MARK: - Timolol ophthalmic (d298)
        .multipleChoice(id: "q10e_c_006", subsectionId: "10e", difficulty: .easy,
            question: "Timoptic is a beta-blocker eye drop used for glaucoma. What is the generic name of Timoptic?",
            options: ["Timolol", "Latanoprost", "Dorzolamide", "Brimonidine", "Bimatoprost"],
            answer: "Timolol",
            explanation: "Timoptic is the brand name for timolol ophthalmic solution.",
            objective: .brandGeneric, relatedDrugIds: ["d298"], tags: ["10e", "timolol", "brand->generic"]),
        .multipleChoice(id: "q10e_c_007", subsectionId: "10e", difficulty: .medium,
            question: "A patient with asthma is prescribed timolol eye drops for glaucoma. Why is this a concern?",
            options: ["Systemic absorption of timolol can cause bronchospasm", "Timolol turns tears orange-red", "Timolol causes permanent iris color change", "Timolol is contraindicated with all antibiotics", "Timolol only works in patients without lung disease"],
            answer: "Systemic absorption of timolol can cause bronchospasm",
            explanation: "Ophthalmic timolol can be absorbed systemically and cause bradycardia and bronchospasm, making it problematic in asthma and COPD.",
            objective: .contraindication, relatedDrugIds: ["d298"], tags: ["10e", "timolol", "asthma"]),
        .multipleChoice(id: "q10e_c_008", subsectionId: "10e", difficulty: .hard,
            question: "A glaucoma patient on timolol eye drops reports fatigue and a resting heart rate of 48 bpm. Which explanation is most likely?",
            options: ["Systemic absorption causing bradycardia", "Local allergic conjunctivitis", "Iris pigmentation change", "Carbonic anhydrase inhibition", "Pupil constriction reflex"],
            answer: "Systemic absorption causing bradycardia",
            explanation: "Timolol is a non-selective beta-blocker that can be absorbed systemically from eye drops and cause bradycardia.",
            objective: .adverseEffect, relatedDrugIds: ["d298"], tags: ["10e", "timolol", "bradycardia"]),

        // MARK: - Dorzolamide (d290) and Dorzolamide/Timolol (d291)
        .multipleChoice(id: "q10e_c_009", subsectionId: "10e", difficulty: .easy,
            question: "Trusopt is a carbonic anhydrase inhibitor eye drop. What is the generic name of Trusopt?",
            options: ["Dorzolamide", "Timolol", "Latanoprost", "Brimonidine", "Olopatadine"],
            answer: "Dorzolamide",
            explanation: "Trusopt is the brand name for dorzolamide ophthalmic solution.",
            objective: .brandGeneric, relatedDrugIds: ["d290"], tags: ["10e", "dorzolamide", "brand->generic"]),
        .multipleChoice(id: "q10e_c_010", subsectionId: "10e", difficulty: .medium,
            question: "A patient with a sulfonamide allergy asks about starting dorzolamide eye drops. Which concern is most accurate?",
            options: ["Dorzolamide is a sulfonamide derivative and caution is warranted", "Dorzolamide contains penicillin and should be avoided in penicillin allergy", "Sulfa allergy only matters for oral medications", "Dorzolamide is safe because it contains no sulfur atoms", "The allergy concern is only with timolol, not dorzolamide"],
            answer: "Dorzolamide is a sulfonamide derivative and caution is warranted",
            explanation: "Dorzolamide is a sulfonamide-derived carbonic anhydrase inhibitor, so caution is warranted in patients with sulfa allergy.",
            objective: .contraindication, relatedDrugIds: ["d290"], tags: ["10e", "dorzolamide", "sulfa"]),
        .multipleChoice(id: "q10e_c_011", subsectionId: "10e", difficulty: .easy,
            question: "Cosopt combines two glaucoma drugs in one eye drop. Which combination does Cosopt contain?",
            options: ["Dorzolamide/Timolol", "Latanoprost/Brimonidine", "Bimatoprost/Olopatadine", "Timolol/Latanoprost", "Dorzolamide/Brimonidine"],
            answer: "Dorzolamide/Timolol",
            explanation: "Cosopt is the brand name for the dorzolamide/timolol combination eye drop.",
            objective: .brandGeneric, relatedDrugIds: ["d291"], tags: ["10e", "cosopt", "brand->generic"]),

        // MARK: - Brimonidine (d284)
        .multipleChoice(id: "q10e_c_012", subsectionId: "10e", difficulty: .easy,
            question: "Alphagan is an alpha-2 agonist eye drop for glaucoma. What is the generic name of Alphagan?",
            options: ["Brimonidine", "Dorzolamide", "Timolol", "Latanoprost", "Ketotifen"],
            answer: "Brimonidine",
            explanation: "Alphagan is the brand name for brimonidine ophthalmic.",
            objective: .brandGeneric, relatedDrugIds: ["d284"], tags: ["10e", "brimonidine", "brand->generic"]),
        .multipleChoice(id: "q10e_c_013", subsectionId: "10e", difficulty: .medium,
            question: "Brimonidine lowers IOP by two mechanisms. Which pair is most accurate?",
            options: ["Reduces aqueous humor production and increases uveoscleral outflow", "Blocks beta receptors and inhibits carbonic anhydrase", "Constricts the pupil and increases trabecular outflow", "Stabilizes mast cells and blocks histamine", "Inhibits prostaglandin synthesis and blocks alpha-1 receptors"],
            answer: "Reduces aqueous humor production and increases uveoscleral outflow",
            explanation: "Brimonidine is an alpha-2 agonist that both decreases aqueous humor production and increases uveoscleral outflow.",
            objective: .moa, relatedDrugIds: ["d284"], tags: ["10e", "brimonidine", "moa"]),

        // MARK: - Bimatoprost (d283)
        .multipleChoice(id: "q10e_c_014", subsectionId: "10e", difficulty: .easy,
            question: "Lumigan is a prostaglandin analog for glaucoma that also has a cosmetic application. What is the generic name of Lumigan?",
            options: ["Bimatoprost", "Latanoprost", "Timolol", "Dorzolamide", "Brimonidine"],
            answer: "Bimatoprost",
            explanation: "Lumigan is the brand name for bimatoprost. The same drug is marketed as Latisse for eyelash growth.",
            objective: .brandGeneric, relatedDrugIds: ["d283"], tags: ["10e", "bimatoprost", "brand->generic"]),
        .multipleChoice(id: "q10e_c_015", subsectionId: "10e", difficulty: .hard,
            question: "A patient on bimatoprost for glaucoma notices longer, thicker eyelashes. Which pearl is most accurate?",
            options: ["Eyelash growth is a known effect of prostaglandin analogs and led to the cosmetic product Latisse", "This indicates an allergic reaction and the drug should be stopped", "This only happens with beta-blocker eye drops", "Eyelash growth means the drug is not lowering IOP", "This is a sign of sulfonamide cross-reactivity"],
            answer: "Eyelash growth is a known effect of prostaglandin analogs and led to the cosmetic product Latisse",
            explanation: "Prostaglandin analogs like bimatoprost commonly cause eyelash growth, which led to the development of Latisse.",
            objective: .pearl, relatedDrugIds: ["d283"], tags: ["10e", "bimatoprost", "eyelash"]),

        // MARK: - Epinephrine (d198)
        .multipleChoice(id: "q10e_c_016", subsectionId: "10e", difficulty: .easy,
            question: "EpiPen delivers epinephrine for life-threatening allergic reactions. What is the primary indication for an EpiPen?",
            options: ["Anaphylaxis", "Asthma maintenance", "Hypertension", "Bradycardia", "Glaucoma"],
            answer: "Anaphylaxis",
            explanation: "Epinephrine via EpiPen is the first-line treatment for anaphylaxis.",
            objective: .indication, relatedDrugIds: ["d198"], tags: ["10e", "epinephrine", "indication"]),
        .multipleChoice(id: "q10e_c_017", subsectionId: "10e", difficulty: .medium,
            question: "Where should an EpiPen be injected during anaphylaxis?",
            options: ["Outer mid-thigh (IM)", "Deltoid (subcutaneous)", "Intravenously in the antecubital fossa", "Intranasally", "Sublingually"],
            answer: "Outer mid-thigh (IM)",
            explanation: "Epinephrine for anaphylaxis is given IM in the outer mid-thigh for fastest absorption.",
            objective: .dosing, relatedDrugIds: ["d198"], tags: ["10e", "epinephrine", "im-thigh"]),
        .multipleChoice(id: "q10e_c_018", subsectionId: "10e", difficulty: .medium,
            question: "Which mechanism best explains why epinephrine reverses anaphylaxis?",
            options: ["Alpha-1 vasoconstriction plus beta-1 cardiac stimulation plus beta-2 bronchodilation", "Selective beta-2 bronchodilation only", "Muscarinic blockade reducing secretions", "Histamine receptor antagonism at H1 and H2", "Leukotriene receptor antagonism"],
            answer: "Alpha-1 vasoconstriction plus beta-1 cardiac stimulation plus beta-2 bronchodilation",
            explanation: "Epinephrine acts on multiple adrenergic receptors: alpha-1 for vasoconstriction, beta-1 for cardiac output, and beta-2 for bronchodilation.",
            objective: .moa, relatedDrugIds: ["d198"], tags: ["10e", "epinephrine", "moa"]),

        // MARK: - Atropine (d199)
        .multipleChoice(id: "q10e_c_019", subsectionId: "10e", difficulty: .easy,
            question: "Atropine is a classic anticholinergic used in ACLS. What is its primary emergency indication?",
            options: ["Symptomatic bradycardia", "Ventricular fibrillation", "Hypertensive emergency", "Anaphylaxis", "Status epilepticus"],
            answer: "Symptomatic bradycardia",
            explanation: "Atropine is first-line for symptomatic bradycardia in ACLS protocols.",
            objective: .indication, relatedDrugIds: ["d199"], tags: ["10e", "atropine", "indication"]),
        .multipleChoice(id: "q10e_c_020", subsectionId: "10e", difficulty: .medium,
            question: "A farmer exposed to an organophosphate insecticide presents with salivation, lacrimation, urination, and defecation (SLUDGE). Which drug is the antidote?",
            options: ["Atropine", "Epinephrine", "Flumazenil", "Naloxone", "Timolol"],
            answer: "Atropine",
            explanation: "Atropine blocks muscarinic receptors and is the classic antidote for organophosphate poisoning (cholinergic crisis).",
            objective: .pearl, relatedDrugIds: ["d199"], tags: ["10e", "atropine", "organophosphate"]),

        // MARK: - Flumazenil (d200)
        .multipleChoice(id: "q10e_c_021", subsectionId: "10e", difficulty: .easy,
            question: "Romazicon is the reversal agent for benzodiazepine overdose. What is the generic name of Romazicon?",
            options: ["Flumazenil", "Naloxone", "Atropine", "Epinephrine", "Protamine"],
            answer: "Flumazenil",
            explanation: "Romazicon is the brand name for flumazenil, a benzodiazepine antagonist.",
            objective: .brandGeneric, relatedDrugIds: ["d200"], tags: ["10e", "flumazenil", "brand->generic"]),
        .multipleChoice(id: "q10e_c_022", subsectionId: "10e", difficulty: .hard,
            question: "A patient with a history of chronic benzodiazepine use is found unresponsive. Why should flumazenil be used cautiously in this situation?",
            options: ["It can precipitate seizures in benzodiazepine-dependent patients", "It always causes permanent cognitive impairment", "It worsens opioid toxicity", "It is contraindicated in all overdose situations", "It only works for barbiturate overdose"],
            answer: "It can precipitate seizures in benzodiazepine-dependent patients",
            explanation: "Flumazenil can precipitate withdrawal seizures in patients who are dependent on benzodiazepines.",
            objective: .contraindication, relatedDrugIds: ["d200"], tags: ["10e", "flumazenil", "seizure-risk"]),

        // MARK: - Tretinoin (d299)
        .multipleChoice(id: "q10e_c_023", subsectionId: "10e", difficulty: .easy,
            question: "Retin-A is a topical retinoid commonly used for acne. What is the generic name of Retin-A?",
            options: ["Tretinoin", "Clobetasol", "Mupirocin", "Fluorouracil", "Hydroquinone"],
            answer: "Tretinoin",
            explanation: "Retin-A is the brand name for tretinoin, a topical retinoid.",
            objective: .brandGeneric, relatedDrugIds: ["d299"], tags: ["10e", "tretinoin", "brand->generic"]),
        .multipleChoice(id: "q10e_c_024", subsectionId: "10e", difficulty: .medium,
            question: "A patient starting tretinoin for acne asks about sun exposure. Which counseling point is most important?",
            options: ["Apply at bedtime and use sunscreen during the day because tretinoin increases photosensitivity", "Apply in the morning before sun exposure for maximum effect", "Tretinoin provides built-in UV protection", "Sun exposure is only a concern with oral retinoids", "Tretinoin should be applied over sunscreen"],
            answer: "Apply at bedtime and use sunscreen during the day because tretinoin increases photosensitivity",
            explanation: "Tretinoin increases photosensitivity, so it should be applied at bedtime and patients should use sunscreen.",
            objective: .pearl, relatedDrugIds: ["d299"], tags: ["10e", "tretinoin", "photosensitivity"]),
        .multipleChoice(id: "q10e_c_025", subsectionId: "10e", difficulty: .medium,
            question: "Which adverse effect is most expected when a patient first starts topical tretinoin?",
            options: ["Skin irritation, peeling, and dryness", "Orange-red urine", "Severe bradycardia", "Iris pigmentation change", "Weight gain"],
            answer: "Skin irritation, peeling, and dryness",
            explanation: "Initial skin irritation, peeling, and dryness are common when starting tretinoin and often improve with continued use.",
            objective: .adverseEffect, relatedDrugIds: ["d299"], tags: ["10e", "tretinoin", "irritation"]),

        // MARK: - Clobetasol (d288) and topical steroids
        .multipleChoice(id: "q10e_c_026", subsectionId: "10e", difficulty: .easy,
            question: "Temovate is the super-high potency topical steroid often reserved for thick plaques. What is the generic name of Temovate?",
            options: ["Clobetasol", "Betamethasone", "Triamcinolone", "Hydrocortisone", "Tretinoin"],
            answer: "Clobetasol",
            explanation: "Temovate is the brand name for clobetasol, a super-high potency topical corticosteroid.",
            objective: .brandGeneric, relatedDrugIds: ["d288"], tags: ["10e", "clobetasol", "brand->generic"]),
        .multipleChoice(id: "q10e_c_027", subsectionId: "10e", difficulty: .medium,
            question: "Why is clobetasol generally limited to 2 weeks of continuous use?",
            options: ["Prolonged use risks skin atrophy and HPA axis suppression", "It becomes an antibiotic after 2 weeks", "It causes permanent iris discoloration", "It loses all potency after 14 days", "It interacts with all oral medications after 2 weeks"],
            answer: "Prolonged use risks skin atrophy and HPA axis suppression",
            explanation: "Super-high potency topical steroids like clobetasol can cause skin atrophy, striae, and systemic HPA suppression with prolonged use.",
            objective: .adverseEffect, relatedDrugIds: ["d288"], tags: ["10e", "clobetasol", "atrophy"]),
        .multipleChoice(id: "q10e_c_028", subsectionId: "10e", difficulty: .hard,
            question: "A patient with facial eczema wants a stronger steroid. Which counseling point about clobetasol is most important?",
            options: ["Super-high potency steroids should generally be avoided on the face and intertriginous areas", "Clobetasol is specifically designed for facial use", "The face is the safest location for high-potency steroids", "Clobetasol is only available in IV form", "Apply it twice daily to the eyelids for best results"],
            answer: "Super-high potency steroids should generally be avoided on the face and intertriginous areas",
            explanation: "High-potency topical steroids are avoided on thin skin (face, axillae, groin) due to increased risk of atrophy and systemic absorption.",
            objective: .pearl, relatedDrugIds: ["d288", "d282"], tags: ["10e", "clobetasol", "face-avoidance"]),

        // MARK: - Triamcinolone topical (d300)
        .multipleChoice(id: "q10e_c_029", subsectionId: "10e", difficulty: .easy,
            question: "Kenalog is a medium-potency topical steroid also available as an injectable. What is the generic name of Kenalog?",
            options: ["Triamcinolone", "Clobetasol", "Betamethasone", "Tretinoin", "Mupirocin"],
            answer: "Triamcinolone",
            explanation: "Kenalog is the brand name for triamcinolone.",
            objective: .brandGeneric, relatedDrugIds: ["d300"], tags: ["10e", "triamcinolone", "brand->generic"]),

        // MARK: - Mupirocin (d296)
        .multipleChoice(id: "q10e_c_030", subsectionId: "10e", difficulty: .easy,
            question: "Bactroban is a topical antibiotic effective against MRSA. What is the generic name of Bactroban?",
            options: ["Mupirocin", "Tretinoin", "Clobetasol", "Fluorouracil", "Ciclopirox"],
            answer: "Mupirocin",
            explanation: "Bactroban is the brand name for mupirocin.",
            objective: .brandGeneric, relatedDrugIds: ["d296"], tags: ["10e", "mupirocin", "brand->generic"]),
        .multipleChoice(id: "q10e_c_031", subsectionId: "10e", difficulty: .medium,
            question: "Mupirocin nasal ointment is often used for which high-yield infection-control purpose?",
            options: ["MRSA nasal decolonization", "Treatment of otitis externa", "Glaucoma prophylaxis", "Acne vulgaris maintenance", "Fungal nail treatment"],
            answer: "MRSA nasal decolonization",
            explanation: "Mupirocin nasal ointment is a key tool for MRSA nasal decolonization in carriers.",
            objective: .indication, relatedDrugIds: ["d296"], tags: ["10e", "mupirocin", "mrsa-decolonization"]),

        // MARK: - Iron / Ferrous sulfate (d196)
        .multipleChoice(id: "q10e_c_032", subsectionId: "10e", difficulty: .easy,
            question: "A patient with iron deficiency anemia is started on ferrous sulfate. Which brand name matches this supplement?",
            options: ["Feosol", "Retin-A", "Lumigan", "Temovate", "Bactroban"],
            answer: "Feosol",
            explanation: "Feosol is a common brand for ferrous sulfate.",
            objective: .genericBrand, relatedDrugIds: ["d196"], tags: ["10e", "iron", "generic->brand"]),
        .multipleChoice(id: "q10e_c_033", subsectionId: "10e", difficulty: .medium,
            question: "Which counseling tip is most important for a patient starting oral iron supplementation?",
            options: ["Take on an empty stomach with vitamin C to enhance absorption", "Always take with calcium and antacids", "Take at bedtime with milk", "Avoid all citrus fruits while on iron", "Iron is best absorbed with coffee or tea"],
            answer: "Take on an empty stomach with vitamin C to enhance absorption",
            explanation: "Iron is best absorbed on an empty stomach, and vitamin C enhances absorption. Calcium, antacids, coffee, and tea reduce absorption.",
            objective: .pearl, relatedDrugIds: ["d196"], tags: ["10e", "iron", "vitamin-c"]),
        .multipleChoice(id: "q10e_c_034", subsectionId: "10e", difficulty: .medium,
            question: "A patient on ferrous sulfate reports constipation and dark stools. Which response is most accurate?",
            options: ["Both are common expected effects of oral iron therapy", "Dark stools always indicate GI bleeding and require urgent evaluation", "Constipation means the iron dose is too low", "These symptoms only occur with IV iron", "The patient should stop iron immediately"],
            answer: "Both are common expected effects of oral iron therapy",
            explanation: "Constipation and dark/black stools are classic adverse effects of oral iron supplementation.",
            objective: .adverseEffect, relatedDrugIds: ["d196"], tags: ["10e", "iron", "constipation"]),

        // MARK: - Vitamin D (d195)
        .multipleChoice(id: "q10e_c_035", subsectionId: "10e", difficulty: .easy,
            question: "Which form of vitamin D is generally preferred for supplementation?",
            options: ["D3 (cholecalciferol)", "D2 (ergocalciferol)", "D1 (lumisterol)", "D4 (dihydrositosterol)", "D5 (sitocalciferol)"],
            answer: "D3 (cholecalciferol)",
            explanation: "Vitamin D3 (cholecalciferol) is generally preferred over D2 because it is more effective at raising and maintaining serum 25(OH)D levels.",
            objective: .classId, relatedDrugIds: ["d195"], tags: ["10e", "vitamin-d", "d3"]),
        .multipleChoice(id: "q10e_c_036", subsectionId: "10e", difficulty: .medium,
            question: "What is the generally accepted target serum 25(OH)D level for vitamin D sufficiency?",
            options: [">30 ng/mL", ">10 ng/mL", ">100 ng/mL", ">5 ng/mL", ">200 ng/mL"],
            answer: ">30 ng/mL",
            explanation: "A serum 25(OH)D level above 30 ng/mL is generally considered sufficient.",
            objective: .monitoring, relatedDrugIds: ["d195"], tags: ["10e", "vitamin-d", "monitoring"]),

        // MARK: - Potassium chloride (d197)
        .multipleChoice(id: "q10e_c_037", subsectionId: "10e", difficulty: .easy,
            question: "K-Dur and Klor-Con are oral potassium supplements. What is the generic name?",
            options: ["Potassium chloride", "Calcium carbonate", "Magnesium oxide", "Sodium bicarbonate", "Ferrous sulfate"],
            answer: "Potassium chloride",
            explanation: "K-Dur and Klor-Con are brand names for potassium chloride.",
            objective: .brandGeneric, relatedDrugIds: ["d197"], tags: ["10e", "potassium", "brand->generic"]),
        .multipleChoice(id: "q10e_c_038", subsectionId: "10e", difficulty: .medium,
            question: "A patient on potassium chloride asks why she needs to take it with a full glass of water and food. Which explanation is best?",
            options: ["It can cause severe GI irritation and even ulceration if not properly diluted", "It only works when dissolved in water first", "Food converts potassium into a more active form", "Water prevents the tablet from being absorbed too quickly into bone", "This instruction only applies to IV potassium"],
            answer: "It can cause severe GI irritation and even ulceration if not properly diluted",
            explanation: "Oral potassium chloride can cause GI irritation, esophageal ulceration, and GI bleeding, so it should be taken with food and water.",
            objective: .adverseEffect, relatedDrugIds: ["d197"], tags: ["10e", "potassium", "gi-irritation"]),

        // MARK: - Fluorouracil topical (d292)
        .multipleChoice(id: "q10e_c_039", subsectionId: "10e", difficulty: .easy,
            question: "Efudex is a topical antineoplastic used for precancerous skin lesions. What is the generic name of Efudex?",
            options: ["Fluorouracil", "Tretinoin", "Clobetasol", "Mupirocin", "Hydroquinone"],
            answer: "Fluorouracil",
            explanation: "Efudex is the brand name for topical fluorouracil (5-FU).",
            objective: .brandGeneric, relatedDrugIds: ["d292"], tags: ["10e", "fluorouracil", "brand->generic"]),
        .multipleChoice(id: "q10e_c_040", subsectionId: "10e", difficulty: .medium,
            question: "A patient on topical fluorouracil for actinic keratoses says the treated skin is red, painful, and eroding. Should the drug be stopped?",
            options: ["This inflammatory reaction is expected and means the drug is working on the abnormal cells", "Yes, this always indicates a severe allergic reaction", "This proves the lesions are not actinic keratoses", "Only IV fluorouracil causes skin reactions", "The cream should be applied more thickly to prevent this"],
            answer: "This inflammatory reaction is expected and means the drug is working on the abnormal cells",
            explanation: "Topical fluorouracil causes an expected inflammatory reaction at treatment sites. Patients should be counseled that redness, erosion, and discomfort are expected.",
            objective: .pearl, relatedDrugIds: ["d292"], tags: ["10e", "fluorouracil", "expected-reaction"]),

        // MARK: - Ciclopirox (d286)
        .multipleChoice(id: "q10e_c_041", subsectionId: "10e", difficulty: .easy,
            question: "Penlac is a topical antifungal nail lacquer. What is the generic name of Penlac?",
            options: ["Ciclopirox", "Terbinafine", "Fluconazole", "Mupirocin", "Tretinoin"],
            answer: "Ciclopirox",
            explanation: "Penlac is the brand name for ciclopirox nail lacquer, used for onychomycosis.",
            objective: .brandGeneric, relatedDrugIds: ["d286"], tags: ["10e", "ciclopirox", "brand->generic"]),

        // MARK: - Olopatadine / Ketotifen ophthalmic (d297, d294)
        .multipleChoice(id: "q10e_c_042", subsectionId: "10e", difficulty: .easy,
            question: "Pataday is an OTC antihistamine eye drop for allergic conjunctivitis. What is the generic name of Pataday?",
            options: ["Olopatadine", "Ketotifen", "Latanoprost", "Timolol", "Dorzolamide"],
            answer: "Olopatadine",
            explanation: "Pataday is the brand name for olopatadine ophthalmic.",
            objective: .brandGeneric, relatedDrugIds: ["d297"], tags: ["10e", "olopatadine", "brand->generic"]),
        .multipleChoice(id: "q10e_c_043", subsectionId: "10e", difficulty: .medium,
            question: "Zaditor (ketotifen) is an OTC eye drop that has a dual mechanism. Which best describes it?",
            options: ["Antihistamine plus mast cell stabilizer", "Beta-blocker plus carbonic anhydrase inhibitor", "Prostaglandin analog plus alpha agonist", "Antibiotic plus corticosteroid", "Decongestant plus NSAID"],
            answer: "Antihistamine plus mast cell stabilizer",
            explanation: "Ketotifen has both antihistamine and mast cell stabilizing properties, making it useful for allergic conjunctivitis.",
            objective: .moa, relatedDrugIds: ["d294"], tags: ["10e", "ketotifen", "moa"]),

        // MARK: - Chlorhexidine (d285)
        .multipleChoice(id: "q10e_c_044", subsectionId: "10e", difficulty: .easy,
            question: "Hibiclens is a broad-spectrum antiseptic used for surgical skin prep. What is the generic name of Hibiclens?",
            options: ["Chlorhexidine", "Mupirocin", "Fluorouracil", "Ciclopirox", "Betamethasone"],
            answer: "Chlorhexidine",
            explanation: "Hibiclens is the brand name for chlorhexidine antiseptic.",
            objective: .brandGeneric, relatedDrugIds: ["d285"], tags: ["10e", "chlorhexidine", "brand->generic"]),
        .multipleChoice(id: "q10e_c_045", subsectionId: "10e", difficulty: .medium,
            question: "Which safety precaution is most important when using chlorhexidine for skin antisepsis?",
            options: ["Avoid contact with eyes and ears because it can cause serious injury", "It must be combined with alcohol to have any antimicrobial effect", "It should only be used on mucous membranes", "It is safe for direct application into the ear canal", "It is only effective against fungi, not bacteria"],
            answer: "Avoid contact with eyes and ears because it can cause serious injury",
            explanation: "Chlorhexidine can cause corneal damage if it enters the eyes and ototoxicity if it enters the middle ear.",
            objective: .adverseEffect, relatedDrugIds: ["d285"], tags: ["10e", "chlorhexidine", "eyes-ears"]),
    ]
}
