// PharmaLingo — Module 2a (Statins)
// Curated Add-On Question Pack (45 questions)
// IDs: q2a_add_001 ... q2a_add_045
//
// Integration options:
//
// Option A (recommended, clean diff):
// 1) Add this file to your project.
// 2) In DrugDataService.populateCuratedBank(_:), AFTER the existing `bank["2a"] = [...]` block,
//    append:
//
//    bank["2a"]?.append(contentsOf: Self.curatedAddOnQuestions_2a)
//
// Option B (quick paste):
// - Copy the questions inside the array below and paste them into the existing `bank["2a"] = [` array.
//
// Notes:
// - All questions are single-best-answer (5 choices each).
// - Stems are written to avoid exact duplicates of your current curated + generated templates.
// - Objectives + relatedDrugIds are set to improve spaced-repetition behavior.

import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_2a: [Question] = [
        .multipleChoice(
            id: "q2a_add_001",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Atorvastatin is a -statin HMG‑CoA reductase inhibitor commonly prescribed to lower LDL cholesterol and reduce ASCVD risk. Which brand name is associated with atorvastatin?",
            options: ["Lipitor", "Crestor", "Zocor", "Pravachol", "Mevacor"],
            answer: "Lipitor",
            explanation: "Atorvastatin is marketed as Lipitor. Pairing the class cue (-statin) with the brand name helps you recognize the same drug across prescriptions and exam stems.",
            objective: .genericBrand,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "brand", "Atorvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_002",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Lipitor is a brand-name statin used for hyperlipidemia and ASCVD prevention. What is the generic name for Lipitor?",
            options: ["Atorvastatin", "Rosuvastatin", "Simvastatin", "Pravastatin", "Lovastatin"],
            answer: "Atorvastatin",
            explanation: "Lipitor is the brand name for atorvastatin. On exams, “Lipitor” should immediately trigger “statin → LDL lowering → myalgia/LFT monitoring.”",
            objective: .brandGeneric,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "generic", "Atorvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_003",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Rosuvastatin is a high-potency -statin often used when significant LDL reduction is needed. Which brand name matches rosuvastatin?",
            options: ["Crestor", "Lipitor", "Zocor", "Pravachol", "Mevacor"],
            answer: "Crestor",
            explanation: "Rosuvastatin is sold as Crestor. Rosuvastatin is one of the two statins that can be dosed as high-intensity therapy (20–40 mg).",
            objective: .genericBrand,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "brand", "Rosuvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_004",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Crestor is a brand name for a high-potency statin used to lower LDL cholesterol. What is the generic name for Crestor?",
            options: ["Rosuvastatin", "Atorvastatin", "Simvastatin", "Pravastatin", "Lovastatin"],
            answer: "Rosuvastatin",
            explanation: "Crestor = rosuvastatin. Remember: statins work by inhibiting HMG‑CoA reductase, lowering cholesterol synthesis and upregulating LDL receptors.",
            objective: .brandGeneric,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "generic", "Rosuvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_005",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Simvastatin is a -statin used to treat hyperlipidemia. Which brand name is associated with simvastatin?",
            options: ["Zocor", "Crestor", "Lipitor", "Pravachol", "Mevacor"],
            answer: "Zocor",
            explanation: "Simvastatin is marketed as Zocor. Simvastatin has important interaction and dosing-limit pearls due to myopathy risk at higher doses.",
            objective: .genericBrand,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "brand", "Simvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_006",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Zocor is a brand-name statin used to lower LDL cholesterol. Which generic drug is Zocor?",
            options: ["Simvastatin", "Lovastatin", "Pravastatin", "Atorvastatin", "Rosuvastatin"],
            answer: "Simvastatin",
            explanation: "Zocor = simvastatin. This is a classic brand–generic pair worth memorizing because simvastatin has many CYP3A4 interaction pearls.",
            objective: .brandGeneric,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "generic", "Simvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_007",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Pravastatin is a -statin often favored when minimizing CYP-related drug interactions is important. What is the brand name for pravastatin?",
            options: ["Pravachol", "Mevacor", "Zocor", "Lipitor", "Crestor"],
            answer: "Pravachol",
            explanation: "Pravastatin is sold as Pravachol. A high-yield pearl is that pravastatin is not significantly metabolized by CYP3A4, so it tends to have fewer interactions.",
            objective: .genericBrand,
            relatedDrugIds: ["d30"],
            tags: ["Statin", "brand", "Pravastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_008",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Pravachol is a brand-name statin prescribed for hyperlipidemia. What is the generic name for Pravachol?",
            options: ["Pravastatin", "Simvastatin", "Lovastatin", "Atorvastatin", "Rosuvastatin"],
            answer: "Pravastatin",
            explanation: "Pravachol = pravastatin. When a patient is on multiple interacting drugs, pravastatin is often a go-to statin because it avoids CYP3A4 metabolism.",
            objective: .brandGeneric,
            relatedDrugIds: ["d30"],
            tags: ["Statin", "generic", "Pravastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_009",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Lovastatin was the first statin approved and is commonly taken with the evening meal. Which brand name matches lovastatin?",
            options: ["Mevacor", "Pravachol", "Zocor", "Crestor", "Lipitor"],
            answer: "Mevacor",
            explanation: "Lovastatin is marketed as Mevacor. High-yield dosing pearl: lovastatin is typically taken with the evening meal to improve absorption.",
            objective: .genericBrand,
            relatedDrugIds: ["d31"],
            tags: ["Statin", "brand", "Lovastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_010",
            subsectionId: "2a",
            difficulty: .easy,
            question: "Mevacor is a brand-name statin used for hyperlipidemia. Which generic medication is Mevacor?",
            options: ["Lovastatin", "Simvastatin", "Pravastatin", "Atorvastatin", "Rosuvastatin"],
            answer: "Lovastatin",
            explanation: "Mevacor = lovastatin. Lovastatin is a shorter half-life statin and is generally dosed in the evening (often with food).",
            objective: .brandGeneric,
            relatedDrugIds: ["d31"],
            tags: ["Statin", "generic", "Lovastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_011",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Statins like atorvastatin lower LDL cholesterol by inhibiting the rate‑limiting enzyme in hepatic cholesterol synthesis. Which enzyme do statins inhibit?",
            options: ["HMG‑CoA reductase", "NPC1L1 transporter", "PCSK9 enzyme", "HMG‑CoA synthase", "Lipoprotein lipase"],
            answer: "HMG‑CoA reductase",
            explanation: "Statins inhibit HMG‑CoA reductase (the rate‑limiting step in cholesterol synthesis). Less hepatic cholesterol → the liver upregulates LDL receptors → LDL levels fall.",
            objective: .moa,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "MOA", "LDL"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_012",
            subsectionId: "2a",
            difficulty: .hard,
            question: "HMG‑CoA reductase catalyzes a key step in cholesterol synthesis. Statins reduce cholesterol by blocking which conversion?",
            options: ["HMG‑CoA → mevalonate", "Cholesterol → bile acids", "LDL → HDL", "Triglycerides → free fatty acids", "Angiotensin I → angiotensin II"],
            answer: "HMG‑CoA → mevalonate",
            explanation: "HMG‑CoA reductase converts HMG‑CoA to mevalonate. Statins block this step, decreasing cholesterol synthesis and ultimately lowering LDL.",
            objective: .moa,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "MOA", "mevalonate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_013",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A key downstream effect of statins is increased clearance of LDL from the bloodstream. Statins accomplish this primarily by upregulating which receptor on hepatocytes?",
            options: ["LDL receptors", "Beta‑1 receptors", "AT1 receptors", "P2Y12 receptors", "H2 receptors"],
            answer: "LDL receptors",
            explanation: "When hepatic cholesterol synthesis drops, the liver responds by increasing LDL receptor expression, pulling more LDL out of circulation.",
            objective: .moa,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "MOA", "LDL receptors"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_014",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient is started on a statin for dyslipidemia. Which lipid parameter is statins' primary (largest) target for reduction?",
            options: ["LDL cholesterol", "HDL cholesterol", "Chylomicrons", "Lipoprotein(a) only", "Triglycerides (TG) only"],
            answer: "LDL cholesterol",
            explanation: "Statins are first-line for lowering LDL cholesterol. They can also modestly lower triglycerides and slightly raise HDL, but LDL reduction is the primary effect.",
            objective: .pearl,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "LDL", "lipids"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_015",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Beyond lowering LDL, statins typically have which overall effect on triglycerides (TG) and HDL?",
            options: ["Modest TG decrease and slight HDL increase", "Large TG increase and large HDL decrease", "No change in TG or HDL", "Large TG decrease and large HDL increase (primary effect)", "TG increase with HDL increase"],
            answer: "Modest TG decrease and slight HDL increase",
            explanation: "Statins primarily lower LDL, but they often modestly decrease triglycerides and slightly increase HDL. This is a helpful ‘big picture’ lipid pearl.",
            objective: .pearl,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "TG", "HDL"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_016",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Atorvastatin and rosuvastatin are commonly used as cornerstone therapy for reducing cardiovascular risk. Which is the most high-yield primary indication for statins as a class?",
            options: ["ASCVD risk reduction (primary/secondary prevention)", "Acute asthma exacerbation", "Chronic pain management", "H. pylori eradication", "Treatment of hyperthyroidism"],
            answer: "ASCVD risk reduction (primary/secondary prevention)",
            explanation: "Statins lower LDL and are foundational for ASCVD risk reduction. Remember the pairing: -statin → LDL down → fewer cardiovascular events over time.",
            objective: .indication,
            relatedDrugIds: ["d27", "d28"],
            tags: ["Statin", "ASCVD", "indication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_017",
            subsectionId: "2a",
            difficulty: .medium,
            question: "High-intensity statin therapy aims for substantial LDL reduction. Which atorvastatin dose range is considered high-intensity therapy?",
            options: ["40–80 mg daily", "5–10 mg daily", "10–20 mg daily", "1–2 mg daily", "200–400 mg daily"],
            answer: "40–80 mg daily",
            explanation: "High-intensity atorvastatin is 40–80 mg daily. High-yield pairing: atorvastatin 40–80 mg and rosuvastatin 20–40 mg are the classic high-intensity options.",
            objective: .dosing,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "high-intensity", "dosing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_018",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient is prescribed atorvastatin 80 mg daily after being found to have very high LDL. How is this regimen best classified?",
            options: ["High-intensity statin therapy", "Moderate-intensity statin therapy", "Low-intensity statin therapy", "Not a statin regimen", "A PCSK9 inhibitor regimen"],
            answer: "High-intensity statin therapy",
            explanation: "Atorvastatin 80 mg is high-intensity therapy. Clinically, high-intensity statins are used when large LDL reductions are desired (e.g., high ASCVD risk).",
            objective: .dosing,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "intensity", "atorvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_019",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A clinician chooses rosuvastatin 20 mg daily for aggressive LDL lowering. What intensity category does rosuvastatin 20 mg fall into?",
            options: ["High-intensity statin therapy", "Moderate-intensity statin therapy", "Low-intensity statin therapy", "Not recommended because it is under-dosed", "Equivalent to ezetimibe monotherapy"],
            answer: "High-intensity statin therapy",
            explanation: "Rosuvastatin 20–40 mg daily is considered high-intensity therapy. Knowing the two high-intensity statins (atorva, rosuva) is extremely high-yield.",
            objective: .dosing,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "intensity", "rosuvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_020",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Some statins are commonly dosed in the evening because hepatic cholesterol synthesis is highest at night and the drug has a shorter half-life. Which statin best fits this classic ‘bedtime dosing’ pearl?",
            options: ["Simvastatin", "Atorvastatin", "Rosuvastatin", "Ezetimibe", "Alirocumab"],
            answer: "Simvastatin",
            explanation: "Shorter half-life statins (classically simvastatin and lovastatin; often pravastatin too) are commonly taken in the evening to align with nighttime cholesterol synthesis.",
            objective: .dosing,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "dosing", "night"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_021",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient wants a statin they can take at any time of day (not necessarily at night). Which statin is commonly acceptable to dose any time due to its longer half-life?",
            options: ["Atorvastatin", "Lovastatin", "Simvastatin", "Pravastatin", "All statins must be taken strictly at bedtime"],
            answer: "Atorvastatin",
            explanation: "Atorvastatin (and also rosuvastatin) have longer half-lives, so timing is more flexible. Shorter half-life statins are often emphasized as ‘night dosing.’",
            objective: .dosing,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "dosing", "half-life"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_022",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Lovastatin has a classic administration pearl that improves absorption. How should lovastatin (Mevacor) typically be taken?",
            options: ["With the evening meal", "On an empty stomach in the morning", "Only as an IV infusion", "With grapefruit juice to increase efficacy", "Sublingually for rapid effect"],
            answer: "With the evening meal",
            explanation: "Lovastatin is commonly taken with the evening meal to improve absorption. Remember: ‘Mevacor with meal’ is a board-style dosing pearl.",
            objective: .dosing,
            relatedDrugIds: ["d31"],
            tags: ["Statin", "lovastatin", "administration"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_023",
            subsectionId: "2a",
            difficulty: .easy,
            question: "One statin is frequently emphasized as the most commonly prescribed in the U.S. for LDL lowering and ASCVD prevention. Which statin is often cited as the most prescribed?",
            options: ["Atorvastatin", "Lovastatin", "Pravastatin", "Simvastatin", "Rosuvastatin"],
            answer: "Atorvastatin",
            explanation: "Atorvastatin (Lipitor) is commonly noted as the most prescribed statin. It is also a standard high-intensity option at 40–80 mg.",
            objective: .pearl,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "pearl", "atorvastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_024",
            subsectionId: "2a",
            difficulty: .easy,
            question: "A classic historical pearl: which statin is often remembered as the first statin approved?",
            options: ["Lovastatin", "Rosuvastatin", "Atorvastatin", "Simvastatin", "Pravastatin"],
            answer: "Lovastatin",
            explanation: "Lovastatin (Mevacor) is commonly taught as the first approved statin. It also has the ‘take with evening meal’ administration pearl.",
            objective: .pearl,
            relatedDrugIds: ["d31"],
            tags: ["Statin", "pearl", "lovastatin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_025",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Simvastatin has a dosing-limit pearl driven by myopathy risk at higher doses. What is the commonly cited maximum routine daily dose for simvastatin in many teaching resources?",
            options: ["40 mg daily", "10 mg daily", "20 mg daily", "80 mg daily is routinely recommended", "200 mg daily"],
            answer: "40 mg daily",
            explanation: "Simvastatin is often taught with a ‘max 40 mg’ pearl because the risk of myopathy increases substantially at very high doses (notably 80 mg).",
            objective: .dosing,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "simvastatin", "safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_026",
            subsectionId: "2a",
            difficulty: .easy,
            question: "A patient on a statin reports diffuse muscle aches without significant weakness. What is the best name for this common statin-associated adverse effect?",
            options: ["Myalgia", "Tendinopathy", "Bronchospasm", "Nephrolithiasis", "Hyperkalemia"],
            answer: "Myalgia",
            explanation: "Statin-associated muscle aches are commonly described as myalgia. If symptoms are severe, clinicians evaluate for myopathy/rhabdomyolysis (often with CK).",
            objective: .adverseEffect,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "adverse effect", "myalgia"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_027",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient taking a statin develops severe muscle pain and notices dark ‘tea-colored’ urine. Which serious adverse effect is most concerning?",
            options: ["Rhabdomyolysis", "Stevens–Johnson syndrome", "Ototoxicity", "Serotonin syndrome", "Torsades de pointes"],
            answer: "Rhabdomyolysis",
            explanation: "Severe muscle symptoms plus dark urine raises concern for rhabdomyolysis (muscle breakdown), which can lead to acute kidney injury. Statin-associated rhabdo is rare but high-yield.",
            objective: .adverseEffect,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "rhabdomyolysis", "safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_028",
            subsectionId: "2a",
            difficulty: .medium,
            question: "When rhabdomyolysis or significant statin-associated myopathy is suspected, which lab test is the most direct marker of skeletal muscle injury?",
            options: ["Creatine kinase (CK)", "INR", "TSH", "Troponin", "Amylase"],
            answer: "Creatine kinase (CK)",
            explanation: "Creatine kinase (CK) rises with skeletal muscle injury and is a key lab when evaluating statin-associated myopathy/rhabdomyolysis.",
            objective: .monitoring,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "monitoring", "CK"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_029",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Statins can cause hepatotoxicity or elevated transaminases in some patients. Which lab is most appropriate to monitor for statin-related liver effects?",
            options: ["ALT/AST (liver transaminases)", "Serum potassium", "Absolute neutrophil count", "aPTT", "Serum lipase"],
            answer: "ALT/AST (liver transaminases)",
            explanation: "Statin safety monitoring often includes liver transaminases (ALT/AST), especially at baseline and if symptoms suggest liver injury.",
            objective: .monitoring,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "monitoring", "LFT"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_030",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient on a statin calls with new fatigue, dark urine, and yellowing of the eyes. These symptoms most strongly suggest which statin-related safety issue?",
            options: ["Possible hepatotoxicity (liver injury)", "ACE-inhibitor cough", "Ototoxicity", "Serotonin syndrome", "Nephrogenic diabetes insipidus"],
            answer: "Possible hepatotoxicity (liver injury)",
            explanation: "Jaundice (yellow eyes), dark urine, and fatigue can indicate liver injury. While uncommon, statin-associated hepatotoxicity is a high-yield safety concept tied to LFT monitoring.",
            objective: .adverseEffect,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "hepatotoxicity", "safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_031",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient newly discovers they are pregnant while taking a statin for hyperlipidemia. Which counseling point is the most high-yield for statins as a class?",
            options: ["Statins are generally avoided in pregnancy; contact the prescriber to stop/switch therapy", "Statins are first-line in pregnancy because LDL rises physiologically", "Increase the statin dose to protect the fetus from cholesterol", "Continue the statin but add grapefruit juice for better absorption", "Switch to warfarin because it is safer in pregnancy"],
            answer: "Statins are generally avoided in pregnancy; contact the prescriber to stop/switch therapy",
            explanation: "Statins are commonly taught as contraindicated/avoided in pregnancy. High-yield: if pregnancy occurs, the patient should contact the prescriber for an alternative plan.",
            objective: .contraindication,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "pregnancy", "contraindication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_032",
            subsectionId: "2a",
            difficulty: .medium,
            question: "Which clinical situation is a major contraindication or strong caution for initiating statin therapy due to safety concerns?",
            options: ["Active liver disease or acute hepatitis", "Seasonal allergies", "Controlled hypertension", "History of migraine headaches", "Myopia (nearsightedness)"],
            answer: "Active liver disease or acute hepatitis",
            explanation: "Because statins can affect liver enzymes, active liver disease/acute hepatitis is a key contraindication/caution scenario in many teaching frameworks.",
            objective: .contraindication,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "liver", "contraindication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_033",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient loves grapefruit juice and takes simvastatin daily. Why is this combination classically discouraged?",
            options: ["Grapefruit inhibits CYP3A4, increasing simvastatin levels and myopathy risk", "Grapefruit binds bile acids and makes the statin ineffective", "Grapefruit neutralizes stomach acid and destroys the statin", "Grapefruit causes hypokalemia with statins", "Grapefruit blocks LDL receptors directly"],
            answer: "Grapefruit inhibits CYP3A4, increasing simvastatin levels and myopathy risk",
            explanation: "Grapefruit juice can inhibit intestinal CYP3A4, raising levels of CYP3A4‑metabolized statins (notably simvastatin and lovastatin) and increasing myopathy risk.",
            objective: .interaction,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "interaction", "grapefruit"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_034",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient on a statin is prescribed clarithromycin for pneumonia. Which statin is most likely to require temporary holding or substitution due to a classic CYP3A4 interaction?",
            options: ["Simvastatin", "Pravastatin", "Rosuvastatin", "Ezetimibe", "Icosapent ethyl"],
            answer: "Simvastatin",
            explanation: "Clarithromycin is a CYP3A4 inhibitor. CYP3A4‑metabolized statins (especially simvastatin and lovastatin) can accumulate, increasing myopathy/rhabdomyolysis risk.",
            objective: .interaction,
            relatedDrugIds: ["d29"],
            tags: ["Statin", "interaction", "CYP3A4"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_035",
            subsectionId: "2a",
            difficulty: .hard,
            question: "Which add-on lipid medication is most classically avoided with statins because it significantly increases the risk of statin-associated myopathy/rhabdomyolysis?",
            options: ["Gemfibrozil", "Ezetimibe", "Icosapent ethyl", "Alirocumab", "Bile acid sequestrant"],
            answer: "Gemfibrozil",
            explanation: "Gemfibrozil has a well-known interaction with statins that raises the risk of myopathy/rhabdomyolysis. If a fibrate is needed with a statin, fenofibrate is often preferred.",
            objective: .interaction,
            relatedDrugIds: ["d27", "d29"],
            tags: ["Statin", "interaction", "myopathy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_036",
            subsectionId: "2a",
            difficulty: .hard,
            question: "If a fibrate must be used together with a statin (for mixed dyslipidemia), which fibrate is often preferred because it tends to have a lower myopathy interaction risk than gemfibrozil?",
            options: ["Fenofibrate", "Gemfibrozil", "Ezetimibe", "Alirocumab", "Evolocumab"],
            answer: "Fenofibrate",
            explanation: "Fenofibrate is commonly preferred over gemfibrozil when combined with a statin because gemfibrozil more strongly increases statin-associated myopathy risk.",
            objective: .interaction,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "interaction", "fibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_037",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient takes multiple medications that inhibit CYP3A4 and needs an LDL-lowering statin. Which statin is a high-yield choice because it is not significantly metabolized by CYP3A4?",
            options: ["Pravastatin", "Simvastatin", "Lovastatin", "Atorvastatin", "None—every statin is heavily metabolized by CYP3A4"],
            answer: "Pravastatin",
            explanation: "Pravastatin is a high-yield ‘low interaction’ statin because it is not significantly metabolized by CYP3A4. This makes it a common choice when interaction risk is high.",
            objective: .interaction,
            relatedDrugIds: ["d30"],
            tags: ["Statin", "pravastatin", "interactions"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_038",
            subsectionId: "2a",
            difficulty: .hard,
            question: "Which statin is most classically considered a CYP3A4 substrate and therefore prone to drug–drug interactions with strong CYP3A4 inhibitors?",
            options: ["Lovastatin", "Pravastatin", "Rosuvastatin", "Pitavastatin", "Fluvastatin"],
            answer: "Lovastatin",
            explanation: "Lovastatin (and simvastatin; atorvastatin to a degree) are classic CYP3A4 substrates. In contrast, pravastatin has minimal CYP3A4 metabolism and fewer interactions.",
            objective: .interaction,
            relatedDrugIds: ["d31"],
            tags: ["Statin", "CYP3A4", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_039",
            subsectionId: "2a",
            difficulty: .hard,
            question: "Some statins are described as more hydrophilic (water-soluble), which is a common teaching pearl. Which statin is classically considered more hydrophilic compared with simvastatin or lovastatin?",
            options: ["Pravastatin", "Lovastatin", "Simvastatin", "Atorvastatin", "All statins are equally hydrophilic"],
            answer: "Pravastatin",
            explanation: "Pravastatin is commonly taught as a more hydrophilic statin (along with rosuvastatin), whereas simvastatin and lovastatin are more lipophilic.",
            objective: .pearl,
            relatedDrugIds: ["d30"],
            tags: ["Statin", "hydrophilic", "pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_040",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A clinician wants to reduce the risk of statin-associated myopathy. Which untreated condition is a classic risk factor that should be corrected because it can worsen muscle symptoms on statins?",
            options: ["Hypothyroidism", "Seasonal allergic rhinitis", "Mild GERD", "Myopia", "Tension headaches"],
            answer: "Hypothyroidism",
            explanation: "Untreated hypothyroidism is a classic risk factor for statin-associated muscle symptoms. Correcting reversible risk factors is a practical safety pearl.",
            objective: .monitoring,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "myopathy", "risk factors"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_041",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient on a statin reports severe muscle pain and weakness that started after a dose increase. Which is the most appropriate next step in a safety-focused approach?",
            options: ["Hold the statin and check CK (evaluate for myopathy/rhabdomyolysis)", "Continue the statin and add a thiazide diuretic", "Double the statin dose to overcome tolerance", "Switch to an ACE inhibitor immediately", "Stop all food intake for 24 hours"],
            answer: "Hold the statin and check CK (evaluate for myopathy/rhabdomyolysis)",
            explanation: "Severe muscle symptoms raise concern for myopathy/rhabdomyolysis. A high-yield approach is to hold the statin and check CK (and assess for contributing interactions).",
            objective: .monitoring,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "safety", "CK"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_042",
            subsectionId: "2a",
            difficulty: .hard,
            question: "Certain drugs markedly raise statin levels and increase myopathy risk. Which immunosuppressant is a classic example that can increase statin toxicity and often requires careful statin selection/dosing?",
            options: ["Cyclosporine", "Metformin", "Amlodipine", "Hydrochlorothiazide", "Albuterol"],
            answer: "Cyclosporine",
            explanation: "Cyclosporine can raise statin exposure and increase myopathy risk. This is why ‘statin + strong interacting drug’ is a repeated safety theme.",
            objective: .interaction,
            relatedDrugIds: ["d30"],
            tags: ["Statin", "interaction", "myopathy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_043",
            subsectionId: "2a",
            difficulty: .medium,
            question: "A patient asks about long-term statin side effects. Beyond muscle symptoms and liver enzyme changes, which metabolic effect is a well-known class association (usually outweighed by CV benefit)?",
            options: ["Slight increase in blood glucose / diabetes risk", "Severe hypoglycemia", "Profound hyperkalemia", "Bronchospasm", "Permanent hearing loss"],
            answer: "Slight increase in blood glucose / diabetes risk",
            explanation: "Statins have been associated with a small increase in blood glucose and diabetes risk. Clinically, the cardiovascular benefit typically outweighs this risk in indicated patients.",
            objective: .adverseEffect,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "diabetes", "adverse effect"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_044",
            subsectionId: "2a",
            difficulty: .hard,
            question: "A patient cannot tolerate statins and asks about an oral alternative that lowers LDL by blocking intestinal cholesterol absorption (not by inhibiting HMG‑CoA reductase). Which drug fits this mechanism?",
            options: ["Ezetimibe", "Gemfibrozil", "Alirocumab", "Evolocumab", "Icosapent ethyl"],
            answer: "Ezetimibe",
            explanation: "Ezetimibe lowers LDL by blocking intestinal cholesterol absorption (NPC1L1). This contrasts with statins, which inhibit HMG‑CoA reductase in the liver.",
            objective: .moa,
            relatedDrugIds: ["d27"],
            tags: ["Statin", "comparison", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2a_add_045",
            subsectionId: "2a",
            difficulty: .easy,
            question: "You see a new medication named “rosuvastatin” on a patient’s med list. Based on the suffix, what drug class and primary therapeutic goal should you immediately think of?",
            options: ["Statin; lower LDL cholesterol", "ACE inhibitor; treat cough", "ARB; treat asthma", "Loop diuretic; treat bradycardia", "P2Y12 inhibitor; thin the blood"],
            answer: "Statin; lower LDL cholesterol",
            explanation: "The -statin suffix identifies HMG‑CoA reductase inhibitors. The high-yield association is LDL lowering and ASCVD risk reduction.",
            objective: .suffixId,
            relatedDrugIds: ["d28"],
            tags: ["Statin", "suffix", "LDL"],
            source: .curated
        ),
    ]
}