// PharmaLingo — Module 1d (MRAs & ARNI)
// Curated Add-On Question Pack (40 questions)
// IDs: q1d_add_001 ... q1d_add_040
//
// Integration options:
//
// Option A (recommended, clean diff):
// 1) Add this file to your project.
// 2) In DrugDataService.populateCuratedBank(_:), AFTER the existing `bank["1d"] = [...]` block,
//    append:
//
//    bank["1d"]?.append(contentsOf: Self.curatedAddOnQuestions_1d)
//
// Option B (quick paste):
// - Copy the questions inside the array below and paste them into the existing `bank["1d"] = [` array.
//
// Notes:
// - All questions are single-best-answer (5 choices each).
// - Stems are written to avoid exact duplicates of your existing curated bank.
// - Objectives + relatedDrugIds are set to improve spaced-repetition behavior.

import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_1d: [Question] = [

        .multipleChoice(
            id: "q1d_add_001",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Spironolactone is a mineralocorticoid receptor antagonist (MRA) used for HFrEF, resistant hypertension, and ascites, and it can cause hyperkalemia. What is the brand name for spironolactone?",
            options: ["Aldactone", "Inspra", "Entresto", "Demadex", "Diovan"],
            answer: "Aldactone",
            explanation: "Spironolactone is marketed as Aldactone. It is an MRA (aldosterone antagonist) that is potassium-sparing, so monitoring potassium and renal function is a key safety step.",
            objective: .genericBrand,
            relatedDrugIds: ["d20"],
            tags: ["MRA", "brand", "Spironolactone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_002",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Aldactone is a potassium-sparing diuretic that blocks aldosterone (a mineralocorticoid) receptors. Aldactone contains which generic medication?",
            options: ["Spironolactone", "Eplerenone", "Sacubitril/valsartan", "Furosemide", "Losartan"],
            answer: "Spironolactone",
            explanation: "Aldactone is the brand name for spironolactone. Spironolactone is less selective than eplerenone and can cause endocrine side effects due to off-target hormone receptor effects.",
            objective: .brandGeneric,
            relatedDrugIds: ["d20"],
            tags: ["MRA", "generic", "Aldactone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_003",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Eplerenone is a more selective mineralocorticoid receptor antagonist (MRA) used for heart failure and hypertension and is less likely than spironolactone to cause sex-hormone related side effects. What is the brand name for eplerenone?",
            options: ["Inspra", "Aldactone", "Entresto", "Thalitone", "Coreg"],
            answer: "Inspra",
            explanation: "Eplerenone is marketed as Inspra. It is an aldosterone antagonist that spares potassium, so hyperkalemia is still a major monitoring concern.",
            objective: .genericBrand,
            relatedDrugIds: ["d21"],
            tags: ["MRA", "brand", "Eplerenone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_004",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Inspra is a potassium-sparing diuretic used in heart failure and hypertension that works by antagonizing aldosterone receptors. Inspra contains which generic medication?",
            options: ["Eplerenone", "Spironolactone", "Sacubitril/valsartan", "Hydrochlorothiazide", "Metoprolol succinate"],
            answer: "Eplerenone",
            explanation: "Inspra is the brand name for eplerenone. Compared with spironolactone, eplerenone is more selective for the mineralocorticoid receptor and has fewer anti-androgen effects.",
            objective: .brandGeneric,
            relatedDrugIds: ["d21"],
            tags: ["MRA", "generic", "Inspra"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_005",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Sacubitril/valsartan is an ARNI (angiotensin receptor–neprilysin inhibitor) used for chronic HFrEF to improve outcomes by enhancing natriuretic peptides while also blocking the RAAS pathway. What is the brand name for sacubitril/valsartan?",
            options: ["Entresto", "Diovan", "Cozaar", "Altace", "Norvasc"],
            answer: "Entresto",
            explanation: "Sacubitril/valsartan is marketed as Entresto. It combines neprilysin inhibition (sacubitril) with an ARB (valsartan), improving natriuresis and reducing RAAS-driven vasoconstriction/aldosterone.",
            objective: .genericBrand,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "brand", "Sacubitril/valsartan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_006",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Entresto is a guideline-directed medication for chronic HFrEF that combines neprilysin inhibition with angiotensin II receptor blockade. Entresto contains which generic medication?",
            options: ["Sacubitril/valsartan", "Spironolactone", "Eplerenone", "Valsartan alone", "Benazepril/amlodipine"],
            answer: "Sacubitril/valsartan",
            explanation: "Entresto contains the fixed-dose combination sacubitril/valsartan. It is not just valsartan; sacubitril adds neprilysin inhibition to increase endogenous natriuretic peptides.",
            objective: .brandGeneric,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "generic", "Entresto"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_007",
            subsectionId: "1d",
            difficulty: .easy,
            question: "You’re reviewing heart-failure drug classes and see the term ARNI (angiotensin receptor–neprilysin inhibitor). Which medication in this subsection is an ARNI?",
            options: ["Entresto (sacubitril/valsartan)", "Inspra (eplerenone)", "Aldactone (spironolactone)", "Lasix (furosemide)", "Zestril (lisinopril)"],
            answer: "Entresto (sacubitril/valsartan)",
            explanation: "ARNI refers to a combo of a neprilysin inhibitor plus an ARB. In this subsection, Entresto is sacubitril/valsartan (ARNI). Spironolactone and eplerenone are MRAs (aldosterone antagonists).",
            objective: .classId,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "class", "HFrEF"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_008",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Mineralocorticoid receptor antagonists (MRAs) are potassium-sparing diuretics used in HFrEF and resistant hypertension. Which medication is an MRA?",
            options: ["Spironolactone", "Sacubitril/valsartan", "Amlodipine", "Torsemide", "Metoprolol tartrate"],
            answer: "Spironolactone",
            explanation: "Spironolactone (Aldactone) is an MRA (aldosterone antagonist). MRAs act in the collecting duct to counter aldosterone, leading to sodium loss and potassium retention.",
            objective: .classId,
            relatedDrugIds: ["d20"],
            tags: ["MRA", "class", "Potassium-sparing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_009",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Spironolactone and eplerenone are MRAs that work as potassium-sparing diuretics. Where in the nephron do MRAs primarily exert their diuretic effect?",
            options: ["Collecting duct (late distal tubule)", "Proximal convoluted tubule", "Thick ascending loop of Henle", "Distal convoluted tubule (early)", "Glomerulus"],
            answer: "Collecting duct (late distal tubule)",
            explanation: "MRAs antagonize aldosterone receptors in the late distal tubule/collecting duct. Aldosterone normally increases sodium reabsorption and potassium (and hydrogen) secretion; blocking it promotes mild diuresis and potassium retention.",
            objective: .moa,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "MOA", "Site of action"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_010",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A key safety issue with MRAs (spironolactone, eplerenone) is their effect on electrolytes. Blocking aldosterone in the collecting duct most directly causes which electrolyte change?",
            options: ["Increased serum potassium", "Decreased serum potassium", "Increased serum calcium", "Decreased serum calcium", "Increased serum sodium"],
            answer: "Increased serum potassium",
            explanation: "Aldosterone promotes potassium excretion. MRAs block aldosterone’s action, decreasing potassium secretion into urine and raising the risk of hyperkalemia (especially with CKD or other RAAS blockers).",
            objective: .adverseEffect,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "hyperkalemia", "Electrolytes"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_011",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Aldosterone normally increases sodium reabsorption in principal cells by upregulating epithelial sodium channels (ENaC). MRAs oppose this effect. What is the net renal effect of spironolactone therapy?",
            options: ["Decreased sodium reabsorption with decreased potassium excretion", "Decreased sodium reabsorption with increased potassium excretion", "Increased sodium reabsorption with decreased potassium excretion", "Increased sodium reabsorption with increased potassium excretion", "No change in sodium handling"],
            answer: "Decreased sodium reabsorption with decreased potassium excretion",
            explanation: "By blocking aldosterone, MRAs reduce sodium reabsorption (mild diuresis) and reduce potassium excretion (potassium-sparing), creating a hyperkalemia risk.",
            objective: .moa,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "MOA", "ENaC"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_012",
            subsectionId: "1d",
            difficulty: .hard,
            question: "Because aldosterone promotes both potassium and hydrogen ion secretion in the collecting duct, MRAs can contribute to which acid–base disturbance, especially in patients with kidney disease?",
            options: ["Hyperkalemic metabolic acidosis (type 4 RTA pattern)", "Metabolic alkalosis due to hydrogen loss", "High anion gap metabolic acidosis", "Respiratory alkalosis", "Respiratory acidosis"],
            answer: "Hyperkalemic metabolic acidosis (type 4 RTA pattern)",
            explanation: "Blocking aldosterone decreases hydrogen and potassium secretion in the collecting duct, which can produce a type 4 renal tubular acidosis pattern: hyperkalemia with a mild non–anion gap metabolic acidosis.",
            objective: .pearl,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "Acid-base", "Type 4 RTA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_013",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Spironolactone is an MRA used for heart failure and resistant hypertension, but it is less receptor-selective than eplerenone. Which adverse effect is most consistent with spironolactone’s off-target sex hormone receptor effects?",
            options: ["Menstrual irregularities or decreased libido", "Ototoxicity", "Cough from bradykinin buildup", "Gingival hyperplasia", "Severe hypocalcemia"],
            answer: "Menstrual irregularities or decreased libido",
            explanation: "Spironolactone can interact with androgen and progesterone receptors, leading to endocrine side effects such as menstrual irregularities, decreased libido, impotence, and breast tenderness. Eplerenone is more selective and usually causes fewer endocrine effects.",
            objective: .adverseEffect,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "adverse effects", "Endocrine"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_014",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A patient benefits from aldosterone blockade for HFrEF but reports breast tenderness and sexual side effects after starting spironolactone. Which alternative in this subsection provides aldosterone antagonism with fewer sex-hormone related adverse effects?",
            options: ["Eplerenone", "Sacubitril/valsartan", "Furosemide", "Hydrochlorothiazide", "Amlodipine"],
            answer: "Eplerenone",
            explanation: "Eplerenone is a more selective mineralocorticoid receptor antagonist than spironolactone, so it generally causes fewer anti-androgen/progestin-related adverse effects while still carrying hyperkalemia risk.",
            objective: .pearl,
            relatedDrugIds: ["d21"],
            tags: ["Eplerenone", "selectivity", "Endocrine effects"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_015",
            subsectionId: "1d",
            difficulty: .easy,
            question: "MRAs are potassium-sparing and can worsen renal function when combined with other RAAS blockers. Which monitoring plan is most high-yield after starting spironolactone or eplerenone?",
            options: ["Check serum potassium and serum creatinine", "Check INR and aPTT", "Check AST/ALT only", "Check calcium and phosphate only", "Check TSH and free T4"],
            answer: "Check serum potassium and serum creatinine",
            explanation: "The two must-know monitoring items for MRAs are potassium (hyperkalemia risk) and renal function (serum creatinine/BUN).",
            objective: .monitoring,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "monitoring", "BMP"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_016",
            subsectionId: "1d",
            difficulty: .easy,
            question: "A patient starting Aldactone for resistant hypertension asks about using a potassium-containing salt substitute. Which safety concern is most important to counsel on?",
            options: ["Dangerous hyperkalemia", "Severe hypokalemia", "Ototoxicity", "Severe constipation", "Acute gout flare from uric acid increase"],
            answer: "Dangerous hyperkalemia",
            explanation: "Spironolactone is potassium-sparing. Adding potassium supplements or salt substitutes (often KCl) can push potassium dangerously high, increasing arrhythmia risk.",
            objective: .interaction,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "interaction", "Potassium supplements"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_017",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Which patient factor most strongly increases the risk of life-threatening hyperkalemia when starting an MRA such as spironolactone?",
            options: ["Chronic kidney disease with reduced GFR", "History of GERD", "Seasonal allergies", "Iron-deficiency anemia", "Osteoarthritis"],
            answer: "Chronic kidney disease with reduced GFR",
            explanation: "Kidney disease limits potassium excretion. Because MRAs are potassium-sparing, reduced GFR markedly increases hyperkalemia risk and makes close potassium/creatinine monitoring essential.",
            objective: .contraindication,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "contraindication", "CKD"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_018",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Spironolactone (Aldactone) is frequently used as an add-on agent when blood pressure remains uncontrolled despite three antihypertensive classes. What is this high-yield indication called?",
            options: ["Resistant hypertension", "Hypertensive emergency", "Orthostatic hypotension", "Vasovagal syncope", "White-coat hypertension"],
            answer: "Resistant hypertension",
            explanation: "Spironolactone is a classic add-on for resistant hypertension because many resistant cases have a mineralocorticoid/aldosterone-driven component.",
            objective: .indication,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "indication", "Resistant HTN"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_019",
            subsectionId: "1d",
            difficulty: .medium,
            question: "In patients with cirrhosis and ascites, diuresis is often targeted at countering aldosterone-mediated sodium retention. Which medication in this subsection is commonly used for ascites because it antagonizes aldosterone?",
            options: ["Spironolactone", "Sacubitril/valsartan", "Amlodipine", "Metoprolol succinate", "Chlorthalidone"],
            answer: "Spironolactone",
            explanation: "Spironolactone blocks aldosterone’s effects in the collecting duct, making it a common and high-yield choice for ascites associated with cirrhosis.",
            objective: .indication,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "indication", "Ascites"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_020",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Sacubitril/valsartan is used primarily for which condition because it improves neurohormonal balance in chronic heart failure?",
            options: ["HFrEF (heart failure with reduced ejection fraction)", "Acute bacterial pneumonia", "Type 1 diabetes", "Status epilepticus", "Peptic ulcer disease"],
            answer: "HFrEF (heart failure with reduced ejection fraction)",
            explanation: "Entresto (sacubitril/valsartan) is an ARNI indicated for chronic HFrEF. It increases beneficial natriuretic peptide activity and blocks harmful angiotensin II signaling.",
            objective: .indication,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "indication", "HFrEF"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_021",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Sacubitril is the neprilysin inhibitor component of Entresto. Neprilysin normally breaks down natriuretic peptides. When neprilysin is inhibited, which effect is expected?",
            options: ["Increased natriuresis and vasodilation", "Increased bronchoconstriction as the primary effect", "Direct stimulation of beta-1 receptors", "Increased aldosterone secretion", "Increased gastric acid secretion"],
            answer: "Increased natriuresis and vasodilation",
            explanation: "Neprilysin inhibition increases endogenous natriuretic peptide activity (e.g., ANP/BNP), promoting natriuresis, diuresis, and vasodilation—helpful physiologic effects in HFrEF.",
            objective: .moa,
            relatedDrugIds: ["d22"],
            tags: ["Sacubitril", "MOA", "Neprilysin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_022",
            subsectionId: "1d",
            difficulty: .hard,
            question: "Why is sacubitril (a neprilysin inhibitor) paired with an ARB (valsartan) in Entresto rather than used alone?",
            options: ["Neprilysin inhibition can increase angiotensin II signaling unless RAAS is blocked", "Sacubitril alone causes severe hypokalemia unless paired with an ARB", "Valsartan prevents ototoxicity from sacubitril", "The combination prevents cough by lowering bradykinin", "Sacubitril is inactive unless activated by valsartan"],
            answer: "Neprilysin inhibition can increase angiotensin II signaling unless RAAS is blocked",
            explanation: "Neprilysin breaks down multiple peptides, including natriuretic peptides and angiotensin II. If neprilysin is inhibited without RAAS blockade, angiotensin II effects can rise. Pairing sacubitril with valsartan blocks angiotensin II receptors while preserving natriuretic peptide benefits.",
            objective: .pearl,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "pearl", "Why combo"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_023",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Entresto is an ARNI that increases vasodilatory peptides and also blocks angiotensin II receptors. Which adverse effect is especially common early in therapy due to vasodilation and reduced RAAS tone?",
            options: ["Symptomatic hypotension", "Severe hypercalcemia", "Ototoxicity", "Hemorrhagic cystitis", "Tendon rupture"],
            answer: "Symptomatic hypotension",
            explanation: "By promoting vasodilation (via increased natriuretic peptides) and blocking angiotensin II receptors, Entresto can lower blood pressure significantly—so dizziness or symptomatic hypotension is a common early dose-limiting effect.",
            objective: .adverseEffect,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "adverse effects", "Hypotension"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_024",
            subsectionId: "1d",
            difficulty: .hard,
            question: "A serious but uncommon adverse effect of Entresto is angioedema. Which mechanistic explanation best fits this risk?",
            options: ["Increased bradykinin/substance P levels due to reduced peptide breakdown", "Direct histamine release from mast cells as the primary mechanism", "Irreversible inhibition of COX-1", "Direct blockade of calcium channels in vascular smooth muscle", "Antagonism of aldosterone receptors"],
            answer: "Increased bradykinin/substance P levels due to reduced peptide breakdown",
            explanation: "Neprilysin helps break down vasoactive peptides such as bradykinin and substance P. Inhibiting neprilysin can increase these peptides, contributing to angioedema risk (especially when combined with ACE inhibitors).",
            objective: .adverseEffect,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "angioedema", "Mechanism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_025",
            subsectionId: "1d",
            difficulty: .hard,
            question: "Which medication combination is contraindicated because it markedly increases angioedema risk by stacking peptide breakdown inhibition?",
            options: ["Entresto + lisinopril", "Entresto + furosemide", "Spironolactone + chlorthalidone", "Eplerenone + amlodipine", "Metoprolol succinate + hydrochlorothiazide"],
            answer: "Entresto + lisinopril",
            explanation: "ACE inhibitors reduce bradykinin breakdown, and neprilysin inhibition can also increase bradykinin-related peptides. Combining an ACE inhibitor (like lisinopril) with Entresto significantly increases angioedema risk and is contraindicated.",
            objective: .contraindication,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "contraindication", "ACE inhibitor"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_026",
            subsectionId: "1d",
            difficulty: .easy,
            question: "One medication in this subsection carries a boxed warning for fetal toxicity because it contains an ARB component. Which medication should be avoided in pregnancy for this reason?",
            options: ["Entresto (sacubitril/valsartan)", "Eplerenone (Inspra)", "Spironolactone (Aldactone)", "Furosemide (Lasix)", "Amlodipine (Norvasc)"],
            answer: "Entresto (sacubitril/valsartan)",
            explanation: "Entresto contains valsartan (an ARB). RAAS blockers (ACE inhibitors/ARBs/ARNIs) have a boxed warning for fetal toxicity and are contraindicated in pregnancy.",
            objective: .contraindication,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "boxed warning", "Pregnancy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_027",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Although Entresto is not a classic diuretic, it can still raise potassium. Which mechanism best explains Entresto-associated hyperkalemia risk?",
            options: ["ARB component lowers aldosterone, decreasing potassium excretion", "It directly blocks the Na+/K+/2Cl- transporter", "It causes calcium retention leading to potassium shift", "It stimulates insulin release causing intracellular potassium shift", "It increases aldosterone secretion"],
            answer: "ARB component lowers aldosterone, decreasing potassium excretion",
            explanation: "Valsartan blocks angiotensin II receptors, which reduces aldosterone production. Less aldosterone means less potassium excretion in the collecting duct, raising hyperkalemia risk—especially when combined with MRAs or potassium supplements.",
            objective: .moa,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "hyperkalemia", "RAAS"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_028",
            subsectionId: "1d",
            difficulty: .easy,
            question: "When initiating Entresto for HFrEF, which set of parameters is most important to monitor during titration?",
            options: ["Blood pressure, serum potassium, and renal function", "INR, platelet count, and aPTT", "TSH, free T4, and cortisol", "Calcium, phosphate, and vitamin D", "Peak flow, FEV1, and eosinophils"],
            answer: "Blood pressure, serum potassium, and renal function",
            explanation: "Entresto can cause hypotension, hyperkalemia, and worsening renal function. Monitoring BP and a basic metabolic panel (K+ and creatinine/BUN) is high yield.",
            objective: .monitoring,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "monitoring", "BP and BMP"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_029",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A patient is currently taking valsartan for HFrEF and is being switched to Entresto. Compared with switching from an ACE inhibitor, what washout period is needed when switching from an ARB to Entresto?",
            options: ["No washout period is required", "12 hours", "24 hours", "36 hours", "72 hours"],
            answer: "No washout period is required",
            explanation: "The classic washout requirement applies when switching from an ACE inhibitor to Entresto to reduce angioedema risk. When switching from an ARB to Entresto, a washout period is not required.",
            objective: .pearl,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "switching", "Washout"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_030",
            subsectionId: "1d",
            difficulty: .hard,
            question: "Eplerenone is metabolized by CYP3A4. Which concomitant medication is most likely to raise eplerenone levels and increase hyperkalemia risk?",
            options: ["Ketoconazole", "Amoxicillin", "Famotidine", "Acetaminophen", "Metformin"],
            answer: "Ketoconazole",
            explanation: "Strong CYP3A4 inhibitors (e.g., ketoconazole, clarithromycin, some protease inhibitors) can increase eplerenone exposure, increasing hyperkalemia risk. This makes drug–drug interaction screening important.",
            objective: .interaction,
            relatedDrugIds: ["d21"],
            tags: ["Eplerenone", "interaction", "CYP3A4"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_031",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A common high-yield interaction involves stacking medications that all raise potassium. Which combination is most likely to cause clinically significant hyperkalemia?",
            options: ["Spironolactone + lisinopril", "Furosemide + hydrochlorothiazide", "Amlodipine + atorvastatin", "Metoprolol succinate + aspirin", "Nitroglycerin + acetaminophen"],
            answer: "Spironolactone + lisinopril",
            explanation: "Spironolactone is potassium-sparing, and ACE inhibitors (like lisinopril) reduce aldosterone—both push potassium higher. Combining RAAS blockers with MRAs is common in HFrEF but requires careful potassium and renal monitoring.",
            objective: .interaction,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "interaction", "Hyperkalemia risk"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_032",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A patient has hypertension with low renin and high aldosterone (primary hyperaldosteronism). Which medication from this subsection directly antagonizes aldosterone’s receptor and is commonly used in this condition?",
            options: ["Spironolactone", "Sacubitril/valsartan", "Atenolol", "Chlorthalidone", "Losartan"],
            answer: "Spironolactone",
            explanation: "Spironolactone is an aldosterone receptor antagonist (MRA), making it a targeted therapy for primary hyperaldosteronism as well as resistant hypertension and HFrEF.",
            objective: .indication,
            relatedDrugIds: ["d20"],
            tags: ["Spironolactone", "indication", "Hyperaldosteronism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_033",
            subsectionId: "1d",
            difficulty: .medium,
            question: "You’re comparing diuretic electrolyte effects. Which statement best matches MRAs like spironolactone and eplerenone?",
            options: ["They spare potassium and can cause hyperkalemia", "They waste calcium and commonly cause hypocalcemia", "They cause HyperGLUC (glucose, lipids, uric acid, calcium)", "They are associated with ototoxicity", "They are carbonic anhydrase inhibitors"],
            answer: "They spare potassium and can cause hyperkalemia",
            explanation: "MRAs are potassium-sparing because they block aldosterone’s effect in the collecting duct. Their signature electrolyte risk is hyperkalemia (not hypocalcemia or HyperGLUC).",
            objective: .classId,
            relatedDrugIds: ["d20", "d21"],
            tags: ["MRA", "electrolytes", "Compare classes"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_034",
            subsectionId: "1d",
            difficulty: .hard,
            question: "A patient on an MRA develops muscle weakness and an ECG with peaked T waves. Which adverse effect best explains these findings?",
            options: ["Hyperkalemia", "Hypokalemia", "Hypocalcemia", "Hyponatremia", "Hypermagnesemia"],
            answer: "Hyperkalemia",
            explanation: "MRAs decrease potassium excretion, raising the risk of hyperkalemia. Severe hyperkalemia can cause muscle weakness and ECG changes such as peaked T waves.",
            objective: .adverseEffect,
            relatedDrugIds: ["d21"],
            tags: ["MRA", "hyperkalemia", "Safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_035",
            subsectionId: "1d",
            difficulty: .medium,
            question: "A patient previously stopped an ACE inhibitor due to a persistent dry cough and is now being considered for Entresto. Compared with ACE inhibitors, which statement about cough with Entresto is most accurate?",
            options: ["Cough can occur but is generally less common than with ACE inhibitors", "Cough is guaranteed in all patients", "Entresto causes cough by inhibiting COX-1", "Entresto causes cough by blocking beta-2 receptors", "Entresto eliminates bradykinin completely"],
            answer: "Cough can occur but is generally less common than with ACE inhibitors",
            explanation: "ACE inhibitors commonly cause cough due to bradykinin accumulation. Entresto is not an ACE inhibitor, so cough is generally less common—though neprilysin inhibition can still affect some peptides, and angioedema risk remains important to recognize.",
            objective: .pearl,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "cough", "Compare to ACEi"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_036",
            subsectionId: "1d",
            difficulty: .hard,
            question: "A patient on Entresto for HFrEF starts taking high-dose NSAIDs daily for chronic pain. Which risk increases because NSAIDs can constrict the afferent arteriole while RAAS blockade affects the efferent arteriole?",
            options: ["Acute kidney injury / worsening renal function", "Severe hypocalcemia", "Ototoxicity", "Serotonin syndrome", "Hemolytic anemia"],
            answer: "Acute kidney injury / worsening renal function",
            explanation: "NSAIDs reduce renal prostaglandins (afferent constriction), and RAAS blockade reduces efferent tone. Together they can reduce glomerular perfusion and increase AKI risk, so renal function monitoring is important.",
            objective: .interaction,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "interaction", "NSAIDs", "AKI"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_037",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Entresto can lower blood pressure, especially when combined with diuretics. Which patient counseling point most directly helps reduce symptomatic hypotension risk?",
            options: ["Monitor for dizziness and avoid sudden position changes (rise slowly)", "Take extra potassium supplements daily", "Avoid all dietary sodium completely", "Skip all other heart failure meds when starting Entresto", "Increase caffeine intake to counteract the medication"],
            answer: "Monitor for dizziness and avoid sudden position changes (rise slowly)",
            explanation: "Because Entresto can cause hypotension (and patients may also be on diuretics), counseling about dizziness, orthostasis, and standing up slowly helps prevent falls and improves adherence.",
            objective: .monitoring,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "counseling", "Hypotension"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_038",
            subsectionId: "1d",
            difficulty: .expert,
            question: "A clinician uses natriuretic peptides to follow heart failure status. Which lab value can be harder to interpret after starting sacubitril/valsartan because it may rise due to neprilysin inhibition?",
            options: ["BNP", "NT-proBNP", "Serum troponin", "Serum creatinine", "Hemoglobin A1c"],
            answer: "BNP",
            explanation: "Neprilysin degrades BNP, so inhibiting neprilysin can increase BNP levels independent of clinical worsening. NT-proBNP is not a neprilysin substrate and is generally preferred for monitoring in patients on sacubitril/valsartan.",
            objective: .pearl,
            relatedDrugIds: ["d22"],
            tags: ["ARNI", "biomarker", "BNP vs NT-proBNP"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_039",
            subsectionId: "1d",
            difficulty: .medium,
            question: "Both spironolactone and eplerenone block mineralocorticoid (aldosterone) receptors. Which one is more selective for the mineralocorticoid receptor and therefore tends to cause fewer anti-androgen effects?",
            options: ["Eplerenone", "Spironolactone", "Sacubitril/valsartan", "Chlorthalidone", "Bumetanide"],
            answer: "Eplerenone",
            explanation: "Eplerenone is more selective for the mineralocorticoid receptor, while spironolactone can also bind androgen/progesterone receptors. This selectivity difference explains why eplerenone usually causes fewer endocrine adverse effects.",
            objective: .moa,
            relatedDrugIds: ["d21"],
            tags: ["Eplerenone", "selectivity", "MRA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1d_add_040",
            subsectionId: "1d",
            difficulty: .easy,
            question: "Entresto contains two active components: sacubitril and valsartan. Which component provides the neprilysin inhibition that boosts endogenous natriuretic peptides?",
            options: ["Sacubitril", "Valsartan", "Spironolactone", "Eplerenone", "Losartan"],
            answer: "Sacubitril",
            explanation: "Sacubitril is the neprilysin inhibitor in Entresto, increasing natriuretic peptide activity (natriuresis/vasodilation). Valsartan is the ARB component that blocks angiotensin II receptors.",
            objective: .moa,
            relatedDrugIds: ["d22"],
            tags: ["Sacubitril", "component", "Neprilysin"],
            source: .curated
        ),
    ]
}