import Foundation

extension DrugDataService {

    // MARK: - Module 1: Cardiovascular I
    static func buildModule1() -> DrugModule {
        let sub1a = Subsection(id: "1a", moduleId: "m1", code: "1a", title: "ACE Inhibitors & ARBs", description: "Master the -pril and -sartan drug classes", iconName: "heart.fill", drugs: [
            Drug(id: "d1", genericName: "Lisinopril", brandName: "Zestril/Prinivil", drugClass: "ACE Inhibitor", suffix: "-pril", indications: ["HTN", "HF", "Post-MI", "Diabetic nephropathy"], sideEffects: ["Dry cough", "Hyperkalemia", "Angioedema", "Dizziness"], clinicalPearls: ["Most prescribed ACE inhibitor", "Monitor K+ and SCr"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy", "History of angioedema", "Bilateral renal artery stenosis"], monitoring: ["Serum potassium", "Serum creatinine/BUN", "Blood pressure"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "10 mg PO daily"), DoseFact(context: "HTN (usual range)", dose: "20–40 mg/day")]),
            Drug(id: "d2", genericName: "Enalapril", brandName: "Vasotec", drugClass: "ACE Inhibitor", suffix: "-pril", indications: ["HTN", "HF"], sideEffects: ["Dry cough", "Hyperkalemia", "Angioedema"], clinicalPearls: ["Available as IV (enalaprilat)", "Prodrug - converted to enalaprilat"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy", "History of angioedema"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "5 mg PO daily"), DoseFact(context: "HTN (usual range)", dose: "10–40 mg/day")]),
            Drug(id: "d3", genericName: "Ramipril", brandName: "Altace", drugClass: "ACE Inhibitor", suffix: "-pril", indications: ["HTN", "HF", "CV risk reduction"], sideEffects: ["Dry cough", "Hyperkalemia"], clinicalPearls: ["CV risk reduction in high-risk patients", "Used post-MI"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy", "History of angioedema"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "2.5 mg PO daily"), DoseFact(context: "HTN (usual range)", dose: "2.5–20 mg/day")]),
            Drug(id: "d4", genericName: "Benazepril", brandName: "Lotensin", drugClass: "ACE Inhibitor", suffix: "-pril", indications: ["HTN"], sideEffects: ["Dry cough", "Hyperkalemia"], clinicalPearls: ["Often combined with amlodipine (Lotrel)"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy", "History of angioedema"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "10 mg PO daily"), DoseFact(context: "HTN (usual range)", dose: "20–40 mg/day")]),
            Drug(id: "d5", genericName: "Losartan", brandName: "Cozaar", drugClass: "ARB", suffix: "-sartan", indications: ["HTN", "Diabetic nephropathy", "Stroke prevention"], sideEffects: ["Hyperkalemia", "Dizziness"], clinicalPearls: ["Uricosuric effect (lowers uric acid)", "First ARB approved"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "50 mg PO daily"), DoseFact(context: "HTN (max)", dose: "100 mg/day")]),
            Drug(id: "d6", genericName: "Valsartan", brandName: "Diovan", drugClass: "ARB", suffix: "-sartan", indications: ["HTN", "HF", "Post-MI"], sideEffects: ["Hyperkalemia", "Hypotension"], clinicalPearls: ["Component of Entresto (sacubitril/valsartan)"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "80–160 mg PO daily"), DoseFact(context: "HTN (usual range)", dose: "80–320 mg/day")]),
            Drug(id: "d7", genericName: "Irbesartan", brandName: "Avapro", drugClass: "ARB", suffix: "-sartan", indications: ["HTN", "Diabetic nephropathy"], sideEffects: ["Hyperkalemia", "Dizziness"], clinicalPearls: ["Strong evidence for nephroprotection in T2DM"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "150 mg PO daily"), DoseFact(context: "HTN (max)", dose: "300 mg/day")]),
            Drug(id: "d8", genericName: "Olmesartan", brandName: "Benicar", drugClass: "ARB", suffix: "-sartan", indications: ["HTN"], sideEffects: ["Hyperkalemia", "Sprue-like enteropathy"], clinicalPearls: ["Unique: sprue-like enteropathy (diarrhea, weight loss)"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "20 mg PO daily"), DoseFact(context: "HTN (max)", dose: "40 mg/day")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls1a_1", title: "ACE Inhibitors: The -pril Family", content: "ACE inhibitors block angiotensin-converting enzyme, reducing angiotensin II production.", bulletPoints: ["All end in suffix -pril", "First-line for HTN, HF, diabetic nephropathy", "Unique side effect: dry cough (bradykinin)", "Black Box Warning: Contraindicated in pregnancy"], highlightText: "Remember: -pril = ACE Inhibitor"),
            LearningSlide(id: "ls1a_2", title: "ARBs: The -sartan Family", content: "ARBs block the angiotensin II receptor directly. Similar benefits to ACE inhibitors but WITHOUT the dry cough.", bulletPoints: ["All end in suffix -sartan", "Alternative when ACE inhibitor cough occurs", "Also contraindicated in pregnancy", "Do NOT combine ACE + ARB"], highlightText: "Remember: -sartan = ARB"),
            LearningSlide(id: "ls1a_3", title: "Key Monitoring & Pearls", content: "Both ACE inhibitors and ARBs require monitoring of potassium and renal function.", bulletPoints: ["Monitor: serum potassium (risk of hyperkalemia)", "Monitor: serum creatinine / BUN", "Hold if bilateral renal artery stenosis", "Losartan has unique uricosuric effect"], highlightText: "Both classes: Monitor K+ and renal function"),
        ])

        let sub1b = Subsection(id: "1b", moduleId: "m1", code: "1b", title: "Thiazide & Loop Diuretics", description: "Diuretics for HTN and fluid overload", iconName: "drop.fill", drugs: [
            Drug(id: "d9", genericName: "Hydrochlorothiazide", brandName: "Microzide", drugClass: "Thiazide Diuretic", suffix: "-thiazide", indications: ["HTN", "Edema"], sideEffects: ["Hypokalemia", "Hyperuricemia", "Hypercalcemia", "Hyperglycemia"], clinicalPearls: ["Most commonly used thiazide", "Causes HyperGLUC"], majorContraindications: ["Anuria", "Sulfonamide hypersensitivity (severe)"], monitoring: ["Serum electrolytes (Na+, K+)", "Serum creatinine/BUN", "Blood glucose", "Uric acid"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "12.5–25 mg PO daily"), DoseFact(context: "HTN (max)", dose: "50 mg/day")]),
            Drug(id: "d10", genericName: "Chlorthalidone", brandName: "Thalitone", drugClass: "Thiazide-like Diuretic", suffix: "", indications: ["HTN"], sideEffects: ["Hypokalemia", "Hyponatremia"], clinicalPearls: ["Longer half-life than HCTZ", "Preferred per guidelines"], majorContraindications: ["Anuria"], monitoring: ["Serum electrolytes (Na+, K+)", "Serum creatinine/BUN", "Blood glucose"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "12.5–25 mg PO daily"), DoseFact(context: "HTN (max)", dose: "50 mg/day")]),
            Drug(id: "d11", genericName: "Furosemide", brandName: "Lasix", drugClass: "Loop Diuretic", suffix: "-semide", indications: ["Edema", "HF", "Acute pulmonary edema"], sideEffects: ["Hypokalemia", "Ototoxicity", "Hypocalcemia", "Dehydration"], clinicalPearls: ["Most potent diuretic class", "IV for acute decompensated HF"], blackBoxWarnings: ["Potent diuretic — excessive doses can cause profound water and electrolyte depletion"], majorContraindications: ["Anuria"], monitoring: ["Serum electrolytes (K+, Na+, Mg2+, Ca2+)", "Serum creatinine/BUN", "Blood pressure", "Hearing (high-dose IV)"], commonDosing: [DoseFact(context: "Edema (adult start)", dose: "20–40 mg PO/IV"), DoseFact(context: "Edema (max)", dose: "600 mg/day")]),
            Drug(id: "d12", genericName: "Bumetanide", brandName: "Bumex", drugClass: "Loop Diuretic", suffix: "", indications: ["Edema", "HF"], sideEffects: ["Hypokalemia", "Ototoxicity"], clinicalPearls: ["40x more potent than furosemide mg-for-mg"], majorContraindications: ["Anuria"], monitoring: ["Serum electrolytes (K+, Na+, Mg2+)", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "Edema (adult start)", dose: "0.5–1 mg PO/IV"), DoseFact(context: "Edema (max)", dose: "10 mg/day")]),
            Drug(id: "d13", genericName: "Torsemide", brandName: "Demadex", drugClass: "Loop Diuretic", suffix: "", indications: ["Edema", "HF"], sideEffects: ["Hypokalemia", "Ototoxicity"], clinicalPearls: ["Best oral bioavailability of loop diuretics"], majorContraindications: ["Anuria"], monitoring: ["Serum electrolytes (K+, Na+)", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "Edema/HF (adult start)", dose: "10–20 mg PO daily"), DoseFact(context: "Edema (max)", dose: "200 mg/day")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls1b_1", title: "Thiazide Diuretics", content: "Thiazides work on the distal convoluted tubule. First-line for hypertension.", bulletPoints: ["Block Na+/Cl- cotransporter in DCT", "Cause HyperGLUC: Glucose, Lipids, Uric acid, Calcium", "Cause HypoKalemia and HypoNatremia"], highlightText: "Thiazides: HyperGLUC + HypoK+"),
            LearningSlide(id: "ls1b_2", title: "Loop Diuretics", content: "Loop diuretics are the most potent diuretics. They work on the thick ascending loop of Henle.", bulletPoints: ["Block Na+/K+/2Cl- transporter in loop of Henle", "OPPOSITE of thiazides: cause HYPOcalcemia", "Risk of ototoxicity (especially with aminoglycosides)"], highlightText: "Loops LOSE calcium (hypocalcemia)"),
        ])

        let sub1c = Subsection(id: "1c", moduleId: "m1", code: "1c", title: "Beta-Blockers", description: "Beta blockers for HTN, HF, and CAD", iconName: "bolt.heart.fill", drugs: [
            Drug(id: "d14", genericName: "Metoprolol succinate", brandName: "Toprol XL", drugClass: "Selective Beta-1 Blocker", suffix: "-olol", indications: ["HTN", "HF (HFrEF)", "Angina"], sideEffects: ["Bradycardia", "Fatigue", "Depression"], clinicalPearls: ["Succinate = extended release for HF"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Severe bradycardia", "Decompensated HF", "2nd/3rd degree heart block"], monitoring: ["Heart rate", "Blood pressure"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "25–100 mg PO daily"), DoseFact(context: "HFrEF (start)", dose: "12.5–25 mg PO daily")]),
            Drug(id: "d15", genericName: "Metoprolol tartrate", brandName: "Lopressor", drugClass: "Selective Beta-1 Blocker", suffix: "-olol", indications: ["HTN", "Acute MI", "Rate control"], sideEffects: ["Bradycardia", "Fatigue"], clinicalPearls: ["Tartrate = immediate release, BID dosing"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Severe bradycardia", "Decompensated HF"], monitoring: ["Heart rate", "Blood pressure"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "25–50 mg PO BID"), DoseFact(context: "Acute MI", dose: "25–50 mg PO q6h")]),
            Drug(id: "d16", genericName: "Carvedilol", brandName: "Coreg", drugClass: "Non-selective Beta + Alpha Blocker", suffix: "-olol", indications: ["HF (HFrEF)", "HTN"], sideEffects: ["Bradycardia", "Hypotension", "Dizziness"], clinicalPearls: ["Alpha + Beta blocker", "Take with food"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Severe bradycardia", "Decompensated HF", "Bronchial asthma"], monitoring: ["Heart rate", "Blood pressure"], commonDosing: [DoseFact(context: "HFrEF (adult start)", dose: "3.125 mg PO BID"), DoseFact(context: "HTN (start)", dose: "6.25 mg PO BID")]),
            Drug(id: "d17", genericName: "Atenolol", brandName: "Tenormin", drugClass: "Selective Beta-1 Blocker", suffix: "-olol", indications: ["HTN", "Angina"], sideEffects: ["Bradycardia", "Fatigue"], clinicalPearls: ["Renally eliminated"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Severe bradycardia", "Decompensated HF", "2nd/3rd degree heart block"], monitoring: ["Heart rate", "Blood pressure", "Renal function"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "25–50 mg PO daily"), DoseFact(context: "HTN (max)", dose: "100 mg/day")]),
            Drug(id: "d18", genericName: "Propranolol", brandName: "Inderal", drugClass: "Non-selective Beta Blocker", suffix: "-olol", indications: ["HTN", "Tremor", "Migraine prophylaxis"], sideEffects: ["Bradycardia", "Bronchospasm", "Mask hypoglycemia"], clinicalPearls: ["Non-selective: blocks B1 and B2", "Avoid in asthma/COPD"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Asthma", "COPD with bronchospasm", "Severe bradycardia"], monitoring: ["Heart rate", "Blood pressure"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "40 mg PO BID"), DoseFact(context: "Tremor (usual)", dose: "40 mg PO BID")]),
            Drug(id: "d19", genericName: "Bisoprolol", brandName: "Zebeta", drugClass: "Selective Beta-1 Blocker", suffix: "-olol", indications: ["HTN", "HF (HFrEF)"], sideEffects: ["Bradycardia", "Fatigue"], clinicalPearls: ["Most beta-1 selective"], blackBoxWarnings: ["Do not abruptly discontinue"], majorContraindications: ["Severe bradycardia", "Decompensated HF"], monitoring: ["Heart rate", "Blood pressure"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "5 mg PO daily"), DoseFact(context: "HFrEF (start)", dose: "1.25 mg PO daily")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls1c_1", title: "Beta Blockers: The -olol Family", content: "Beta blockers reduce heart rate, contractility, and blood pressure.", bulletPoints: ["All end in suffix -olol", "Selective (B1): metoprolol, atenolol, bisoprolol", "Non-selective (B1+B2): propranolol, carvedilol", "Three proven for HFrEF: metoprolol succinate, carvedilol, bisoprolol"], highlightText: "-olol = Beta Blocker"),
            LearningSlide(id: "ls1c_2", title: "Selective vs Non-Selective", content: "Beta-1 receptors are in the heart. Beta-2 receptors are in the lungs.", bulletPoints: ["B1 selective = safer in asthma/COPD", "Non-selective can cause bronchospasm", "Propranolol can mask hypoglycemia in diabetics"], highlightText: "B1 = Heart, B2 = Lungs"),
        ])

        let sub1d = Subsection(id: "1d", moduleId: "m1", code: "1d", title: "MRAs & ARNI", description: "Spironolactone, Eplerenone, and Entresto", iconName: "staroflife.fill", drugs: [
            Drug(id: "d20", genericName: "Spironolactone", brandName: "Aldactone", drugClass: "MRA", suffix: "", indications: ["HF", "Resistant HTN", "Ascites"], sideEffects: ["Hyperkalemia", "Gynecomastia"], clinicalPearls: ["Potassium-SPARING diuretic"], majorContraindications: ["Severe renal impairment (eGFR < 30)", "Hyperkalemia (K+ > 5.5)"], monitoring: ["Serum potassium", "Serum creatinine/BUN", "Blood pressure"], commonDosing: [DoseFact(context: "HF (adult start)", dose: "12.5–25 mg PO daily"), DoseFact(context: "Resistant HTN (usual)", dose: "25–50 mg/day")]),
            Drug(id: "d21", genericName: "Eplerenone", brandName: "Inspra", drugClass: "MRA", suffix: "", indications: ["HF", "HTN"], sideEffects: ["Hyperkalemia"], clinicalPearls: ["More selective, less gynecomastia"], majorContraindications: ["Severe renal impairment", "Hyperkalemia (K+ > 5.5)", "Strong CYP3A4 inhibitors"], monitoring: ["Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HF (adult start)", dose: "25 mg PO daily"), DoseFact(context: "HTN (start)", dose: "50 mg PO daily")]),
            Drug(id: "d22", genericName: "Sacubitril/Valsartan", brandName: "Entresto", drugClass: "ARNI", suffix: "", indications: ["HFrEF"], sideEffects: ["Hypotension", "Hyperkalemia", "Angioedema"], clinicalPearls: ["36-hour ACE washout required"], blackBoxWarnings: ["Contraindicated in pregnancy (fetal toxicity)"], majorContraindications: ["Pregnancy", "Concomitant ACE inhibitor use", "History of angioedema with ACEi/ARB"], monitoring: ["Blood pressure", "Serum potassium", "Serum creatinine/BUN"], commonDosing: [DoseFact(context: "HFrEF (adult start)", dose: "24/26 mg PO BID"), DoseFact(context: "HFrEF (target)", dose: "97/103 mg PO BID")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls1d_1", title: "MRAs: Potassium-Sparing Diuretics", content: "MRAs block aldosterone receptors.", bulletPoints: ["Spironolactone and eplerenone", "SPARING = they spare potassium", "Spironolactone: gynecomastia (anti-androgen)"], highlightText: "MRAs SPARE potassium!"),
            LearningSlide(id: "ls1d_2", title: "ARNI: Entresto", content: "Sacubitril/Valsartan combines neprilysin inhibitor with ARB.", bulletPoints: ["MUST have 36-hour washout from ACE inhibitor", "NEVER combine with ACE inhibitor"], highlightText: "Entresto: 36-hour ACE washout required"),
        ])

        let sub1f = Subsection(id: "1f", moduleId: "m1", code: "1f", title: "Calcium Channel Blockers", description: "Dihydropyridines and Non-dihydropyridines", iconName: "waveform.path.ecg", drugs: [
            Drug(id: "d23", genericName: "Amlodipine", brandName: "Norvasc", drugClass: "DHP CCB", suffix: "-dipine", indications: ["HTN", "Angina"], sideEffects: ["Peripheral edema", "Flushing"], clinicalPearls: ["Most commonly prescribed CCB", "Long half-life"], monitoring: ["Blood pressure", "Heart rate", "Peripheral edema assessment"], commonDosing: [DoseFact(context: "HTN (adult start)", dose: "5 mg PO daily"), DoseFact(context: "HTN (max)", dose: "10 mg/day")]),
            Drug(id: "d24", genericName: "Nifedipine", brandName: "Procardia", drugClass: "DHP CCB", suffix: "-dipine", indications: ["HTN", "Angina", "Raynaud's"], sideEffects: ["Peripheral edema", "Reflex tachycardia", "Flushing", "Gingival hyperplasia"], clinicalPearls: ["Extended release preferred"], monitoring: ["Blood pressure", "Heart rate"], commonDosing: [DoseFact(context: "HTN (adult start ER)", dose: "30 mg PO daily"), DoseFact(context: "HTN (max)", dose: "90 mg/day")]),
            Drug(id: "d25", genericName: "Diltiazem", brandName: "Cardizem", drugClass: "Non-DHP CCB", suffix: "", indications: ["HTN", "Angina", "Rate control (AFib)"], sideEffects: ["Bradycardia", "Constipation"], clinicalPearls: ["Avoid combining with beta blockers"], majorContraindications: ["Severe bradycardia", "2nd/3rd degree AV block", "Systolic HF (HFrEF)"], monitoring: ["Heart rate", "Blood pressure", "ECG (PR interval)"], commonDosing: [DoseFact(context: "HTN (adult start ER)", dose: "120–180 mg PO daily"), DoseFact(context: "Rate control (IV bolus)", dose: "0.25 mg/kg IV")]),
            Drug(id: "d26", genericName: "Verapamil", brandName: "Calan", drugClass: "Non-DHP CCB", suffix: "", indications: ["HTN", "Angina", "SVT"], sideEffects: ["Bradycardia", "Constipation", "Heart block"], clinicalPearls: ["Most cardiac-selective non-DHP CCB", "Significant constipation"], majorContraindications: ["Severe bradycardia", "2nd/3rd degree AV block", "Systolic HF (HFrEF)", "Concomitant IV beta blocker"], monitoring: ["Heart rate", "Blood pressure", "ECG (PR interval)", "Constipation assessment"], commonDosing: [DoseFact(context: "HTN (adult start ER)", dose: "120–180 mg PO daily"), DoseFact(context: "SVT (IV bolus)", dose: "2.5–5 mg IV")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls1f_1", title: "CCBs: Two Subclasses", content: "Calcium channel blockers have two important subclasses.", bulletPoints: ["DHP (dihydropyridines): end in -dipine, mainly vasodilate", "Non-DHP: diltiazem and verapamil, affect heart rate", "DHPs: reflex tachycardia, peripheral edema", "Non-DHPs: bradycardia, constipation"], highlightText: "DHP = -dipine = Vessels | Non-DHP = Heart"),
        ])

        let sub1g = Subsection(id: "1g", moduleId: "m1", code: "1g", title: "Mastering Cardiovascular I (Boss)", description: "Comprehensive cardiovascular review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m1", number: 1, title: "Cardiovascular I", subtitle: "HTN & HF Workhorses", iconName: "heart.fill", accentColorHex: "E53935", subsections: [sub1a, sub1b, sub1c, sub1d, sub1f, sub1g])
    }

    // MARK: - Module 2: Cardiovascular II
    static func buildModule2() -> DrugModule {
        let sub2a = Subsection(id: "2a", moduleId: "m2", code: "2a", title: "Statins", description: "HMG-CoA Reductase Inhibitors", iconName: "chart.line.downtrend.xyaxis", drugs: [
            Drug(id: "d27", genericName: "Atorvastatin", brandName: "Lipitor", drugClass: "Statin", suffix: "-statin", indications: ["Hyperlipidemia", "ASCVD prevention"], sideEffects: ["Myalgia", "Hepatotoxicity", "Rhabdomyolysis", "Slight diabetes risk"], clinicalPearls: ["Most prescribed statin", "High-intensity: 40-80mg", "Long half-life — can dose any time of day"], majorContraindications: ["Active liver disease", "Pregnancy"], monitoring: ["LFTs (ALT/AST)", "Lipid panel", "CK if muscle symptoms"], commonDosing: [DoseFact(context: "Moderate-intensity", dose: "10–20 mg PO daily"), DoseFact(context: "High-intensity", dose: "40–80 mg PO daily")]),
            Drug(id: "d28", genericName: "Rosuvastatin", brandName: "Crestor", drugClass: "Statin", suffix: "-statin", indications: ["Hyperlipidemia", "ASCVD prevention"], sideEffects: ["Myalgia", "Hepatotoxicity", "Proteinuria (high doses)"], clinicalPearls: ["Most potent statin", "High-intensity: 20-40mg", "Hydrophilic — fewer CNS effects"], majorContraindications: ["Active liver disease", "Pregnancy"], monitoring: ["LFTs (ALT/AST)", "Lipid panel", "CK if muscle symptoms"], commonDosing: [DoseFact(context: "Moderate-intensity", dose: "5–10 mg PO daily"), DoseFact(context: "High-intensity", dose: "20–40 mg PO daily")]),
            Drug(id: "d29", genericName: "Simvastatin", brandName: "Zocor", drugClass: "Statin", suffix: "-statin", indications: ["Hyperlipidemia"], sideEffects: ["Myalgia", "Hepatotoxicity", "Rhabdomyolysis (dose-dependent)"], clinicalPearls: ["Max dose 40 mg (myopathy risk at 80 mg)", "CYP3A4 substrate — many interactions", "Take in the evening (shorter half-life)"], majorContraindications: ["Active liver disease", "Pregnancy", "Strong CYP3A4 inhibitors at higher doses"], monitoring: ["LFTs (ALT/AST)", "Lipid panel", "CK if muscle symptoms"], commonDosing: [DoseFact(context: "Moderate-intensity", dose: "20–40 mg PO in evening"), DoseFact(context: "Max recommended", dose: "40 mg/day")]),
            Drug(id: "d30", genericName: "Pravastatin", brandName: "Pravachol", drugClass: "Statin", suffix: "-statin", indications: ["Hyperlipidemia"], sideEffects: ["Myalgia"], clinicalPearls: ["Not metabolized by CYP3A4", "Fewer drug interactions", "Hydrophilic statin"], majorContraindications: ["Active liver disease", "Pregnancy"], monitoring: ["LFTs (ALT/AST)", "Lipid panel"], commonDosing: [DoseFact(context: "Usual dose", dose: "40–80 mg PO daily")]),
            Drug(id: "d31", genericName: "Lovastatin", brandName: "Mevacor", drugClass: "Statin", suffix: "-statin", indications: ["Hyperlipidemia"], sideEffects: ["Myalgia", "Hepatotoxicity"], clinicalPearls: ["First statin approved", "Take with evening meal for absorption", "CYP3A4 substrate"], majorContraindications: ["Active liver disease", "Pregnancy", "Strong CYP3A4 inhibitors"], monitoring: ["LFTs (ALT/AST)", "Lipid panel"], commonDosing: [DoseFact(context: "Usual start", dose: "20 mg PO with evening meal"), DoseFact(context: "Max", dose: "80 mg/day")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2a_1", title: "Statins: The -statin Family", content: "Statins inhibit HMG-CoA reductase.", bulletPoints: ["All end in suffix -statin", "Cornerstone of ASCVD prevention", "High-intensity: atorvastatin 40-80mg, rosuvastatin 20-40mg"], highlightText: "-statin = HMG-CoA Reductase Inhibitor"),
            LearningSlide(id: "ls2a_2", title: "Statin Safety", content: "Monitor LFTs and watch for myopathy.", bulletPoints: ["Myalgia most common (~10%)", "Rhabdomyolysis rare but serious", "Contraindicated in pregnancy"], highlightText: "Monitor: LFTs + CK if muscle symptoms"),
        ])

        let sub2b = Subsection(id: "2b", moduleId: "m2", code: "2b", title: "Non-Statin Lipid Agents", description: "Ezetimibe, PCSK9 inhibitors, fibrates", iconName: "pill.fill", drugs: [
            Drug(id: "d32", genericName: "Ezetimibe", brandName: "Zetia", drugClass: "Cholesterol Absorption Inhibitor", suffix: "", indications: ["Hyperlipidemia", "Add-on to statin for additional LDL lowering"], sideEffects: ["Diarrhea", "Arthralgia"], clinicalPearls: ["Blocks NPC1L1 transporter in intestine", "First oral add-on to statins for LDL", "Different MOA from statins — complementary"], monitoring: ["Lipid panel", "LFTs if combined with statin"], commonDosing: [DoseFact(context: "Standard dose", dose: "10 mg PO daily")]),
            Drug(id: "d33", genericName: "Evolocumab", brandName: "Repatha", drugClass: "PCSK9 Inhibitor", suffix: "", indications: ["Familial hypercholesterolemia", "ASCVD with inadequate LDL lowering"], sideEffects: ["Injection site reactions", "Nasopharyngitis"], clinicalPearls: ["Monoclonal antibody against PCSK9", "Prevents LDL receptor degradation", "Very potent LDL reduction"], monitoring: ["Lipid panel"], commonDosing: [DoseFact(context: "Standard", dose: "140 mg SubQ every 2 weeks or 420 mg monthly")]),
            Drug(id: "d34", genericName: "Alirocumab", brandName: "Praluent", drugClass: "PCSK9 Inhibitor", suffix: "", indications: ["Familial hypercholesterolemia", "ASCVD with inadequate LDL lowering"], sideEffects: ["Injection site reactions", "Pruritus"], clinicalPearls: ["SubQ injection every 2–4 weeks", "mAb that blocks PCSK9 protein"], monitoring: ["Lipid panel"], commonDosing: [DoseFact(context: "Standard", dose: "75 mg SubQ every 2 weeks")]),
            Drug(id: "d35", genericName: "Fenofibrate", brandName: "Tricor", drugClass: "Fibrate", suffix: "", indications: ["Hypertriglyceridemia", "Mixed dyslipidemia"], sideEffects: ["Myopathy", "Cholelithiasis", "GI upset"], clinicalPearls: ["Primarily lowers triglycerides via PPAR-alpha activation", "Preferred fibrate with statins (lower myopathy risk)"], majorContraindications: ["Active gallbladder disease", "Severe hepatic disease", "Severe renal impairment"], monitoring: ["LFTs", "Renal function", "Lipid panel"], commonDosing: [DoseFact(context: "Standard", dose: "145 mg PO daily")]),
            Drug(id: "d36", genericName: "Gemfibrozil", brandName: "Lopid", drugClass: "Fibrate", suffix: "", indications: ["Hypertriglyceridemia"], sideEffects: ["Myopathy", "Cholelithiasis", "GI upset"], clinicalPearls: ["Avoid combining with statins (markedly increases myopathy risk)", "PPAR-alpha agonist", "Can potentiate warfarin"], majorContraindications: ["Active gallbladder disease", "Severe hepatic disease", "Concurrent statin use (relative)"], monitoring: ["LFTs", "Lipid panel", "INR if on warfarin"], commonDosing: [DoseFact(context: "Standard", dose: "600 mg PO BID, 30 min before meals")]),
            Drug(id: "d37", genericName: "Icosapent ethyl", brandName: "Vascepa", drugClass: "Omega-3 Fatty Acid", suffix: "", indications: ["Hypertriglyceridemia", "ASCVD risk reduction in select patients"], sideEffects: ["Arthralgia", "Bleeding risk", "Atrial fibrillation/flutter"], clinicalPearls: ["Pure EPA (eicosapentaenoic acid) — not generic fish oil", "REDUCE-IT trial showed CV benefit"], monitoring: ["Lipid panel", "Signs of bleeding"], commonDosing: [DoseFact(context: "Standard", dose: "2 g PO BID with food")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2b_1", title: "Beyond Statins", content: "Multiple non-statin agents for lipid management.", bulletPoints: ["Ezetimibe: blocks intestinal cholesterol absorption", "PCSK9 inhibitors: monoclonal antibodies, very potent", "Fibrates: primarily lower triglycerides", "Icosapent ethyl (Vascepa): pure EPA"], highlightText: "Add-on therapy when statins aren't enough"),
        ])

        let sub2c = Subsection(id: "2c", moduleId: "m2", code: "2c", title: "Antiplatelets", description: "Aspirin, Clopidogrel, Ticagrelor", iconName: "bandage.fill", drugs: [
            Drug(id: "d38", genericName: "Aspirin", brandName: "Bayer/Ecotrin", drugClass: "Antiplatelet", suffix: "", indications: ["ACS", "Stroke prevention", "Post-stent DAPT"], sideEffects: ["GI bleeding", "Tinnitus (salicylism)", "Bruising"], clinicalPearls: ["Irreversible COX-1 inhibitor", "Low dose (81 mg) for CV prevention", "Platelet effect lasts 7–10 days (platelet lifespan)"], majorContraindications: ["Active GI bleeding", "Children with viral illness (Reye syndrome)", "Severe aspirin allergy"], monitoring: ["Signs of GI bleeding", "CBC if prolonged use"], commonDosing: [DoseFact(context: "CV prevention", dose: "81 mg PO daily"), DoseFact(context: "ACS loading", dose: "325 mg chewed")]),
            Drug(id: "d39", genericName: "Clopidogrel", brandName: "Plavix", drugClass: "P2Y12 Inhibitor", suffix: "", indications: ["ACS", "Post-stent DAPT", "Stroke prevention"], sideEffects: ["Bleeding", "TTP (rare)", "Bruising"], clinicalPearls: ["Prodrug — requires CYP2C19 activation", "Avoid omeprazole (CYP2C19 inhibitor)", "Irreversible P2Y12 inhibition"], majorContraindications: ["Active pathological bleeding"], monitoring: ["Signs of bleeding", "CBC"], commonDosing: [DoseFact(context: "ACS loading", dose: "300–600 mg PO"), DoseFact(context: "Maintenance", dose: "75 mg PO daily")]),
            Drug(id: "d40", genericName: "Ticagrelor", brandName: "Brilinta", drugClass: "P2Y12 Inhibitor", suffix: "", indications: ["ACS", "Post-stent DAPT"], sideEffects: ["Bleeding", "Dyspnea", "Bradycardia"], clinicalPearls: ["NOT a prodrug — direct-acting, reversible P2Y12 inhibitor", "Must use with aspirin 81 mg only (higher doses reduce efficacy)", "CYP3A4 substrate"], majorContraindications: ["Active pathological bleeding", "History of intracranial hemorrhage"], monitoring: ["Signs of bleeding", "CBC"], commonDosing: [DoseFact(context: "ACS loading", dose: "180 mg PO"), DoseFact(context: "Maintenance", dose: "90 mg PO BID")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2c_1", title: "Antiplatelets", content: "Antiplatelets prevent arterial thrombosis.", bulletPoints: ["Aspirin: irreversible COX inhibitor, 81mg for prevention", "Clopidogrel: P2Y12 inhibitor, prodrug needing CYP2C19", "Ticagrelor: direct-acting P2Y12, must use 81mg aspirin", "DAPT = Dual Antiplatelet Therapy (aspirin + P2Y12)"], highlightText: "Antiplatelets for arterial clots"),
        ])

        let sub2d = Subsection(id: "2d", moduleId: "m2", code: "2d", title: "Anticoagulants", description: "Warfarin, DOACs, and LMWH", iconName: "drop.triangle.fill", drugs: [
            Drug(id: "d41", genericName: "Warfarin", brandName: "Coumadin", drugClass: "Vitamin K Antagonist", suffix: "", indications: ["AFib", "DVT/PE", "Mechanical heart valves"], sideEffects: ["Bleeding", "Skin necrosis (early therapy)", "Teratogenic"], clinicalPearls: ["Monitor INR (goal 2–3 for most indications)", "Many food/drug interactions (vitamin K, CYP2C9)", "Reversal: vitamin K ± 4-factor PCC"], blackBoxWarnings: ["Major or fatal bleeding"], majorContraindications: ["Pregnancy", "Active major bleeding", "Severe hepatic disease"], monitoring: ["INR regularly", "Signs of bleeding"], commonDosing: [DoseFact(context: "Typical start", dose: "2–5 mg PO daily, titrate to INR")]),
            Drug(id: "d42", genericName: "Rivaroxaban", brandName: "Xarelto", drugClass: "Direct Xa Inhibitor", suffix: "-xaban", indications: ["Nonvalvular AFib", "DVT/PE treatment and prophylaxis"], sideEffects: ["Bleeding", "Bruising"], clinicalPearls: ["Take with evening meal (improves absorption at higher doses)", "Once daily for AFib", "No routine INR monitoring needed"], blackBoxWarnings: ["Spinal/epidural hematoma risk with neuraxial anesthesia", "Premature discontinuation increases thrombotic risk"], majorContraindications: ["Active pathological bleeding", "Mechanical heart valves"], monitoring: ["CBC", "Renal function", "Signs of bleeding"], commonDosing: [DoseFact(context: "AFib", dose: "20 mg PO daily with evening meal"), DoseFact(context: "DVT/PE treatment", dose: "15 mg PO BID × 21 days, then 20 mg daily")]),
            Drug(id: "d43", genericName: "Apixaban", brandName: "Eliquis", drugClass: "Direct Xa Inhibitor", suffix: "-xaban", indications: ["Nonvalvular AFib", "DVT/PE treatment and prophylaxis"], sideEffects: ["Bleeding", "Bruising"], clinicalPearls: ["Preferred DOAC per many guidelines", "Twice daily dosing", "No routine INR monitoring needed"], blackBoxWarnings: ["Spinal/epidural hematoma risk with neuraxial anesthesia", "Premature discontinuation increases thrombotic risk"], majorContraindications: ["Active pathological bleeding", "Mechanical heart valves"], monitoring: ["CBC", "Renal function", "Signs of bleeding"], commonDosing: [DoseFact(context: "AFib", dose: "5 mg PO BID (2.5 mg BID if dose-reduction criteria met)"), DoseFact(context: "DVT/PE treatment", dose: "10 mg PO BID × 7 days, then 5 mg BID")]),
            Drug(id: "d44", genericName: "Enoxaparin", brandName: "Lovenox", drugClass: "Low Molecular Weight Heparin", suffix: "", indications: ["DVT prophylaxis", "ACS", "DVT/PE treatment", "Warfarin bridging"], sideEffects: ["Bleeding", "HIT", "Injection site hematoma"], clinicalPearls: ["Subcutaneous injection", "Monitor anti-Xa in renal impairment, pregnancy, extremes of weight", "Reversal: protamine (partial)", "Preferred anticoagulant in pregnancy"], majorContraindications: ["Active major bleeding", "HIT history", "Severe thrombocytopenia"], monitoring: ["CBC/platelets", "Anti-Xa level in select patients", "Signs of bleeding"], commonDosing: [DoseFact(context: "DVT prophylaxis", dose: "40 mg SubQ daily"), DoseFact(context: "DVT/PE treatment", dose: "1 mg/kg SubQ BID")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2d_1", title: "Anticoagulants", content: "Anticoagulants prevent venous thromboembolism and stroke in AFib.", bulletPoints: ["Warfarin: vitamin K antagonist, monitor INR", "DOACs (-xaban): fewer monitoring needs", "Apixaban preferred DOAC per many guidelines", "Enoxaparin: LMWH, SubQ injection"], highlightText: "DOACs replacing warfarin for most indications"),
        ])

        let sub2e = Subsection(id: "2e", moduleId: "m2", code: "2e", title: "Antianginals & Nitrates", description: "Nitroglycerin, Isosorbide, Ranolazine", iconName: "heart.text.square.fill", drugs: [
            Drug(id: "d63", genericName: "Nitroglycerin (sublingual)", brandName: "Nitrostat", drugClass: "Nitrate", suffix: "", indications: ["Acute angina relief"], sideEffects: ["Headache", "Hypotension", "Flushing", "Dizziness"], clinicalPearls: ["SL: onset 1–3 min", "Max 3 doses 5 min apart then call 911", "Contraindicated with PDE-5 inhibitors (sildenafil, tadalafil)", "Sit or lie down before use"], majorContraindications: ["Concurrent PDE-5 inhibitor use", "Severe hypotension"], monitoring: ["Blood pressure", "Heart rate"], commonDosing: [DoseFact(context: "Acute angina", dose: "0.4 mg SL q5min × 3 doses max")]),
            Drug(id: "d64", genericName: "Nitroglycerin (IV)", brandName: "Tridil", drugClass: "Nitrate", suffix: "", indications: ["ACS", "Acute decompensated HF"], sideEffects: ["Hypotension", "Headache", "Reflex tachycardia"], clinicalPearls: ["Use non-PVC tubing", "Titratable infusion for hospital use"], majorContraindications: ["Concurrent PDE-5 inhibitor use", "Severe hypotension"], monitoring: ["Blood pressure (continuous)", "Heart rate"]),
            Drug(id: "d65", genericName: "Isosorbide mononitrate", brandName: "Imdur", drugClass: "Nitrate", suffix: "", indications: ["Angina prophylaxis"], sideEffects: ["Headache", "Hypotension", "Dizziness"], clinicalPearls: ["Requires nitrate-free interval (10–12 hours) to prevent tolerance", "Long-acting oral nitrate for prevention, NOT rescue"], majorContraindications: ["Concurrent PDE-5 inhibitor use", "Severe hypotension"], monitoring: ["Blood pressure"], commonDosing: [DoseFact(context: "ER tablet", dose: "30–60 mg PO daily in the morning")]),
            Drug(id: "d66", genericName: "Isosorbide dinitrate", brandName: "Isordil", drugClass: "Nitrate", suffix: "", indications: ["Angina prophylaxis", "HFrEF (with hydralazine)"], sideEffects: ["Headache", "Hypotension", "Dizziness"], clinicalPearls: ["Combined with hydralazine (BiDil) for HFrEF", "Requires nitrate-free interval"], majorContraindications: ["Concurrent PDE-5 inhibitor use", "Severe hypotension"], monitoring: ["Blood pressure"], commonDosing: [DoseFact(context: "Angina", dose: "20–40 mg PO TID with nitrate-free interval")]),
            Drug(id: "d67", genericName: "Ranolazine", brandName: "Ranexa", drugClass: "Late Sodium Current Inhibitor", suffix: "", indications: ["Chronic stable angina (add-on)"], sideEffects: ["Dizziness", "Nausea", "Constipation", "QT prolongation"], clinicalPearls: ["Does NOT significantly affect HR or BP", "Add-on for refractory angina", "CYP3A4 substrate"], majorContraindications: ["Strong CYP3A4 inhibitors", "Hepatic cirrhosis"], monitoring: ["ECG (QT interval)"], commonDosing: [DoseFact(context: "Standard", dose: "500 mg PO BID, may increase to 1000 mg BID")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2e_1", title: "Nitrates: Vasodilators for Angina", content: "Nitrates release nitric oxide, causing vasodilation.", bulletPoints: ["SL NTG: acute relief in 1-3 minutes", "Max 3 SL doses, 5 min apart - then call 911", "NEVER combine with PDE-5 inhibitors", "Long-acting nitrates need nitrate-free interval"], highlightText: "Nitrates + PDE-5 inhibitors = SEVERE hypotension"),
        ])

        let sub2f = Subsection(id: "2f", moduleId: "m2", code: "2f", title: "Anti-Arrhythmics", description: "Amiodarone, Digoxin, Adenosine & More", iconName: "waveform.path.ecg.rectangle.fill", drugs: [
            Drug(id: "d68", genericName: "Amiodarone", brandName: "Cordarone/Pacerone", drugClass: "Class III Antiarrhythmic", suffix: "", indications: ["AFib", "VTach", "VFib", "ACLS"], sideEffects: ["Pulmonary toxicity", "Thyroid dysfunction (hypo or hyper)", "Hepatotoxicity", "Corneal deposits", "Blue-gray skin discoloration", "QT prolongation"], clinicalPearls: ["Most effective but most toxic antiarrhythmic", "Half-life 40–55 days", "Contains iodine — affects thyroid", "Increases warfarin effect (check INR)"], blackBoxWarnings: ["Pulmonary toxicity (potentially fatal)", "Hepatotoxicity", "Proarrhythmia"], majorContraindications: ["Severe sinus-node dysfunction", "2nd/3rd degree AV block without pacemaker"], monitoring: ["TFTs (thyroid)", "LFTs (liver)", "PFTs (lung)", "Eye exams (corneal deposits)", "ECG (QT interval)"], commonDosing: [DoseFact(context: "AFib loading (oral)", dose: "400–800 mg/day × 1–3 weeks"), DoseFact(context: "Maintenance", dose: "100–200 mg PO daily")]),
            Drug(id: "d69", genericName: "Dronedarone", brandName: "Multaq", drugClass: "Class III Antiarrhythmic", suffix: "", indications: ["AFib (rate/rhythm control in paroxysmal or persistent)"], sideEffects: ["GI upset", "Bradycardia", "QT prolongation"], clinicalPearls: ["Structurally similar to amiodarone but fewer thyroid/pulmonary toxicities", "No iodine moiety"], blackBoxWarnings: ["Contraindicated in permanent AFib", "Contraindicated in NYHA class IV HF or recent decompensation"], majorContraindications: ["Permanent AFib", "NYHA class IV HF", "Severe hepatic impairment"], monitoring: ["LFTs", "ECG", "Signs of HF worsening"], commonDosing: [DoseFact(context: "Standard", dose: "400 mg PO BID with meals")]),
            Drug(id: "d70", genericName: "Sotalol", brandName: "Betapace", drugClass: "Class III Antiarrhythmic + Beta Blocker", suffix: "-olol", indications: ["AFib", "VTach"], sideEffects: ["Bradycardia", "QT prolongation", "Torsades de Pointes", "Fatigue"], clinicalPearls: ["Both beta blocker AND class III antiarrhythmic", "Must initiate in hospital with ECG monitoring", "Renally cleared — dose adjust for renal impairment"], majorContraindications: ["Baseline QT prolongation", "Severe bradycardia", "Decompensated HF", "Bronchial asthma"], monitoring: ["ECG/QTc", "Renal function", "Heart rate", "Electrolytes (K+, Mg2+)"], commonDosing: [DoseFact(context: "AFib", dose: "80 mg PO BID, titrate based on QTc"), DoseFact(context: "Max", dose: "160 mg PO BID")]),
            Drug(id: "d71", genericName: "Flecainide", brandName: "Tambocor", drugClass: "Class IC Antiarrhythmic", suffix: "", indications: ["AFib (no structural heart disease)", "SVT"], sideEffects: ["Proarrhythmic (ventricular arrhythmias)", "Dizziness", "Visual disturbances"], clinicalPearls: ["Avoid in structural heart disease or CAD (proarrhythmic risk)", "Strong sodium-channel blocker — can widen QRS"], majorContraindications: ["Structural heart disease", "CAD or prior MI", "2nd/3rd degree AV block"], monitoring: ["ECG (QRS width, PR interval)", "Heart rate"], commonDosing: [DoseFact(context: "AFib", dose: "50–150 mg PO BID")]),
            Drug(id: "d72", genericName: "Digoxin", brandName: "Lanoxin", drugClass: "Cardiac Glycoside", suffix: "", indications: ["HFrEF (symptom support)", "AFib (rate control)"], sideEffects: ["Nausea/vomiting", "Visual changes (yellow-green halos)", "Arrhythmias", "Fatigue"], clinicalPearls: ["Narrow therapeutic index (0.5–2 ng/mL)", "Toxicity increased by hypokalemia", "Antidote: digoxin immune Fab", "Inhibits Na+/K+-ATPase"], majorContraindications: ["Ventricular fibrillation", "Hypokalemia (increases toxicity risk)"], monitoring: ["Serum digoxin level", "Serum potassium", "Renal function", "Heart rate/ECG"], commonDosing: [DoseFact(context: "Maintenance", dose: "0.125–0.25 mg PO daily")]),
            Drug(id: "d73", genericName: "Adenosine", brandName: "Adenocard", drugClass: "Endogenous Nucleoside", suffix: "", indications: ["SVT (acute conversion)"], sideEffects: ["Flushing", "Chest tightness", "Transient asystole", "Dyspnea"], clinicalPearls: ["Half-life < 10 seconds", "Rapid IV push with flush", "Caffeine/theophylline can antagonize effect", "Dipyridamole potentiates effect"], majorContraindications: ["2nd/3rd degree AV block (without pacemaker)", "Sick sinus syndrome"], monitoring: ["Continuous ECG during administration", "Blood pressure"], commonDosing: [DoseFact(context: "Adult SVT", dose: "6 mg rapid IV push; if no response, 12 mg × 1–2")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls2f_1", title: "Amiodarone & Key Antiarrhythmics", content: "Amiodarone is the most effective antiarrhythmic but comes with significant toxicity.", bulletPoints: ["Amiodarone: half-life 40-55 days, monitor thyroid/liver/lungs/eyes", "Digoxin: narrow index 0.5-2 ng/mL, toxicity ↑ by low K+", "Adenosine: ultra-short acting (< 10 sec), first-line for SVT", "Sotalol: beta blocker + class III, initiate in hospital"], highlightText: "Amiodarone: monitor Thyroid, Liver, Lungs, Eyes"),
        ])

        let sub2g = Subsection(id: "2g", moduleId: "m2", code: "2g", title: "Mastering Cardiovascular II", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m2", number: 2, title: "Cardiovascular II", subtitle: "Lipids, Thrombosis & Rhythm", iconName: "drop.triangle.fill", accentColorHex: "1565C0", subsections: [sub2a, sub2b, sub2c, sub2d, sub2e, sub2f, sub2g])
    }

    // MARK: - Module 3: Endocrine & Diabetes
    static func buildModule3() -> DrugModule {
        let sub3a = Subsection(id: "3a", moduleId: "m3", code: "3a", title: "Insulin Overview", description: "Basal & Bolus insulin therapy", iconName: "syringe.fill", drugs: [
            Drug(id: "d46", genericName: "Insulin glargine", brandName: "Lantus", drugClass: "Long-acting Insulin", suffix: "", indications: ["T1DM", "T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["Peakless, 24-hour duration", "Cannot mix with other insulins"]),
            Drug(id: "d47", genericName: "Insulin lispro", brandName: "Humalog", drugClass: "Rapid-acting Insulin", suffix: "", indications: ["T1DM", "T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["Onset 15 min, peak 1-2 hours", "Give within 15 min of meals"]),
            Drug(id: "d48", genericName: "Insulin aspart", brandName: "NovoLog", drugClass: "Rapid-acting Insulin", suffix: "", indications: ["T1DM", "T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["Similar to lispro", "Can be used in insulin pumps"]),
            Drug(id: "d49", genericName: "Insulin detemir", brandName: "Levemir", drugClass: "Long-acting Insulin", suffix: "", indications: ["T1DM", "T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["May need BID dosing"]),
            Drug(id: "d50", genericName: "Regular insulin", brandName: "Humulin R/Novolin R", drugClass: "Short-acting Insulin", suffix: "", indications: ["T1DM", "T2DM", "DKA", "Hyperkalemia"], sideEffects: ["Hypoglycemia"], clinicalPearls: ["Only insulin for IV use", "Onset 30 min"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3a_1", title: "Insulin Types", content: "Know the onset, peak, and duration.", bulletPoints: ["Rapid-acting (lispro, aspart): onset 15 min, peak 1-2h", "Short-acting (regular): onset 30 min, peak 2-4h", "Long-acting (glargine, detemir): peakless, 24h duration", "Only REGULAR insulin can be given IV"], highlightText: "Rapid = 15 min | Short = 30 min | Long = 24h"),
        ])

        let sub3b = Subsection(id: "3b", moduleId: "m3", code: "3b", title: "Metformin & Oral Agents", description: "Foundation of T2DM management", iconName: "pill.circle.fill", drugs: [
            Drug(id: "d45", genericName: "Metformin", brandName: "Glucophage", drugClass: "Biguanide", suffix: "", indications: ["T2DM"], sideEffects: ["GI upset", "Lactic acidosis (rare)", "B12 deficiency"], clinicalPearls: ["First-line for T2DM", "Hold before contrast dye", "Contraindicated if eGFR < 30"]),
            Drug(id: "d58", genericName: "Pioglitazone", brandName: "Actos", drugClass: "Thiazolidinedione", suffix: "", indications: ["T2DM"], sideEffects: ["Weight gain", "Edema", "HF exacerbation", "Bone fractures"], clinicalPearls: ["Insulin sensitizer (PPARg agonist)", "Contraindicated in NYHA Class III-IV HF"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3b_1", title: "Metformin: First-Line for T2DM", content: "Metformin decreases hepatic glucose production.", bulletPoints: ["First-line for ALL T2DM patients", "Does NOT cause hypoglycemia when used alone", "GI side effects common - titrate slowly", "Hold if eGFR < 30 or before IV contrast"], highlightText: "Metformin = First-line T2DM, NO hypoglycemia risk"),
        ])

        let sub3c = Subsection(id: "3c", moduleId: "m3", code: "3c", title: "SGLT2 Inhibitors", description: "Empagliflozin and Dapagliflozin", iconName: "drop.fill", drugs: [
            Drug(id: "d51", genericName: "Empagliflozin", brandName: "Jardiance", drugClass: "SGLT2 Inhibitor", suffix: "-gliflozin", indications: ["T2DM", "HFrEF", "CKD"], sideEffects: ["UTIs", "Genital mycotic infections", "DKA"], clinicalPearls: ["CV and renal benefits", "Blocks glucose reabsorption in kidney"]),
            Drug(id: "d52", genericName: "Dapagliflozin", brandName: "Farxiga", drugClass: "SGLT2 Inhibitor", suffix: "-gliflozin", indications: ["T2DM", "HF", "CKD"], sideEffects: ["UTIs", "Genital mycotic infections"], clinicalPearls: ["Benefits even in non-diabetic HF/CKD"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3c_1", title: "SGLT2 Inhibitors", content: "Block glucose reabsorption in the kidney.", bulletPoints: ["All end in -gliflozin", "CV benefit, renal protection, weight loss", "Risk of genital mycotic infections and UTIs", "Rare euglycemic DKA"], highlightText: "-gliflozin = SGLT2 Inhibitor"),
        ])

        let sub3d = Subsection(id: "3d", moduleId: "m3", code: "3d", title: "GLP-1, DPP-4, Sulfonylureas", description: "High-yield oral and injectable antidiabetics", iconName: "pill.fill", drugs: [
            Drug(id: "d53", genericName: "Semaglutide", brandName: "Ozempic/Wegovy", drugClass: "GLP-1 Receptor Agonist", suffix: "-glutide", indications: ["T2DM", "Obesity"], sideEffects: ["Nausea", "Vomiting", "Pancreatitis risk"], clinicalPearls: ["Weekly injection", "Significant weight loss", "Oral form available (Rybelsus)"]),
            Drug(id: "d54", genericName: "Liraglutide", brandName: "Victoza/Saxenda", drugClass: "GLP-1 Receptor Agonist", suffix: "-glutide", indications: ["T2DM", "Obesity"], sideEffects: ["Nausea", "Pancreatitis risk"], clinicalPearls: ["CV benefit", "Daily injection"]),
            Drug(id: "d55", genericName: "Sitagliptin", brandName: "Januvia", drugClass: "DPP-4 Inhibitor", suffix: "-gliptin", indications: ["T2DM"], sideEffects: ["Nasopharyngitis", "Pancreatitis risk"], clinicalPearls: ["Weight neutral", "Dose adjust for renal impairment"]),
            Drug(id: "d56", genericName: "Glipizide", brandName: "Glucotrol", drugClass: "Sulfonylurea", suffix: "", indications: ["T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["Stimulates insulin release", "Take 30 min before meals"]),
            Drug(id: "d57", genericName: "Glimepiride", brandName: "Amaryl", drugClass: "Sulfonylurea", suffix: "", indications: ["T2DM"], sideEffects: ["Hypoglycemia", "Weight gain"], clinicalPearls: ["Once daily dosing"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3d_1", title: "GLP-1 RAs & DPP-4 Inhibitors", content: "Newer agents with CV and weight benefits.", bulletPoints: ["GLP-1 RA (-glutide): incretin mimetics, weight loss, CV benefit", "DPP-4 inhibitors (-gliptin): weight neutral, low hypoglycemia", "Sulfonylureas: cheap but cause hypoglycemia + weight gain"], highlightText: "GLP-1 RA: weight loss + CV benefit"),
        ])

        let sub3e = Subsection(id: "3e", moduleId: "m3", code: "3e", title: "Thyroid Agents", description: "Levothyroxine, Methimazole, PTU", iconName: "brain.head.profile.fill", drugs: [
            Drug(id: "d59", genericName: "Levothyroxine", brandName: "Synthroid", drugClass: "Thyroid Hormone", suffix: "", indications: ["Hypothyroidism", "TSH suppression"], sideEffects: ["Tachycardia", "Tremor", "Weight loss (if overdosed)"], clinicalPearls: ["Take on empty stomach, 30-60 min before food", "Separate from calcium, iron by 4 hours", "Most prescribed drug in US"]),
            Drug(id: "d60", genericName: "Liothyronine", brandName: "Cytomel", drugClass: "Thyroid Hormone (T3)", suffix: "", indications: ["Hypothyroidism", "Myxedema coma"], sideEffects: ["Tachycardia"], clinicalPearls: ["Active T3 form", "Shorter half-life than T4"]),
            Drug(id: "d61", genericName: "Methimazole", brandName: "Tapazole", drugClass: "Thionamide", suffix: "", indications: ["Hyperthyroidism", "Graves' disease"], sideEffects: ["Agranulocytosis", "Hepatotoxicity", "Rash"], clinicalPearls: ["Preferred over PTU (less hepatotoxicity)"]),
            Drug(id: "d62", genericName: "Propylthiouracil (PTU)", brandName: "PTU", drugClass: "Thionamide", suffix: "", indications: ["Hyperthyroidism (1st trimester)", "Thyroid storm"], sideEffects: ["Agranulocytosis", "Hepatotoxicity (severe)"], clinicalPearls: ["Preferred in 1st trimester pregnancy", "Also blocks T4→T3 conversion"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3e_1", title: "Thyroid Medications", content: "Key drugs for hypo- and hyperthyroidism.", bulletPoints: ["Levothyroxine: synthetic T4, first-line for hypothyroidism", "Take on empty stomach, separate from calcium/iron by 4 hours", "Methimazole: first-line for hyperthyroidism", "PTU: preferred in 1st trimester pregnancy and thyroid storm"], highlightText: "Levothyroxine = empty stomach, separate from Ca/Fe"),
        ])

        let sub3f = Subsection(id: "3f", moduleId: "m3", code: "3f", title: "Adrenal Steroids", description: "Systemic Corticosteroids", iconName: "cross.vial.fill", drugs: [
            Drug(id: "d163", genericName: "Prednisone", brandName: "Deltasone", drugClass: "Corticosteroid", suffix: "", indications: ["Inflammatory conditions", "Autoimmune diseases", "Asthma exacerbations"], sideEffects: ["Hyperglycemia", "Osteoporosis", "Adrenal suppression", "Cushing syndrome"], clinicalPearls: ["Taper slowly if used >2 weeks", "Take in the morning"]),
            Drug(id: "d164", genericName: "Methylprednisolone", brandName: "Medrol/Solu-Medrol", drugClass: "Corticosteroid", suffix: "", indications: ["Acute inflammation", "MS exacerbations"], sideEffects: ["Hyperglycemia", "Insomnia", "GI upset"], clinicalPearls: ["IV (Solu-Medrol) for acute flares"]),
            Drug(id: "d165", genericName: "Dexamethasone", brandName: "Decadron", drugClass: "Corticosteroid", suffix: "", indications: ["Cerebral edema", "Croup", "Chemotherapy N/V"], sideEffects: ["Hyperglycemia", "Insomnia"], clinicalPearls: ["Most potent corticosteroid", "Long half-life (36-72 hours)", "No mineralocorticoid activity"]),
            Drug(id: "d166", genericName: "Hydrocortisone", brandName: "Cortef/Solu-Cortef", drugClass: "Corticosteroid", suffix: "", indications: ["Adrenal insufficiency", "Inflammatory conditions"], sideEffects: ["Fluid retention", "Hyperglycemia"], clinicalPearls: ["Physiologic replacement for adrenal insufficiency", "Most mineralocorticoid activity"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls3f_1", title: "Systemic Corticosteroids", content: "Anti-inflammatory powerhouses with significant side effects.", bulletPoints: ["Taper slowly if used >2 weeks (adrenal suppression)", "Side effects: hyperglycemia, osteoporosis, Cushing's", "Potency: dexamethasone > methylpred > prednisone > hydrocortisone", "Take in the morning to mimic natural cortisol"], highlightText: "Corticosteroids: TAPER if >2 weeks"),
        ])

        let sub3g = Subsection(id: "3g", moduleId: "m3", code: "3g", title: "Mastering Endocrine & Diabetes", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m3", number: 3, title: "Endocrine & Diabetes", subtitle: "Insulin, Metformin & More", iconName: "syringe.fill", accentColorHex: "6A1B9A", subsections: [sub3a, sub3b, sub3c, sub3d, sub3e, sub3f, sub3g])
    }

    // MARK: - Module 4: CNS & Psych
    static func buildModule4() -> DrugModule {
        let sub4a = Subsection(id: "4a", moduleId: "m4", code: "4a", title: "Antidepressants I (SSRIs, SNRIs)", description: "First-line antidepressants", iconName: "brain.fill", drugs: [
            Drug(id: "d74", genericName: "Sertraline", brandName: "Zoloft", drugClass: "SSRI", suffix: "", indications: ["MDD", "OCD", "PTSD", "Panic disorder"], sideEffects: ["Nausea", "Diarrhea", "Sexual dysfunction", "Insomnia"], clinicalPearls: ["Most prescribed antidepressant", "Preferred SSRI in cardiac patients"]),
            Drug(id: "d75", genericName: "Fluoxetine", brandName: "Prozac", drugClass: "SSRI", suffix: "", indications: ["MDD", "OCD", "Bulimia", "Panic disorder"], sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction"], clinicalPearls: ["Longest half-life SSRI (2-6 days)", "Strong CYP2D6 inhibitor"]),
            Drug(id: "d76", genericName: "Escitalopram", brandName: "Lexapro", drugClass: "SSRI", suffix: "", indications: ["MDD", "GAD"], sideEffects: ["Nausea", "Sexual dysfunction", "QT prolongation at high doses"], clinicalPearls: ["Fewest drug interactions among SSRIs"]),
            Drug(id: "d77", genericName: "Paroxetine", brandName: "Paxil", drugClass: "SSRI", suffix: "", indications: ["MDD", "GAD", "OCD", "PTSD"], sideEffects: ["Weight gain", "Sedation", "Sexual dysfunction"], clinicalPearls: ["Most anticholinergic SSRI", "Worst withdrawal syndrome", "Avoid in pregnancy (category D)"]),
            Drug(id: "d78", genericName: "Venlafaxine", brandName: "Effexor XR", drugClass: "SNRI", suffix: "", indications: ["MDD", "GAD", "Neuropathic pain"], sideEffects: ["Nausea", "Hypertension", "Sexual dysfunction"], clinicalPearls: ["Monitor blood pressure"]),
            Drug(id: "d79", genericName: "Duloxetine", brandName: "Cymbalta", drugClass: "SNRI", suffix: "", indications: ["MDD", "GAD", "Neuropathic pain", "Fibromyalgia"], sideEffects: ["Nausea", "Dizziness", "Hepatotoxicity"], clinicalPearls: ["Avoid if hepatic impairment"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls4a_1", title: "SSRIs: First-Line for Depression", content: "SSRIs selectively block serotonin reuptake.", bulletPoints: ["First-line for MDD, anxiety, OCD, PTSD", "Takes 4-6 weeks for full effect", "Common: GI upset, sexual dysfunction, insomnia", "Risk of serotonin syndrome if combined with MAOIs"], highlightText: "SSRIs: 4-6 weeks for full effect"),
            LearningSlide(id: "ls4a_2", title: "SNRIs: Dual Action", content: "SNRIs block reuptake of serotonin AND norepinephrine.", bulletPoints: ["Venlafaxine: monitor BP (dose-dependent HTN)", "Duloxetine: also treats neuropathic pain and fibromyalgia", "Both have significant withdrawal if stopped abruptly"], highlightText: "SNRIs = Serotonin + Norepinephrine"),
        ])

        let sub4b = Subsection(id: "4b", moduleId: "m4", code: "4b", title: "Antidepressants II + Mood Stabilizers", description: "TCAs, Atypicals, Lithium", iconName: "brain.head.profile.fill", drugs: [
            Drug(id: "d201", genericName: "Amitriptyline", brandName: "Elavil", drugClass: "TCA", suffix: "", indications: ["MDD", "Neuropathic pain", "Migraine prophylaxis"], sideEffects: ["Sedation", "Anticholinergic effects", "Weight gain", "QT prolongation"], clinicalPearls: ["Most anticholinergic TCA", "Avoid in elderly"]),
            Drug(id: "d202", genericName: "Bupropion", brandName: "Wellbutrin/Zyban", drugClass: "NDRI", suffix: "", indications: ["MDD", "Smoking cessation", "Seasonal affective disorder"], sideEffects: ["Insomnia", "Seizures", "Dry mouth"], clinicalPearls: ["NO sexual dysfunction or weight gain", "Lowers seizure threshold", "Contraindicated in eating disorders"]),
            Drug(id: "d203", genericName: "Buspirone", brandName: "BuSpar", drugClass: "5-HT1A Partial Agonist", suffix: "", indications: ["GAD"], sideEffects: ["Dizziness", "Nausea", "Headache"], clinicalPearls: ["Non-sedating, non-addictive anxiolytic", "Takes 2-4 weeks for effect"]),
            Drug(id: "d204", genericName: "Citalopram", brandName: "Celexa", drugClass: "SSRI", suffix: "", indications: ["MDD"], sideEffects: ["Nausea", "QT prolongation", "Sexual dysfunction"], clinicalPearls: ["Max 40mg due to QT prolongation risk", "Max 20mg in elderly"]),
            Drug(id: "d205", genericName: "Clonazepam", brandName: "Klonopin", drugClass: "Benzodiazepine", suffix: "-lam/-pam", indications: ["Panic disorder", "Seizures"], sideEffects: ["Sedation", "Dependence"], clinicalPearls: ["Long-acting benzodiazepine", "Also used for seizures"]),
            Drug(id: "d206", genericName: "Desvenlafaxine", brandName: "Pristiq", drugClass: "SNRI", suffix: "", indications: ["MDD"], sideEffects: ["Nausea", "Dizziness", "Insomnia"], clinicalPearls: ["Active metabolite of venlafaxine", "Fixed dose 50mg"]),
            Drug(id: "d207", genericName: "Doxepin", brandName: "Sinequan/Silenor", drugClass: "TCA", suffix: "", indications: ["MDD", "Insomnia", "Pruritus"], sideEffects: ["Sedation", "Anticholinergic effects", "Weight gain"], clinicalPearls: ["Low-dose (Silenor) for insomnia", "Highly sedating"]),
            Drug(id: "d208", genericName: "Hydroxyzine", brandName: "Vistaril/Atarax", drugClass: "Antihistamine", suffix: "", indications: ["Anxiety", "Pruritus", "Insomnia"], sideEffects: ["Sedation", "Dry mouth", "QT prolongation"], clinicalPearls: ["Non-addictive anxiolytic", "Also used as antipruritic"]),
            Drug(id: "d92", genericName: "Lithium", brandName: "Lithobid", drugClass: "Mood Stabilizer", suffix: "", indications: ["Bipolar disorder"], sideEffects: ["Tremor", "Polyuria", "Hypothyroidism", "Nephrogenic DI", "Teratogenic (Ebstein anomaly)"], clinicalPearls: ["Narrow therapeutic index: 0.6-1.2 mEq/L", "Monitor levels, renal, thyroid", "Avoid NSAIDs, ACEi, thiazides"]),
            Drug(id: "d209", genericName: "Mirtazapine", brandName: "Remeron", drugClass: "Atypical Antidepressant", suffix: "", indications: ["MDD", "Insomnia", "Appetite stimulation"], sideEffects: ["Sedation", "Weight gain", "Increased appetite"], clinicalPearls: ["Sedating at low doses (7.5-15mg)", "Good for insomnia + poor appetite"]),
            Drug(id: "d210", genericName: "Nortriptyline", brandName: "Pamelor", drugClass: "TCA", suffix: "", indications: ["MDD", "Neuropathic pain"], sideEffects: ["Anticholinergic effects", "Sedation"], clinicalPearls: ["Less anticholinergic than amitriptyline", "Therapeutic drug monitoring available"]),
            Drug(id: "d211", genericName: "Trazodone", brandName: "Desyrel", drugClass: "SARI", suffix: "", indications: ["MDD", "Insomnia (off-label)"], sideEffects: ["Sedation", "Orthostatic hypotension", "Priapism (rare)"], clinicalPearls: ["Most commonly used as sleep aid at low doses", "Priapism is rare but serious"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls4b_1", title: "TCAs & Atypical Antidepressants", content: "Older antidepressants with unique roles.", bulletPoints: ["TCAs (amitriptyline, nortriptyline): effective but anticholinergic", "Bupropion: NO sexual dysfunction, smoking cessation", "Mirtazapine: sedating + appetite stimulant", "Trazodone: most common off-label sleep aid"], highlightText: "Bupropion: NO sexual dysfunction, lowers seizure threshold"),
            LearningSlide(id: "ls4b_2", title: "Lithium: The Gold Standard for Bipolar", content: "Lithium remains the gold standard mood stabilizer.", bulletPoints: ["Narrow therapeutic index: 0.6-1.2 mEq/L", "Monitor: levels, renal function, thyroid", "Avoid NSAIDs, ACE inhibitors, thiazides (↑ levels)", "Teratogenic: Ebstein anomaly"], highlightText: "Lithium: 0.6-1.2 mEq/L, avoid NSAIDs"),
        ])

        let sub4c = Subsection(id: "4c", moduleId: "m4", code: "4c", title: "Antipsychotics", description: "Typical and atypical antipsychotics", iconName: "person.fill.questionmark", drugs: [
            Drug(id: "d86", genericName: "Quetiapine", brandName: "Seroquel", drugClass: "Atypical Antipsychotic", suffix: "", indications: ["Schizophrenia", "Bipolar disorder", "MDD (adjunct)"], sideEffects: ["Sedation", "Weight gain", "Metabolic syndrome"], clinicalPearls: ["Most sedating atypical"]),
            Drug(id: "d87", genericName: "Risperidone", brandName: "Risperdal", drugClass: "Atypical Antipsychotic", suffix: "", indications: ["Schizophrenia", "Bipolar mania", "Irritability in autism"], sideEffects: ["EPS", "Hyperprolactinemia", "Weight gain"], clinicalPearls: ["Most likely atypical to cause EPS"]),
            Drug(id: "d88", genericName: "Aripiprazole", brandName: "Abilify", drugClass: "Atypical Antipsychotic", suffix: "", indications: ["Schizophrenia", "Bipolar disorder", "MDD (adjunct)"], sideEffects: ["Akathisia", "Insomnia"], clinicalPearls: ["Partial D2 agonist (unique)", "Weight-neutral"]),
            Drug(id: "d89", genericName: "Olanzapine", brandName: "Zyprexa", drugClass: "Atypical Antipsychotic", suffix: "", indications: ["Schizophrenia", "Bipolar disorder"], sideEffects: ["Significant weight gain", "Metabolic syndrome", "Sedation"], clinicalPearls: ["Highest metabolic risk"]),
            Drug(id: "d90", genericName: "Clozapine", brandName: "Clozaril", drugClass: "Atypical Antipsychotic", suffix: "", indications: ["Treatment-resistant schizophrenia"], sideEffects: ["Agranulocytosis", "Seizures", "Myocarditis", "Metabolic syndrome"], clinicalPearls: ["Gold standard for treatment-resistant schizophrenia", "REMS: mandatory ANC monitoring"]),
            Drug(id: "d91", genericName: "Haloperidol", brandName: "Haldol", drugClass: "Typical Antipsychotic", suffix: "", indications: ["Schizophrenia", "Acute psychosis", "Tourette's"], sideEffects: ["EPS", "Tardive dyskinesia", "NMS", "QT prolongation"], clinicalPearls: ["High-potency typical", "High EPS risk"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls4c_1", title: "Typical vs Atypical Antipsychotics", content: "Antipsychotics block dopamine D2 receptors.", bulletPoints: ["Typical (1st gen): haloperidol - high EPS risk", "Atypical (2nd gen): less EPS but more metabolic effects", "NMS: fever, rigidity, AMS - medical emergency", "Clozapine: REMS required, monitor ANC"], highlightText: "Typical = EPS | Atypical = Metabolic"),
        ])

        let sub4d = Subsection(id: "4d", moduleId: "m4", code: "4d", title: "Anxiolytics & Sedatives", description: "Benzos, Z-drugs, Sleep aids", iconName: "moon.fill", drugs: [
            Drug(id: "d80", genericName: "Alprazolam", brandName: "Xanax", drugClass: "Benzodiazepine", suffix: "-lam/-pam", indications: ["Panic disorder", "GAD"], sideEffects: ["Sedation", "Dependence", "Respiratory depression"], clinicalPearls: ["High abuse potential", "Short-acting"]),
            Drug(id: "d81", genericName: "Lorazepam", brandName: "Ativan", drugClass: "Benzodiazepine", suffix: "-lam/-pam", indications: ["Anxiety", "Status epilepticus", "Alcohol withdrawal"], sideEffects: ["Sedation", "Dependence", "Amnesia"], clinicalPearls: ["LOT drugs: no active metabolites", "Preferred in liver disease"]),
            Drug(id: "d82", genericName: "Diazepam", brandName: "Valium", drugClass: "Benzodiazepine", suffix: "-lam/-pam", indications: ["Anxiety", "Muscle spasm", "Seizures", "Alcohol withdrawal"], sideEffects: ["Sedation", "Dependence"], clinicalPearls: ["Very long-acting (active metabolites)"]),
            Drug(id: "d83", genericName: "Midazolam", brandName: "Versed", drugClass: "Benzodiazepine", suffix: "-lam/-pam", indications: ["Procedural sedation", "Status epilepticus"], sideEffects: ["Respiratory depression", "Amnesia"], clinicalPearls: ["Ultra-short acting", "Intranasal for seizures"]),
            Drug(id: "d84", genericName: "Zolpidem", brandName: "Ambien", drugClass: "Non-benzodiazepine hypnotic", suffix: "", indications: ["Insomnia"], sideEffects: ["Somnambulism", "Complex sleep behaviors"], clinicalPearls: ["Z-drug: binds GABA-A selectively", "Lower dose for women (FDA)"]),
            Drug(id: "d85", genericName: "Suvorexant", brandName: "Belsomra", drugClass: "Orexin Receptor Antagonist", suffix: "", indications: ["Insomnia"], sideEffects: ["Daytime somnolence", "Sleep paralysis"], clinicalPearls: ["Blocks orexin (wakefulness neuropeptide)"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls4d_1", title: "Benzodiazepines", content: "Enhance GABA-A receptor activity.", bulletPoints: ["All contain -lam or -pam", "Reversal agent: FLUMAZENIL", "LOT drugs preferred in liver disease", "Schedule IV controlled substances"], highlightText: "Benzo reversal = Flumazenil"),
        ])

        let sub4e = Subsection(id: "4e", moduleId: "m4", code: "4e", title: "Stimulants & ADHD Meds", description: "Amphetamines, Methylphenidate & more", iconName: "bolt.fill", drugs: [
            Drug(id: "d212", genericName: "Amphetamine/dextroamphetamine", brandName: "Adderall", drugClass: "Amphetamine", suffix: "", indications: ["ADHD", "Narcolepsy"], sideEffects: ["Insomnia", "Decreased appetite", "Tachycardia", "Growth suppression"], clinicalPearls: ["Schedule II controlled substance", "Mixed amphetamine salts"]),
            Drug(id: "d213", genericName: "Atomoxetine", brandName: "Strattera", drugClass: "SNRI (selective NRI)", suffix: "", indications: ["ADHD"], sideEffects: ["Decreased appetite", "Nausea", "Suicidal ideation (Black Box)"], clinicalPearls: ["Non-stimulant ADHD option", "Not a controlled substance"], blackBoxWarnings: ["Suicidal ideation in children/adolescents"]),
            Drug(id: "d214", genericName: "Dexmethylphenidate", brandName: "Focalin", drugClass: "Methylphenidate derivative", suffix: "", indications: ["ADHD"], sideEffects: ["Insomnia", "Decreased appetite", "Tachycardia"], clinicalPearls: ["D-isomer of methylphenidate", "More potent mg-for-mg"]),
            Drug(id: "d215", genericName: "Guanfacine ER", brandName: "Intuniv", drugClass: "Alpha-2 Agonist", suffix: "", indications: ["ADHD"], sideEffects: ["Somnolence", "Hypotension", "Bradycardia"], clinicalPearls: ["Non-stimulant", "Also used for tic disorders"]),
            Drug(id: "d216", genericName: "Lisdexamfetamine", brandName: "Vyvanse", drugClass: "Amphetamine prodrug", suffix: "", indications: ["ADHD", "Binge eating disorder"], sideEffects: ["Insomnia", "Decreased appetite", "Tachycardia"], clinicalPearls: ["Prodrug - less abuse potential than Adderall", "Schedule II"]),
            Drug(id: "d217", genericName: "Methylphenidate", brandName: "Ritalin/Concerta", drugClass: "Methylphenidate", suffix: "", indications: ["ADHD", "Narcolepsy"], sideEffects: ["Insomnia", "Decreased appetite", "Growth suppression", "Tachycardia"], clinicalPearls: ["Most commonly prescribed stimulant", "Multiple formulations (IR, ER, patch)"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls4e_1", title: "ADHD Medications", content: "Stimulants are first-line for ADHD.", bulletPoints: ["Methylphenidate (Ritalin/Concerta): most prescribed stimulant", "Amphetamines (Adderall, Vyvanse): Schedule II", "Non-stimulants: atomoxetine, guanfacine ER", "Monitor: growth, HR, BP, appetite"], highlightText: "Stimulants = first-line ADHD treatment"),
        ])

        let sub4f = Subsection(id: "4f", moduleId: "m4", code: "4f", title: "Mastering CNS & Psych", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m4", number: 4, title: "CNS & Psych", subtitle: "Antidepressants, Anxiolytics & More", iconName: "brain.fill", accentColorHex: "00897B", subsections: [sub4a, sub4b, sub4c, sub4d, sub4e, sub4f])
    }

    // MARK: - Module 5: Pain, Inflammation & Rheum
    static func buildModule5() -> DrugModule {
        let sub5a = Subsection(id: "5a", moduleId: "m5", code: "5a", title: "NSAIDs & Acetaminophen", description: "Non-opioid analgesics and anti-inflammatories", iconName: "pill.fill", drugs: [
            Drug(id: "d155", genericName: "Acetaminophen", brandName: "Tylenol", drugClass: "Non-opioid Analgesic", suffix: "", indications: ["Pain", "Fever"], sideEffects: ["Hepatotoxicity (overdose)"], clinicalPearls: ["Max 4g/day (2g if liver disease)", "Antidote: N-acetylcysteine (NAC)", "Safe in pregnancy"]),
            Drug(id: "d218", genericName: "Acetaminophen/Butalbital/Caffeine", brandName: "Fioricet", drugClass: "Combination Analgesic", suffix: "", indications: ["Tension headache"], sideEffects: ["Sedation", "Rebound headache", "Hepatotoxicity (APAP)"], clinicalPearls: ["Butalbital is a barbiturate", "Risk of medication overuse headache"]),
            Drug(id: "d219", genericName: "Acetaminophen/Oxycodone", brandName: "Percocet", drugClass: "Opioid Combination", suffix: "", indications: ["Moderate-severe pain"], sideEffects: ["Respiratory depression", "Constipation", "Hepatotoxicity (APAP)"], clinicalPearls: ["Watch cumulative APAP dose (max 4g/day)", "Schedule II"]),
            Drug(id: "d154", genericName: "Celecoxib", brandName: "Celebrex", drugClass: "COX-2 Selective NSAID", suffix: "-coxib", indications: ["Osteoarthritis", "RA", "Pain"], sideEffects: ["CV risk", "GI effects (less than non-selective)"], clinicalPearls: ["Selective COX-2: less GI bleeding", "Avoid if sulfa allergy"]),
            Drug(id: "d220", genericName: "Diclofenac", brandName: "Voltaren", drugClass: "NSAID", suffix: "", indications: ["Pain", "Osteoarthritis", "Inflammation"], sideEffects: ["GI bleeding", "CV risk", "Hepatotoxicity"], clinicalPearls: ["Available as topical gel (Voltaren Gel)", "Oral and topical formulations"]),
            Drug(id: "d221", genericName: "Etodolac", brandName: "Lodine", drugClass: "NSAID", suffix: "", indications: ["Pain", "Osteoarthritis", "RA"], sideEffects: ["GI bleeding", "Renal impairment"], clinicalPearls: ["Somewhat COX-2 selective", "Less GI toxicity than some NSAIDs"]),
            Drug(id: "d152", genericName: "Ibuprofen", brandName: "Advil/Motrin", drugClass: "NSAID", suffix: "", indications: ["Pain", "Fever", "Inflammation"], sideEffects: ["GI bleeding", "Renal impairment", "CV risk"], clinicalPearls: ["Non-selective COX inhibitor", "Take with food"]),
            Drug(id: "d222", genericName: "Indomethacin", brandName: "Indocin", drugClass: "NSAID", suffix: "", indications: ["Gout (acute)", "PDA closure", "RA"], sideEffects: ["GI bleeding", "Headache", "Renal impairment"], clinicalPearls: ["Potent NSAID", "Used for acute gout and PDA closure in neonates"]),
            Drug(id: "d156", genericName: "Ketorolac", brandName: "Toradol", drugClass: "NSAID", suffix: "", indications: ["Moderate-severe acute pain"], sideEffects: ["GI bleeding", "Renal impairment"], clinicalPearls: ["IV/IM NSAID", "Limit to 5 days maximum"]),
            Drug(id: "d223", genericName: "Lidocaine (patch)", brandName: "Lidoderm", drugClass: "Local Anesthetic", suffix: "", indications: ["Postherpetic neuralgia", "Localized pain"], sideEffects: ["Skin irritation", "Rash"], clinicalPearls: ["Topical 5% patch", "Apply 12 hours on, 12 hours off"]),
            Drug(id: "d224", genericName: "Meloxicam", brandName: "Mobic", drugClass: "NSAID", suffix: "", indications: ["Osteoarthritis", "RA"], sideEffects: ["GI bleeding", "CV risk"], clinicalPearls: ["Preferentially COX-2 at low doses", "Once daily dosing"]),
            Drug(id: "d225", genericName: "Nabumetone", brandName: "Relafen", drugClass: "NSAID", suffix: "", indications: ["Osteoarthritis", "RA"], sideEffects: ["GI bleeding", "Renal impairment"], clinicalPearls: ["Prodrug", "Less GI toxicity than some NSAIDs"]),
            Drug(id: "d153", genericName: "Naproxen", brandName: "Aleve/Naprosyn", drugClass: "NSAID", suffix: "", indications: ["Pain", "Inflammation", "Gout"], sideEffects: ["GI bleeding", "Renal impairment"], clinicalPearls: ["Longer duration (q12h)", "Lowest CV risk among NSAIDs"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls5a_1", title: "NSAIDs: COX Inhibitors", content: "NSAIDs inhibit cyclooxygenase enzymes.", bulletPoints: ["Non-selective (ibuprofen, naproxen): block COX-1 and COX-2", "COX-2 selective (celecoxib): less GI bleeding", "All NSAIDs: GI + renal + CV risk", "Ketorolac (Toradol): IV NSAID, max 5 days"], highlightText: "NSAIDs: GI + Renal + CV risk"),
            LearningSlide(id: "ls5a_2", title: "Acetaminophen", content: "First-line analgesic/antipyretic without anti-inflammatory properties.", bulletPoints: ["Max 4g/day (2g if liver disease)", "Overdose antidote: N-acetylcysteine (NAC)", "No anti-inflammatory effect", "Safe in pregnancy"], highlightText: "APAP overdose = NAC antidote | Max 4g/day"),
        ])

        let sub5b = Subsection(id: "5b", moduleId: "m5", code: "5b", title: "Opioids & Pain Adjuncts", description: "Opioids, muscle relaxants, neuropathic agents", iconName: "cross.case.fill", drugs: [
            Drug(id: "d160", genericName: "Baclofen", brandName: "Lioresal", drugClass: "GABA-B Agonist", suffix: "", indications: ["Spasticity (MS, spinal cord injury)"], sideEffects: ["Sedation", "Weakness", "Withdrawal seizures"], clinicalPearls: ["Do NOT stop abruptly (withdrawal seizures)"]),
            Drug(id: "d158", genericName: "Cyclobenzaprine", brandName: "Flexeril", drugClass: "Muscle Relaxant", suffix: "", indications: ["Acute musculoskeletal pain"], sideEffects: ["Sedation", "Dry mouth", "Anticholinergic effects"], clinicalPearls: ["Structurally similar to TCAs", "Short-term use only"]),
            Drug(id: "d149", genericName: "Fentanyl", brandName: "Duragesic (patch)", drugClass: "Opioid Agonist", suffix: "", indications: ["Severe chronic pain", "Anesthesia"], sideEffects: ["Respiratory depression", "Bradycardia"], clinicalPearls: ["80-100x more potent than morphine", "Transdermal patch: 72-hour duration"]),
            Drug(id: "d161", genericName: "Gabapentin", brandName: "Neurontin", drugClass: "Gabapentinoid", suffix: "", indications: ["Neuropathic pain", "Postherpetic neuralgia", "Seizures"], sideEffects: ["Sedation", "Dizziness", "Peripheral edema", "Weight gain"], clinicalPearls: ["Dose adjust for renal impairment"]),
            Drug(id: "d148", genericName: "Hydrocodone/Acetaminophen", brandName: "Norco/Vicodin", drugClass: "Opioid Combination", suffix: "", indications: ["Moderate pain"], sideEffects: ["Respiratory depression", "Constipation", "Hepatotoxicity (APAP)"], clinicalPearls: ["Most prescribed opioid in US", "Watch APAP dose"]),
            Drug(id: "d159", genericName: "Methocarbamol", brandName: "Robaxin", drugClass: "Muscle Relaxant", suffix: "", indications: ["Acute musculoskeletal pain"], sideEffects: ["Sedation", "Dizziness"], clinicalPearls: ["Less sedating than cyclobenzaprine"]),
            Drug(id: "d146", genericName: "Morphine", brandName: "MS Contin", drugClass: "Opioid Agonist", suffix: "", indications: ["Severe pain", "Acute MI pain"], sideEffects: ["Respiratory depression", "Constipation", "Nausea", "Pruritus"], clinicalPearls: ["Gold standard opioid", "Accumulates in renal impairment"]),
            Drug(id: "d151", genericName: "Naloxone", brandName: "Narcan", drugClass: "Opioid Antagonist", suffix: "", indications: ["Opioid overdose reversal"], sideEffects: ["Acute withdrawal symptoms"], clinicalPearls: ["Intranasal or IV/IM", "Short duration - may need repeat doses"]),
            Drug(id: "d147", genericName: "Oxycodone", brandName: "OxyContin/Roxicodone", drugClass: "Opioid Agonist", suffix: "", indications: ["Moderate-severe pain"], sideEffects: ["Respiratory depression", "Constipation"], clinicalPearls: ["OxyContin = extended-release", "High abuse potential"]),
            Drug(id: "d162", genericName: "Pregabalin", brandName: "Lyrica", drugClass: "Gabapentinoid", suffix: "", indications: ["Neuropathic pain", "Fibromyalgia", "Seizures"], sideEffects: ["Sedation", "Dizziness", "Weight gain"], clinicalPearls: ["Schedule V", "FDA-approved for fibromyalgia"]),
            Drug(id: "d150", genericName: "Tramadol", brandName: "Ultram", drugClass: "Weak Opioid + SNRI", suffix: "", indications: ["Moderate pain"], sideEffects: ["Seizures", "Serotonin syndrome", "Nausea"], clinicalPearls: ["Dual mechanism: weak mu-agonist + SNRI", "Lowers seizure threshold"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls5b_1", title: "Opioid Pharmacology", content: "Opioids bind mu receptors for analgesia.", bulletPoints: ["All opioids: respiratory depression + constipation", "Morphine: gold standard, avoid in renal failure", "Fentanyl: 80-100x more potent than morphine", "Naloxone (Narcan): reverses opioid overdose"], highlightText: "ALL opioids: respiratory depression + constipation"),
            LearningSlide(id: "ls5b_2", title: "Neuropathic Pain & Muscle Relaxants", content: "Non-opioid adjuncts for pain management.", bulletPoints: ["Gabapentin/pregabalin: first-line for neuropathic pain", "Cyclobenzaprine: short-term muscle spasm only", "Baclofen: GABA-B agonist for spasticity, never stop abruptly"], highlightText: "Gabapentinoids: first-line for neuropathic pain"),
        ])

        let sub5c = Subsection(id: "5c", moduleId: "m5", code: "5c", title: "Gout Medications", description: "Allopurinol, Colchicine, Febuxostat", iconName: "figure.stand", drugs: [
            Drug(id: "d176", genericName: "Allopurinol", brandName: "Zyloprim", drugClass: "Xanthine Oxidase Inhibitor", suffix: "", indications: ["Chronic gout", "Hyperuricemia"], sideEffects: ["Rash", "SJS/TEN", "Hepatotoxicity"], clinicalPearls: ["Start low, go slow", "HLA-B*5801 testing in high-risk populations", "Do NOT start during acute flare"]),
            Drug(id: "d157", genericName: "Colchicine", brandName: "Colcrys", drugClass: "Anti-inflammatory (gout)", suffix: "", indications: ["Acute gout", "Gout prophylaxis", "Pericarditis"], sideEffects: ["Diarrhea", "Nausea", "Bone marrow suppression"], clinicalPearls: ["First-line for acute gout flares", "Also used for pericarditis"]),
            Drug(id: "d177", genericName: "Febuxostat", brandName: "Uloric", drugClass: "Xanthine Oxidase Inhibitor", suffix: "", indications: ["Chronic gout"], sideEffects: ["CV events", "Hepatotoxicity"], clinicalPearls: ["Alternative to allopurinol"], blackBoxWarnings: ["Increased CV death risk"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls5c_1", title: "Gout Management", content: "Acute flare treatment vs chronic urate-lowering.", bulletPoints: ["Colchicine: first-line for acute gout flares", "Allopurinol: first-line urate-lowering, start low go slow", "NEVER start allopurinol during acute gout flare", "HLA-B*5801 testing before allopurinol in at-risk populations"], highlightText: "Allopurinol: NOT during acute flare"),
        ])

        let sub5d = Subsection(id: "5d", moduleId: "m5", code: "5d", title: "DMARDs & Biologics", description: "Disease-modifying agents + immunosuppressants", iconName: "shield.lefthalf.filled", drugs: [
            Drug(id: "d169", genericName: "Adalimumab", brandName: "Humira", drugClass: "Anti-TNF Biologic", suffix: "", indications: ["RA", "Psoriasis", "Crohn's", "UC"], sideEffects: ["Infection risk", "Injection site reactions", "TB reactivation"], clinicalPearls: ["Most prescribed biologic worldwide", "Screen for TB before starting"]),
            Drug(id: "d181", genericName: "Azathioprine", brandName: "Imuran", drugClass: "Antimetabolite", suffix: "", indications: ["Transplant rejection", "RA", "IBD", "SLE"], sideEffects: ["Bone marrow suppression", "Hepatotoxicity"], clinicalPearls: ["Check TPMT before starting", "Avoid allopurinol (increases toxicity)"]),
            Drug(id: "d179", genericName: "Cyclosporine", brandName: "Neoral/Sandimmune", drugClass: "Calcineurin Inhibitor", suffix: "", indications: ["Transplant rejection", "RA", "Psoriasis"], sideEffects: ["Nephrotoxicity", "Hypertension", "Gingival hyperplasia", "Hirsutism"], clinicalPearls: ["Monitor trough levels", "Avoid grapefruit"]),
            Drug(id: "d170", genericName: "Etanercept", brandName: "Enbrel", drugClass: "Anti-TNF Biologic", suffix: "", indications: ["RA", "Psoriasis"], sideEffects: ["Infection risk", "Injection site reactions"], clinicalPearls: ["TNF receptor fusion protein", "Screen for TB"]),
            Drug(id: "d168", genericName: "Hydroxychloroquine", brandName: "Plaquenil", drugClass: "DMARD", suffix: "", indications: ["RA", "SLE", "Malaria"], sideEffects: ["Retinal toxicity", "GI upset", "QT prolongation"], clinicalPearls: ["Annual eye exams required", "Safe in pregnancy for SLE"]),
            Drug(id: "d167", genericName: "Methotrexate", brandName: "Trexall/Rheumatrex", drugClass: "DMARD / Antimetabolite", suffix: "", indications: ["RA", "Psoriasis", "Ectopic pregnancy"], sideEffects: ["Hepatotoxicity", "Bone marrow suppression", "Mucositis", "Teratogenic"], clinicalPearls: ["Take folic acid to reduce side effects", "Weekly dosing for RA (NOT daily)"]),
            Drug(id: "d180", genericName: "Mycophenolate mofetil", brandName: "CellCept", drugClass: "Antimetabolite", suffix: "", indications: ["Transplant rejection", "Lupus nephritis"], sideEffects: ["GI upset", "Bone marrow suppression", "Teratogenic"], clinicalPearls: ["REMS: pregnancy prevention required"]),
            Drug(id: "d178", genericName: "Tacrolimus", brandName: "Prograf", drugClass: "Calcineurin Inhibitor", suffix: "", indications: ["Transplant rejection"], sideEffects: ["Nephrotoxicity", "Hyperglycemia", "Tremor", "Hyperkalemia"], clinicalPearls: ["Narrow therapeutic index", "Monitor trough levels"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls5d_1", title: "DMARDs & Biologics", content: "Disease-modifying agents target the underlying immune process.", bulletPoints: ["Methotrexate: anchor drug for RA, give folic acid, weekly dosing", "Hydroxychloroquine: annual eye exams for retinal toxicity", "Anti-TNF biologics (adalimumab, etanercept): screen for TB", "Calcineurin inhibitors: nephrotoxicity is dose-limiting"], highlightText: "MTX = weekly + folic acid | Anti-TNF = screen TB"),
        ])

        let sub5e = Subsection(id: "5e", moduleId: "m5", code: "5e", title: "Systemic Steroids in Rheum", description: "Review of steroid use in rheumatology", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        let sub5f = Subsection(id: "5f", moduleId: "m5", code: "5f", title: "Mastering Pain & Rheum", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m5", number: 5, title: "Pain, Inflammation & Rheum", subtitle: "NSAIDs, Opioids & DMARDs", iconName: "cross.case.fill", accentColorHex: "C62828", subsections: [sub5a, sub5b, sub5c, sub5d, sub5e, sub5f])
    }
}
