import Foundation

extension DrugDataService {

    // MARK: - Module 6: Infectious Disease
    static func buildModule6() -> DrugModule {
        let sub6a = Subsection(id: "6a", moduleId: "m6", code: "6a", title: "Antibiotic Strategy", description: "Big-picture review of antibiotic classes", iconName: "shield.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        let sub6b = Subsection(id: "6b", moduleId: "m6", code: "6b", title: "Beta-Lactams", description: "Penicillins & Cephalosporins", iconName: "pills.fill", drugs: [
            Drug(id: "d98", genericName: "Amoxicillin", brandName: "Amoxil", drugClass: "Aminopenicillin", suffix: "-cillin", indications: ["Otitis media", "Sinusitis", "Strep pharyngitis", "H. pylori"], sideEffects: ["Diarrhea", "Rash", "Allergic reactions"], clinicalPearls: ["Most prescribed antibiotic in children"], commonDosing: [DoseFact(context: "Adult strep pharyngitis", dose: "500 mg BID or 875 mg BID × 10 days"), DoseFact(context: "Pediatric otitis media", dose: "80–90 mg/kg/day divided BID")]),
            Drug(id: "d99", genericName: "Amoxicillin/Clavulanate", brandName: "Augmentin", drugClass: "Aminopenicillin + BLI", suffix: "", indications: ["Sinusitis", "Otitis media", "UTI", "Bite wounds"], sideEffects: ["Diarrhea", "Nausea"], clinicalPearls: ["Clavulanate inhibits beta-lactamase"], commonDosing: [DoseFact(context: "Adult sinusitis/bite wound", dose: "875/125 mg BID × 7–10 days")]),
            Drug(id: "d100", genericName: "Piperacillin/Tazobactam", brandName: "Zosyn", drugClass: "Extended-spectrum penicillin", suffix: "", indications: ["Nosocomial infections", "Intra-abdominal infections"], sideEffects: ["Diarrhea", "Thrombocytopenia"], clinicalPearls: ["IV only, covers Pseudomonas"]),
            Drug(id: "d101", genericName: "Cephalexin", brandName: "Keflex", drugClass: "1st-gen Cephalosporin", suffix: "ceph-/cef-", indications: ["Skin infections", "UTI", "Strep pharyngitis"], sideEffects: ["Diarrhea", "Nausea"], clinicalPearls: ["1st-gen: best gram-positive coverage"]),
            Drug(id: "d102", genericName: "Ceftriaxone", brandName: "Rocephin", drugClass: "3rd-gen Cephalosporin", suffix: "ceph-/cef-", indications: ["Meningitis", "Pneumonia", "Gonorrhea"], sideEffects: ["Diarrhea", "Biliary sludging"], clinicalPearls: ["IM/IV, once daily", "Empiric for meningitis"]),
            Drug(id: "d103", genericName: "Cefepime", brandName: "Maxipime", drugClass: "4th-gen Cephalosporin", suffix: "ceph-/cef-", indications: ["Febrile neutropenia", "Pseudomonal infections"], sideEffects: ["Neurotoxicity", "Diarrhea"], clinicalPearls: ["4th-gen: covers Pseudomonas", "Neurotoxicity in renal failure"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls6b_1", title: "Beta-Lactams", content: "Kill bacteria by inhibiting cell wall synthesis.", bulletPoints: ["Penicillins: amoxicillin most prescribed in children", "BLI combos: clavulanate, tazobactam extend spectrum", "Cephalosporins: higher gen = more gram-negative", "Cross-reactivity with penicillin ~1-2%"], highlightText: "All beta-lactams inhibit cell wall synthesis"),
        ])

        let sub6c = Subsection(id: "6c", moduleId: "m6", code: "6c", title: "Macrolides, FQs, Tetracyclines", description: "Broad-spectrum antibiotics", iconName: "capsule.fill", drugs: [
            Drug(id: "d106", genericName: "Azithromycin", brandName: "Zithromax/Z-Pack", drugClass: "Macrolide", suffix: "-mycin/-thromycin", indications: ["CAP", "Strep pharyngitis", "Chlamydia"], sideEffects: ["GI upset", "QT prolongation"], clinicalPearls: ["Z-Pack: 5-day course", "Long tissue half-life"], commonDosing: [DoseFact(context: "Z-Pack (CAP/sinusitis)", dose: "500 mg day 1, then 250 mg days 2–5"), DoseFact(context: "Chlamydia", dose: "1 g single dose")]),
            Drug(id: "d104", genericName: "Ciprofloxacin", brandName: "Cipro", drugClass: "Fluoroquinolone", suffix: "-floxacin", indications: ["UTI", "Pseudomonal infections", "Anthrax"], sideEffects: ["Tendon rupture", "QT prolongation", "CNS effects"], clinicalPearls: ["Black box: tendinitis/tendon rupture", "Chelates with divalent cations"], blackBoxWarnings: ["Tendinitis/tendon rupture"]),
            Drug(id: "d107", genericName: "Clarithromycin", brandName: "Biaxin", drugClass: "Macrolide", suffix: "-mycin/-thromycin", indications: ["CAP", "H. pylori", "MAC"], sideEffects: ["Metallic taste", "GI upset", "QT prolongation"], clinicalPearls: ["Strong CYP3A4 inhibitor"]),
            Drug(id: "d108", genericName: "Doxycycline", brandName: "Vibramycin", drugClass: "Tetracycline", suffix: "-cycline", indications: ["Acne", "Lyme disease", "MRSA skin infections", "Chlamydia"], sideEffects: ["Photosensitivity", "Esophageal ulceration"], clinicalPearls: ["Take with water, sit upright", "Avoid in children < 8"], commonDosing: [DoseFact(context: "Most infections", dose: "100 mg BID"), DoseFact(context: "Chlamydia", dose: "100 mg BID × 7 days")]),
            Drug(id: "d105", genericName: "Levofloxacin", brandName: "Levaquin", drugClass: "Fluoroquinolone", suffix: "-floxacin", indications: ["CAP", "UTI", "Sinusitis"], sideEffects: ["Tendon rupture", "QT prolongation"], clinicalPearls: ["Respiratory fluoroquinolone"], blackBoxWarnings: ["Tendinitis/tendon rupture"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls6c_1", title: "Macrolides, FQs & Tetracyclines", content: "Key non-beta-lactam antibiotics.", bulletPoints: ["Fluoroquinolones (-floxacin): Black Box for tendons", "Macrolides: azithromycin Z-Pack, QT prolongation", "Doxycycline: photosensitivity, avoid in children < 8", "All macrolides can prolong QT interval"], highlightText: "-floxacin = Black Box: tendons"),
        ])

        let sub6d = Subsection(id: "6d", moduleId: "m6", code: "6d", title: "Sulfonamides & Other Antibiotics", description: "TMP/SMX, Vancomycin, Linezolid, Daptomycin", iconName: "shield.fill", drugs: [
            Drug(id: "d113", genericName: "Daptomycin", brandName: "Cubicin", drugClass: "Lipopeptide", suffix: "", indications: ["MRSA bacteremia", "Endocarditis"], sideEffects: ["CPK elevation", "Myopathy"], clinicalPearls: ["Inactivated by surfactant: do NOT use for pneumonia", "Monitor CPK weekly"], monitoring: ["CPK weekly"]),
            Drug(id: "d112", genericName: "Linezolid", brandName: "Zyvox", drugClass: "Oxazolidinone", suffix: "", indications: ["VRE", "MRSA pneumonia"], sideEffects: ["Thrombocytopenia", "Serotonin syndrome"], clinicalPearls: ["Weak MAO inhibitor: serotonin syndrome risk with SSRIs", "Monitor CBC weekly"], monitoring: ["CBC weekly", "Visual acuity if prolonged therapy"]),
            Drug(id: "d109", genericName: "Trimethoprim/Sulfamethoxazole", brandName: "Bactrim", drugClass: "Sulfonamide combination", suffix: "", indications: ["UTI", "MRSA skin infections", "PJP prophylaxis"], sideEffects: ["Hyperkalemia", "Rash", "SJS/TEN"], clinicalPearls: ["Sulfa allergy common"], commonDosing: [DoseFact(context: "Uncomplicated UTI", dose: "1 DS tablet BID × 3 days"), DoseFact(context: "PJP prophylaxis", dose: "1 DS tablet daily or 1 SS tablet daily")]),
            Drug(id: "d110", genericName: "Vancomycin (IV)", brandName: "Vancocin", drugClass: "Glycopeptide", suffix: "", indications: ["MRSA", "Serious gram-positive infections"], sideEffects: ["Nephrotoxicity", "Red man syndrome", "Ototoxicity"], clinicalPearls: ["Monitor AUC/MIC or trough levels", "Red man syndrome: slow infusion"], monitoring: ["Vancomycin AUC/MIC or trough levels", "Renal function (SCr)"]),
            Drug(id: "d111", genericName: "Vancomycin (oral)", brandName: "Vancocin", drugClass: "Glycopeptide", suffix: "", indications: ["C. difficile colitis"], sideEffects: ["Nausea"], clinicalPearls: ["Oral stays in GI tract", "NOT absorbed systemically", "First-line for C. diff"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls6d_1", title: "Anti-MRSA & Specialty Antibiotics", content: "Reserved agents for resistant organisms.", bulletPoints: ["IV vancomycin: MRSA | Oral vancomycin: C. diff only", "Linezolid: covers VRE, weak MAO inhibitor", "Daptomycin: NEVER for pneumonia (surfactant inactivation)", "TMP/SMX (Bactrim): first-line UTI and MRSA skin"], highlightText: "IV vanco = MRSA | Oral vanco = C. diff"),
        ])

        let sub6e = Subsection(id: "6e", moduleId: "m6", code: "6e", title: "Antifungals & Antivirals", description: "High-yield antifungals, antivirals, and extras", iconName: "microbe.fill", drugs: [
            Drug(id: "d226", genericName: "Acyclovir", brandName: "Zovirax", drugClass: "Antiviral (nucleoside analog)", suffix: "", indications: ["HSV", "VZV (shingles)", "Genital herpes"], sideEffects: ["Nephrotoxicity", "Nausea"], clinicalPearls: ["Hydrate well to prevent renal toxicity", "Dose adjust for renal impairment"], monitoring: ["Renal function"], commonDosing: [DoseFact(context: "HSV (oral)", dose: "400 mg TID × 7–10 days"), DoseFact(context: "VZV (shingles)", dose: "800 mg 5×/day × 7 days")]),
            Drug(id: "d227", genericName: "Cefdinir", brandName: "Omnicef", drugClass: "3rd-gen Cephalosporin", suffix: "cef-", indications: ["Otitis media", "Sinusitis", "Pharyngitis"], sideEffects: ["Diarrhea", "Red-tinged stools (with iron)"], clinicalPearls: ["Common pediatric antibiotic", "Red stools with iron = harmless"]),
            Drug(id: "d228", genericName: "Cefuroxime", brandName: "Ceftin", drugClass: "2nd-gen Cephalosporin", suffix: "cef-", indications: ["Sinusitis", "Otitis media", "UTI", "Lyme disease"], sideEffects: ["Diarrhea", "Nausea"], clinicalPearls: ["2nd-gen: moderate gram-negative coverage"]),
            Drug(id: "d229", genericName: "Clindamycin", brandName: "Cleocin", drugClass: "Lincosamide", suffix: "", indications: ["Skin infections", "MRSA (oral)", "Anaerobes"], sideEffects: ["C. difficile colitis", "Diarrhea"], clinicalPearls: ["High risk of C. diff", "Good bone penetration"]),
            Drug(id: "d230", genericName: "Erythromycin", brandName: "Ery-Tab", drugClass: "Macrolide", suffix: "-mycin", indications: ["CAP", "Pertussis", "Gastroparesis (off-label)"], sideEffects: ["GI upset", "QT prolongation"], clinicalPearls: ["Prokinetic agent", "Many drug interactions (CYP3A4)"]),
            Drug(id: "d231", genericName: "Fluconazole", brandName: "Diflucan", drugClass: "Azole Antifungal", suffix: "-conazole", indications: ["Candidiasis", "Cryptococcal meningitis"], sideEffects: ["Hepatotoxicity", "QT prolongation"], clinicalPearls: ["First-line for most Candida infections", "Good CNS penetration"], monitoring: ["LFTs if prolonged therapy"], commonDosing: [DoseFact(context: "Vaginal candidiasis", dose: "150 mg single dose"), DoseFact(context: "Oropharyngeal candidiasis", dose: "200 mg day 1, then 100 mg daily × 7–14 days")]),
            Drug(id: "d232", genericName: "Ketoconazole", brandName: "Nizoral", drugClass: "Azole Antifungal", suffix: "-conazole", indications: ["Fungal skin infections", "Seborrheic dermatitis"], sideEffects: ["Hepatotoxicity", "Adrenal suppression"], clinicalPearls: ["Topical preferred over systemic", "Shampoo for dandruff/seborrheic dermatitis"]),
            Drug(id: "d233", genericName: "Metronidazole", brandName: "Flagyl", drugClass: "Nitroimidazole", suffix: "", indications: ["Anaerobic infections", "C. difficile", "Trichomoniasis", "H. pylori"], sideEffects: ["Metallic taste", "Nausea", "Peripheral neuropathy"], clinicalPearls: ["Disulfiram-like reaction with alcohol", "Avoid alcohol during and 3 days after"]),
            Drug(id: "d234", genericName: "Moxifloxacin", brandName: "Avelox", drugClass: "Fluoroquinolone", suffix: "-floxacin", indications: ["CAP", "Sinusitis", "Intra-abdominal infections"], sideEffects: ["QT prolongation", "Tendon rupture"], clinicalPearls: ["Respiratory FQ with anaerobic coverage", "No renal dose adjustment"], blackBoxWarnings: ["Tendinitis/tendon rupture"]),
            Drug(id: "d235", genericName: "Nirmatrelvir/Ritonavir", brandName: "Paxlovid", drugClass: "Protease Inhibitor combo", suffix: "", indications: ["COVID-19 (high-risk)"], sideEffects: ["Dysgeusia", "Diarrhea", "Myalgia"], clinicalPearls: ["Ritonavir is CYP3A4 inhibitor - MANY drug interactions", "Must start within 5 days of symptoms"]),
            Drug(id: "d236", genericName: "Nitrofurantoin", brandName: "Macrobid", drugClass: "Nitrofuran", suffix: "", indications: ["Uncomplicated UTI", "UTI prophylaxis"], sideEffects: ["GI upset", "Pulmonary toxicity (chronic use)"], clinicalPearls: ["Only works in bladder (not systemic)", "Avoid if CrCl < 30"], commonDosing: [DoseFact(context: "Uncomplicated UTI (Macrobid)", dose: "100 mg BID × 5 days")]),
            Drug(id: "d237", genericName: "Nystatin", brandName: "Mycostatin", drugClass: "Polyene Antifungal", suffix: "", indications: ["Oral thrush", "Cutaneous candidiasis"], sideEffects: ["GI upset", "Nausea"], clinicalPearls: ["Swish and swallow for oral thrush", "Not absorbed systemically"]),
            Drug(id: "d238", genericName: "Ofloxacin", brandName: "Floxin Otic", drugClass: "Fluoroquinolone", suffix: "-floxacin", indications: ["Otitis externa", "Conjunctivitis"], sideEffects: ["Local irritation"], clinicalPearls: ["Otic/ophthalmic formulations", "Safe in perforated TM (otic)"]),
            Drug(id: "d239", genericName: "Oseltamivir", brandName: "Tamiflu", drugClass: "Neuraminidase Inhibitor", suffix: "", indications: ["Influenza A & B (treatment/prophylaxis)"], sideEffects: ["Nausea", "Vomiting"], clinicalPearls: ["Start within 48 hours of symptoms", "Can be used for prophylaxis"], commonDosing: [DoseFact(context: "Influenza treatment (adult)", dose: "75 mg BID × 5 days"), DoseFact(context: "Influenza prophylaxis", dose: "75 mg once daily × 10 days")]),
            Drug(id: "d240", genericName: "Penicillin V", brandName: "Pen VK", drugClass: "Natural Penicillin", suffix: "-cillin", indications: ["Strep pharyngitis", "Dental infections"], sideEffects: ["Diarrhea", "Allergic reactions"], clinicalPearls: ["Oral penicillin", "First-line for strep pharyngitis"]),
            Drug(id: "d241", genericName: "Polymyxin B/Trimethoprim", brandName: "Polytrim", drugClass: "Ophthalmic antibiotic", suffix: "", indications: ["Bacterial conjunctivitis"], sideEffects: ["Local irritation", "Stinging"], clinicalPearls: ["Common first-line for bacterial pink eye"]),
            Drug(id: "d242", genericName: "Terbinafine", brandName: "Lamisil", drugClass: "Allylamine Antifungal", suffix: "", indications: ["Onychomycosis", "Tinea infections"], sideEffects: ["Hepatotoxicity", "Taste disturbance", "Headache"], clinicalPearls: ["First-line for onychomycosis", "Monitor LFTs"], monitoring: ["Baseline and periodic LFTs"], commonDosing: [DoseFact(context: "Fingernail onychomycosis", dose: "250 mg daily × 6 weeks"), DoseFact(context: "Toenail onychomycosis", dose: "250 mg daily × 12 weeks")]),
            Drug(id: "d243", genericName: "Tobramycin", brandName: "Tobrex", drugClass: "Aminoglycoside (ophthalmic)", suffix: "", indications: ["Bacterial conjunctivitis", "Corneal ulcers"], sideEffects: ["Local irritation"], clinicalPearls: ["Ophthalmic formulation", "Also available as inhaled for CF"]),
            Drug(id: "d244", genericName: "Valacyclovir", brandName: "Valtrex", drugClass: "Antiviral (prodrug of acyclovir)", suffix: "", indications: ["HSV", "VZV (shingles)", "Genital herpes suppression"], sideEffects: ["Headache", "Nausea"], clinicalPearls: ["Prodrug of acyclovir - better oral bioavailability", "Less frequent dosing than acyclovir"], commonDosing: [DoseFact(context: "Herpes zoster (shingles)", dose: "1 g TID × 7 days"), DoseFact(context: "Genital herpes suppression", dose: "500 mg–1 g once daily")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls6e_1", title: "Antifungals", content: "Key antifungal agents.", bulletPoints: ["Fluconazole: first-line for most Candida", "Nystatin: swish and swallow for oral thrush", "Terbinafine: first-line for onychomycosis", "Azoles (-conazole): hepatotoxicity risk"], highlightText: "Fluconazole = first-line Candida"),
            LearningSlide(id: "ls6e_2", title: "Antivirals & Extra Antibiotics", content: "High-yield antiviral agents.", bulletPoints: ["Acyclovir/valacyclovir: HSV and VZV treatment", "Oseltamivir (Tamiflu): start within 48h of flu symptoms", "Metronidazole: avoid alcohol (disulfiram-like reaction)", "Nitrofurantoin: uncomplicated UTI only, avoid if CrCl < 30"], highlightText: "Metronidazole + alcohol = disulfiram reaction"),
        ])

        let sub6f = Subsection(id: "6f", moduleId: "m6", code: "6f", title: "Mastering Infectious Disease", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m6", number: 6, title: "Infectious Disease", subtitle: "Antibiotics, Antivirals & Antifungals", iconName: "microbe.fill", accentColorHex: "EF6C00", subsections: [sub6a, sub6b, sub6c, sub6d, sub6e, sub6f])
    }

    // MARK: - Module 7: Respiratory & Allergy
    static func buildModule7() -> DrugModule {
        let sub7a = Subsection(id: "7a", moduleId: "m7", code: "7a", title: "Asthma/COPD Overview", description: "Stepwise therapy review", iconName: "lungs.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        let sub7b = Subsection(id: "7b", moduleId: "m7", code: "7b", title: "Inhaled Bronchodilators", description: "SABA, LABA, LAMA", iconName: "wind", drugs: [
            Drug(id: "d120", genericName: "Albuterol", brandName: "ProAir/Ventolin", drugClass: "SABA", suffix: "", indications: ["Acute bronchospasm", "Asthma rescue"], sideEffects: ["Tachycardia", "Tremor", "Hypokalemia"], clinicalPearls: ["First-line rescue inhaler"], commonDosing: [DoseFact(context: "Acute bronchospasm", dose: "2 puffs every 4-6 hours as needed"), DoseFact(context: "Exercise-induced", dose: "2 puffs 15-30 min before exercise")]),
            Drug(id: "d122", genericName: "Ipratropium", brandName: "Atrovent", drugClass: "Short-acting Anticholinergic", suffix: "", indications: ["COPD", "Acute bronchospasm"], sideEffects: ["Dry mouth", "Urinary retention"], clinicalPearls: ["Often combined with albuterol (DuoNeb)"], majorContraindications: ["Hypersensitivity to atropine or derivatives"]),
            Drug(id: "d121", genericName: "Levalbuterol", brandName: "Xopenex", drugClass: "SABA", suffix: "", indications: ["Acute bronchospasm"], sideEffects: ["Tachycardia", "Tremor"], clinicalPearls: ["R-enantiomer of albuterol"]),
            Drug(id: "d123", genericName: "Tiotropium", brandName: "Spiriva", drugClass: "LAMA", suffix: "", indications: ["COPD", "Asthma (add-on)"], sideEffects: ["Dry mouth", "Urinary retention"], clinicalPearls: ["Once daily, COPD maintenance cornerstone"], majorContraindications: ["Hypersensitivity to ipratropium or tiotropium"], commonDosing: [DoseFact(context: "COPD maintenance", dose: "18 mcg (1 capsule) inhaled once daily via HandiHaler")]),
            Drug(id: "d124", genericName: "Umeclidinium/Vilanterol", brandName: "Anoro Ellipta", drugClass: "LAMA/LABA Combination", suffix: "", indications: ["COPD"], sideEffects: ["Dry mouth", "Headache"], clinicalPearls: ["Dual bronchodilator for COPD"], majorContraindications: ["Severe milk protein allergy", "Not indicated for asthma"], commonDosing: [DoseFact(context: "COPD maintenance", dose: "62.5/25 mcg inhaled once daily")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls7b_1", title: "Bronchodilators", content: "Quick-relief and long-acting agents.", bulletPoints: ["Albuterol: first-line rescue inhaler", "Tiotropium (Spiriva): COPD maintenance cornerstone", "Ipratropium: short-acting anticholinergic, with albuterol for acute", "LAMA + LABA combos (Anoro) for COPD"], highlightText: "Albuterol = #1 rescue inhaler"),
        ])

        let sub7c = Subsection(id: "7c", moduleId: "m7", code: "7c", title: "Inhaled Corticosteroids & Combos", description: "ICS and ICS/LABA combinations", iconName: "lungs.fill", drugs: [
            Drug(id: "d115", genericName: "Budesonide (inhaled)", brandName: "Pulmicort", drugClass: "Inhaled Corticosteroid", suffix: "", indications: ["Asthma", "Croup"], sideEffects: ["Oral thrush", "Hoarseness"], clinicalPearls: ["Nebulizer form for young children"], monitoring: ["Growth velocity in pediatric patients"]),
            Drug(id: "d117", genericName: "Budesonide/Formoterol", brandName: "Symbicort", drugClass: "ICS/LABA Combination", suffix: "", indications: ["Asthma", "COPD"], sideEffects: ["Oral thrush", "Headache"], clinicalPearls: ["SMART therapy: maintenance AND reliever"]),
            Drug(id: "d114", genericName: "Fluticasone (inhaled)", brandName: "Flovent HFA", drugClass: "Inhaled Corticosteroid", suffix: "", indications: ["Asthma", "COPD"], sideEffects: ["Oral thrush", "Dysphonia"], clinicalPearls: ["Rinse mouth after use", "Maintenance only - NOT rescue"], monitoring: ["Growth velocity in pediatric patients"]),
            Drug(id: "d116", genericName: "Fluticasone/Salmeterol", brandName: "Advair", drugClass: "ICS/LABA Combination", suffix: "", indications: ["Asthma", "COPD"], sideEffects: ["Oral thrush", "Tachycardia"], clinicalPearls: ["LABA should NEVER be used alone in asthma"]),
            Drug(id: "d119", genericName: "Mometasone/Formoterol", brandName: "Dulera", drugClass: "ICS/LABA Combination", suffix: "", indications: ["Asthma"], sideEffects: ["Oral thrush", "Headache"], clinicalPearls: ["MDI formulation"]),
            Drug(id: "d118", genericName: "Salmeterol", brandName: "Serevent", drugClass: "LABA", suffix: "", indications: ["Asthma (with ICS)", "COPD"], sideEffects: ["Tachycardia", "Tremor"], clinicalPearls: ["NEVER use alone in asthma"], blackBoxWarnings: ["Increased asthma-related death if used without ICS"], majorContraindications: ["Monotherapy in asthma without ICS"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls7c_1", title: "ICS & Combination Inhalers", content: "ICS are cornerstone of persistent asthma maintenance.", bulletPoints: ["Rinse mouth after ICS to prevent thrush", "LABA alone in asthma = Black Box Warning", "Advair = fluticasone + salmeterol", "Symbicort = budesonide + formoterol (SMART therapy)"], highlightText: "ICS = Maintenance, NOT rescue. Rinse mouth!"),
        ])

        let sub7d = Subsection(id: "7d", moduleId: "m7", code: "7d", title: "Leukotriene Modifiers & Controllers", description: "Montelukast, biologics, and specialty agents", iconName: "allergens.fill", drugs: [
            Drug(id: "d127", genericName: "Dupilumab", brandName: "Dupixent", drugClass: "Anti-IL-4/IL-13 MAb", suffix: "", indications: ["Moderate-severe asthma", "Atopic dermatitis", "Nasal polyps"], sideEffects: ["Injection site reactions", "Conjunctivitis"], clinicalPearls: ["Blocks IL-4 and IL-13", "Also for eczema"]),
            Drug(id: "d125", genericName: "Montelukast", brandName: "Singulair", drugClass: "Leukotriene Receptor Antagonist", suffix: "", indications: ["Asthma", "Allergic rhinitis"], sideEffects: ["Headache", "Neuropsychiatric events"], clinicalPearls: ["Oral, taken at bedtime"], blackBoxWarnings: ["Neuropsychiatric events (suicidal ideation)"], monitoring: ["Monitor for neuropsychiatric symptoms"], commonDosing: [DoseFact(context: "Asthma/allergic rhinitis (adults)", dose: "10 mg once daily in the evening")]),
            Drug(id: "d126", genericName: "Omalizumab", brandName: "Xolair", drugClass: "Anti-IgE MAb", suffix: "", indications: ["Moderate-severe allergic asthma", "Chronic urticaria"], sideEffects: ["Anaphylaxis", "Injection site reactions"], clinicalPearls: ["Binds free IgE"], blackBoxWarnings: ["Anaphylaxis risk"], monitoring: ["Observe patient after injection for anaphylaxis", "Serum total IgE (pre-treatment for dosing)"]),
            Drug(id: "d128", genericName: "Roflumilast", brandName: "Daliresp", drugClass: "PDE-4 Inhibitor", suffix: "", indications: ["Severe COPD"], sideEffects: ["Diarrhea", "Weight loss", "Psychiatric symptoms"], clinicalPearls: ["NOT a bronchodilator"], majorContraindications: ["Moderate-to-severe hepatic impairment"], monitoring: ["Weight", "Psychiatric symptoms"], commonDosing: [DoseFact(context: "COPD", dose: "250 mcg once daily for 4 weeks, then 500 mcg once daily")]),
            Drug(id: "d129", genericName: "Theophylline", brandName: "Theo-24", drugClass: "Methylxanthine", suffix: "", indications: ["Asthma", "COPD"], sideEffects: ["Tachycardia", "Seizures", "Nausea"], clinicalPearls: ["Narrow therapeutic index: 5-15 mcg/mL", "Rarely used now"], monitoring: ["Serum theophylline levels (target 5-15 mcg/mL)"], commonDosing: [DoseFact(context: "Asthma/COPD", dose: "Individualized; target serum level 5-15 mcg/mL")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls7d_1", title: "Leukotriene Modifiers & Biologics", content: "Additional controllers for asthma.", bulletPoints: ["Montelukast: Black Box for neuropsychiatric events", "Omalizumab (Xolair): anti-IgE, anaphylaxis risk", "Dupilumab: anti-IL-4/IL-13, also for eczema", "Theophylline: narrow index, rarely used"], highlightText: "Montelukast Black Box: neuropsychiatric events"),
        ])

        let sub7e = Subsection(id: "7e", moduleId: "m7", code: "7e", title: "Antihistamines & Nasal Steroids", description: "Allergy management", iconName: "nose.fill", drugs: [
            Drug(id: "d245", genericName: "Azelastine (nasal)", brandName: "Astelin", drugClass: "Intranasal Antihistamine", suffix: "", indications: ["Allergic rhinitis", "Vasomotor rhinitis"], sideEffects: ["Bitter taste", "Somnolence"], clinicalPearls: ["Nasal spray antihistamine", "Can combine with nasal steroid"]),
            Drug(id: "d246", genericName: "Cetirizine", brandName: "Zyrtec", drugClass: "2nd-gen Antihistamine", suffix: "", indications: ["Allergic rhinitis", "Urticaria"], sideEffects: ["Drowsiness (mild)", "Dry mouth"], clinicalPearls: ["Less sedating than 1st-gen", "OTC"]),
            Drug(id: "d247", genericName: "Diphenhydramine", brandName: "Benadryl", drugClass: "1st-gen Antihistamine", suffix: "", indications: ["Allergic reactions", "Insomnia", "Motion sickness"], sideEffects: ["Sedation", "Anticholinergic effects", "Dry mouth"], clinicalPearls: ["Very sedating", "Avoid in elderly (anticholinergic)"], majorContraindications: ["Avoid in elderly (Beers Criteria)"], commonDosing: [DoseFact(context: "Allergic reactions", dose: "25-50 mg every 4-6 hours as needed")]),
            Drug(id: "d248", genericName: "Fexofenadine", brandName: "Allegra", drugClass: "2nd-gen Antihistamine", suffix: "", indications: ["Allergic rhinitis", "Urticaria"], sideEffects: ["Headache"], clinicalPearls: ["Least sedating antihistamine", "Do not take with fruit juice"]),
            Drug(id: "d249", genericName: "Fluticasone (nasal)", brandName: "Flonase", drugClass: "Intranasal Corticosteroid", suffix: "", indications: ["Allergic rhinitis", "Nasal congestion"], sideEffects: ["Nasal irritation", "Epistaxis"], clinicalPearls: ["Most effective class for allergic rhinitis", "OTC"]),
            Drug(id: "d250", genericName: "Levocetirizine", brandName: "Xyzal", drugClass: "2nd-gen Antihistamine", suffix: "", indications: ["Allergic rhinitis", "Urticaria"], sideEffects: ["Drowsiness (mild)"], clinicalPearls: ["Active enantiomer of cetirizine"], monitoring: ["Renal function (dose adjustment needed)"]),
            Drug(id: "d251", genericName: "Loratadine", brandName: "Claritin", drugClass: "2nd-gen Antihistamine", suffix: "", indications: ["Allergic rhinitis", "Urticaria"], sideEffects: ["Headache", "Dry mouth"], clinicalPearls: ["Non-sedating", "OTC"]),
            Drug(id: "d252", genericName: "Loratadine/Pseudoephedrine", brandName: "Claritin-D", drugClass: "Antihistamine/Decongestant", suffix: "", indications: ["Allergic rhinitis with congestion"], sideEffects: ["Insomnia", "Tachycardia", "HTN"], clinicalPearls: ["Behind-the-counter (pseudoephedrine)"]),
            Drug(id: "d253", genericName: "Mometasone (nasal)", brandName: "Nasonex", drugClass: "Intranasal Corticosteroid", suffix: "", indications: ["Allergic rhinitis", "Nasal polyps"], sideEffects: ["Nasal irritation", "Headache"], clinicalPearls: ["Also used for nasal polyps"]),
            Drug(id: "d254", genericName: "Pseudoephedrine", brandName: "Sudafed", drugClass: "Decongestant", suffix: "", indications: ["Nasal congestion"], sideEffects: ["Insomnia", "Tachycardia", "Hypertension"], clinicalPearls: ["Behind-the-counter", "Avoid in uncontrolled HTN"], majorContraindications: ["Uncontrolled hypertension", "MAOI use within 14 days"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls7e_1", title: "Antihistamines", content: "1st-gen vs 2nd-gen antihistamines.", bulletPoints: ["1st-gen (diphenhydramine): sedating, anticholinergic", "2nd-gen (cetirizine, loratadine, fexofenadine): less sedating", "Fexofenadine (Allegra): least sedating", "Intranasal steroids: most effective for allergic rhinitis"], highlightText: "2nd-gen antihistamines: less sedating, preferred"),
        ])

        let sub7f = Subsection(id: "7f", moduleId: "m7", code: "7f", title: "Mastering Respiratory & Allergy", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m7", number: 7, title: "Respiratory & Allergy", subtitle: "Asthma, COPD & Allergy", iconName: "lungs.fill", accentColorHex: "0288D1", subsections: [sub7a, sub7b, sub7c, sub7d, sub7e, sub7f])
    }

    // MARK: - Module 8: GI & Hepatic
    static func buildModule8() -> DrugModule {
        let sub8a = Subsection(id: "8a", moduleId: "m8", code: "8a", title: "Acid Suppression", description: "PPIs, H2 Blockers, Mucosal Protection", iconName: "flame.fill", drugs: [
            Drug(id: "d131", genericName: "Esomeprazole", brandName: "Nexium", drugClass: "Proton Pump Inhibitor", suffix: "-prazole", indications: ["GERD", "Erosive esophagitis"], sideEffects: ["C. diff risk", "Hypomagnesemia"], clinicalPearls: ["S-enantiomer of omeprazole"]),
            Drug(id: "d134", genericName: "Famotidine", brandName: "Pepcid", drugClass: "H2 Receptor Antagonist", suffix: "-tidine", indications: ["GERD", "Peptic ulcer", "Heartburn"], sideEffects: ["Headache", "Constipation"], clinicalPearls: ["Most commonly used H2 blocker"]),
            Drug(id: "d133", genericName: "Lansoprazole", brandName: "Prevacid", drugClass: "Proton Pump Inhibitor", suffix: "-prazole", indications: ["GERD", "Peptic ulcer"], sideEffects: ["C. diff risk", "Headache"], clinicalPearls: ["Orally disintegrating tablet available"]),
            Drug(id: "d130", genericName: "Omeprazole", brandName: "Prilosec", drugClass: "Proton Pump Inhibitor", suffix: "-prazole", indications: ["GERD", "Peptic ulcer", "H. pylori"], sideEffects: ["C. diff risk", "Hypomagnesemia", "Bone fractures", "B12 deficiency"], clinicalPearls: ["Take 30-60 min before first meal", "Inhibits CYP2C19 (avoid with clopidogrel)"]),
            Drug(id: "d132", genericName: "Pantoprazole", brandName: "Protonix", drugClass: "Proton Pump Inhibitor", suffix: "-prazole", indications: ["GERD", "ICU stress ulcer prophylaxis"], sideEffects: ["C. diff risk", "Hypomagnesemia"], clinicalPearls: ["Preferred PPI with clopidogrel (less CYP2C19)"]),
            Drug(id: "d135", genericName: "Sucralfate", brandName: "Carafate", drugClass: "Mucosal Protectant", suffix: "", indications: ["Duodenal ulcer"], sideEffects: ["Constipation"], clinicalPearls: ["Forms protective barrier over ulcer", "Take on empty stomach"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls8a_1", title: "PPIs & H2 Blockers", content: "Acid suppression therapy.", bulletPoints: ["PPIs (-prazole): most potent acid suppression, take before meals", "H2 blockers (-tidine): less potent, faster onset", "Long-term PPI risks: C. diff, fractures, hypomagnesemia", "Avoid omeprazole with clopidogrel (CYP2C19)"], highlightText: "-prazole = PPI. Take BEFORE meals!"),
        ])

        let sub8b = Subsection(id: "8b", moduleId: "m8", code: "8b", title: "Antiemetics", description: "Ondansetron, Promethazine, and more", iconName: "stomach.fill", drugs: [
            Drug(id: "d140", genericName: "Aprepitant", brandName: "Emend", drugClass: "NK1 Receptor Antagonist", suffix: "", indications: ["Highly emetogenic chemotherapy"], sideEffects: ["Fatigue", "Hiccups"], clinicalPearls: ["Added to 5-HT3 + dex for high emetic risk"]),
            Drug(id: "d138", genericName: "Metoclopramide", brandName: "Reglan", drugClass: "Dopamine Antagonist / Prokinetic", suffix: "", indications: ["Gastroparesis", "GERD", "Nausea"], sideEffects: ["EPS", "Tardive dyskinesia"], clinicalPearls: ["Prokinetic agent"], blackBoxWarnings: ["Tardive dyskinesia with long-term use"]),
            Drug(id: "d136", genericName: "Ondansetron", brandName: "Zofran", drugClass: "5-HT3 Antagonist", suffix: "-setron", indications: ["Chemo N/V", "Post-op N/V", "Gastroenteritis"], sideEffects: ["Headache", "Constipation", "QT prolongation"], clinicalPearls: ["First-line for most N/V", "ODT available"]),
            Drug(id: "d137", genericName: "Promethazine", brandName: "Phenergan", drugClass: "Phenothiazine Antiemetic", suffix: "", indications: ["Nausea", "Motion sickness"], sideEffects: ["Sedation", "EPS", "Tissue necrosis (IV)"], clinicalPearls: ["Avoid in children < 2"], blackBoxWarnings: ["Avoid in children < 2 (respiratory depression)"]),
            Drug(id: "d139", genericName: "Scopolamine", brandName: "Transderm Scop", drugClass: "Anticholinergic", suffix: "", indications: ["Motion sickness", "Post-op N/V"], sideEffects: ["Dry mouth", "Drowsiness", "Blurred vision"], clinicalPearls: ["Transdermal patch behind the ear"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls8b_1", title: "Antiemetics", content: "Match antiemetic to the cause of nausea.", bulletPoints: ["Ondansetron (Zofran): first-line for most N/V", "Scopolamine: patch for motion sickness", "Metoclopramide: prokinetic, Black Box for tardive dyskinesia", "Aprepitant: NK1 antagonist for chemo-induced N/V"], highlightText: "Ondansetron = #1 antiemetic"),
        ])

        let sub8c = Subsection(id: "8c", moduleId: "m8", code: "8c", title: "Laxatives & Antidiarrheals", description: "Constipation and diarrhea management", iconName: "cross.vial.fill", drugs: [
            Drug(id: "d143", genericName: "Bisacodyl", brandName: "Dulcolax", drugClass: "Stimulant Laxative", suffix: "", indications: ["Acute constipation", "Bowel prep"], sideEffects: ["Cramping", "Diarrhea"], clinicalPearls: ["Oral and suppository", "Avoid long-term use"]),
            Drug(id: "d255", genericName: "Diphenoxylate/Atropine", brandName: "Lomotil", drugClass: "Antidiarrheal (opioid)", suffix: "", indications: ["Acute diarrhea"], sideEffects: ["Anticholinergic effects", "Sedation"], clinicalPearls: ["Schedule V controlled substance", "Atropine added to deter abuse"]),
            Drug(id: "d142", genericName: "Docusate sodium", brandName: "Colace", drugClass: "Stool Softener", suffix: "", indications: ["Constipation prevention"], sideEffects: ["Mild cramping"], clinicalPearls: ["Surfactant - softens stool", "Often with opioids"]),
            Drug(id: "d256", genericName: "Lactulose", brandName: "Kristalose", drugClass: "Osmotic Laxative", suffix: "", indications: ["Constipation", "Hepatic encephalopathy"], sideEffects: ["Bloating", "Flatulence", "Diarrhea"], clinicalPearls: ["Metabolized by colonic bacteria to organic acids", "Traps ammonia in hepatic encephalopathy"]),
            Drug(id: "d257", genericName: "Linaclotide", brandName: "Linzess", drugClass: "Guanylate Cyclase-C Agonist", suffix: "", indications: ["IBS-C", "Chronic idiopathic constipation"], sideEffects: ["Diarrhea"], clinicalPearls: ["Take on empty stomach 30 min before first meal"]),
            Drug(id: "d258", genericName: "Loperamide", brandName: "Imodium", drugClass: "Antidiarrheal (opioid)", suffix: "", indications: ["Acute diarrhea"], sideEffects: ["Constipation", "Abdominal cramping"], clinicalPearls: ["OTC", "Does not cross BBB at normal doses", "QT prolongation at supratherapeutic doses"]),
            Drug(id: "d141", genericName: "Polyethylene glycol", brandName: "MiraLAX", drugClass: "Osmotic Laxative", suffix: "", indications: ["Constipation", "Bowel prep"], sideEffects: ["Bloating", "Diarrhea"], clinicalPearls: ["First-line for chronic constipation", "OTC"]),
            Drug(id: "d259", genericName: "Polyethylene glycol w/ electrolytes", brandName: "GoLYTELY", drugClass: "Bowel Prep", suffix: "", indications: ["Colonoscopy bowel preparation"], sideEffects: ["Nausea", "Bloating", "Vomiting"], clinicalPearls: ["Large-volume bowel prep", "Must drink entire solution"]),
            Drug(id: "d260", genericName: "Senna/Docusate", brandName: "Senokot-S", drugClass: "Stimulant Laxative + Softener", suffix: "", indications: ["Opioid-induced constipation", "Constipation"], sideEffects: ["Cramping", "Diarrhea"], clinicalPearls: ["Standard combo for opioid-induced constipation"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls8c_1", title: "Laxatives & Antidiarrheals", content: "Multiple mechanisms for bowel management.", bulletPoints: ["MiraLAX: first-line chronic constipation, OTC", "Lactulose: also for hepatic encephalopathy", "Senna/Docusate: standard for opioid-induced constipation", "Loperamide (Imodium): OTC antidiarrheal"], highlightText: "MiraLAX = first-line constipation"),
        ])

        let sub8d = Subsection(id: "8d", moduleId: "m8", code: "8d", title: "Antispasmodics", description: "Dicyclomine for IBS", iconName: "stomach.fill", drugs: [
            Drug(id: "d261", genericName: "Dicyclomine", brandName: "Bentyl", drugClass: "Anticholinergic / Antispasmodic", suffix: "", indications: ["IBS (cramping/pain)"], sideEffects: ["Dry mouth", "Constipation", "Blurred vision", "Urinary retention"], clinicalPearls: ["Anticholinergic antispasmodic for IBS", "Avoid in elderly"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls8d_1", title: "Antispasmodics", content: "Anticholinergic agents for GI spasm.", bulletPoints: ["Dicyclomine (Bentyl): first-line antispasmodic for IBS", "Anticholinergic: dry mouth, constipation, blurred vision", "Avoid in elderly (anticholinergic burden)"], highlightText: "Dicyclomine: anticholinergic for IBS cramps"),
        ])

        let sub8e = Subsection(id: "8e", moduleId: "m8", code: "8e", title: "IBD", description: "High-yield IBD agents", iconName: "cross.vial.fill", drugs: [
            Drug(id: "d145", genericName: "Infliximab", brandName: "Remicade", drugClass: "Anti-TNF MAb", suffix: "", indications: ["Crohn's disease", "UC", "RA", "Psoriasis"], sideEffects: ["Infection risk", "Infusion reactions", "TB reactivation"], clinicalPearls: ["Screen for TB before starting", "IV infusion q6-8 weeks"]),
            Drug(id: "d144", genericName: "Mesalamine", brandName: "Asacol/Lialda", drugClass: "5-ASA", suffix: "", indications: ["Ulcerative colitis"], sideEffects: ["Headache", "Nausea"], clinicalPearls: ["First-line for mild-moderate UC"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls8e_1", title: "IBD Treatments", content: "Targeted therapy for inflammatory bowel disease.", bulletPoints: ["Mesalamine (5-ASA): first-line for mild-moderate UC", "Infliximab (Remicade): anti-TNF for moderate-severe IBD", "Screen for TB before anti-TNF therapy"], highlightText: "Anti-TNF: always screen for TB first"),
        ])

        let sub8f = Subsection(id: "8f", moduleId: "m8", code: "8f", title: "Mastering GI & Hepatic", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m8", number: 8, title: "GI & Hepatic", subtitle: "Acid, Nausea & IBD", iconName: "stomach.fill", accentColorHex: "7B1FA2", subsections: [sub8a, sub8b, sub8c, sub8d, sub8e, sub8f])
    }

    // MARK: - Module 9: Neuro & Seizure Disorders
    static func buildModule9() -> DrugModule {
        let sub9a = Subsection(id: "9a", moduleId: "m9", code: "9a", title: "Seizure Meds Overview", description: "Review of seizure pharmacology", iconName: "bolt.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        let sub9b = Subsection(id: "9b", moduleId: "m9", code: "9b", title: "Classic Antiepileptics", description: "Carbamazepine, Phenytoin, Valproic acid", iconName: "bolt.fill", drugs: [
            Drug(id: "d96", genericName: "Carbamazepine", brandName: "Tegretol", drugClass: "Anticonvulsant", suffix: "", indications: ["Seizures", "Trigeminal neuralgia", "Bipolar disorder"], sideEffects: ["SJS/TEN", "Aplastic anemia", "Hyponatremia (SIADH)"], clinicalPearls: ["Strong CYP3A4 inducer", "HLA-B*1502 testing in Asian patients", "Autoinduction"]),
            Drug(id: "d97", genericName: "Phenytoin", brandName: "Dilantin", drugClass: "Anticonvulsant", suffix: "", indications: ["Seizures", "Status epilepticus"], sideEffects: ["Gingival hyperplasia", "Hirsutism", "Ataxia", "Nystagmus", "Osteoporosis"], clinicalPearls: ["Zero-order kinetics", "Monitor free levels if low albumin"]),
            Drug(id: "d93", genericName: "Valproic acid", brandName: "Depakote", drugClass: "Anticonvulsant / Mood Stabilizer", suffix: "", indications: ["Seizures", "Bipolar disorder", "Migraine prophylaxis"], sideEffects: ["Hepatotoxicity", "Pancreatitis", "Thrombocytopenia", "Weight gain", "Teratogenic (neural tube defects)"], clinicalPearls: ["Monitor LFTs and CBC"], blackBoxWarnings: ["Hepatotoxicity", "Pancreatitis", "Teratogenicity"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls9b_1", title: "Classic Antiepileptics", content: "Older agents with unique side effect profiles.", bulletPoints: ["Phenytoin: zero-order kinetics, gingival hyperplasia", "Carbamazepine: CYP inducer, HLA-B*1502 testing", "Valproic acid: hepatotoxicity, teratogenic (neural tube defects)", "All require therapeutic drug monitoring"], highlightText: "Phenytoin = zero-order | Carbamazepine = CYP inducer"),
        ])

        let sub9c = Subsection(id: "9c", moduleId: "m9", code: "9c", title: "Newer Seizure/Tremor Agents", description: "Lamotrigine, Levetiracetam, and more", iconName: "bolt.heart.fill", drugs: [
            Drug(id: "d94", genericName: "Lamotrigine", brandName: "Lamictal", drugClass: "Anticonvulsant / Mood Stabilizer", suffix: "", indications: ["Seizures", "Bipolar depression"], sideEffects: ["SJS/TEN", "Rash", "Dizziness"], clinicalPearls: ["MUST titrate slowly to prevent SJS/TEN", "Preferred for bipolar depression"]),
            Drug(id: "d95", genericName: "Levetiracetam", brandName: "Keppra", drugClass: "Anticonvulsant", suffix: "", indications: ["Partial seizures", "Generalized seizures"], sideEffects: ["Behavioral changes", "Irritability", "Somnolence"], clinicalPearls: ["Few drug interactions", "Renally eliminated", "'Keppra rage'"]),
            Drug(id: "d262", genericName: "Oxcarbazepine", brandName: "Trileptal", drugClass: "Anticonvulsant", suffix: "", indications: ["Partial seizures", "Trigeminal neuralgia"], sideEffects: ["Hyponatremia", "Dizziness", "Rash"], clinicalPearls: ["Derivative of carbamazepine with fewer interactions", "Less CYP induction"]),
            Drug(id: "d263", genericName: "Primidone", brandName: "Mysoline", drugClass: "Anticonvulsant", suffix: "", indications: ["Seizures", "Essential tremor"], sideEffects: ["Sedation", "Ataxia", "Nausea"], clinicalPearls: ["Metabolized to phenobarbital", "Used for essential tremor"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls9c_1", title: "Newer Anticonvulsants", content: "Better tolerated agents for seizures.", bulletPoints: ["Lamotrigine: titrate slowly (SJS risk), preferred for bipolar depression", "Levetiracetam: few interactions, 'Keppra rage'", "Oxcarbazepine: fewer interactions than carbamazepine", "Primidone: metabolizes to phenobarbital, used for tremor"], highlightText: "Lamotrigine: TITRATE SLOWLY (SJS risk)"),
        ])

        let sub9d = Subsection(id: "9d", moduleId: "m9", code: "9d", title: "Migraine + Cognition + Vestibular", description: "Triptans, dementia drugs, and more", iconName: "brain.fill", drugs: [
            Drug(id: "d264", genericName: "Donepezil", brandName: "Aricept", drugClass: "Cholinesterase Inhibitor", suffix: "", indications: ["Alzheimer's disease"], sideEffects: ["Nausea", "Diarrhea", "Bradycardia", "Insomnia"], clinicalPearls: ["First-line for mild-moderate Alzheimer's", "Take at bedtime"]),
            Drug(id: "d265", genericName: "Meclizine", brandName: "Antivert", drugClass: "Antihistamine (antivertigo)", suffix: "", indications: ["Vertigo", "Motion sickness"], sideEffects: ["Drowsiness", "Dry mouth"], clinicalPearls: ["First-line for vertigo symptoms", "OTC"]),
            Drug(id: "d266", genericName: "Melatonin", brandName: "Melatonin", drugClass: "Hormone supplement", suffix: "", indications: ["Insomnia", "Circadian rhythm disorders"], sideEffects: ["Drowsiness", "Headache"], clinicalPearls: ["OTC supplement", "Best for circadian rhythm issues and jet lag"]),
            Drug(id: "d267", genericName: "Memantine", brandName: "Namenda", drugClass: "NMDA Receptor Antagonist", suffix: "", indications: ["Moderate-severe Alzheimer's"], sideEffects: ["Dizziness", "Headache", "Confusion"], clinicalPearls: ["Often combined with donepezil (Namzaric)", "For moderate-severe AD"]),
            Drug(id: "d268", genericName: "Rimegepant", brandName: "Nurtec ODT", drugClass: "CGRP Receptor Antagonist", suffix: "-gepant", indications: ["Acute migraine", "Migraine prevention"], sideEffects: ["Nausea"], clinicalPearls: ["ODT formulation", "Dual role: acute AND preventive"]),
            Drug(id: "d269", genericName: "Rizatriptan", brandName: "Maxalt", drugClass: "Triptan", suffix: "-triptan", indications: ["Acute migraine"], sideEffects: ["Chest tightness", "Dizziness", "Paresthesias"], clinicalPearls: ["Fast-acting triptan", "Reduce dose with propranolol"]),
            Drug(id: "d270", genericName: "Sumatriptan", brandName: "Imitrex", drugClass: "Triptan", suffix: "-triptan", indications: ["Acute migraine", "Cluster headache"], sideEffects: ["Chest tightness", "Flushing", "Paresthesias"], clinicalPearls: ["First triptan approved", "SubQ, nasal, and oral forms", "Avoid in CAD, uncontrolled HTN"]),
            Drug(id: "d271", genericName: "Topiramate", brandName: "Topamax", drugClass: "Anticonvulsant", suffix: "", indications: ["Seizures", "Migraine prophylaxis", "Weight loss (off-label)"], sideEffects: ["Cognitive impairment", "Weight loss", "Kidney stones", "Metabolic acidosis", "Teratogenic"], clinicalPearls: ["'Dopamax' - cognitive slowing", "Causes weight loss (unlike most AEDs)", "Teratogenic (cleft lip/palate)"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls9d_1", title: "Triptans & Migraine", content: "Acute and preventive migraine therapy.", bulletPoints: ["Triptans (-triptan): first-line acute migraine, avoid in CAD", "CGRP antagonists (-gepant): newer, dual acute + preventive", "Topiramate: migraine prevention, causes weight loss + cognitive issues", "Sumatriptan: SubQ for fastest onset"], highlightText: "Triptans: avoid in CAD/uncontrolled HTN"),
            LearningSlide(id: "ls9d_2", title: "Dementia & Vestibular", content: "Cognitive and vestibular agents.", bulletPoints: ["Donepezil (Aricept): first-line mild-moderate Alzheimer's", "Memantine: for moderate-severe AD, often combined with donepezil", "Meclizine: first-line for vertigo/motion sickness"], highlightText: "Donepezil = first-line Alzheimer's"),
        ])

        let sub9e = Subsection(id: "9e", moduleId: "m9", code: "9e", title: "Parkinson's Disease Medications", description: "Dopamine agonists", iconName: "figure.walk", drugs: [
            Drug(id: "d272", genericName: "Pramipexole", brandName: "Mirapex", drugClass: "Dopamine Agonist", suffix: "", indications: ["Parkinson's disease", "Restless legs syndrome"], sideEffects: ["Nausea", "Orthostatic hypotension", "Somnolence", "Impulse control disorders"], clinicalPearls: ["Impulse control: gambling, hypersexuality, compulsive shopping", "Renally eliminated"]),
            Drug(id: "d273", genericName: "Ropinirole", brandName: "Requip", drugClass: "Dopamine Agonist", suffix: "", indications: ["Parkinson's disease", "Restless legs syndrome"], sideEffects: ["Nausea", "Somnolence", "Impulse control disorders"], clinicalPearls: ["Similar to pramipexole", "Hepatically metabolized"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls9e_1", title: "Dopamine Agonists for Parkinson's", content: "Dopamine agonists directly stimulate D2 receptors.", bulletPoints: ["Pramipexole and ropinirole: also for restless legs syndrome", "Key side effect: impulse control disorders (gambling, hypersexuality)", "Orthostatic hypotension and somnolence common", "Often used as adjunct to levodopa"], highlightText: "Dopamine agonists: watch for impulse control disorders"),
        ])

        let sub9f = Subsection(id: "9f", moduleId: "m9", code: "9f", title: "Mastering Neuro & Seizure", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m9", number: 9, title: "Neuro & Seizure Disorders", subtitle: "Seizures, Migraine & Parkinson's", iconName: "brain.fill", accentColorHex: "00ACC1", subsections: [sub9a, sub9b, sub9c, sub9d, sub9e, sub9f])
    }

    // MARK: - Module 10: GU, End-Organs & Misc
    static func buildModule10() -> DrugModule {
        let sub10a = Subsection(id: "10a", moduleId: "m10", code: "10a", title: "BPH + OAB + Urinary", description: "Prostate, bladder, and ED medications", iconName: "cross.fill", drugs: [
            Drug(id: "d190", genericName: "Dutasteride", brandName: "Avodart", drugClass: "5-Alpha Reductase Inhibitor", suffix: "-steride", indications: ["BPH"], sideEffects: ["Sexual dysfunction", "Decreased PSA"], clinicalPearls: ["Inhibits both type 1 and type 2 5-AR"]),
            Drug(id: "d189", genericName: "Finasteride", brandName: "Proscar/Propecia", drugClass: "5-Alpha Reductase Inhibitor", suffix: "-steride", indications: ["BPH", "Male pattern baldness"], sideEffects: ["Sexual dysfunction", "Decreased PSA", "Teratogenic"], clinicalPearls: ["Lowers PSA by ~50%", "Women should not handle crushed tablets"]),
            Drug(id: "d192", genericName: "Mirabegron", brandName: "Myrbetriq", drugClass: "Beta-3 Agonist", suffix: "", indications: ["Overactive bladder"], sideEffects: ["Hypertension", "UTI", "Headache"], clinicalPearls: ["Alternative to anticholinergics for OAB"]),
            Drug(id: "d191", genericName: "Oxybutynin", brandName: "Ditropan", drugClass: "Anticholinergic", suffix: "", indications: ["Overactive bladder"], sideEffects: ["Dry mouth", "Constipation", "Blurred vision", "Cognitive impairment"], clinicalPearls: ["Avoid in elderly (anticholinergic burden)"]),
            Drug(id: "d274", genericName: "Phenazopyridine", brandName: "Pyridium", drugClass: "Urinary Analgesic", suffix: "", indications: ["UTI symptom relief (dysuria)"], sideEffects: ["Orange-red urine", "Headache"], clinicalPearls: ["Symptomatic relief only - NOT an antibiotic", "Warn about urine color change"]),
            Drug(id: "d193", genericName: "Sildenafil", brandName: "Viagra", drugClass: "PDE-5 Inhibitor", suffix: "-afil", indications: ["Erectile dysfunction", "PAH (Revatio)"], sideEffects: ["Headache", "Flushing", "Visual changes"], clinicalPearls: ["NEVER combine with nitrates"]),
            Drug(id: "d275", genericName: "Solifenacin", brandName: "Vesicare", drugClass: "Anticholinergic", suffix: "", indications: ["Overactive bladder"], sideEffects: ["Dry mouth", "Constipation", "Blurred vision"], clinicalPearls: ["More selective for bladder muscarinic receptors"]),
            Drug(id: "d194", genericName: "Tadalafil", brandName: "Cialis", drugClass: "PDE-5 Inhibitor", suffix: "-afil", indications: ["ED", "BPH", "PAH"], sideEffects: ["Headache", "Back pain", "Flushing"], clinicalPearls: ["Longest acting PDE-5i (36 hours)", "NEVER combine with nitrates"]),
            Drug(id: "d188", genericName: "Tamsulosin", brandName: "Flomax", drugClass: "Alpha-1 Blocker", suffix: "-osin", indications: ["BPH"], sideEffects: ["Orthostatic hypotension", "Dizziness", "Retrograde ejaculation"], clinicalPearls: ["Most prescribed BPH medication"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls10a_1", title: "BPH & Overactive Bladder", content: "Two main drug classes for BPH, plus OAB agents.", bulletPoints: ["Alpha-1 blockers (-osin): tamsulosin, fast relief", "5-alpha reductase inhibitors (-steride): shrink prostate over months", "OAB: oxybutynin (anticholinergic), mirabegron (beta-3 agonist)", "PDE-5 inhibitors (-afil): NEVER with nitrates"], highlightText: "-osin = fast | -steride = shrinks prostate"),
        ])

        let sub10b = Subsection(id: "10b", moduleId: "m10", code: "10b", title: "Osteoporosis & Bone Health", description: "Bisphosphonates, denosumab, teriparatide", iconName: "figure.stand", drugs: [
            Drug(id: "d171", genericName: "Alendronate", brandName: "Fosamax", drugClass: "Bisphosphonate", suffix: "-dronate", indications: ["Osteoporosis"], sideEffects: ["Esophageal irritation", "Jaw osteonecrosis", "Atypical femur fractures"], clinicalPearls: ["Take AM with water, upright 30 min"]),
            Drug(id: "d174", genericName: "Denosumab", brandName: "Prolia", drugClass: "RANK-L Inhibitor", suffix: "", indications: ["Osteoporosis"], sideEffects: ["Hypocalcemia", "Jaw osteonecrosis"], clinicalPearls: ["SubQ q6 months", "MUST not delay doses (rebound fractures)"]),
            Drug(id: "d172", genericName: "Risedronate", brandName: "Actonel", drugClass: "Bisphosphonate", suffix: "-dronate", indications: ["Osteoporosis"], sideEffects: ["Esophageal irritation"], clinicalPearls: ["Weekly or monthly dosing"]),
            Drug(id: "d175", genericName: "Teriparatide", brandName: "Forteo", drugClass: "PTH Analog", suffix: "", indications: ["Severe osteoporosis"], sideEffects: ["Hypercalcemia", "Orthostatic hypotension"], clinicalPearls: ["Anabolic (builds bone)", "Max 2 years of use"]),
            Drug(id: "d173", genericName: "Zoledronic acid", brandName: "Reclast", drugClass: "Bisphosphonate (IV)", suffix: "-dronate", indications: ["Osteoporosis", "Paget's disease"], sideEffects: ["Flu-like symptoms", "Renal impairment", "Jaw osteonecrosis"], clinicalPearls: ["IV once yearly for osteoporosis"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls10b_1", title: "Bisphosphonates & Bone Agents", content: "Bisphosphonates inhibit osteoclasts.", bulletPoints: ["All end in -dronate", "Oral: take AM, upright 30 min, full glass of water", "Denosumab (Prolia): SubQ q6 months, never delay", "Teriparatide (Forteo): anabolic, max 2 years"], highlightText: "-dronate = Bisphosphonate. Upright 30 min!"),
        ])

        let sub10c = Subsection(id: "10c", moduleId: "m10", code: "10c", title: "Contraceptives & Hormonal Therapy", description: "Oral contraceptives, IUDs, HRT", iconName: "heart.circle.fill", drugs: [
            Drug(id: "d186", genericName: "Conjugated estrogens", brandName: "Premarin", drugClass: "Estrogen", suffix: "", indications: ["Menopausal symptoms", "Osteoporosis prevention"], sideEffects: ["VTE risk", "Breast cancer risk"], clinicalPearls: ["Must add progestin if patient has uterus"]),
            Drug(id: "d276", genericName: "Drospirenone/Ethinyl estradiol", brandName: "Yaz/Yasmin", drugClass: "Combined Oral Contraceptive", suffix: "", indications: ["Contraception", "PMDD", "Acne"], sideEffects: ["VTE risk", "Hyperkalemia (drospirenone)"], clinicalPearls: ["Drospirenone has antimineralocorticoid activity", "Check K+ if on ACEi/ARB/spironolactone"]),
            Drug(id: "d277", genericName: "Estradiol", brandName: "Estrace", drugClass: "Estrogen", suffix: "", indications: ["Menopausal symptoms", "Vaginal atrophy"], sideEffects: ["VTE risk", "Breast tenderness"], clinicalPearls: ["Available as oral, patch, topical, vaginal"]),
            Drug(id: "d278", genericName: "Ethinyl estradiol/Etonogestrel", brandName: "NuvaRing", drugClass: "Vaginal Ring Contraceptive", suffix: "", indications: ["Contraception"], sideEffects: ["VTE risk", "Vaginal irritation", "Headache"], clinicalPearls: ["Insert 3 weeks, remove 1 week"]),
            Drug(id: "d279", genericName: "Ethinyl estradiol/Levonorgestrel", brandName: "Levlen/Seasonique", drugClass: "Combined Oral Contraceptive", suffix: "", indications: ["Contraception"], sideEffects: ["VTE risk", "Nausea", "Breakthrough bleeding"], clinicalPearls: ["Common generic OCP", "Extended-cycle formulations available"]),
            Drug(id: "d182", genericName: "Ethinyl estradiol/Norgestimate", brandName: "Ortho Tri-Cyclen", drugClass: "Combined Oral Contraceptive", suffix: "", indications: ["Contraception", "Acne"], sideEffects: ["VTE risk", "Headache", "Nausea"], clinicalPearls: ["Contraindicated if >35 and smoking"]),
            Drug(id: "d185", genericName: "Levonorgestrel IUD", brandName: "Mirena", drugClass: "Intrauterine Progestin", suffix: "", indications: ["Contraception", "Heavy menstrual bleeding"], sideEffects: ["Irregular bleeding", "Ovarian cysts"], clinicalPearls: ["Most effective reversible contraception"]),
            Drug(id: "d184", genericName: "Medroxyprogesterone (depot)", brandName: "Depo-Provera", drugClass: "Injectable Progestin", suffix: "", indications: ["Contraception", "Endometriosis"], sideEffects: ["Weight gain", "Bone density loss", "Irregular bleeding"], clinicalPearls: ["IM every 3 months"], blackBoxWarnings: ["Bone density loss with long-term use"]),
            Drug(id: "d183", genericName: "Norethindrone", brandName: "Micronor/Camila", drugClass: "Progestin-Only Pill", suffix: "", indications: ["Contraception"], sideEffects: ["Irregular bleeding"], clinicalPearls: ["Mini-pill: take at same time daily", "Safe in breastfeeding"]),
            Drug(id: "d280", genericName: "Progesterone", brandName: "Prometrium", drugClass: "Progestin", suffix: "", indications: ["Endometrial protection with HRT", "Luteal phase support"], sideEffects: ["Drowsiness", "Headache"], clinicalPearls: ["Micronized progesterone", "Take at bedtime (sedating)"]),
            Drug(id: "d187", genericName: "Raloxifene", brandName: "Evista", drugClass: "SERM", suffix: "", indications: ["Osteoporosis prevention", "Breast cancer risk reduction"], sideEffects: ["VTE risk", "Hot flashes"], clinicalPearls: ["Estrogen agonist on bone, antagonist on breast", "Does NOT treat hot flashes"]),
            Drug(id: "d281", genericName: "Testosterone", brandName: "AndroGel/Testopel", drugClass: "Androgen", suffix: "", indications: ["Male hypogonadism"], sideEffects: ["Polycythemia", "Acne", "Sleep apnea worsening", "Liver toxicity (oral)"], clinicalPearls: ["Monitor hematocrit (polycythemia risk)", "Topical gel: avoid skin-to-skin transfer"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls10c_1", title: "Hormonal Contraception", content: "Options vary by route and hormone content.", bulletPoints: ["COCs: highest efficacy pills but VTE risk", "Progestin-only: safe in breastfeeding and smokers >35", "Mirena IUD: most effective reversible contraception", "Depo-Provera: IM q3 months, bone density loss"], highlightText: "COC: no smoking >35 | IUD: most effective"),
            LearningSlide(id: "ls10c_2", title: "HRT & Hormones", content: "Hormone replacement and related agents.", bulletPoints: ["Conjugated estrogens: add progestin if uterus present", "Raloxifene: SERM, bone agonist, breast antagonist, worsens hot flashes", "Testosterone: monitor hematocrit for polycythemia"], highlightText: "HRT: add progestin if uterus present"),
        ])

        let sub10d = Subsection(id: "10d", moduleId: "m10", code: "10d", title: "Smoking Cessation", description: "Nicotine replacement, bupropion, varenicline", iconName: "lungs.fill", drugs: [
            Drug(id: "d301", genericName: "Nicotine transdermal patch", brandName: "Nicoderm CQ", drugClass: "Long-acting NRT", suffix: "", indications: ["Smoking cessation"], sideEffects: ["Application-site irritation", "Vivid dreams", "Insomnia"], clinicalPearls: ["Apply daily to clean, dry, hair-free skin", "Rotate sites", "Remove at bedtime if vivid dreams occur"], commonDosing: [DoseFact(context: ">10 cig/day start", dose: "21 mg/day × 6 wk → 14 mg × 2 wk → 7 mg × 2 wk")]),
            Drug(id: "d302", genericName: "Nicotine polacrilex gum", brandName: "Nicorette", drugClass: "Short-acting NRT", suffix: "", indications: ["Smoking cessation"], sideEffects: ["Hiccups", "Heartburn", "Jaw soreness"], clinicalPearls: ["Chew-and-park technique", "Avoid acidic drinks 15 min before/during use", "≥9 pieces/day first 6 weeks"], commonDosing: [DoseFact(context: "1st cig ≤30 min after waking", dose: "4 mg; otherwise 2 mg")]),
            Drug(id: "d303", genericName: "Nicotine polacrilex lozenge", brandName: "Commit", drugClass: "Short-acting NRT", suffix: "", indications: ["Smoking cessation"], sideEffects: ["Nausea", "Heartburn", "Hiccups"], clinicalPearls: ["Let dissolve slowly—do not chew or swallow", "Avoid food/drink 15 min before use", "≥9 lozenges/day first 6 weeks"], commonDosing: [DoseFact(context: "1st cig ≤30 min after waking", dose: "4 mg; otherwise 2 mg")]),
            Drug(id: "d304", genericName: "Bupropion SR", brandName: "Zyban", drugClass: "NDRI", suffix: "", indications: ["Smoking cessation"], sideEffects: ["Insomnia", "Dry mouth", "Seizure risk"], clinicalPearls: ["Start 1-2 weeks before quit date", "Swallow whole—do not crush", "May delay post-quit weight gain"], blackBoxWarnings: ["Neuropsychiatric symptoms"], majorContraindications: ["Seizure disorder", "Bulimia/anorexia nervosa", "MAO inhibitor use"], commonDosing: [DoseFact(context: "Smoking cessation", dose: "150 mg daily × 3 days → 150 mg BID ≥8 h apart")]),
            Drug(id: "d305", genericName: "Varenicline", brandName: "Chantix", drugClass: "Nicotinic Partial Agonist", suffix: "", indications: ["Smoking cessation"], sideEffects: ["Nausea", "Vivid dreams", "Insomnia"], clinicalPearls: ["Start 1 week before quit date", "Take with food to reduce nausea", "Dose-adjust in severe renal impairment"], commonDosing: [DoseFact(context: "Titration", dose: "0.5 mg daily × 3 d → 0.5 mg BID × 4 d → 1 mg BID")]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls10d_1", title: "Smoking Cessation Agents", content: "Five key agents for quitting smoking.", bulletPoints: ["Patch (Nicoderm CQ): long-acting, 21→14→7 mg taper", "Gum (Nicorette) & Lozenge (Commit): short-acting, chew-and-park / dissolve", "Bupropion SR (Zyban): NDRI, CI in seizures & bulimia", "Varenicline (Chantix): partial agonist at α4β2, most effective single agent"], highlightText: "Patch + gum/lozenge = most effective OTC combo"),
        ])

        let sub10e = Subsection(id: "10e", moduleId: "m10", code: "10e", title: "Eye/Ear + Derm + Misc", description: "High-yield topical, ophthalmic, and misc agents", iconName: "leaf.fill", drugs: [
            Drug(id: "d199", genericName: "Atropine", brandName: "AtroPen", drugClass: "Anticholinergic", suffix: "", indications: ["Symptomatic bradycardia", "Organophosphate poisoning"], sideEffects: ["Tachycardia", "Dry mouth", "Mydriasis"], clinicalPearls: ["ACLS: first-line for symptomatic bradycardia"]),
            Drug(id: "d282", genericName: "Betamethasone (topical)", brandName: "Diprolene", drugClass: "Topical Corticosteroid", suffix: "", indications: ["Dermatitis", "Psoriasis", "Eczema"], sideEffects: ["Skin atrophy", "Striae", "Telangiectasia"], clinicalPearls: ["High-potency topical steroid", "Avoid on face/intertriginous areas"]),
            Drug(id: "d283", genericName: "Bimatoprost", brandName: "Lumigan", drugClass: "Prostaglandin Analog", suffix: "", indications: ["Open-angle glaucoma", "Eyelash growth (Latisse)"], sideEffects: ["Iris pigmentation change", "Eyelash growth", "Periorbital darkening"], clinicalPearls: ["Once daily at bedtime", "Permanent iris color change possible"]),
            Drug(id: "d284", genericName: "Brimonidine", brandName: "Alphagan", drugClass: "Alpha-2 Agonist (ophthalmic)", suffix: "", indications: ["Open-angle glaucoma"], sideEffects: ["Ocular allergy", "Dry mouth", "Drowsiness"], clinicalPearls: ["Also available as topical for rosacea (Mirvaso)"]),
            Drug(id: "d285", genericName: "Chlorhexidine", brandName: "Hibiclens", drugClass: "Antiseptic", suffix: "", indications: ["Surgical skin prep", "Wound antisepsis"], sideEffects: ["Skin irritation", "Allergic reaction (rare)"], clinicalPearls: ["Broad-spectrum antiseptic", "Avoid contact with eyes and ears"]),
            Drug(id: "d286", genericName: "Ciclopirox", brandName: "Loprox/Penlac", drugClass: "Antifungal", suffix: "", indications: ["Tinea infections", "Onychomycosis", "Seborrheic dermatitis"], sideEffects: ["Local irritation"], clinicalPearls: ["Nail lacquer for onychomycosis", "Broad antifungal spectrum"]),
            Drug(id: "d287", genericName: "Ciprofloxacin/Dexamethasone (otic)", brandName: "Ciprodex", drugClass: "Otic antibiotic/steroid", suffix: "", indications: ["Acute otitis media with tubes", "Otitis externa"], sideEffects: ["Ear discomfort"], clinicalPearls: ["Otic suspension", "Safe with perforated TM"]),
            Drug(id: "d288", genericName: "Clobetasol", brandName: "Temovate", drugClass: "Topical Corticosteroid", suffix: "", indications: ["Severe dermatitis", "Psoriasis"], sideEffects: ["Skin atrophy", "HPA suppression with overuse"], clinicalPearls: ["Super-high potency topical steroid", "Limit use to 2 weeks"]),
            Drug(id: "d289", genericName: "Dexamethasone/Neomycin/Polymyxin B", brandName: "Maxitrol", drugClass: "Ophthalmic antibiotic/steroid", suffix: "", indications: ["Ocular inflammation with infection risk"], sideEffects: ["Elevated IOP", "Cataract (prolonged use)"], clinicalPearls: ["Short-term use only", "Monitor IOP"]),
            Drug(id: "d290", genericName: "Dorzolamide", brandName: "Trusopt", drugClass: "Carbonic Anhydrase Inhibitor (ophthalmic)", suffix: "", indications: ["Open-angle glaucoma"], sideEffects: ["Stinging", "Bitter taste"], clinicalPearls: ["Reduces aqueous humor production", "Avoid in sulfa allergy"]),
            Drug(id: "d291", genericName: "Dorzolamide/Timolol", brandName: "Cosopt", drugClass: "CAI + Beta-blocker (ophthalmic)", suffix: "", indications: ["Open-angle glaucoma"], sideEffects: ["Stinging", "Bradycardia"], clinicalPearls: ["Combination drop", "Avoid in asthma/COPD (timolol)"]),
            Drug(id: "d198", genericName: "Epinephrine", brandName: "EpiPen", drugClass: "Sympathomimetic", suffix: "", indications: ["Anaphylaxis", "Cardiac arrest"], sideEffects: ["Tachycardia", "Hypertension", "Tremor"], clinicalPearls: ["First-line for anaphylaxis - IM thigh"]),
            Drug(id: "d200", genericName: "Flumazenil", brandName: "Romazicon", drugClass: "Benzodiazepine Antagonist", suffix: "", indications: ["Benzodiazepine overdose reversal"], sideEffects: ["Seizures", "Nausea"], clinicalPearls: ["Can precipitate seizures in benzo-dependent patients"]),
            Drug(id: "d292", genericName: "Fluorouracil (topical)", brandName: "Efudex", drugClass: "Topical Antineoplastic", suffix: "", indications: ["Actinic keratoses", "Superficial basal cell carcinoma"], sideEffects: ["Skin irritation", "Pain", "Erosion at application site"], clinicalPearls: ["Apply to lesions for 2-4 weeks", "Expect skin reaction"]),
            Drug(id: "d293", genericName: "Hydroquinone", brandName: "Lustra", drugClass: "Skin Lightening Agent", suffix: "", indications: ["Hyperpigmentation", "Melasma"], sideEffects: ["Skin irritation", "Ochronosis (prolonged use)"], clinicalPearls: ["Limit use to 3-6 months", "Use with sunscreen"]),
            Drug(id: "d196", genericName: "Iron (ferrous sulfate)", brandName: "Feosol", drugClass: "Iron Supplement", suffix: "", indications: ["Iron deficiency anemia"], sideEffects: ["Constipation", "Dark stools", "GI upset"], clinicalPearls: ["Take on empty stomach with vitamin C"]),
            Drug(id: "d294", genericName: "Ketotifen (ophthalmic)", brandName: "Zaditor", drugClass: "Antihistamine (ophthalmic)", suffix: "", indications: ["Allergic conjunctivitis"], sideEffects: ["Stinging", "Headache"], clinicalPearls: ["Mast cell stabilizer + antihistamine", "OTC"]),
            Drug(id: "d295", genericName: "Latanoprost", brandName: "Xalatan", drugClass: "Prostaglandin Analog", suffix: "", indications: ["Open-angle glaucoma"], sideEffects: ["Iris pigmentation change", "Eyelash growth"], clinicalPearls: ["First-line for open-angle glaucoma", "Once daily at bedtime"]),
            Drug(id: "d296", genericName: "Mupirocin", brandName: "Bactroban", drugClass: "Topical Antibiotic", suffix: "", indications: ["Impetigo", "MRSA nasal decolonization"], sideEffects: ["Local irritation"], clinicalPearls: ["Effective against MRSA topically", "Nasal ointment for decolonization"]),
            Drug(id: "d297", genericName: "Olopatadine (ophthalmic)", brandName: "Pataday", drugClass: "Antihistamine (ophthalmic)", suffix: "", indications: ["Allergic conjunctivitis"], sideEffects: ["Mild stinging"], clinicalPearls: ["Once daily formulation", "OTC"]),
            Drug(id: "d197", genericName: "Potassium chloride", brandName: "K-Dur/Klor-Con", drugClass: "Electrolyte", suffix: "", indications: ["Hypokalemia"], sideEffects: ["GI irritation", "Hyperkalemia"], clinicalPearls: ["Take with food and full glass of water"]),
            Drug(id: "d298", genericName: "Timolol (ophthalmic)", brandName: "Timoptic", drugClass: "Beta-blocker (ophthalmic)", suffix: "-olol", indications: ["Open-angle glaucoma"], sideEffects: ["Bradycardia", "Bronchospasm"], clinicalPearls: ["Systemic absorption can cause bradycardia/bronchospasm", "Avoid in asthma"]),
            Drug(id: "d299", genericName: "Tretinoin", brandName: "Retin-A", drugClass: "Topical Retinoid", suffix: "", indications: ["Acne vulgaris", "Photoaging"], sideEffects: ["Skin irritation", "Peeling", "Photosensitivity"], clinicalPearls: ["Apply at bedtime", "Use sunscreen", "Teratogenic (topical risk low but avoid in pregnancy)"]),
            Drug(id: "d300", genericName: "Triamcinolone (topical)", brandName: "Kenalog", drugClass: "Topical Corticosteroid", suffix: "", indications: ["Dermatitis", "Eczema", "Psoriasis"], sideEffects: ["Skin atrophy", "Striae"], clinicalPearls: ["Medium-potency topical steroid", "Also available as injection for joint/soft tissue"]),
            Drug(id: "d195", genericName: "Vitamin D (cholecalciferol)", brandName: "D3", drugClass: "Vitamin", suffix: "", indications: ["Vitamin D deficiency", "Osteoporosis prevention"], sideEffects: ["Hypercalcemia (toxic doses)"], clinicalPearls: ["D3 preferred over D2", "Goal >30 ng/mL"]),
        ], isMasteryQuiz: false, learningSlides: [
            LearningSlide(id: "ls10e_1", title: "Glaucoma Medications", content: "Multiple classes lower intraocular pressure.", bulletPoints: ["Prostaglandin analogs (latanoprost): first-line, once daily at bedtime", "Beta-blockers (timolol): avoid in asthma/COPD", "CAI (dorzolamide): avoid in sulfa allergy", "Iris color change with prostaglandin analogs"], highlightText: "Latanoprost = first-line glaucoma"),
            LearningSlide(id: "ls10e_2", title: "Topical Steroids & Dermatology", content: "Topical corticosteroid potency matters.", bulletPoints: ["Super-high: clobetasol (Temovate) - limit 2 weeks", "High: betamethasone (Diprolene)", "Medium: triamcinolone (Kenalog)", "Tretinoin (Retin-A): acne, apply at bedtime, use sunscreen"], highlightText: "Higher potency = more skin atrophy risk"),
            LearningSlide(id: "ls10e_3", title: "Emergency Agents & Supplements", content: "Essential emergency and supplemental agents.", bulletPoints: ["Epinephrine: #1 for anaphylaxis, IM in thigh", "Atropine: symptomatic bradycardia, organophosphate poisoning", "Iron: take with vitamin C, separate from levothyroxine", "Vitamin D3: goal >30 ng/mL"], highlightText: "Epi = anaphylaxis | Atropine = bradycardia"),
        ])

        let sub10f = Subsection(id: "10f", moduleId: "m10", code: "10f", title: "Mastering GU & Misc", description: "Comprehensive review", iconName: "trophy.fill", drugs: [], isMasteryQuiz: true, learningSlides: [])

        return DrugModule(id: "m10", number: 10, title: "GU, End-Organs & Misc", subtitle: "Urology, Bones, Hormones & More", iconName: "leaf.fill", accentColorHex: "AD1457", subsections: [sub10a, sub10b, sub10c, sub10d, sub10e, sub10f])
    }
}
