// PharmaLingo — Module 10b (Osteoporosis & Bone Health)
// Curated Add-On Question Pack (45 questions)
// IDs: q10b_add_001 ... q10b_add_045
//
// Integration:
// 1) Add this file to your project.
// 2) In DrugDataService.populateCuratedBank(_:), ensure subsection 10b exists, then append:
//
//    if bank["10b"] == nil { bank["10b"] = [] }
//    bank["10b"]?.append(contentsOf: Self.curatedAddOnQuestions_10b)
//
// Notes:
// - All questions are single-best-answer multiple choice with 5 choices.
// - Stems are written in a teaching style and designed to avoid exact duplicates
//   of the current generated templates.
// - relatedDrugIds use the uploaded repo IDs:
//   d171 (Alendronate / Fosamax)
//   d172 (Risedronate / Actonel)
//   d173 (Zoledronic acid / Reclast)
//   d174 (Denosumab / Prolia)
//   d175 (Teriparatide / Forteo)
//
// Generated on: 2026-03-11

import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_10b: [Question] = [
        .multipleChoice(
            id: "q10b_add_001",
            subsectionId: "10b",
            difficulty: .easy,
            question: "Fosamax is a classic oral bisphosphonate used for osteoporosis, especially when a once-weekly option is desired. What is the generic name of Fosamax?",
            options: ["Alendronate", "Risedronate", "Denosumab", "Teriparatide", "Zoledronic acid"],
            answer: "Alendronate",
            explanation: "Fosamax is the brand name for alendronate, an oral bisphosphonate used to reduce fracture risk in osteoporosis.",
            objective: .brandGeneric,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_002",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A student remembers that bisphosphonates bind bone hydroxyapatite and specifically inhibit osteoclast-mediated bone resorption. Which 10b drug best matches that mechanism as the classic oral example?",
            options: ["Alendronate", "Denosumab", "Teriparatide", "Tamsulosin", "Mirabegron"],
            answer: "Alendronate",
            explanation: "Alendronate is a bisphosphonate that inhibits osteoclast-mediated bone resorption. Denosumab works through RANKL, and teriparatide is a PTH analog that is anabolic rather than antiresorptive.",
            objective: .moa,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "moa"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_003",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient is starting weekly alendronate for osteoporosis. Which administration instruction is most appropriate to reduce esophageal irritation and maximize absorption?",
            options: ["Take it first thing in the morning with plain water, stay upright for at least 30 minutes, and wait at least 30 minutes before food or other medicines", "Take it at bedtime with milk so it is easier on the stomach", "Take it with breakfast and a calcium supplement for better absorption", "Chew it after lunch and lie down if it causes nausea", "Take it only when bone pain flares up"],
            answer: "Take it first thing in the morning with plain water, stay upright for at least 30 minutes, and wait at least 30 minutes before food or other medicines",
            explanation: "Alendronate should be taken upon arising with plain water only, before food or other medications, and the patient must remain upright for at least 30 minutes to reduce esophageal injury risk.",
            objective: .dosing,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "administration"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_004",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient with osteoporosis also has achalasia and cannot reliably sit upright for 30 minutes after taking pills. Which drug from this section is a poor choice specifically because of that administration-related contraindication?",
            options: ["Alendronate", "Denosumab", "Teriparatide", "Zoledronic acid", "Mirabegron"],
            answer: "Alendronate",
            explanation: "Alendronate is contraindicated in patients with esophageal abnormalities that delay emptying, such as achalasia, and in patients who cannot remain upright for at least 30 minutes.",
            objective: .contraindication,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "contraindication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_005",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A woman starts alendronate and then reports chest pain, pain with swallowing, and new worsening heartburn. Which high-yield adverse effect should come to mind first?",
            options: ["Esophageal irritation or ulceration", "Severe neutropenia", "Acute glaucoma", "Orange-red urine", "Bronchospasm"],
            answer: "Esophageal irritation or ulceration",
            explanation: "Alendronate can cause esophageal irritation, esophagitis, or ulceration, especially if administration instructions are not followed carefully.",
            objective: .adverseEffect,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "esophagus"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_006",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient wants to swallow her weekly alendronate with her morning calcium tablet so she can take everything together. What is the best response?",
            options: ["Calcium can markedly reduce alendronate absorption, so alendronate should be taken first by itself with plain water", "Calcium improves alendronate absorption and should be taken at the same time", "Alendronate should always be taken with antacids to prevent ulceration", "The only important interaction is with insulin, not calcium", "It is better to take alendronate with orange juice than with water"],
            answer: "Calcium can markedly reduce alendronate absorption, so alendronate should be taken first by itself with plain water",
            explanation: "Calcium supplements, antacids, and other oral medications can interfere with alendronate absorption. It should be taken alone with plain water before other products.",
            objective: .interaction,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_007",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Before starting alendronate, which abnormality should be corrected because the drug can worsen it?",
            options: ["Hypocalcemia", "Mild hyperlipidemia", "Seasonal allergies", "Migraine aura", "Insomnia"],
            answer: "Hypocalcemia",
            explanation: "Pre-existing hypocalcemia should be corrected before starting alendronate because bisphosphonates can worsen low calcium levels.",
            objective: .monitoring,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "hypocalcemia"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_008",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A postmenopausal patient wants a well-known oral bisphosphonate option for osteoporosis that is commonly used once weekly. Which drug best fits that description?",
            options: ["Alendronate", "Denosumab", "Teriparatide", "Zoledronic acid", "Phenazopyridine"],
            answer: "Alendronate",
            explanation: "Alendronate is a classic oral bisphosphonate commonly used once weekly for osteoporosis treatment and fracture-risk reduction.",
            objective: .indication,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "indication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_009",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient on long-term alendronate says she has persistent dull pain in her thigh and groin before any obvious trauma. Which rare but high-yield complication should be considered?",
            options: ["Atypical femur fracture", "Acute pancreatitis", "Serotonin syndrome", "Nephrogenic diabetes insipidus", "Tardive dyskinesia"],
            answer: "Atypical femur fracture",
            explanation: "Long-term bisphosphonate therapy has been associated with atypical femur fractures, and thigh or groin pain can be a warning symptom before a complete fracture occurs.",
            objective: .adverseEffect,
            relatedDrugIds: ["d171"],
            tags: ["10b", "alendronate", "atypical-femur-fracture"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_010",
            subsectionId: "10b",
            difficulty: .easy,
            question: "Actonel is another oral osteoporosis medication from the -dronate family. What is the generic name of Actonel?",
            options: ["Risedronate", "Alendronate", "Denosumab", "Teriparatide", "Zoledronic acid"],
            answer: "Risedronate",
            explanation: "Actonel is the brand name for risedronate, an oral bisphosphonate used for osteoporosis.",
            objective: .brandGeneric,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_011",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A learner notices that risedronate ends in -dronate and wants to sort it into the correct class. Which class does risedronate belong to?",
            options: ["Bisphosphonate", "RANK-L inhibitor", "PTH analog", "SERM", "Calcitonin receptor blocker"],
            answer: "Bisphosphonate",
            explanation: "Risedronate is a bisphosphonate. The -dronate ending is a classic clue for this osteoporosis drug class.",
            objective: .classId,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "class"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_012",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient wants an oral antiresorptive option for osteoporosis and asks whether any choices can be taken less often than every week. Which drug from this subsection is known for weekly or monthly oral dosing options?",
            options: ["Risedronate", "Denosumab", "Teriparatide", "Zoledronic acid", "Tamsulosin"],
            answer: "Risedronate",
            explanation: "Risedronate is an oral bisphosphonate that can be used with weekly or monthly regimens depending on the formulation and indication.",
            objective: .indication,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "dosing-frequency"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_013",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Which counseling point is best for a patient starting risedronate tablets for osteoporosis?",
            options: ["Take it with plain water at least 30 minutes before the first food, drink, or medication of the day and avoid lying down for 30 minutes", "Take it with breakfast and coffee to lessen nausea", "Take it at bedtime so the drug can work overnight", "Take it only when bone pain is present", "Chew the tablet and then follow with calcium"],
            answer: "Take it with plain water at least 30 minutes before the first food, drink, or medication of the day and avoid lying down for 30 minutes",
            explanation: "Risedronate should be taken with plain water before food or other medications, and the patient should remain upright for at least 30 minutes.",
            objective: .dosing,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "administration"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_014",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A woman with severe dysphagia from an esophageal stricture is being considered for risedronate. Which statement is most accurate?",
            options: ["Risedronate is contraindicated because esophageal abnormalities can increase the risk of serious upper GI injury", "Risedronate is preferred because it dissolves in the esophagus before absorption", "Risedronate is the safest option when the patient cannot sit upright after swallowing pills", "Risedronate should be taken with milk to coat the esophagus", "This history matters only for teriparatide, not risedronate"],
            answer: "Risedronate is contraindicated because esophageal abnormalities can increase the risk of serious upper GI injury",
            explanation: "Risedronate is contraindicated in patients with esophageal abnormalities that delay emptying, such as stricture or achalasia, and in those unable to remain upright for at least 30 minutes.",
            objective: .contraindication,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "contraindication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_015",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient with low dietary dairy intake asks whether anything else matters while taking risedronate. Which teaching point is most appropriate?",
            options: ["Adequate calcium and vitamin D intake is still important while on antiresorptive therapy", "Calcium and vitamin D should be permanently avoided during therapy", "Only vitamin K matters for risedronate effectiveness", "The drug replaces the need for all calcium and vitamin D intake", "Supplementation matters only with teriparatide, not bisphosphonates"],
            answer: "Adequate calcium and vitamin D intake is still important while on antiresorptive therapy",
            explanation: "Patients taking risedronate should ensure adequate calcium and vitamin D intake if diet alone is insufficient.",
            objective: .pearl,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "calcium-vitamin-d"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_016",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient on Actonel calls because she has new painful swallowing and worsening heartburn. Which advice is most appropriate?",
            options: ["These can signal serious esophageal irritation, so she should contact her prescriber promptly", "These symptoms are expected and mean the drug is working", "Double the next dose to get through the irritation phase faster", "Take the next dose with milk and lie down right away", "Ignore the symptoms unless she also develops a rash"],
            answer: "These can signal serious esophageal irritation, so she should contact her prescriber promptly",
            explanation: "Pain with swallowing, chest pain, or new worsening heartburn can signal esophageal injury from oral bisphosphonates and should not be ignored.",
            objective: .adverseEffect,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "esophagus"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_017",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Why is taking risedronate with breakfast, coffee, or other morning pills a bad idea?",
            options: ["Food and other oral products can markedly reduce absorption and clinical benefit", "It causes the tablet to become toxic in the stomach", "It instantly raises serum calcium to dangerous levels", "It causes all bisphosphonates to become sedating", "Breakfast only matters for denosumab, not risedronate"],
            answer: "Food and other oral products can markedly reduce absorption and clinical benefit",
            explanation: "Risedronate absorption is reduced by food, beverages other than plain water, and other oral medications or supplements such as calcium and antacids.",
            objective: .interaction,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "absorption"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_018",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient on long-term risedronate undergoes a tooth extraction and later develops jaw pain with poor healing. Which rare but high-yield complication should be considered?",
            options: ["Osteonecrosis of the jaw", "Serotonin syndrome", "Red man syndrome", "Drug-induced lupus", "Torsades de pointes"],
            answer: "Osteonecrosis of the jaw",
            explanation: "Osteonecrosis of the jaw is a rare but important adverse effect associated with antiresorptive therapies including bisphosphonates, especially around invasive dental procedures.",
            objective: .adverseEffect,
            relatedDrugIds: ["d172"],
            tags: ["10b", "risedronate", "onj"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_019",
            subsectionId: "10b",
            difficulty: .easy,
            question: "Reclast is the well-known IV bone agent given much less often than oral bisphosphonates. What is the generic name of Reclast?",
            options: ["Zoledronic acid", "Denosumab", "Teriparatide", "Alendronate", "Risedronate"],
            answer: "Zoledronic acid",
            explanation: "Reclast is the brand name for zoledronic acid, an IV bisphosphonate used for osteoporosis and Paget's disease.",
            objective: .brandGeneric,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_020",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient has osteoporosis but cannot reliably follow fasting and upright instructions for oral bisphosphonates. Which 10b option is an IV bisphosphonate commonly given once yearly?",
            options: ["Zoledronic acid", "Alendronate", "Risedronate", "Teriparatide", "Phenazopyridine"],
            answer: "Zoledronic acid",
            explanation: "Zoledronic acid is an IV bisphosphonate often used once yearly for osteoporosis, making it useful when oral bisphosphonate administration is impractical.",
            objective: .indication,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "yearly-iv"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_021",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Zoledronic acid helps avoid daily or weekly pills, but the infusion still has an important administration rule. Which instruction is correct for the osteoporosis formulation?",
            options: ["Infuse it over no less than 15 minutes", "Push it IV over 1 to 2 minutes to reduce chair time", "Inject it subcutaneously every month", "Take it by mouth with juice the morning after the infusion", "Chew a tablet once yearly"],
            answer: "Infuse it over no less than 15 minutes",
            explanation: "Zoledronic acid should be administered as an IV infusion over no less than 15 minutes to reduce renal toxicity risk.",
            objective: .dosing,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "infusion"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_022",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient is returning for her next yearly Reclast infusion. Which monitoring step is especially important before each dose?",
            options: ["Check serum creatinine and renal function", "Check INR", "Check TSH", "Check digoxin level", "Check A1c"],
            answer: "Check serum creatinine and renal function",
            explanation: "Zoledronic acid can impair renal function, so serum creatinine and renal status should be assessed before each dose.",
            objective: .monitoring,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "monitoring"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_023",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A provider is reviewing whether a patient can receive zoledronic acid for osteoporosis. Which renal finding is the clearest reason to avoid it?",
            options: ["Creatinine clearance below 35 mL/min", "LDL of 160 mg/dL", "A history of migraines", "Mild seasonal allergic rhinitis", "A past ankle sprain"],
            answer: "Creatinine clearance below 35 mL/min",
            explanation: "Zoledronic acid is contraindicated in patients with creatinine clearance below 35 mL/min or with evidence of acute renal impairment.",
            objective: .contraindication,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "renal"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_024",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Which electrolyte problem should be corrected before giving zoledronic acid because the drug can worsen it?",
            options: ["Hypocalcemia", "Hypernatremia", "Hyperuricemia", "Hypoglycemia", "Hyperchloremia"],
            answer: "Hypocalcemia",
            explanation: "Pre-existing hypocalcemia should be corrected before starting zoledronic acid, and calcium plus vitamin D supplementation is typically recommended.",
            objective: .monitoring,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "hypocalcemia"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_025",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient develops fever, myalgias, arthralgias, and chills the day after her first zoledronic acid infusion. Which high-yield adverse effect best explains this?",
            options: ["Acute phase reaction", "Angioedema from sulfonamide allergy", "Anticholinergic toxicity", "Serotonin syndrome", "Stevens-Johnson syndrome"],
            answer: "Acute phase reaction",
            explanation: "Zoledronic acid can cause an acute phase reaction within a few days of infusion, often with fever, myalgias, arthralgias, and flu-like symptoms.",
            objective: .adverseEffect,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "acute-phase-reaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_026",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Which drug in this subsection is listed in your course materials for both osteoporosis and Paget's disease of bone?",
            options: ["Zoledronic acid", "Denosumab", "Teriparatide", "Finasteride", "Oxybutynin"],
            answer: "Zoledronic acid",
            explanation: "Zoledronic acid is used for osteoporosis and is also a classic high-yield agent for Paget's disease of bone.",
            objective: .indication,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "pagets"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_027",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient arrives for zoledronic acid infusion after several days of vomiting and poor oral intake. Why might the infusion be delayed?",
            options: ["Dehydration can increase the risk of renal injury, so therapy may be held until she is normovolemic", "Vomiting proves the patient has hyperparathyroidism", "Zoledronic acid only works when the patient is fasting for 12 hours", "The drug must never be given during winter months", "Vomiting means the patient should switch to oral alendronate that same day"],
            answer: "Dehydration can increase the risk of renal injury, so therapy may be held until she is normovolemic",
            explanation: "If a patient appears dehydrated, zoledronic acid may be withheld until normovolemia is restored because renal toxicity is a major concern with this IV bisphosphonate.",
            objective: .pearl,
            relatedDrugIds: ["d173"],
            tags: ["10b", "zoledronic-acid", "renal-pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_028",
            subsectionId: "10b",
            difficulty: .easy,
            question: "Prolia is the every-6-month bone medication that is given by subcutaneous injection rather than by mouth. What is the generic name of Prolia?",
            options: ["Denosumab", "Zoledronic acid", "Teriparatide", "Risedronate", "Alendronate"],
            answer: "Denosumab",
            explanation: "Prolia is the brand name for denosumab, a RANK-L inhibitor used for osteoporosis and other bone-loss states.",
            objective: .brandGeneric,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_029",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Denosumab is not a bisphosphonate. Instead, it prevents osteoclast activation by binding which target?",
            options: ["RANKL", "Vitamin D receptor", "Calcitonin receptor", "Cyclooxygenase-2", "HMG-CoA reductase"],
            answer: "RANKL",
            explanation: "Denosumab binds RANKL, preventing it from activating RANK on osteoclasts and their precursors. This decreases bone resorption.",
            objective: .moa,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "moa"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_030",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient wants to know how often Prolia is usually given for osteoporosis. Which schedule is correct?",
            options: ["Subcutaneous injection every 6 months", "IV infusion once yearly", "Subcutaneous injection once daily", "Oral tablet once weekly", "Oral tablet every 12 hours"],
            answer: "Subcutaneous injection every 6 months",
            explanation: "Denosumab for osteoporosis is typically administered as a subcutaneous injection every 6 months.",
            objective: .dosing,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "dosing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_031",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient misses her scheduled Prolia appointment by several weeks. What is the best next step?",
            options: ["Give the injection as soon as feasible, then schedule future doses every 6 months from the date of that last injection", "Skip the missed dose and wait until next year", "Double the next dose to catch up", "Restart with weekly oral dosing for one month only", "Stop treatment permanently because missed doses are never replaced"],
            answer: "Give the injection as soon as feasible, then schedule future doses every 6 months from the date of that last injection",
            explanation: "If a denosumab dose is missed, it should be administered as soon as the patient is available, and future injections are then scheduled every 6 months from the last injection date.",
            objective: .dosing,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "missed-dose"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_032",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Which serious current boxed warning is especially important to remember for denosumab products used for osteoporosis?",
            options: ["Severe hypocalcemia in patients with advanced kidney disease", "Fatal lactic acidosis in all patients over age 65", "Torsades de pointes with grapefruit juice", "Irreversible pulmonary fibrosis after one dose", "Aplastic anemia with every formulation"],
            answer: "Severe hypocalcemia in patients with advanced kidney disease",
            explanation: "Denosumab products carry a boxed warning for severe hypocalcemia in patients with advanced chronic kidney disease, including dialysis-dependent patients.",
            objective: .contraindication,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "boxed-warning"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_033",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Before giving the first Prolia injection, which problem should be corrected and then monitored closely, especially in patients with kidney disease?",
            options: ["Hypocalcemia", "Mild hypertriglyceridemia", "Iron deficiency without anemia", "Sleep apnea", "Rosacea"],
            answer: "Hypocalcemia",
            explanation: "Pre-existing hypocalcemia must be corrected before starting denosumab, and serum calcium deserves close attention, especially in advanced CKD.",
            objective: .monitoring,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "calcium-monitoring"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_034",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient about to start denosumab asks why her clinician also asked about dental work and oral health. What is the best explanation?",
            options: ["Denosumab can rarely be associated with osteonecrosis of the jaw, so oral evaluation and dental awareness matter", "The injection permanently stains the teeth unless a cleaning is done first", "Denosumab can only be given by a dentist", "The drug causes immediate tooth eruption", "Dental hygiene matters only with fluoride, not bone medications"],
            answer: "Denosumab can rarely be associated with osteonecrosis of the jaw, so oral evaluation and dental awareness matter",
            explanation: "Osteonecrosis of the jaw is a rare but important denosumab adverse effect, so dental history, oral symptoms, and invasive dental procedures matter when counseling patients.",
            objective: .pearl,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "onj"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_035",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Which counseling point is most important if a patient is doing well on Prolia and wonders whether she can simply delay the next dose by several months?",
            options: ["Delays or discontinuation can increase fracture risk, including multiple vertebral fractures", "Spacing the dose farther apart always improves safety with no downside", "It is fine to wait until bone pain returns before receiving another dose", "Missing doses only matters for insulin, not denosumab", "A late Prolia dose should always be replaced by twice-daily oral calcium alone"],
            answer: "Delays or discontinuation can increase fracture risk, including multiple vertebral fractures",
            explanation: "Stopping or substantially delaying denosumab can lead to rebound increases in bone turnover and higher fracture risk, including multiple vertebral fractures.",
            objective: .pearl,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "rebound-fracture"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_036",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient on denosumab reports persistent new thigh pain without clear trauma. Which rare complication should be considered and evaluated?",
            options: ["Atypical femoral fracture", "Esophageal perforation", "Acute liver failure", "Tendon rupture", "Ototoxicity"],
            answer: "Atypical femoral fracture",
            explanation: "Denosumab has been associated with atypical femoral fractures, and new thigh or groin pain can be an early warning symptom.",
            objective: .adverseEffect,
            relatedDrugIds: ["d174"],
            tags: ["10b", "denosumab", "atypical-femur-fracture"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_037",
            subsectionId: "10b",
            difficulty: .easy,
            question: "Forteo is the daily self-injected bone-building medication used for severe osteoporosis. What is the generic name of Forteo?",
            options: ["Teriparatide", "Denosumab", "Zoledronic acid", "Alendronate", "Risedronate"],
            answer: "Teriparatide",
            explanation: "Forteo is the brand name for teriparatide, a parathyroid hormone analog used for patients at high fracture risk.",
            objective: .brandGeneric,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_038",
            subsectionId: "10b",
            difficulty: .medium,
            question: "Most osteoporosis drugs in this subsection reduce bone breakdown. Which one is the anabolic PTH analog that helps build new bone?",
            options: ["Teriparatide", "Alendronate", "Risedronate", "Zoledronic acid", "Denosumab"],
            answer: "Teriparatide",
            explanation: "Teriparatide is a parathyroid hormone analog and is anabolic, meaning it stimulates new bone formation rather than simply slowing bone resorption.",
            objective: .classId,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "anabolic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_039",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient has severe osteoporosis with multiple vertebral fractures despite prior antiresorptive therapy. Which 10b medication is most associated with an anabolic, bone-building strategy?",
            options: ["Teriparatide", "Alendronate", "Risedronate", "Zoledronic acid", "Phenazopyridine"],
            answer: "Teriparatide",
            explanation: "Teriparatide is used for patients with severe osteoporosis or very high fracture risk and is the classic anabolic option in this subsection.",
            objective: .indication,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "high-fracture-risk"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_040",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Which dosing instruction is most accurate for teriparatide used in osteoporosis?",
            options: ["Inject 20 mcg subcutaneously once daily into the thigh or abdominal wall", "Infuse 5 mg intravenously once yearly over 15 minutes", "Take one tablet by mouth every morning with water and remain upright", "Inject 60 mg subcutaneously every 6 months", "Use one nasal spray in each nostril every night"],
            answer: "Inject 20 mcg subcutaneously once daily into the thigh or abdominal wall",
            explanation: "Teriparatide is given as a 20 mcg subcutaneous injection once daily, usually into the thigh or abdominal wall. It is not given IV or IM.",
            objective: .dosing,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "dosing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_041",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A patient feels dizzy and lightheaded shortly after one of her first teriparatide injections. Which high-yield adverse effect best explains this?",
            options: ["Transient orthostatic hypotension", "Red man syndrome", "Tendon rupture", "Esophageal ulceration", "Retinal detachment"],
            answer: "Transient orthostatic hypotension",
            explanation: "Teriparatide can cause transient orthostatic hypotension, especially with the first several doses. Patients should be able to sit or lie down if symptoms occur.",
            objective: .adverseEffect,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "orthostasis"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_042",
            subsectionId: "10b",
            difficulty: .hard,
            question: "Which patient would make teriparatide a poor choice because of increased baseline concern for osteosarcoma?",
            options: ["A patient with Paget's disease of bone and prior skeletal radiation", "A patient with seasonal allergic rhinitis", "A patient with controlled hypothyroidism", "A patient with mild osteoarthritis of the knee", "A patient with uncomplicated GERD"],
            answer: "A patient with Paget's disease of bone and prior skeletal radiation",
            explanation: "Teriparatide should be avoided in patients at increased baseline risk of osteosarcoma, such as those with Paget's disease, prior skeletal radiation, bone metastases, or open epiphyses.",
            objective: .contraindication,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "osteosarcoma-risk"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_043",
            subsectionId: "10b",
            difficulty: .medium,
            question: "A clinician is deciding whether teriparatide is appropriate for a patient with primary hyperparathyroidism and elevated calcium. Which statement is best?",
            options: ["Teriparatide can worsen hypercalcemia and is a poor choice here", "Teriparatide is preferred because it lowers calcium", "Teriparatide is safe only if taken with an antacid", "Hypercalcemia matters for denosumab only, not teriparatide", "The main issue is orange-red urine, not calcium"],
            answer: "Teriparatide can worsen hypercalcemia and is a poor choice here",
            explanation: "Teriparatide may raise serum calcium and should be avoided or used with great caution in patients with pre-existing hypercalcemic disorders such as primary hyperparathyroidism.",
            objective: .contraindication,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "hypercalcemia"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_044",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient with recurrent kidney stones is being considered for teriparatide. Which monitoring or counseling point is most appropriate?",
            options: ["Use caution because teriparatide has not been well studied in active urolithiasis and urinary calcium may need assessment", "Kidney stone history is irrelevant because teriparatide lowers urinary calcium", "Increase the dose to flush out calcium stones", "Combine teriparatide with a bisphosphonate on the same morning for protection", "Avoid all calcium and vitamin D permanently while on treatment"],
            answer: "Use caution because teriparatide has not been well studied in active urolithiasis and urinary calcium may need assessment",
            explanation: "Teriparatide can increase calcium burden, so patients with hypercalciuria or active/recent urolithiasis may require extra caution and evaluation.",
            objective: .monitoring,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "urolithiasis"],
            source: .curated
        ),
        .multipleChoice(
            id: "q10b_add_045",
            subsectionId: "10b",
            difficulty: .hard,
            question: "A patient taking digoxin for atrial fibrillation is started on teriparatide. Which interaction pearl is most important?",
            options: ["Transient teriparatide-related hypercalcemia may predispose the patient to digitalis toxicity", "Teriparatide blocks digoxin absorption if they are taken on the same day", "Digoxin completely prevents teriparatide from building bone", "The combination is required to prevent orthostatic hypotension", "There is no meaningful interaction concern to remember"],
            answer: "Transient teriparatide-related hypercalcemia may predispose the patient to digitalis toxicity",
            explanation: "Teriparatide can transiently increase serum calcium, which can increase the risk of digoxin toxicity. This is a classic high-yield interaction pearl.",
            objective: .interaction,
            relatedDrugIds: ["d175"],
            tags: ["10b", "teriparatide", "digoxin"],
            source: .curated
        )
    ]
}
