import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_10d: [Question] = [
        .multipleChoice(id: "q10d_add_001", subsectionId: "10d", difficulty: .easy,
            question: "Nicoderm CQ is an over-the-counter nicotine replacement product used to reduce withdrawal symptoms during a quit attempt. What is the generic name of Nicoderm CQ?",
            options: ["Nicotine transdermal patch", "Nicotine polacrilex gum", "Nicotine polacrilex lozenge", "Bupropion SR", "Varenicline"],
            answer: "Nicotine transdermal patch",
            explanation: "Nicoderm CQ is the brand name for the nicotine transdermal patch.",
            objective: .brandGeneric, relatedDrugIds: ["d301"], tags: ["10d", "nicoderm-cq", "brand->generic"]),
        .multipleChoice(id: "q10d_add_002", subsectionId: "10d", difficulty: .easy,
            question: "A patient wants the long-acting nicotine replacement product that sticks to the skin and releases nicotine steadily through the day. Which brand matches the nicotine transdermal patch?",
            options: ["Nicoderm CQ", "Nicorette", "Commit", "Zyban", "Chantix"],
            answer: "Nicoderm CQ",
            explanation: "Nicoderm CQ is a common brand for the nicotine transdermal patch.",
            objective: .genericBrand, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "generic->brand"]),
        .multipleChoice(id: "q10d_add_003", subsectionId: "10d", difficulty: .medium,
            question: "A smoker asks why nicotine patches are used during a quit attempt. What is the primary indication for the nicotine transdermal patch?",
            options: ["Reducing nicotine withdrawal symptoms and cravings while quitting smoking", "Treating acute nicotine overdose", "Reversing opioid overdose", "Treating generalized anxiety disorder", "Providing rapid rescue for breakthrough cigarette cravings within minutes"],
            answer: "Reducing nicotine withdrawal symptoms and cravings while quitting smoking",
            explanation: "Nicotine patches are stop-smoking aids that reduce withdrawal symptoms, including nicotine craving, during a quit attempt.",
            objective: .indication, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "indication"]),
        .multipleChoice(id: "q10d_add_004", subsectionId: "10d", difficulty: .medium,
            question: "A nicotine patch is often paired with a short-acting nicotine product because it provides a steady background nicotine level. Which class best describes the patch?",
            options: ["Long-acting nicotine replacement therapy", "Dopamine agonist", "5-alpha reductase inhibitor", "Selective serotonin reuptake inhibitor", "Leukotriene receptor antagonist"],
            answer: "Long-acting nicotine replacement therapy",
            explanation: "The nicotine patch is a long-acting form of nicotine replacement therapy that provides steady nicotine delivery through the skin.",
            objective: .classId, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "class"]),
        .multipleChoice(id: "q10d_add_005", subsectionId: "10d", difficulty: .medium,
            question: "A person smoking more than 10 cigarettes per day wants to start OTC nicotine patch therapy. According to common stop-smoking guidance, which initial strength is typically considered first?",
            options: ["21 mg patch", "14 mg patch", "7 mg patch", "4 mg lozenge only", "150 mg tablet twice daily"],
            answer: "21 mg patch",
            explanation: "For many adults who smoke more than 10 cigarettes per day, the 21 mg patch is the typical starting strength before stepping down over time.",
            objective: .dosing, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "dosing", "21-mg"]),
        .multipleChoice(id: "q10d_add_006", subsectionId: "10d", difficulty: .medium,
            question: "A student is counseling a patient on proper patch application. Which instruction is most appropriate for a nicotine transdermal patch?",
            options: ["Apply one patch daily to clean, dry, hair-free skin and rotate sites", "Chew the patch slowly until it tingles, then park it in the cheek", "Place the patch under the tongue and let it dissolve", "Cut the patch into quarters when cravings are mild", "Apply the patch only when a craving suddenly occurs"],
            answer: "Apply one patch daily to clean, dry, hair-free skin and rotate sites",
            explanation: "Nicotine patches are applied once daily to clean, dry, hair-free skin, and application sites should be rotated to limit irritation.",
            objective: .pearl, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "counseling", "application"]),
        .multipleChoice(id: "q10d_add_007", subsectionId: "10d", difficulty: .medium,
            question: "A patient says the nicotine patch is helping cravings but is causing vivid dreams and poor sleep. What is the most practical high-yield counseling response?",
            options: ["If sleep is disturbed, remove the patch at bedtime and apply a new one the next morning", "Double the evening dose to wear off faster overnight", "Switch immediately to varenicline because vivid dreams prove patch failure", "Chew nicotine gum at bedtime instead of changing patch timing", "Stop all quit-smoking medicines permanently"],
            answer: "If sleep is disturbed, remove the patch at bedtime and apply a new one the next morning",
            explanation: "Some people develop vivid dreams or disturbed sleep with overnight patch wear; removing it at bedtime and replacing it in the morning is a common counseling pearl.",
            objective: .adverseEffect, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "vivid-dreams", "sleep"]),
        .multipleChoice(id: "q10d_add_008", subsectionId: "10d", difficulty: .medium,
            question: "A patient wants steady all-day nicotine coverage plus something faster for sudden cravings while driving home from work. Which pairing best fits that strategy?",
            options: ["Nicotine patch plus nicotine gum or lozenge as needed", "Varenicline plus two nicotine patches at all times", "Bupropion SR plus phenazopyridine", "Nicotine gum plus tadalafil", "Nicotine patch plus diphenhydramine"],
            answer: "Nicotine patch plus nicotine gum or lozenge as needed",
            explanation: "The patch provides steady background nicotine, while gum or lozenge can be used for breakthrough cravings.",
            objective: .mixedReview, relatedDrugIds: ["d301", "d302", "d303"], tags: ["10d", "combination-therapy", "patch", "cravings"]),
        .multipleChoice(id: "q10d_add_009", subsectionId: "10d", difficulty: .medium,
            question: "A patient develops mild local redness and itching where the nicotine patch was worn. Which adverse effect is most consistent with the transdermal route?",
            options: ["Application-site irritation", "Severe neutropenia", "Blue-gray skin discoloration", "Achilles tendon rupture", "Acute urinary retention"],
            answer: "Application-site irritation",
            explanation: "Local skin irritation is a common adverse effect of nicotine patches and is one reason sites should be rotated.",
            objective: .adverseEffect, relatedDrugIds: ["d301"], tags: ["10d", "nicotine-patch", "application-site", "adverse-effect"]),
        .multipleChoice(id: "q10d_add_010", subsectionId: "10d", difficulty: .easy,
            question: "Nicorette is a common smoking-cessation brand that delivers nicotine through the oral mucosa when used correctly. What is the generic name of Nicorette gum?",
            options: ["Nicotine polacrilex gum", "Nicotine transdermal patch", "Nicotine polacrilex lozenge", "Bupropion SR", "Varenicline"],
            answer: "Nicotine polacrilex gum",
            explanation: "Nicorette gum contains nicotine polacrilex and is used as a short-acting nicotine replacement product.",
            objective: .brandGeneric, relatedDrugIds: ["d302"], tags: ["10d", "nicorette", "brand->generic"]),
        .multipleChoice(id: "q10d_add_011", subsectionId: "10d", difficulty: .easy,
            question: "A patient wants the stop-smoking aid that is chewed and then parked between the cheek and gum. Which brand best matches nicotine polacrilex gum?",
            options: ["Nicorette", "Nicoderm CQ", "Commit", "Zyban", "Chantix"],
            answer: "Nicorette",
            explanation: "Nicorette is a common brand for nicotine polacrilex gum.",
            objective: .genericBrand, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "generic->brand"]),
        .multipleChoice(id: "q10d_add_012", subsectionId: "10d", difficulty: .medium,
            question: "Nicotine gum is often used for breakthrough cravings while a patient is tapering away from cigarettes. Which class best describes nicotine gum?",
            options: ["Short-acting nicotine replacement therapy", "Nicotinic receptor partial agonist", "Norepinephrine-dopamine reuptake inhibitor", "Opioid antagonist", "Antimuscarinic"],
            answer: "Short-acting nicotine replacement therapy",
            explanation: "Nicotine gum is a short-acting nicotine replacement product used to control cravings and withdrawal symptoms.",
            objective: .classId, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "class"]),
        .multipleChoice(id: "q10d_add_013", subsectionId: "10d", difficulty: .medium,
            question: "A smoker has the first cigarette of the day within 30 minutes of waking up. Which nicotine gum strength is usually the more appropriate starting choice?",
            options: ["4 mg gum", "2 mg gum", "21 mg patch", "7 mg patch", "No medication is appropriate"],
            answer: "4 mg gum",
            explanation: "If the first cigarette is within 30 minutes of waking, 4 mg nicotine gum is generally the preferred starting strength.",
            objective: .dosing, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "4-mg", "timing"]),
        .multipleChoice(id: "q10d_add_014", subsectionId: "10d", difficulty: .medium,
            question: "A patient says, \u{201C}I\u{2019}ll chew nicotine gum the same way I chew regular gum.\u{201D} Which correction is most appropriate?",
            options: ["Chew slowly until it tingles, then park it between the cheek and gum until the tingle fades", "Swallow it whole to avoid jaw soreness", "Chew continuously for 2 minutes and then spit it out", "Dissolve it under the tongue without chewing", "Use two pieces at once every time"],
            answer: "Chew slowly until it tingles, then park it between the cheek and gum until the tingle fades",
            explanation: "Nicotine gum is not used like regular gum; the \u{201C}chew and park\u{201D} technique improves buccal nicotine absorption.",
            objective: .pearl, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "chew-and-park", "counseling"]),
        .multipleChoice(id: "q10d_add_015", subsectionId: "10d", difficulty: .medium,
            question: "A patient drinks coffee immediately before every piece of nicotine gum and says the gum \u{201C}doesn\u{2019}t seem to work.\u{201D} Which counseling point is most accurate?",
            options: ["Avoid food and acidic drinks for 15 minutes before and during gum use because they can reduce nicotine absorption", "Coffee must be taken together with nicotine gum to activate it", "The gum should be swallowed with soda to improve absorption", "Only milk interferes with nicotine gum", "Acidic drinks matter only with the patch"],
            answer: "Avoid food and acidic drinks for 15 minutes before and during gum use because they can reduce nicotine absorption",
            explanation: "Coffee, soda, and other acidic drinks can reduce buccal nicotine absorption, so patients are told not to eat or drink for 15 minutes before and during gum use.",
            objective: .interaction, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "acidic-drinks", "interaction"]),
        .multipleChoice(id: "q10d_add_016", subsectionId: "10d", difficulty: .medium,
            question: "To reduce withdrawal symptoms early in a quit attempt, what is the high-yield \u{201C}use enough\u{201D} counseling pearl for nicotine gum during the first 6 weeks?",
            options: ["Use at least 9 pieces per day during the first 6 weeks", "Use only 1 piece per day to avoid dependence", "Use gum only after every relapse cigarette", "Use the gum exclusively at bedtime", "Never use gum on a schedule"],
            answer: "Use at least 9 pieces per day during the first 6 weeks",
            explanation: "Patients often under-dose nicotine gum. A key pearl is to use at least 9 pieces per day during the first 6 weeks to better control withdrawal.",
            objective: .dosing, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "use-enough", "dosing"]),
        .multipleChoice(id: "q10d_add_017", subsectionId: "10d", difficulty: .medium,
            question: "A patient with strong cravings keeps reaching for nicotine gum every few minutes. Which upper limit is highest yield from OTC labeling?",
            options: ["Do not use more than 24 pieces per day", "Do not use more than 6 pieces per day", "Do not use more than 1 piece per day", "Do not use more than 2 pieces per week", "There is no practical daily maximum"],
            answer: "Do not use more than 24 pieces per day",
            explanation: "Nicotine gum labeling advises not to use more than 24 pieces per day.",
            objective: .dosing, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "max-dose"]),
        .multipleChoice(id: "q10d_add_018", subsectionId: "10d", difficulty: .medium,
            question: "A patient using nicotine gum correctly reports hiccups and heartburn after frequently using one piece right after another. Which explanation is most appropriate?",
            options: ["Nicotine gum can cause hiccups, heartburn, and nausea if it is overused or used back-to-back", "These symptoms prove the patient needs a higher dose immediately", "Hiccups mean the gum is not being absorbed at all", "Heartburn is a classic sign of nicotine deficiency, not treatment effect", "These symptoms suggest agranulocytosis"],
            answer: "Nicotine gum can cause hiccups, heartburn, and nausea if it is overused or used back-to-back",
            explanation: "Using nicotine gum too aggressively can trigger hiccups, heartburn, nausea, and other nicotine-related side effects.",
            objective: .adverseEffect, relatedDrugIds: ["d302"], tags: ["10d", "nicotine-gum", "hiccups", "heartburn"]),
        .multipleChoice(id: "q10d_add_019", subsectionId: "10d", difficulty: .easy,
            question: "Commit is a smoking-cessation product that dissolves slowly in the mouth to deliver nicotine. What is the generic name of Commit?",
            options: ["Nicotine polacrilex lozenge", "Nicotine transdermal patch", "Nicotine polacrilex gum", "Bupropion SR", "Varenicline"],
            answer: "Nicotine polacrilex lozenge",
            explanation: "Commit is a brand of nicotine polacrilex lozenge.",
            objective: .brandGeneric, relatedDrugIds: ["d303"], tags: ["10d", "commit", "brand->generic"]),
        .multipleChoice(id: "q10d_add_020", subsectionId: "10d", difficulty: .easy,
            question: "A patient wants the nicotine product that dissolves in the mouth rather than being chewed or worn on the skin. Which brand best matches nicotine polacrilex lozenge?",
            options: ["Commit", "Nicorette", "Nicoderm CQ", "Zyban", "Chantix"],
            answer: "Commit",
            explanation: "Commit is a brand commonly associated with nicotine polacrilex lozenges.",
            objective: .genericBrand, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "generic->brand"]),
        .multipleChoice(id: "q10d_add_021", subsectionId: "10d", difficulty: .medium,
            question: "Nicotine lozenges are often used as a \u{201C}craving rescue\u{201D} option during smoking cessation. Which class best describes nicotine lozenge therapy?",
            options: ["Short-acting nicotine replacement therapy", "Atypical antidepressant", "Nicotinic receptor blocker", "Selective estrogen receptor modulator", "Acetylcholinesterase inhibitor"],
            answer: "Short-acting nicotine replacement therapy",
            explanation: "Nicotine lozenges are short-acting nicotine replacement products used to control cravings and withdrawal symptoms.",
            objective: .classId, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "class"]),
        .multipleChoice(id: "q10d_add_022", subsectionId: "10d", difficulty: .medium,
            question: "A smoker reaches for the first cigarette within 30 minutes of waking and wants to use nicotine lozenges. Which starting strength is usually more appropriate?",
            options: ["4 mg lozenge", "2 mg lozenge", "7 mg patch", "14 mg patch", "150 mg tablet daily"],
            answer: "4 mg lozenge",
            explanation: "If the first cigarette is within 30 minutes of waking, 4 mg nicotine lozenge is generally the more appropriate starting strength.",
            objective: .dosing, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "4-mg", "timing"]),
        .multipleChoice(id: "q10d_add_023", subsectionId: "10d", difficulty: .medium,
            question: "Which counseling instruction is most appropriate for proper nicotine lozenge use?",
            options: ["Let it dissolve slowly in the mouth and do not chew or swallow it", "Chew rapidly until the tingling stops", "Swallow it whole with water", "Put it directly on the skin over the upper arm", "Use it only immediately after smoking a cigarette"],
            answer: "Let it dissolve slowly in the mouth and do not chew or swallow it",
            explanation: "Nicotine lozenges should dissolve slowly in the mouth. They are not chewed like gum or swallowed whole.",
            objective: .pearl, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "counseling"]),
        .multipleChoice(id: "q10d_add_024", subsectionId: "10d", difficulty: .medium,
            question: "A patient keeps drinking cola while a nicotine lozenge is in the mouth and says it seems weak. Which advice is best?",
            options: ["Do not eat or drink for 15 minutes before use or while the lozenge is in the mouth", "Drink more soda to increase nicotine absorption", "Take two lozenges at once whenever soda is used", "Only dairy products interfere with lozenge absorption", "The lozenge should be swallowed with coffee"],
            answer: "Do not eat or drink for 15 minutes before use or while the lozenge is in the mouth",
            explanation: "Acidic beverages can interfere with buccal nicotine absorption, so patients should avoid eating or drinking for 15 minutes before use and while the lozenge is in the mouth.",
            objective: .interaction, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "acidic-drinks", "interaction"]),
        .multipleChoice(id: "q10d_add_025", subsectionId: "10d", difficulty: .medium,
            question: "What is the high-yield early-treatment counseling pearl for nicotine lozenge use during the first 6 weeks of a quit attempt?",
            options: ["Use at least 9 lozenges per day during the first 6 weeks", "Use exactly 1 lozenge per day only when cravings become unbearable", "Never use the lozenge on a schedule", "Limit use to weekends to prevent dependence", "Start at the 4 mg strength in every patient regardless of smoking pattern"],
            answer: "Use at least 9 lozenges per day during the first 6 weeks",
            explanation: "Like nicotine gum, the lozenge is often underused. A key pearl is to use enough early, typically at least 9 lozenges per day during the first 6 weeks.",
            objective: .dosing, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "use-enough", "dosing"]),
        .multipleChoice(id: "q10d_add_026", subsectionId: "10d", difficulty: .medium,
            question: "A patient asks about the highest safe daily amount of nicotine lozenge from standard OTC guidance. Which limit is most accurate?",
            options: ["No more than 20 lozenges per day", "No more than 6 lozenges per day", "No more than 1 lozenge every 24 hours", "No more than 2 lozenges per week", "There is no daily limit"],
            answer: "No more than 20 lozenges per day",
            explanation: "Nicotine lozenge labeling limits use to a maximum of 20 lozenges per day.",
            objective: .dosing, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "max-dose"]),
        .multipleChoice(id: "q10d_add_027", subsectionId: "10d", difficulty: .medium,
            question: "A patient uses nicotine lozenges one right after another and develops nausea and heartburn. Which explanation is most likely?",
            options: ["Short-acting nicotine products can cause GI irritation and nausea when used too aggressively", "This proves the nicotine dose is too low", "It means the patient is allergic to all forms of nicotine", "It indicates opioid withdrawal rather than nicotine withdrawal", "It shows severe hepatic failure from the lozenge"],
            answer: "Short-acting nicotine products can cause GI irritation and nausea when used too aggressively",
            explanation: "Using lozenges too often or back-to-back can trigger nausea, heartburn, and other nicotine-related side effects.",
            objective: .adverseEffect, relatedDrugIds: ["d303"], tags: ["10d", "nicotine-lozenge", "nausea", "heartburn"]),
        .multipleChoice(id: "q10d_add_028", subsectionId: "10d", difficulty: .easy,
            question: "Zyban is prescribed as a pill to help people stop smoking, but it does not contain nicotine. What is the generic name of Zyban?",
            options: ["Bupropion SR", "Varenicline", "Nicotine transdermal patch", "Nicotine polacrilex gum", "Nicotine polacrilex lozenge"],
            answer: "Bupropion SR",
            explanation: "Zyban is the smoking-cessation brand associated with bupropion SR.",
            objective: .brandGeneric, relatedDrugIds: ["d304"], tags: ["10d", "zyban", "brand->generic"]),
        .multipleChoice(id: "q10d_add_029", subsectionId: "10d", difficulty: .easy,
            question: "A clinician wants the sustained-release bupropion product specifically used for smoking cessation rather than depression branding. Which brand matches bupropion SR in this setting?",
            options: ["Zyban", "Chantix", "Nicorette", "Commit", "Nicoderm CQ"],
            answer: "Zyban",
            explanation: "Zyban is the smoking-cessation brand associated with bupropion SR.",
            objective: .genericBrand, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "generic->brand"]),
        .multipleChoice(id: "q10d_add_030", subsectionId: "10d", difficulty: .hard,
            question: "Bupropion SR helps with smoking cessation without supplying nicotine. Which mechanism best describes its pharmacology?",
            options: ["Norepinephrine and dopamine reuptake inhibition", "Partial agonism at alpha4beta2 nicotinic receptors", "Direct nicotine replacement through buccal absorption", "Competitive blockade of opioid receptors", "Selective serotonin reuptake inhibition only"],
            answer: "Norepinephrine and dopamine reuptake inhibition",
            explanation: "Bupropion is a non-nicotine smoking-cessation pill that works primarily as a norepinephrine-dopamine reuptake inhibitor.",
            objective: .moa, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "moa"]),
        .multipleChoice(id: "q10d_add_031", subsectionId: "10d", difficulty: .medium,
            question: "A patient wants to use bupropion SR to quit smoking. When is it generally started relative to the quit date?",
            options: ["About 1 to 2 weeks before the quit date", "Only after being smoke-free for 1 month", "Exactly on the first cigarette-free morning with no lead-in", "Only after nicotine patch therapy fails for 12 weeks", "Never before a quit date is chosen"],
            answer: "About 1 to 2 weeks before the quit date",
            explanation: "Bupropion SR is usually started about 1 to 2 weeks before the quit date so medication is on board when the patient stops smoking.",
            objective: .dosing, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "quit-date", "timing"]),
        .multipleChoice(id: "q10d_add_032", subsectionId: "10d", difficulty: .hard,
            question: "Which dosing schedule best matches the common smoking-cessation titration for bupropion SR?",
            options: ["150 mg once daily for 3 days, then 150 mg twice daily at least 8 hours apart", "150 mg twice daily from day 1 with no titration", "300 mg once nightly starting on day 1", "21 mg daily for 6 weeks, then 14 mg", "0.5 mg once daily for 3 days, then 1 mg twice daily"],
            answer: "150 mg once daily for 3 days, then 150 mg twice daily at least 8 hours apart",
            explanation: "Bupropion SR is typically started at 150 mg daily for 3 days, then increased to 150 mg twice daily with doses separated by at least 8 hours.",
            objective: .dosing, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "titration"]),
        .multipleChoice(id: "q10d_add_033", subsectionId: "10d", difficulty: .hard,
            question: "A patient with a history of bulimia wants help quitting smoking. Which smoking-cessation medication is classically avoided because it can increase seizure risk in this setting?",
            options: ["Bupropion SR", "Nicotine patch", "Nicotine lozenge", "Nicotine gum", "Varenicline"],
            answer: "Bupropion SR",
            explanation: "Bupropion SR is contraindicated in patients with a current or prior diagnosis of bulimia or anorexia nervosa because of increased seizure risk.",
            objective: .contraindication, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "bulimia", "contraindication"]),
        .multipleChoice(id: "q10d_add_034", subsectionId: "10d", difficulty: .hard,
            question: "Which patient history is the clearest reason to avoid bupropion SR for smoking cessation?",
            options: ["Known seizure disorder", "Vivid dreams with nicotine patch", "Use of a daily nicotine lozenge", "Desire to limit post-quit weight gain", "A preference for a non-nicotine medication"],
            answer: "Known seizure disorder",
            explanation: "Bupropion can lower seizure threshold and is contraindicated in patients with a known seizure disorder.",
            objective: .contraindication, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "seizure", "contraindication"]),
        .multipleChoice(id: "q10d_add_035", subsectionId: "10d", difficulty: .medium,
            question: "A patient on bupropion SR reports dry mouth and trouble sleeping after beginning a quit attempt. Which interpretation is most accurate?",
            options: ["These are common side effects of bupropion SR", "These symptoms mean the patient is taking too little bupropion", "They prove a nicotine allergy", "They are most specific for renal failure from bupropion", "They are the expected result of excessive serotonin blockade"],
            answer: "These are common side effects of bupropion SR",
            explanation: "Dry mouth and insomnia are common adverse effects of bupropion SR.",
            objective: .adverseEffect, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "dry-mouth", "insomnia"]),
        .multipleChoice(id: "q10d_add_036", subsectionId: "10d", difficulty: .medium,
            question: "A patient asks whether it is okay to split or crush bupropion SR tablets to make them easier to swallow. What is the best counseling point?",
            options: ["Swallow them whole; crushing or chewing can raise adverse-effect risk, including seizures", "Crush them and mix with acidic juice for best effect", "Split every tablet in half to reduce insomnia", "Chew each tablet after meals to improve absorption", "Take all daily tablets together in the morning"],
            answer: "Swallow them whole; crushing or chewing can raise adverse-effect risk, including seizures",
            explanation: "Bupropion SR tablets should be swallowed whole. Crushing, chewing, or dividing can alter release and increase adverse-effect risk.",
            objective: .pearl, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "swallow-whole", "counseling"]),
        .multipleChoice(id: "q10d_add_037", subsectionId: "10d", difficulty: .hard,
            question: "A patient is prescribed both bupropion SR and a nicotine patch during a supervised quit attempt. Which monitoring pearl is highest yield for the combination?",
            options: ["Monitor for treatment-emergent hypertension", "Expect profound hypoglycemia in most patients", "Avoid all counseling because medication alone is enough", "Assume the combination is contraindicated in every adult", "Monitor INR every day because both strongly inhibit warfarin metabolism"],
            answer: "Monitor for treatment-emergent hypertension",
            explanation: "Bupropion SR can be combined with a nicotine transdermal system, but monitoring for treatment-emergent hypertension is recommended.",
            objective: .interaction, relatedDrugIds: ["d301", "d304"], tags: ["10d", "bupropion-sr", "nicotine-patch", "hypertension"]),
        .multipleChoice(id: "q10d_add_038", subsectionId: "10d", difficulty: .medium,
            question: "A patient worried about weight gain after quitting wants a non-nicotine pill. Which smoking-cessation medication has a high-yield pearl that it may help delay post-quit weight gain?",
            options: ["Bupropion SR", "Nicotine patch", "Nicotine gum", "Nicotine lozenge", "Varenicline"],
            answer: "Bupropion SR",
            explanation: "A common smoking-cessation pearl is that bupropion SR may help delay weight gain associated with quitting.",
            objective: .pearl, relatedDrugIds: ["d304"], tags: ["10d", "bupropion-sr", "weight-gain", "pearl"]),
        .multipleChoice(id: "q10d_add_039", subsectionId: "10d", difficulty: .easy,
            question: "Chantix is a prescription smoking-cessation pill that does not contain nicotine. What is the generic name of Chantix?",
            options: ["Varenicline", "Bupropion SR", "Nicotine transdermal patch", "Nicotine polacrilex gum", "Nicotine polacrilex lozenge"],
            answer: "Varenicline",
            explanation: "Chantix is the brand name for varenicline.",
            objective: .brandGeneric, relatedDrugIds: ["d305"], tags: ["10d", "chantix", "brand->generic"]),
        .multipleChoice(id: "q10d_add_040", subsectionId: "10d", difficulty: .hard,
            question: "Varenicline helps people quit smoking without directly replacing nicotine. Which mechanism best describes how it works?",
            options: ["Partial agonism at alpha4beta2 nicotinic acetylcholine receptors", "Pure serotonin reuptake inhibition", "Transdermal replacement of nicotine over 24 hours", "Direct antagonism of opioid receptors", "Peripheral muscarinic blockade of airway receptors"],
            answer: "Partial agonism at alpha4beta2 nicotinic acetylcholine receptors",
            explanation: "Varenicline is a partial agonist at alpha4beta2 nicotinic acetylcholine receptors, which helps reduce withdrawal and blocks some rewarding effects of smoking.",
            objective: .moa, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "moa"]),
        .multipleChoice(id: "q10d_add_041", subsectionId: "10d", difficulty: .medium,
            question: "A patient wants to know when to begin varenicline before a planned quit date. Which answer is most accurate?",
            options: ["A common option is to start varenicline 1 week before the quit date", "It should only be started after 30 days of abstinence", "It must always be started on the same day the last cigarette is smoked with no lead-in", "It should not be started until nicotine patch therapy fails", "It is only used after completing bupropion SR"],
            answer: "A common option is to start varenicline 1 week before the quit date",
            explanation: "A standard approach is to begin varenicline one week before the quit date, although flexible quit-date strategies also exist.",
            objective: .dosing, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "quit-date", "timing"]),
        .multipleChoice(id: "q10d_add_042", subsectionId: "10d", difficulty: .hard,
            question: "Which titration schedule best matches typical varenicline use for smoking cessation?",
            options: ["0.5 mg daily for days 1 to 3, then 0.5 mg twice daily for days 4 to 7, then 1 mg twice daily", "150 mg daily for 3 days, then 150 mg twice daily", "21 mg daily for 6 weeks, then 14 mg then 7 mg", "4 mg every 1 to 2 hours for 6 weeks", "1 mg twice daily from day 1 with no titration"],
            answer: "0.5 mg daily for days 1 to 3, then 0.5 mg twice daily for days 4 to 7, then 1 mg twice daily",
            explanation: "Varenicline is titrated over the first week to improve tolerability before reaching the maintenance dose of 1 mg twice daily.",
            objective: .dosing, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "titration"]),
        .multipleChoice(id: "q10d_add_043", subsectionId: "10d", difficulty: .medium,
            question: "A patient taking varenicline says the medication is helping but causes nausea. Which counseling point is highest yield?",
            options: ["Nausea is common; taking varenicline with food or a full glass of water may help", "Nausea means the drug is contraindicated and must always be stopped immediately", "Double the dose because nausea suggests underdosing", "Switch to chewing the tablet like gum", "Take it only at bedtime every third day"],
            answer: "Nausea is common; taking varenicline with food or a full glass of water may help",
            explanation: "Nausea is the most common adverse effect of varenicline, and taking it with food or a full glass of water can improve tolerability.",
            objective: .adverseEffect, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "nausea", "counseling"]),
        .multipleChoice(id: "q10d_add_044", subsectionId: "10d", difficulty: .medium,
            question: "Which adverse effect pair is especially high yield to remember for varenicline during a quit attempt?",
            options: ["Nausea and vivid or unusual dreams", "Tendon rupture and photosensitivity", "Gingival hyperplasia and hirsutism", "Constipation and orange-red urine", "Neutropenia and alopecia"],
            answer: "Nausea and vivid or unusual dreams",
            explanation: "Varenicline commonly causes nausea and can also cause vivid or unusual dreams and insomnia.",
            objective: .adverseEffect, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "vivid-dreams", "adverse-effect"]),
        .multipleChoice(id: "q10d_add_045", subsectionId: "10d", difficulty: .hard,
            question: "A smoker with significant chronic kidney disease wants a non-nicotine pill for smoking cessation. Which option has the highest-yield renal dosing consideration?",
            options: ["Varenicline", "Nicotine gum", "Nicotine lozenge", "Nicotine patch", "Phenazopyridine"],
            answer: "Varenicline",
            explanation: "Varenicline is largely renally eliminated and has important dose-adjustment considerations in kidney impairment.",
            objective: .monitoring, relatedDrugIds: ["d305"], tags: ["10d", "varenicline", "renal-dosing", "monitoring"]),
    ]
}
