// PharmaLingo — Module 2c (Antiplatelets)
// Curated Add-On Question Pack (45 questions)
// IDs: q2c_add_001 ... q2c_add_045
//
// Integration options:
//
// Option A (recommended, clean diff):
// 1) Add this file to your project.
// 2) In DrugDataService.populateCuratedBank(_:), ensure subsection 2c exists, then append:
//
//    if bank["2c"] == nil { bank["2c"] = [] }
//    bank["2c"]?.append(contentsOf: Self.curatedAddOnQuestions_2c)
//
// Option B (quick paste):
// - Create a new block `bank["2c"] = [` in populateCuratedBank(_:), then paste the questions below.
//
// Notes:
// - All questions are single-best-answer (5 choices each).
// - Stems are written to avoid exact duplicates of your current generated templates.
// - Objectives + relatedDrugIds are set to improve spaced-repetition behavior.

import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_2c: [Question] = [

        .multipleChoice(
            id: "q2c_add_001",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Aspirin is the classic antiplatelet used for ACS, stroke prevention, and after coronary stenting. Which brand name is commonly associated with aspirin?",
            options: ["Bayer/Ecotrin", "Plavix", "Brilinta", "Eliquis", "Coumadin"],
            answer: "Bayer/Ecotrin",
            explanation: "Aspirin is commonly marketed as Bayer or Ecotrin. Pairing the indication (ACS/stroke prevention) with the brand helps you recognize aspirin on medication lists.",
            objective: .genericBrand,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "brand", "Antiplatelet"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_002",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Ecotrin is an enteric-coated product frequently used for low-dose antiplatelet therapy. What is the generic medication in Ecotrin?",
            options: ["Aspirin", "Clopidogrel", "Ticagrelor", "Apixaban", "Acetaminophen"],
            answer: "Aspirin",
            explanation: "Ecotrin is an enteric-coated formulation of aspirin. Enteric coating may reduce stomach irritation, but it does not eliminate bleeding risk.",
            objective: .brandGeneric,
            relatedDrugIds: ["d38"],
            tags: ["Ecotrin", "Aspirin", "brand->generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_003",
            subsectionId: "2c",
            difficulty: .medium,
            question: "At low doses, aspirin prevents arterial thrombosis by irreversibly inhibiting platelet COX-1. This decreases which mediator that normally promotes platelet aggregation and vasoconstriction?",
            options: ["Thromboxane A2 (TXA2)", "Prostacyclin (PGI2)", "Adenosine diphosphate (ADP)", "Factor Xa", "Fibrinogen"],
            answer: "Thromboxane A2 (TXA2)",
            explanation: "Aspirin lowers TXA2 by inhibiting COX-1 in platelets. TXA2 is pro-aggregation and pro-vasoconstriction, so lowering it produces an antiplatelet effect.",
            objective: .moa,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "MOA", "TXA2"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_004",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Aspirin's antiplatelet effect is best explained by irreversible inhibition of which enzyme target in platelets?",
            options: ["Cyclooxygenase-1 (COX-1)", "PCSK9 protein", "HMG-CoA reductase", "P2Y12 receptor", "Vitamin K epoxide reductase"],
            answer: "Cyclooxygenase-1 (COX-1)",
            explanation: "Aspirin irreversibly acetylates COX-1 in platelets -> decreased thromboxane A2 -> decreased platelet aggregation.",
            objective: .moa,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "COX-1", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_005",
            subsectionId: "2c",
            difficulty: .medium,
            question: "A patient is placed on dual antiplatelet therapy (DAPT) after a coronary stent. Unless contraindicated, which medication is the foundational agent included in most DAPT regimens?",
            options: ["Aspirin", "Warfarin", "Apixaban", "Atorvastatin", "Furosemide"],
            answer: "Aspirin",
            explanation: "DAPT most commonly means aspirin plus a P2Y12 inhibitor. Aspirin is the usual backbone antiplatelet unless there is a clear contraindication (e.g., active bleeding).",
            objective: .indication,
            relatedDrugIds: ["d38"],
            tags: ["DAPT", "stent", "Aspirin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_006",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Because aspirin impairs platelet aggregation, which serious adverse effect is most important to counsel patients about?",
            options: ["Gastrointestinal bleeding", "Bradycardia", "Dry cough", "Hyperkalemia", "Tendon rupture"],
            answer: "Gastrointestinal bleeding",
            explanation: "Aspirin increases bleeding risk, especially GI bleeding. Patients should watch for black stools, vomiting blood, or unexplained bruising.",
            objective: .adverseEffect,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "bleeding", "GI"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_007",
            subsectionId: "2c",
            difficulty: .medium,
            question: "A patient taking high-dose aspirin for pain develops ringing in the ears. This classic symptom points most strongly to:",
            options: ["Salicylate toxicity (salicylism)", "Serotonin syndrome", "Digoxin toxicity", "Amiodarone toxicity", "Lithium toxicity"],
            answer: "Salicylate toxicity (salicylism)",
            explanation: "Tinnitus is a high-yield clue for salicylate toxicity. Think: aspirin overdose/salicylism when a patient reports ringing in the ears.",
            objective: .adverseEffect,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "tinnitus", "salicylism"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_008",
            subsectionId: "2c",
            difficulty: .hard,
            question: "Which patient should generally avoid aspirin because of a classic safety concern taught in pharmacology?",
            options: ["A child with a viral illness (e.g., influenza or varicella)", "An adult with hyperlipidemia", "An adult with mild hypertension", "An adult with type 2 diabetes", "A patient with seasonal allergies"],
            answer: "A child with a viral illness (e.g., influenza or varicella)",
            explanation: "Aspirin in children/teens with viral illness is associated with Reye syndrome (acute liver failure/encephalopathy). This is a high-yield contraindication.",
            objective: .contraindication,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "Reye syndrome", "contraindication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_009",
            subsectionId: "2c",
            difficulty: .hard,
            question: "A patient takes low-dose aspirin for cardiovascular prevention and also uses ibuprofen for headaches. Taking ibuprofen right before aspirin can reduce aspirin's antiplatelet effect because ibuprofen:",
            options: ["Competitively blocks the COX-1 binding site, preventing aspirin's irreversible acetylation", "Induces CYP2C19, increasing aspirin clearance", "Increases thromboxane synthesis directly", "Activates P2Y12 receptors on platelets", "Chelates aspirin in the stomach and prevents absorption"],
            answer: "Competitively blocks the COX-1 binding site, preventing aspirin's irreversible acetylation",
            explanation: "Ibuprofen can occupy COX-1 and interfere with aspirin's irreversible platelet inhibition if taken first. High-yield counseling: timing matters when patients take both.",
            objective: .interaction,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "ibuprofen", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_010",
            subsectionId: "2c",
            difficulty: .easy,
            question: "For chronic cardiovascular antiplatelet prevention, the typical \"baby aspirin\" dose is closest to:",
            options: ["81 mg once daily", "10 mg once daily", "325 mg three times daily", "1 g twice daily", "5 mg once weekly"],
            answer: "81 mg once daily",
            explanation: "Low-dose aspirin for CV prevention is typically 81 mg daily (often called \"baby aspirin\").",
            objective: .dosing,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "81 mg", "dosing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_011",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Enteric-coated aspirin (e.g., Ecotrin) is designed primarily to:",
            options: ["Reduce direct gastric irritation (but not eliminate bleeding risk)", "Prevent tinnitus from occurring", "Eliminate the need to take aspirin with food", "Completely prevent GI bleeding", "Convert aspirin into a reversible COX inhibitor"],
            answer: "Reduce direct gastric irritation (but not eliminate bleeding risk)",
            explanation: "Enteric coating can lessen stomach irritation for some patients, but it does not \"turn off\" aspirin's systemic antiplatelet effect or bleeding risk.",
            objective: .pearl,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "Ecotrin", "pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_012",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Aspirin irreversibly inhibits platelet COX-1. Because platelets can't synthesize new COX enzyme, aspirin's antiplatelet effect lasts for:",
            options: ["The lifespan of the platelet (about 7-10 days)", "About 6 hours", "About 24 hours", "Only until the next meal", "About 30 days"],
            answer: "The lifespan of the platelet (about 7-10 days)",
            explanation: "Aspirin's platelet effect is irreversible. Platelet function returns as new platelets are produced (roughly 7-10 days).",
            objective: .pearl,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "irreversible", "platelet lifespan"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_013",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Clopidogrel is a P2Y12 inhibitor frequently paired with aspirin after PCI. Which brand name corresponds to clopidogrel?",
            options: ["Plavix", "Brilinta", "Bayer/Ecotrin", "Crestor", "Xarelto"],
            answer: "Plavix",
            explanation: "Clopidogrel is marketed as Plavix. Think: Plavix = P2Y12 inhibitor commonly used in DAPT.",
            objective: .genericBrand,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "Plavix", "brand"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_014",
            subsectionId: "2c",
            difficulty: .easy,
            question: "A discharge summary lists \"Plavix\" as part of dual antiplatelet therapy after a stent. Which generic drug is Plavix?",
            options: ["Clopidogrel", "Ticagrelor", "Aspirin", "Apixaban", "Enoxaparin"],
            answer: "Clopidogrel",
            explanation: "Plavix is the brand name for clopidogrel, an ADP (P2Y12) receptor inhibitor.",
            objective: .brandGeneric,
            relatedDrugIds: ["d39"],
            tags: ["Plavix", "Clopidogrel", "generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_015",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Clopidogrel reduces platelet aggregation primarily by irreversibly blocking:",
            options: ["The P2Y12 (ADP) receptor", "Cyclooxygenase-1 (COX-1)", "Factor Xa", "Thrombin (factor IIa)", "GPIIb/IIIa receptor"],
            answer: "The P2Y12 (ADP) receptor",
            explanation: "Clopidogrel irreversibly inhibits the platelet P2Y12 (ADP) receptor -> decreased ADP-mediated activation of GPIIb/IIIa -> decreased platelet aggregation.",
            objective: .moa,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "P2Y12", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_016",
            subsectionId: "2c",
            difficulty: .hard,
            question: "A key pharmacology pearl: clopidogrel requires metabolic activation to work. It is best described as a:",
            options: ["Prodrug activated by CYP2C19", "Direct-acting reversible P2Y12 inhibitor", "Direct thrombin inhibitor", "Irreversible COX inhibitor", "GPIIb/IIIa monoclonal antibody"],
            answer: "Prodrug activated by CYP2C19",
            explanation: "Clopidogrel is a prodrug that requires CYP2C19 activation. Poor metabolizers or CYP2C19 inhibitors can reduce its antiplatelet effect.",
            objective: .pearl,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "CYP2C19", "prodrug"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_017",
            subsectionId: "2c",
            difficulty: .hard,
            question: "Which common medication can reduce clopidogrel's antiplatelet effect by inhibiting CYP2C19 and decreasing its activation?",
            options: ["Omeprazole", "Famotidine", "Aspirin", "Furosemide", "Atorvastatin"],
            answer: "Omeprazole",
            explanation: "Omeprazole can inhibit CYP2C19 and reduce activation of clopidogrel (a prodrug). This is a classic high-yield drug interaction.",
            objective: .interaction,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "interaction", "omeprazole"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_018",
            subsectionId: "2c",
            difficulty: .medium,
            question: "A patient needs antiplatelet therapy for secondary stroke prevention but has a severe aspirin allergy. Which medication is a high-yield alternative from this subsection?",
            options: ["Clopidogrel (Plavix)", "Apixaban (Eliquis)", "Warfarin (Coumadin)", "Furosemide (Lasix)", "Atorvastatin (Lipitor)"],
            answer: "Clopidogrel (Plavix)",
            explanation: "Clopidogrel is commonly used for stroke prevention and is an important alternative when aspirin can't be used (e.g., true aspirin allergy).",
            objective: .indication,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "stroke prevention", "aspirin allergy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_019",
            subsectionId: "2c",
            difficulty: .easy,
            question: "The most important routine counseling point for a patient starting clopidogrel is to watch for:",
            options: ["Easy bruising or bleeding", "Dry cough", "Ankle edema", "Hypokalemia", "Constipation"],
            answer: "Easy bruising or bleeding",
            explanation: "All antiplatelets increase bleeding risk. Counsel on bruising, nosebleeds, gum bleeding, and when to seek help for serious bleeding signs.",
            objective: .adverseEffect,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "bleeding", "counseling"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_020",
            subsectionId: "2c",
            difficulty: .hard,
            question: "Clopidogrel rarely causes a serious hematologic emergency. Which adverse effect is classically associated with clopidogrel (rare but high-yield)?",
            options: ["Thrombotic thrombocytopenic purpura (TTP)", "QT prolongation", "Pulmonary fibrosis", "Gynecomastia", "Sprue-like enteropathy"],
            answer: "Thrombotic thrombocytopenic purpura (TTP)",
            explanation: "A rare but board-relevant adverse effect of clopidogrel is TTP. Think thrombocytopenia + microangiopathic hemolytic anemia with neurologic/renal findings.",
            objective: .adverseEffect,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "TTP", "rare"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_021",
            subsectionId: "2c",
            difficulty: .hard,
            question: "If clopidogrel-associated TTP is suspected, which finding pattern best fits the diagnosis?",
            options: ["Thrombocytopenia + microangiopathic hemolytic anemia", "Thrombocytopenia + high INR from vitamin K deficiency", "Leukocytosis + eosinophilia", "Hyperkalemia + metabolic alkalosis", "Elevated CK + diffuse myalgias only"],
            answer: "Thrombocytopenia + microangiopathic hemolytic anemia",
            explanation: "TTP classically presents with thrombocytopenia and microangiopathic hemolysis (schistocytes), often with neurologic symptoms and renal injury.",
            objective: .monitoring,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "TTP", "monitoring"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_022",
            subsectionId: "2c",
            difficulty: .medium,
            question: "After placement of a coronary stent, dual antiplatelet therapy (DAPT) is often prescribed. Which pairing below best represents DAPT?",
            options: ["Aspirin + clopidogrel", "Apixaban + warfarin", "Atorvastatin + ezetimibe", "Furosemide + chlorthalidone", "Lisinopril + losartan"],
            answer: "Aspirin + clopidogrel",
            explanation: "DAPT usually means aspirin plus a P2Y12 inhibitor (such as clopidogrel or ticagrelor). It is used to reduce stent thrombosis and recurrent ischemic events.",
            objective: .mixedReview,
            relatedDrugIds: ["d38", "d39"],
            tags: ["DAPT", "aspirin", "clopidogrel"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_023",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Clopidogrel works by blocking ADP-mediated platelet activation. ADP signals through which receptor on platelets?",
            options: ["P2Y12", "Beta-1 adrenergic receptor", "HMG-CoA reductase", "NKCC2 cotransporter", "Angiotensin-converting enzyme (ACE)"],
            answer: "P2Y12",
            explanation: "Clopidogrel inhibits the P2Y12 receptor, preventing ADP-driven platelet activation and downstream GPIIb/IIIa expression.",
            objective: .moa,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "ADP", "P2Y12"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_024",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Clopidogrel's antiplatelet effect is considered \"irreversible\" because it:",
            options: ["Permanently disables P2Y12 receptors on that platelet until new platelets are produced", "Only blocks COX-1 for a few hours", "Covalently binds factor Xa and inactivates it", "Must be given as a continuous infusion to work", "Is metabolized into aspirin in the liver"],
            answer: "Permanently disables P2Y12 receptors on that platelet until new platelets are produced",
            explanation: "Clopidogrel irreversibly inhibits P2Y12 receptors on existing platelets. Function returns as new platelets enter circulation.",
            objective: .pearl,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "irreversible", "pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_025",
            subsectionId: "2c",
            difficulty: .hard,
            question: "A patient is a poor CYP2C19 metabolizer and has reduced response to clopidogrel. Which alternative P2Y12 inhibitor from this subsection is NOT a prodrug and avoids this activation step?",
            options: ["Ticagrelor", "Aspirin", "Warfarin", "Apixaban", "Enoxaparin"],
            answer: "Ticagrelor",
            explanation: "Ticagrelor is direct-acting (not a prodrug), so it does not rely on CYP2C19 activation the way clopidogrel does.",
            objective: .pearl,
            relatedDrugIds: ["d39", "d40"],
            tags: ["Clopidogrel", "CYP2C19", "Ticagrelor"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_026",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Ticagrelor is a direct-acting P2Y12 inhibitor used in acute coronary syndrome and often paired with low-dose aspirin. Which brand name matches ticagrelor?",
            options: ["Brilinta", "Plavix", "Bayer/Ecotrin", "Xarelto", "Zocor"],
            answer: "Brilinta",
            explanation: "Ticagrelor is marketed as Brilinta. On exams, Brilinta should trigger: \"P2Y12 inhibitor + dyspnea + use with 81 mg aspirin.\"",
            objective: .genericBrand,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "Brilinta", "brand"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_027",
            subsectionId: "2c",
            difficulty: .easy,
            question: "A patient with ACS is prescribed Brilinta along with baby aspirin. Brilinta is the brand name for:",
            options: ["Ticagrelor", "Clopidogrel", "Aspirin", "Apixaban", "Rivaroxaban"],
            answer: "Ticagrelor",
            explanation: "Brilinta = ticagrelor. It is a P2Y12 inhibitor used in ACS and does not require metabolic activation.",
            objective: .brandGeneric,
            relatedDrugIds: ["d40"],
            tags: ["Brilinta", "Ticagrelor", "generic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_028",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Ticagrelor prevents platelet aggregation primarily by:",
            options: ["Reversibly inhibiting the P2Y12 receptor", "Irreversibly inhibiting COX-1", "Directly inhibiting factor Xa", "Enhancing antithrombin to inhibit thrombin", "Activating PPAR-alpha to lower triglycerides"],
            answer: "Reversibly inhibiting the P2Y12 receptor",
            explanation: "Ticagrelor is a direct, reversible P2Y12 inhibitor. Contrast: clopidogrel is an irreversible P2Y12 inhibitor and a prodrug.",
            objective: .moa,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "P2Y12", "reversible"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_029",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which adverse effect is especially high-yield for ticagrelor (Brilinta) and can lead patients to stop the drug if not counseled?",
            options: ["Dyspnea", "Dry cough", "Hypercalcemia", "Ototoxicity", "Tendon rupture"],
            answer: "Dyspnea",
            explanation: "Dyspnea is a classic adverse effect of ticagrelor. Counseling helps patients distinguish this side effect from worsening heart disease while still taking bleeding precautions.",
            objective: .adverseEffect,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "dyspnea", "side effect"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_030",
            subsectionId: "2c",
            difficulty: .hard,
            question: "When ticagrelor is used with aspirin, the aspirin dose is typically kept low (e.g., 81 mg). Higher aspirin doses can:",
            options: ["Reduce ticagrelor's effectiveness", "Prevent clopidogrel activation", "Cause hypokalemia", "Completely reverse platelet inhibition", "Increase LDL cholesterol"],
            answer: "Reduce ticagrelor's effectiveness",
            explanation: "High-yield counseling: ticagrelor should be used with low-dose aspirin (around 81 mg). Higher aspirin doses may reduce ticagrelor's efficacy.",
            objective: .interaction,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "aspirin 81 mg", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_031",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which comparison is most accurate for the two P2Y12 inhibitors in this subsection?",
            options: ["Ticagrelor is direct-acting; clopidogrel is a prodrug", "Ticagrelor is a prodrug; clopidogrel is direct-acting", "Both require CYP2C19 activation", "Both are irreversible COX inhibitors", "Both directly inhibit factor Xa"],
            answer: "Ticagrelor is direct-acting; clopidogrel is a prodrug",
            explanation: "Clopidogrel needs activation (CYP2C19), while ticagrelor is direct-acting. This difference matters for drug interactions and genetic variation.",
            objective: .pearl,
            relatedDrugIds: ["d39", "d40"],
            tags: ["P2Y12", "prodrug vs direct", "pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_032",
            subsectionId: "2c",
            difficulty: .easy,
            question: "In this drug list, ticagrelor (Brilinta) is most strongly associated with which primary indication?",
            options: ["Acute coronary syndrome (ACS)", "Chronic stable hypertension", "Asthma maintenance therapy", "Hypertriglyceridemia", "Bacterial pneumonia"],
            answer: "Acute coronary syndrome (ACS)",
            explanation: "Ticagrelor is a P2Y12 inhibitor commonly used in ACS. Clopidogrel can also be used in ACS, but ticagrelor's 'ACS + dyspnea + low-dose aspirin' association is high yield.",
            objective: .indication,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "ACS", "indication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_033",
            subsectionId: "2c",
            difficulty: .hard,
            question: "Ticagrelor is metabolized by CYP3A4. Which option is most likely to raise ticagrelor levels and bleeding risk via strong CYP3A4 inhibition?",
            options: ["Strong CYP3A4 inhibitors (e.g., clarithromycin or ketoconazole)", "Thiazide diuretics", "H2 blockers like famotidine", "Statins like pravastatin", "ACE inhibitors like lisinopril"],
            answer: "Strong CYP3A4 inhibitors (e.g., clarithromycin or ketoconazole)",
            explanation: "High-yield interaction: strong CYP3A4 inhibitors can increase ticagrelor exposure -> higher bleeding risk. Always scan for interacting azoles/macrolides.",
            objective: .interaction,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "CYP3A4", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_034",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which medication from this subsection is most likely to cause ringing in the ears (tinnitus) at higher doses?",
            options: ["Aspirin", "Ticagrelor", "Clopidogrel", "Apixaban", "Rivaroxaban"],
            answer: "Aspirin",
            explanation: "Tinnitus is a classic clue for salicylate (aspirin) toxicity, especially with higher analgesic/anti-inflammatory doses.",
            objective: .adverseEffect,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "tinnitus", "comparison"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_035",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Both clopidogrel and ticagrelor inhibit the P2Y12 receptor. Compared with clopidogrel, ticagrelor is more accurately described as a:",
            options: ["Reversible P2Y12 inhibitor", "Irreversible P2Y12 inhibitor requiring CYP2C19 activation", "COX-1 inhibitor", "Direct thrombin inhibitor", "Vitamin K antagonist"],
            answer: "Reversible P2Y12 inhibitor",
            explanation: "Ticagrelor is reversible and direct-acting. Clopidogrel is irreversible and requires metabolic activation.",
            objective: .pearl,
            relatedDrugIds: ["d40", "d39"],
            tags: ["Ticagrelor", "reversible", "P2Y12"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_036",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which DAPT regimen uses aspirin plus a direct-acting (non-prodrug) P2Y12 inhibitor from this subsection?",
            options: ["Aspirin + ticagrelor", "Aspirin + clopidogrel", "Ticagrelor + warfarin", "Clopidogrel + apixaban", "Aspirin + atorvastatin"],
            answer: "Aspirin + ticagrelor",
            explanation: "Aspirin + ticagrelor is a common DAPT combination in ACS. Ticagrelor is direct-acting, while clopidogrel is a prodrug.",
            objective: .mixedReview,
            relatedDrugIds: ["d38", "d40"],
            tags: ["DAPT", "ticagrelor", "aspirin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_037",
            subsectionId: "2c",
            difficulty: .easy,
            question: "All antiplatelet agents increase bleeding risk. Which symptom should prompt urgent evaluation for possible serious GI bleeding?",
            options: ["Black, tarry stools (melena)", "Increased appetite", "Mild dry eyes", "Morning stiffness", "Nasal congestion"],
            answer: "Black, tarry stools (melena)",
            explanation: "Melena suggests upper GI bleeding. This is a high-yield counseling point for aspirin and P2Y12 inhibitors.",
            objective: .monitoring,
            relatedDrugIds: ["d38"],
            tags: ["bleeding", "melena", "monitoring"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_038",
            subsectionId: "2c",
            difficulty: .medium,
            question: "In general, antiplatelet drugs (like aspirin and P2Y12 inhibitors) are most effective at preventing:",
            options: ["Arterial thrombosis (platelet-rich clots)", "Venous thrombosis (fibrin-rich clots)", "Bacterial infections", "Bronchospasm", "Hyperglycemia"],
            answer: "Arterial thrombosis (platelet-rich clots)",
            explanation: "Antiplatelets primarily prevent platelet-rich arterial clots (e.g., ACS, stroke). Anticoagulants are the mainstay for venous clots (DVT/PE).",
            objective: .pearl,
            relatedDrugIds: ["d38", "d39", "d40"],
            tags: ["antiplatelet", "arterial", "pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_039",
            subsectionId: "2c",
            difficulty: .easy,
            question: "Which medication listed is a P2Y12 (ADP) receptor inhibitor rather than a COX inhibitor?",
            options: ["Clopidogrel", "Aspirin", "Ibuprofen", "Naproxen", "Acetaminophen"],
            answer: "Clopidogrel",
            explanation: "Clopidogrel inhibits the platelet P2Y12 receptor. Aspirin/ibuprofen/naproxen act via COX; acetaminophen is analgesic/antipyretic with minimal antiplatelet effect.",
            objective: .classId,
            relatedDrugIds: ["d39"],
            tags: ["P2Y12", "class", "Clopidogrel"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_040",
            subsectionId: "2c",
            difficulty: .hard,
            question: "Because aspirin irreversibly inhibits platelets, platelet function returns mainly by which mechanism after the drug is stopped?",
            options: ["Production of new platelets", "Giving vitamin K", "Giving protamine", "Giving idarucizumab", "Giving naloxone"],
            answer: "Production of new platelets",
            explanation: "Aspirin's effect is irreversible for existing platelets; recovery occurs as new platelets are produced over several days.",
            objective: .pearl,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "irreversible", "surgery pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_041",
            subsectionId: "2c",
            difficulty: .hard,
            question: "A patient on clopidogrel needs treatment for reflux. Which option is least likely to blunt clopidogrel activation because it is not a CYP2C19-inhibiting PPI?",
            options: ["Famotidine (Pepcid)", "Omeprazole (Prilosec)", "Esomeprazole (Nexium)", "Lansoprazole (Prevacid)", "Pantoprazole (Protonix)"],
            answer: "Famotidine (Pepcid)",
            explanation: "Clopidogrel is a CYP2C19-activated prodrug. PPIs (especially omeprazole/esomeprazole) can inhibit CYP2C19. An H2 blocker like famotidine avoids that interaction.",
            objective: .interaction,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "GERD", "CYP2C19 interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_042",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Between the two P2Y12 inhibitors in this subsection, which adverse effect is more characteristic of ticagrelor than clopidogrel?",
            options: ["Dyspnea", "TTP", "Tinnitus", "Severe hypokalemia", "Ototoxicity"],
            answer: "Dyspnea",
            explanation: "Ticagrelor is classically associated with dyspnea. Clopidogrel's rare board-relevant adverse effect is TTP.",
            objective: .adverseEffect,
            relatedDrugIds: ["d40", "d39"],
            tags: ["Ticagrelor", "dyspnea", "comparison"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_043",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which drug-target pairing is correctly matched?",
            options: ["Aspirin - irreversible COX inhibition", "Clopidogrel - direct factor Xa inhibition", "Ticagrelor - HMG-CoA reductase inhibition", "Enoxaparin - P2Y12 receptor inhibition", "Atorvastatin - thromboxane synthase inhibition"],
            answer: "Aspirin - irreversible COX inhibition",
            explanation: "Aspirin irreversibly inhibits COX (especially platelet COX-1 at low doses). The other pairings list incorrect targets for those drugs.",
            objective: .moa,
            relatedDrugIds: ["d38"],
            tags: ["Aspirin", "target", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_044",
            subsectionId: "2c",
            difficulty: .hard,
            question: "A patient post-ACS is on DAPT and reports new shortness of breath. Which medication in the regimen is known for dyspnea and also requires pairing with low-dose aspirin (81 mg)?",
            options: ["Ticagrelor (Brilinta)", "Clopidogrel (Plavix)", "Aspirin (Bayer/Ecotrin)", "Warfarin (Coumadin)", "Ezetimibe (Zetia)"],
            answer: "Ticagrelor (Brilinta)",
            explanation: "Ticagrelor is associated with dyspnea and should be used with low-dose aspirin. Always also counsel about bleeding risk and not stopping the medication without guidance.",
            objective: .pearl,
            relatedDrugIds: ["d40"],
            tags: ["Ticagrelor", "dyspnea", "81 mg aspirin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2c_add_045",
            subsectionId: "2c",
            difficulty: .medium,
            question: "Which antiplatelet in this subsection is most impacted by CYP2C19 genetics/drug interactions because it must be metabolically activated?",
            options: ["Clopidogrel", "Ticagrelor", "Aspirin", "Apixaban", "Enoxaparin"],
            answer: "Clopidogrel",
            explanation: "Clopidogrel is a CYP2C19-activated prodrug. Ticagrelor is direct-acting and aspirin works via COX inhibition.",
            objective: .pearl,
            relatedDrugIds: ["d39"],
            tags: ["Clopidogrel", "CYP2C19", "activation"],
            source: .curated
        ),
    ]
}
