// PharmaLingo — Module 2b (Non-Statin Lipid Agents)
// Curated Add-On Question Pack (45 questions)
// IDs: q2b_add_001 ... q2b_add_045
//
// Integration options:
//
// Option A (recommended, clean diff):
// 1) Add this file to your project.
// 2) In DrugDataService.populateCuratedBank(_:), AFTER the existing `bank["2b"] = [...]` block,
//    append:
//
//    bank["2b"]?.append(contentsOf: Self.curatedAddOnQuestions_2b)
//
// Option B (quick paste):
// - Copy the questions inside the array below and paste them into the existing `bank["2b"] = [` array.
//
// Notes:
// - All questions are single-best-answer (5 choices each).
// - Stems are written to avoid exact duplicates of your current curated + generated templates.
// - Objectives + relatedDrugIds are set to improve spaced-repetition behavior.

import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_2b: [Question] = [
        .multipleChoice(
            id: "q2b_add_001",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Ezetimibe is a non‑statin lipid agent often added to a statin to further lower LDL cholesterol. Which brand name is associated with ezetimibe?",
            options: ["Zetia", "Repatha", "Praluent", "Tricor", "Lopid"],
            answer: "Zetia",
            explanation: "Ezetimibe is marketed as Zetia. Remember it as the oral “cholesterol absorption blocker” that pairs well with statins for additional LDL lowering.",
            objective: .genericBrand,
            relatedDrugIds: ["d32"],
            tags: ["Ezetimibe", "brand", "Non-statin"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_002",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Zetia is an oral medication used to help lower LDL cholesterol, often as add‑on therapy to statins. What is the generic name for Zetia?",
            options: ["Ezetimibe", "Evolocumab", "Alirocumab", "Fenofibrate", "Icosapent ethyl"],
            answer: "Ezetimibe",
            explanation: "Zetia = ezetimibe. On exams, Zetia should trigger: “non‑statin → blocks intestinal cholesterol absorption.”",
            objective: .brandGeneric,
            relatedDrugIds: ["d32"],
            tags: ["Zetia", "generic", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_003",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Ezetimibe lowers LDL primarily by blocking cholesterol uptake at the intestinal brush border. Which target does ezetimibe inhibit?",
            options: ["NPC1L1 transporter", "HMG‑CoA reductase", "PCSK9 protein", "PPAR‑α receptor", "NKCC2 cotransporter"],
            answer: "NPC1L1 transporter",
            explanation: "Ezetimibe inhibits the NPC1L1 transporter in the small intestine, reducing dietary and biliary cholesterol absorption → lower hepatic cholesterol → more LDL receptor expression.",
            objective: .moa,
            relatedDrugIds: ["d32"],
            tags: ["MOA", "NPC1L1", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_004",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A patient is already taking a maximally tolerated statin but still has elevated LDL cholesterol. Which oral, non‑statin agent is commonly used as the first add‑on because it reduces intestinal cholesterol absorption?",
            options: ["Ezetimibe (Zetia)", "Fenofibrate (Tricor)", "Icosapent ethyl (Vascepa)", "Evolocumab (Repatha)", "Gemfibrozil (Lopid)"],
            answer: "Ezetimibe (Zetia)",
            explanation: "Ezetimibe (Zetia) is a common first add‑on to statins for additional LDL lowering because it blocks intestinal cholesterol absorption (NPC1L1).",
            objective: .indication,
            relatedDrugIds: ["d32"],
            tags: ["LDL", "add-on", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_005",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Ezetimibe belongs to which drug class used for lipid management?",
            options: ["Cholesterol absorption inhibitor", "PCSK9 inhibitor", "Fibrate", "Omega‑3 fatty acid", "HMG‑CoA reductase inhibitor"],
            answer: "Cholesterol absorption inhibitor",
            explanation: "Ezetimibe is a cholesterol absorption inhibitor (blocks NPC1L1). It is not a statin, fibrate, omega‑3, or PCSK9 inhibitor.",
            objective: .classId,
            relatedDrugIds: ["d32"],
            tags: ["Class", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_006",
            subsectionId: "2b",
            difficulty: .easy,
            question: "A patient starts ezetimibe and develops mild GI symptoms. Which adverse effect is a well‑known, high‑yield side effect of ezetimibe?",
            options: ["Diarrhea", "Dry cough", "Ototoxicity", "Severe bradycardia", "Photosensitivity"],
            answer: "Diarrhea",
            explanation: "Ezetimibe commonly causes GI effects such as diarrhea; arthralgia can also occur. It does not cause classic ACE‑inhibitor cough or loop‑diuretic ototoxicity.",
            objective: .adverseEffect,
            relatedDrugIds: ["d32"],
            tags: ["Side effects", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_007",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient on a statin plus ezetimibe reports unusual fatigue and dark urine. Which monitoring test is most appropriate to evaluate a serious, high‑yield adverse effect that can occur with lipid‑lowering therapy (especially in combination)?",
            options: ["AST/ALT (liver transaminases)", "TSH", "Amylase/Lipase", "INR", "Serum troponin"],
            answer: "AST/ALT (liver transaminases)",
            explanation: "Unusual fatigue and dark urine can signal liver injury. When combining lipid‑lowering agents (statin + ezetimibe), monitoring liver enzymes (AST/ALT) is a high‑yield safety step.",
            objective: .monitoring,
            relatedDrugIds: ["d32"],
            tags: ["Monitoring", "LFTs", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_008",
            subsectionId: "2b",
            difficulty: .medium,
            question: "By reducing intestinal cholesterol absorption, ezetimibe lowers hepatic cholesterol. What is a key downstream hepatic response that helps lower circulating LDL?",
            options: ["Upregulation of LDL receptors", "Irreversible platelet inhibition", "Inhibition of angiotensin II formation", "Blockade of L‑type calcium channels", "Activation of PCSK9 protein"],
            answer: "Upregulation of LDL receptors",
            explanation: "Less hepatic cholesterol → the liver increases LDL receptor expression → more LDL is cleared from blood. This concept also explains why ezetimibe pairs well with statins.",
            objective: .moa,
            relatedDrugIds: ["d32"],
            tags: ["LDL receptor", "Mechanism", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_009",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Which route of administration is correct for ezetimibe (Zetia) in routine outpatient lipid management?",
            options: ["Oral tablet", "Subcutaneous injection", "Intravenous infusion", "Transdermal patch", "Inhalation"],
            answer: "Oral tablet",
            explanation: "Ezetimibe is taken orally. In contrast, PCSK9 inhibitors (e.g., evolocumab/alirocumab) are given as subcutaneous injections.",
            objective: .dosing,
            relatedDrugIds: ["d32"],
            tags: ["Dosing", "Route", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_010",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A student says ezetimibe is “basically a weaker statin.” Which statement best corrects that misconception?",
            options: ["Ezetimibe blocks intestinal cholesterol absorption rather than inhibiting HMG‑CoA reductase.", "Ezetimibe directly dissolves LDL particles in plasma.", "Ezetimibe is a PCSK9 monoclonal antibody.", "Ezetimibe activates PPAR‑α to lower triglycerides.", "Ezetimibe works by binding bile acids in the gut."],
            answer: "Ezetimibe blocks intestinal cholesterol absorption rather than inhibiting HMG‑CoA reductase.",
            explanation: "Statins inhibit HMG‑CoA reductase. Ezetimibe is different: it reduces cholesterol absorption at the intestine (NPC1L1). Knowing this prevents mixing up mechanisms on exams.",
            objective: .pearl,
            relatedDrugIds: ["d32"],
            tags: ["Pearl", "Mechanism", "Ezetimibe"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_011",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Evolocumab is a PCSK9 inhibitor used for very high LDL levels (e.g., familial hypercholesterolemia or ASCVD needing additional LDL lowering). What is the brand name for evolocumab?",
            options: ["Repatha", "Praluent", "Zetia", "Tricor", "Vascepa"],
            answer: "Repatha",
            explanation: "Evolocumab is marketed as Repatha. It’s a potent LDL-lowering PCSK9 monoclonal antibody given by subcutaneous injection.",
            objective: .genericBrand,
            relatedDrugIds: ["d33"],
            tags: ["Evolocumab", "brand", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_012",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Repatha is an injectable medication that can dramatically lower LDL cholesterol. What is the generic name for Repatha?",
            options: ["Evolocumab", "Alirocumab", "Ezetimibe", "Gemfibrozil", "Fenofibrate"],
            answer: "Evolocumab",
            explanation: "Repatha = evolocumab. Both Repatha (evolocumab) and Praluent (alirocumab) are PCSK9 inhibitors.",
            objective: .brandGeneric,
            relatedDrugIds: ["d33"],
            tags: ["Repatha", "generic", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_013",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Alirocumab is a PCSK9 inhibitor used for patients with ASCVD or familial hypercholesterolemia who need major LDL reduction. Which brand name matches alirocumab?",
            options: ["Praluent", "Repatha", "Zetia", "Lopid", "Tricor"],
            answer: "Praluent",
            explanation: "Alirocumab is sold as Praluent. It’s a subcutaneous PCSK9 monoclonal antibody that boosts LDL receptor recycling to lower LDL.",
            objective: .genericBrand,
            relatedDrugIds: ["d34"],
            tags: ["Alirocumab", "brand", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_014",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Praluent is a PCSK9 inhibitor given by subcutaneous injection. What is the generic name for Praluent?",
            options: ["Alirocumab", "Evolocumab", "Ezetimibe", "Icosapent ethyl", "Atorvastatin"],
            answer: "Alirocumab",
            explanation: "Praluent = alirocumab. Repatha = evolocumab. Pairing these brands with the PCSK9 class is a classic board-style memory anchor.",
            objective: .brandGeneric,
            relatedDrugIds: ["d34"],
            tags: ["Praluent", "generic", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_015",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Evolocumab and alirocumab are best classified as which type of lipid-lowering therapy?",
            options: ["PCSK9 inhibitors (monoclonal antibodies)", "Omega‑3 fatty acids", "Fibrates", "Cholesterol absorption inhibitors", "HMG‑CoA reductase inhibitors"],
            answer: "PCSK9 inhibitors (monoclonal antibodies)",
            explanation: "Evolocumab and alirocumab are PCSK9 inhibitor monoclonal antibodies. Their hallmark: potent LDL reduction and subcutaneous administration.",
            objective: .classId,
            relatedDrugIds: ["d33", "d34"],
            tags: ["Class", "PCSK9", "mAb"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_016",
            subsectionId: "2b",
            difficulty: .hard,
            question: "PCSK9 inhibitors lower LDL cholesterol by increasing the number of LDL receptors available on hepatocytes. They do this most directly by preventing degradation of which structure?",
            options: ["LDL receptor", "HDL receptor", "NPC1L1 transporter", "PPAR‑α receptor", "COX‑1 enzyme"],
            answer: "LDL receptor",
            explanation: "PCSK9 promotes LDL receptor degradation. Blocking PCSK9 allows LDL receptors to recycle back to the cell surface, increasing LDL clearance from the blood.",
            objective: .moa,
            relatedDrugIds: ["d33"],
            tags: ["MOA", "LDL receptor", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_017",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which statement best describes the normal role of PCSK9 in LDL metabolism (the process that PCSK9 inhibitors interrupt)?",
            options: ["PCSK9 binds LDL receptors and targets them for lysosomal degradation.", "PCSK9 blocks cholesterol absorption in the gut.", "PCSK9 activates PPAR‑α to lower triglycerides.", "PCSK9 irreversibly inhibits platelet COX‑1.", "PCSK9 converts HMG‑CoA to mevalonate."],
            answer: "PCSK9 binds LDL receptors and targets them for lysosomal degradation.",
            explanation: "PCSK9 reduces LDL receptor recycling by directing receptors toward degradation. PCSK9 inhibitors preserve receptors, allowing more LDL removal from circulation.",
            objective: .moa,
            relatedDrugIds: ["d34"],
            tags: ["PCSK9", "Mechanism", "LDL"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_018",
            subsectionId: "2b",
            difficulty: .easy,
            question: "How are PCSK9 inhibitors like evolocumab and alirocumab typically administered in outpatient practice?",
            options: ["Subcutaneous injection", "Oral tablet", "Intranasal spray", "Inhaled powder", "Intrathecal injection"],
            answer: "Subcutaneous injection",
            explanation: "PCSK9 inhibitors are monoclonal antibodies given subcutaneously (often every 2–4 weeks). They are not oral medications.",
            objective: .dosing,
            relatedDrugIds: ["d33"],
            tags: ["Route", "PCSK9", "Injection"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_019",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A common dosing pattern for PCSK9 inhibitor therapy is subcutaneous administration at an interval measured in weeks. Which schedule best matches typical PCSK9 inhibitor dosing?",
            options: ["Every 2–4 weeks", "Every 6 hours", "Once yearly", "Three times daily", "Only as a one-time IV bolus"],
            answer: "Every 2–4 weeks",
            explanation: "PCSK9 inhibitors are typically administered subcutaneously every 2–4 weeks (varies by product and dose). This is a high-yield distinguishing feature vs oral agents.",
            objective: .dosing,
            relatedDrugIds: ["d33"],
            tags: ["Frequency", "PCSK9", "Dosing"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_020",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient with familial hypercholesterolemia has persistently high LDL despite statin therapy and ezetimibe. Which non‑statin option from this list is most associated with dramatic LDL reduction through LDL‑receptor recycling?",
            options: ["Evolocumab (Repatha)", "Fenofibrate (Tricor)", "Gemfibrozil (Lopid)", "Icosapent ethyl (Vascepa)", "Hydrochlorothiazide (Microzide)"],
            answer: "Evolocumab (Repatha)",
            explanation: "PCSK9 inhibitors (e.g., evolocumab) produce very large LDL reductions by increasing LDL receptor recycling and surface expression.",
            objective: .indication,
            relatedDrugIds: ["d33"],
            tags: ["Familial hypercholesterolemia", "LDL", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_021",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Which adverse effect is most commonly associated with PCSK9 inhibitors such as evolocumab and alirocumab?",
            options: ["Injection site reactions", "Severe constipation", "Dry cough", "Ototoxicity", "Life‑threatening QT prolongation"],
            answer: "Injection site reactions",
            explanation: "Because PCSK9 inhibitors are injected monoclonal antibodies, injection site reactions are a classic, high-yield side effect.",
            objective: .adverseEffect,
            relatedDrugIds: ["d34"],
            tags: ["Side effects", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_022",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A learner is trying to remember which non‑statin agent is an injectable monoclonal antibody (not an oral pill). Which drug fits that description?",
            options: ["Alirocumab", "Ezetimibe", "Fenofibrate", "Gemfibrozil", "Icosapent ethyl"],
            answer: "Alirocumab",
            explanation: "Alirocumab is a PCSK9 inhibitor monoclonal antibody given by subcutaneous injection. The others listed are oral agents.",
            objective: .pearl,
            relatedDrugIds: ["d34"],
            tags: ["Injectable", "PCSK9", "Pearl"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_023",
            subsectionId: "2b",
            difficulty: .medium,
            question: "After initiating a PCSK9 inhibitor, what is the most direct parameter to monitor to confirm therapeutic effect?",
            options: ["LDL cholesterol on a lipid panel", "Serum sodium", "INR", "Troponin", "Peak flow"],
            answer: "LDL cholesterol on a lipid panel",
            explanation: "PCSK9 inhibitors primarily lower LDL. Checking a lipid panel (especially LDL) after starting therapy confirms response.",
            objective: .monitoring,
            relatedDrugIds: ["d33"],
            tags: ["Monitoring", "LDL", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_024",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which pairing correctly matches a PCSK9 inhibitor with its brand name?",
            options: ["Evolocumab — Repatha", "Ezetimibe — Vascepa", "Fenofibrate — Lopid", "Gemfibrozil — Tricor", "Alirocumab — Zetia"],
            answer: "Evolocumab — Repatha",
            explanation: "Repatha is evolocumab. Praluent is alirocumab. Zetia is ezetimibe, and Vascepa is icosapent ethyl.",
            objective: .brandGeneric,
            relatedDrugIds: ["d33"],
            tags: ["Brand-generic", "PCSK9"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_025",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Fenofibrate is a fibrate primarily used to lower triglycerides. Which brand name is associated with fenofibrate?",
            options: ["Tricor", "Lopid", "Zetia", "Repatha", "Praluent"],
            answer: "Tricor",
            explanation: "Fenofibrate is marketed as Tricor. Fibrates are the classic “triglyceride-lowering” class.",
            objective: .genericBrand,
            relatedDrugIds: ["d35"],
            tags: ["Fenofibrate", "brand", "Fibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_026",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Tricor is a medication used mainly for hypertriglyceridemia. What is the generic name for Tricor?",
            options: ["Fenofibrate", "Gemfibrozil", "Ezetimibe", "Icosapent ethyl", "Evolocumab"],
            answer: "Fenofibrate",
            explanation: "Tricor = fenofibrate. Fenofibrate is generally the preferred fibrate if combination therapy with a statin is needed.",
            objective: .brandGeneric,
            relatedDrugIds: ["d35"],
            tags: ["Tricor", "generic", "Fenofibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_027",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Gemfibrozil is a fibrate used to lower triglycerides. Which brand name matches gemfibrozil?",
            options: ["Lopid", "Tricor", "Zetia", "Vascepa", "Crestor"],
            answer: "Lopid",
            explanation: "Gemfibrozil is marketed as Lopid. High-yield interaction pearl: gemfibrozil + statins increases myopathy risk.",
            objective: .genericBrand,
            relatedDrugIds: ["d36"],
            tags: ["Gemfibrozil", "brand", "Fibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_028",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Lopid is used to treat hypertriglyceridemia. What is the generic name for Lopid?",
            options: ["Gemfibrozil", "Fenofibrate", "Ezetimibe", "Alirocumab", "Icosapent ethyl"],
            answer: "Gemfibrozil",
            explanation: "Lopid = gemfibrozil. Memorize this pair because gemfibrozil has a notorious interaction with statins (increased myopathy risk).",
            objective: .brandGeneric,
            relatedDrugIds: ["d36"],
            tags: ["Lopid", "generic", "Gemfibrozil"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_029",
            subsectionId: "2b",
            difficulty: .hard,
            question: "Fibrates lower triglycerides by activating a nuclear receptor that increases lipoprotein lipase activity. Which receptor is activated by fibrates like fenofibrate and gemfibrozil?",
            options: ["PPAR‑α", "AT1 receptor", "NPC1L1 transporter", "HMG‑CoA reductase", "P2Y12 receptor"],
            answer: "PPAR‑α",
            explanation: "Fibrates activate PPAR‑α → increased lipoprotein lipase and fatty acid oxidation → lowered triglycerides (and modest HDL increase).",
            objective: .moa,
            relatedDrugIds: ["d35"],
            tags: ["MOA", "PPAR-alpha", "Fibrates"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_030",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which lipid parameter is most directly and most strongly reduced by fibrates such as fenofibrate?",
            options: ["Triglycerides (TG)", "LDL cholesterol", "HDL cholesterol", "Lipoprotein(a)", "Chylomicrons only (with no TG change)"],
            answer: "Triglycerides (TG)",
            explanation: "Fibrates primarily lower triglycerides. They can modestly raise HDL and have variable effects on LDL, but TG lowering is the key high-yield point.",
            objective: .indication,
            relatedDrugIds: ["d35"],
            tags: ["Triglycerides", "Fibrate", "Indication"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_031",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient has severe hypertriglyceridemia and the major goal is to reduce pancreatitis risk by lowering TG. Which medication class is most directly aimed at that goal?",
            options: ["Fibrates (e.g., fenofibrate)", "PCSK9 inhibitors", "Cholesterol absorption inhibitors", "Beta blockers", "ACE inhibitors"],
            answer: "Fibrates (e.g., fenofibrate)",
            explanation: "For very high triglycerides, fibrates are the classic first-line triglyceride-lowering agents to reduce pancreatitis risk.",
            objective: .indication,
            relatedDrugIds: ["d35"],
            tags: ["Pancreatitis", "Hypertriglyceridemia", "Fibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_032",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Fibrates are associated with a high-yield biliary adverse effect due to increased cholesterol in bile. Which adverse effect is classically linked to fibrates?",
            options: ["Cholelithiasis (gallstones)", "Cough", "Agranulocytosis", "Tendon rupture", "Ototoxicity"],
            answer: "Cholelithiasis (gallstones)",
            explanation: "Fibrates can increase the risk of gallstones (cholelithiasis). This is a classic adverse-effect association for the class.",
            objective: .adverseEffect,
            relatedDrugIds: ["d36"],
            tags: ["Adverse effects", "Gallstones", "Fibrates"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_033",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient taking a fibrate develops new muscle pain and weakness. Which adverse effect should you consider, especially if a statin is also on board?",
            options: ["Myopathy/rhabdomyolysis risk", "Severe hypoglycemia", "Torsades de pointes", "Serotonin syndrome", "Pulmonary fibrosis"],
            answer: "Myopathy/rhabdomyolysis risk",
            explanation: "Fibrates can cause myopathy, and the risk is higher with concurrent statin therapy (particularly with gemfibrozil).",
            objective: .adverseEffect,
            relatedDrugIds: ["d36"],
            tags: ["Myopathy", "Fibrate", "Safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_034",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A clinician wants to add a fibrate to a patient already taking a statin but wants the safest pairing. Which fibrate is generally preferred if a fibrate must be combined with a statin?",
            options: ["Fenofibrate", "Gemfibrozil", "Both are equally safe with statins", "Neither can ever be used with a statin", "Gemfibrozil only at low statin doses"],
            answer: "Fenofibrate",
            explanation: "Fenofibrate is generally preferred with statins. Gemfibrozil is more strongly associated with increased statin-associated myopathy risk.",
            objective: .interaction,
            relatedDrugIds: ["d35"],
            tags: ["Interaction", "Statin combo", "Fenofibrate"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_035",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A student is memorizing a high-yield interaction: one fibrate markedly increases statin-associated myopathy risk and is typically avoided in combination. Which fibrate is that?",
            options: ["Gemfibrozil", "Fenofibrate", "Icosapent ethyl", "Ezetimibe", "Evolocumab"],
            answer: "Gemfibrozil",
            explanation: "Gemfibrozil is the fibrate most famously associated with higher myopathy risk when used with statins; fenofibrate is the preferred alternative if combination is necessary.",
            objective: .interaction,
            relatedDrugIds: ["d36"],
            tags: ["Gemfibrozil", "Statin interaction", "Myopathy"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_036",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which monitoring strategy is most appropriate when starting fenofibrate for hypertriglyceridemia?",
            options: ["Check liver enzymes and renal function", "Check TSH weekly", "Check serum troponin", "Check peak flow", "Check hearing tests"],
            answer: "Check liver enzymes and renal function",
            explanation: "Fibrates can affect liver function and are renally cleared to varying degrees. Monitoring liver enzymes and renal function is high-yield for safety.",
            objective: .monitoring,
            relatedDrugIds: ["d35"],
            tags: ["Monitoring", "Fenofibrate", "LFT/renal"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_037",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which patient factor is a high-yield reason to use caution or avoid fibrates like fenofibrate?",
            options: ["Active gallbladder disease or severe liver disease", "History of seasonal allergies", "Mild acne", "Controlled hypothyroidism", "Myopia requiring glasses"],
            answer: "Active gallbladder disease or severe liver disease",
            explanation: "Because fibrates can cause gallstones and affect liver function, active gallbladder disease and significant hepatic disease are classic caution/avoid situations.",
            objective: .contraindication,
            relatedDrugIds: ["d35"],
            tags: ["Contraindications", "Fibrate", "Safety"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_038",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient on warfarin starts a fibrate for high triglycerides. Which action is most appropriate due to a drug–drug interaction risk?",
            options: ["Monitor INR more closely", "Stop all dietary vitamin K permanently", "Add aspirin automatically", "Switch warfarin to an ACE inhibitor", "No additional monitoring is needed"],
            answer: "Monitor INR more closely",
            explanation: "Fibrates can potentiate warfarin’s effect (bleeding risk). A high-yield safety move is closer INR monitoring when starting or changing fibrate therapy.",
            objective: .interaction,
            relatedDrugIds: ["d35"],
            tags: ["Warfarin", "Interaction", "INR"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_039",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Icosapent ethyl is a prescription omega‑3 product used for high triglycerides and ASCVD risk reduction. Which brand name matches icosapent ethyl?",
            options: ["Vascepa", "Zetia", "Tricor", "Lopid", "Repatha"],
            answer: "Vascepa",
            explanation: "Icosapent ethyl is marketed as Vascepa. High-yield pearl: it’s a prescription, purified EPA product—not the same as OTC fish oil mixtures.",
            objective: .genericBrand,
            relatedDrugIds: ["d37"],
            tags: ["Icosapent ethyl", "brand", "Omega-3"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_040",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Vascepa is a prescription lipid agent that contains purified EPA. What is the generic name for Vascepa?",
            options: ["Icosapent ethyl", "Ezetimibe", "Fenofibrate", "Evolocumab", "Alirocumab"],
            answer: "Icosapent ethyl",
            explanation: "Vascepa = icosapent ethyl. It’s an omega‑3 fatty acid product (pure EPA) used for hypertriglyceridemia and ASCVD risk reduction in select patients.",
            objective: .brandGeneric,
            relatedDrugIds: ["d37"],
            tags: ["Vascepa", "generic", "EPA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_041",
            subsectionId: "2b",
            difficulty: .easy,
            question: "Icosapent ethyl (Vascepa) belongs to which drug class for lipid management?",
            options: ["Omega‑3 fatty acid (EPA)", "PCSK9 inhibitor", "Fibrate", "Cholesterol absorption inhibitor", "Statin"],
            answer: "Omega‑3 fatty acid (EPA)",
            explanation: "Vascepa is an omega‑3 fatty acid product containing purified EPA (eicosapentaenoic acid). It is not a statin, fibrate, ezetimibe, or PCSK9 inhibitor.",
            objective: .classId,
            relatedDrugIds: ["d37"],
            tags: ["Class", "Omega-3", "Vascepa"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_042",
            subsectionId: "2b",
            difficulty: .medium,
            question: "A patient has elevated triglycerides and needs a non‑statin option that can help lower TG and is also used for ASCVD risk reduction in selected patients. Which medication from this list best matches that role?",
            options: ["Icosapent ethyl (Vascepa)", "Ezetimibe (Zetia)", "Alirocumab (Praluent)", "Evolocumab (Repatha)", "Lovastatin (Mevacor)"],
            answer: "Icosapent ethyl (Vascepa)",
            explanation: "Icosapent ethyl (Vascepa) is used for hypertriglyceridemia and has an ASCVD risk-reduction indication in select high-risk patients, distinguishing it from ezetimibe/PCSK9 agents that mainly target LDL.",
            objective: .indication,
            relatedDrugIds: ["d37"],
            tags: ["Triglycerides", "ASCVD", "Vascepa"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_043",
            subsectionId: "2b",
            difficulty: .hard,
            question: "Vascepa is often remembered as a “pure EPA” prescription omega‑3. EPA stands for:",
            options: ["Eicosapentaenoic acid", "Docosahexaenoic acid", "Erythropoietic acid", "Eicosatetraenoic acid", "Erucic acid"],
            answer: "Eicosapentaenoic acid",
            explanation: "Vascepa contains purified EPA (eicosapentaenoic acid). Knowing EPA vs DHA helps distinguish prescription icosapent ethyl from mixed fish-oil products.",
            objective: .pearl,
            relatedDrugIds: ["d37"],
            tags: ["EPA", "Pearl", "Omega-3"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_044",
            subsectionId: "2b",
            difficulty: .medium,
            question: "Which adverse effect is especially important to counsel about with icosapent ethyl (Vascepa), particularly in patients already on antithrombotic therapy?",
            options: ["Increased bleeding risk", "Dry cough", "Severe constipation", "Ototoxicity", "Hyperkalemia"],
            answer: "Increased bleeding risk",
            explanation: "Omega‑3 products like icosapent ethyl can increase bleeding risk. This matters most when combined with anticoagulants or antiplatelet agents.",
            objective: .adverseEffect,
            relatedDrugIds: ["d37"],
            tags: ["Bleeding", "Side effects", "Vascepa"],
            source: .curated
        ),
        .multipleChoice(
            id: "q2b_add_045",
            subsectionId: "2b",
            difficulty: .hard,
            question: "A patient taking apixaban is started on icosapent ethyl (Vascepa). Which counseling point is most appropriate based on a high-yield interaction/side-effect overlap?",
            options: ["Watch for bleeding or easy bruising and report it.", "Expect a persistent dry cough and stop the drug if it occurs.", "Avoid potassium-rich foods to prevent hyperkalemia.", "Plan for weekly INR checks to keep the INR between 2 and 3.", "The medication must be injected subcutaneously every 2 weeks."],
            answer: "Watch for bleeding or easy bruising and report it.",
            explanation: "Icosapent ethyl can increase bleeding risk. When combined with anticoagulants (like apixaban), patients should be counseled to watch for bleeding or easy bruising.",
            objective: .interaction,
            relatedDrugIds: ["d37"],
            tags: ["Interaction", "Bleeding", "Apixaban"],
            source: .curated
        ),
    ]
}