import Foundation

extension DrugDataService {
    static let curatedAddOnQuestions_1b: [Question] = [
        .multipleChoice(
            id: "q1b_add_001",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Hydrochlorothiazide is a thiazide diuretic commonly used for hypertension and mild edema. What is the brand name most associated with hydrochlorothiazide?",
            options: ["Microzide", "Thalitone", "Lasix", "Bumex", "Demadex"],
            answer: "Microzide",
            explanation: "Hydrochlorothiazide (a thiazide diuretic used for HTN/edema) is marketed as Microzide. Recognizing the class + indication while you recall the brand name strengthens memory.",
            objective: .genericBrand,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "brand", "Hydrochlorothiazide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_002",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Microzide is a brand-name diuretic often used as first-line therapy for uncomplicated hypertension. What is the generic name of Microzide?",
            options: ["Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Bumetanide", "Torsemide"],
            answer: "Hydrochlorothiazide",
            explanation: "Microzide is the brand name for hydrochlorothiazide. Seeing a brand name should prompt you to recall the drug's class (thiazide) and its common electrolyte effects.",
            objective: .brandGeneric,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "generic", "Microzide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_003",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Chlorthalidone is a thiazide-like diuretic that is often preferred for long-term blood pressure control due to its long duration of action. Which brand name matches chlorthalidone?",
            options: ["Thalitone", "Microzide", "Lasix", "Demadex", "Bumex"],
            answer: "Thalitone",
            explanation: "Chlorthalidone is marketed as Thalitone. It's considered \"thiazide-like\" and is longer-acting than hydrochlorothiazide for BP control.",
            objective: .genericBrand,
            relatedDrugIds: ["d10"],
            tags: ["Thiazide-like Diuretic", "brand", "Chlorthalidone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_004",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Thalitone is a brand-name diuretic prescribed primarily for hypertension. What is the generic name of Thalitone?",
            options: ["Chlorthalidone", "Hydrochlorothiazide", "Torsemide", "Bumetanide", "Furosemide"],
            answer: "Chlorthalidone",
            explanation: "Thalitone = chlorthalidone. Even though it doesn't end in \"-thiazide,\" it behaves like a thiazide and is a go-to long-acting option for HTN.",
            objective: .brandGeneric,
            relatedDrugIds: ["d10"],
            tags: ["Thiazide-like Diuretic", "generic", "Thalitone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_005",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Furosemide is a potent loop diuretic frequently used for edema and acute pulmonary edema in heart failure. What is the brand name for furosemide?",
            options: ["Lasix", "Demadex", "Bumex", "Microzide", "Thalitone"],
            answer: "Lasix",
            explanation: "Furosemide is sold as Lasix. Loop diuretics are the most potent diuretic class and are commonly used for symptomatic fluid overload.",
            objective: .genericBrand,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "brand", "Furosemide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_006",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Lasix is a brand-name medication often given (sometimes IV) for acute volume overload in heart failure. What is the generic name of Lasix?",
            options: ["Furosemide", "Torsemide", "Bumetanide", "Hydrochlorothiazide", "Chlorthalidone"],
            answer: "Furosemide",
            explanation: "Lasix = furosemide. When you see Lasix, think \"loop diuretic,\" powerful diuresis, and monitoring for low potassium and volume depletion.",
            objective: .brandGeneric,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "generic", "Lasix"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_007",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Bumetanide is a loop diuretic often used for edema and heart failure when a strong diuretic effect is needed in a small dose. Which brand name matches bumetanide?",
            options: ["Bumex", "Lasix", "Demadex", "Microzide", "Thalitone"],
            answer: "Bumex",
            explanation: "Bumetanide is marketed as Bumex. It's a loop diuretic and is very potent on a milligram-per-milligram basis.",
            objective: .genericBrand,
            relatedDrugIds: ["d12"],
            tags: ["Loop Diuretic", "brand", "Bumetanide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_008",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Bumex is a brand-name loop diuretic used for edema in conditions like heart failure. What is the generic name of Bumex?",
            options: ["Bumetanide", "Torsemide", "Furosemide", "Chlorthalidone", "Hydrochlorothiazide"],
            answer: "Bumetanide",
            explanation: "Bumex = bumetanide. Knowing the brand name helps you recognize loop diuretic therapy quickly when reviewing medication lists.",
            objective: .brandGeneric,
            relatedDrugIds: ["d12"],
            tags: ["Loop Diuretic", "generic", "Bumex"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_009",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Torsemide is a loop diuretic used for edema and heart failure and is known for reliable oral absorption. Which brand name matches torsemide?",
            options: ["Demadex", "Lasix", "Bumex", "Microzide", "Thalitone"],
            answer: "Demadex",
            explanation: "Torsemide is marketed as Demadex. Compared with some other loops, it has more predictable oral bioavailability—useful in chronic HF.",
            objective: .genericBrand,
            relatedDrugIds: ["d13"],
            tags: ["Loop Diuretic", "brand", "Torsemide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_010",
            subsectionId: "1b",
            difficulty: .easy,
            question: "Demadex is a brand-name loop diuretic used for edema and heart failure. What is the generic name of Demadex?",
            options: ["Torsemide", "Furosemide", "Bumetanide", "Hydrochlorothiazide", "Chlorthalidone"],
            answer: "Torsemide",
            explanation: "Demadex = torsemide. When you see Demadex, think loop diuretic, strong natriuresis, and the need to monitor electrolytes and renal function.",
            objective: .brandGeneric,
            relatedDrugIds: ["d13"],
            tags: ["Loop Diuretic", "generic", "Demadex"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_011",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Hydrochlorothiazide (Microzide) lowers blood pressure by inhibiting which renal transporter?",
            options: ["Na+/Cl\u{2212} cotransporter in the distal convoluted tubule", "Na+/K+/2Cl\u{2212} transporter in the thick ascending limb", "ENaC sodium channel in the collecting duct", "Carbonic anhydrase in the proximal tubule", "V2 (ADH) receptor in the collecting duct"],
            answer: "Na+/Cl\u{2212} cotransporter in the distal convoluted tubule",
            explanation: "Hydrochlorothiazide is a thiazide diuretic that inhibits the Na+/Cl\u{2212} cotransporter in the distal convoluted tubule (DCT). This mechanism explains both its BP effect and its classic electrolyte patterns.",
            objective: .moa,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "MOA", "NaCl cotransporter", "DCT"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_012",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Chlorthalidone is \"thiazide-like\" for hypertension even though it does not end in \"-thiazide.\" Which mechanism best describes how chlorthalidone works?",
            options: ["Blocks the Na+/Cl\u{2212} cotransporter in the distal convoluted tubule", "Blocks the Na+/K+/2Cl\u{2212} transporter in the thick ascending limb", "Blocks ENaC channels in the collecting duct", "Inhibits carbonic anhydrase in the proximal tubule", "Antagonizes ADH (V2 receptors) in the collecting duct"],
            answer: "Blocks the Na+/Cl\u{2212} cotransporter in the distal convoluted tubule",
            explanation: "Chlorthalidone is thiazide-like: it inhibits the Na+/Cl\u{2212} cotransporter in the distal convoluted tubule. Class recognition tells you both expected benefits (BP reduction) and expected adverse effects.",
            objective: .moa,
            relatedDrugIds: ["d10"],
            tags: ["Thiazide-like Diuretic", "MOA", "Chlorthalidone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_013",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Loop diuretics are the most potent diuretics because they block a major sodium transporter in the kidney. Which transporter does furosemide inhibit?",
            options: ["Na+/K+/2Cl\u{2212} transporter in the thick ascending limb", "Na+/Cl\u{2212} cotransporter in the distal convoluted tubule", "ENaC sodium channel in the collecting duct", "Na+/H+ exchanger in the proximal tubule", "V2 (ADH) receptor in the collecting duct"],
            answer: "Na+/K+/2Cl\u{2212} transporter in the thick ascending limb",
            explanation: "Furosemide is a loop diuretic that inhibits the Na+/K+/2Cl\u{2212} (NKCC2) transporter in the thick ascending limb. This is why loops cause powerful natriuresis and can disrupt calcium/magnesium handling.",
            objective: .moa,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "MOA", "NKCC2"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_014",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient with severe hypercalcemia needs a diuretic to increase urinary calcium excretion (after appropriate volume repletion). Which medication from this subsection is the best match?",
            options: ["Furosemide", "Hydrochlorothiazide", "Chlorthalidone", "Lisinopril", "Amlodipine"],
            answer: "Furosemide",
            explanation: "Loop diuretics (like furosemide) increase calcium excretion by inhibiting NKCC2 in the thick ascending limb, reducing the driving force for paracellular Ca2+ reabsorption. Thiazides tend to increase calcium reabsorption.",
            objective: .pearl,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "hypercalcemia", "calcium excretion"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_015",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient has recurrent calcium oxalate kidney stones with hypercalciuria. Which medication in this subsection is a true thiazide diuretic that can help reduce urinary calcium excretion?",
            options: ["Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Torsemide", "Bumetanide"],
            answer: "Hydrochlorothiazide",
            explanation: "Thiazides decrease urinary calcium by increasing calcium reabsorption in the DCT. Hydrochlorothiazide is the classic thiazide that represents this high-yield kidney-stone prevention pearl.",
            objective: .pearl,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "nephrolithiasis", "hypercalciuria"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_016",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A patient started on hydrochlorothiazide for hypertension later shows increased glucose, increased uric acid, and mild hypercalcemia on labs. Which adverse-effect pattern best explains this?",
            options: ["Thiazides can raise glucose, uric acid, and calcium", "Thiazides uniquely cause hypocalcemia and hypoglycemia", "Loop diuretics classically cause hypercalcemia", "Potassium-sparing diuretics cause severe hypernatremia", "Osmotic diuretics cause marked hypercalcemia"],
            answer: "Thiazides can raise glucose, uric acid, and calcium",
            explanation: "Thiazides are famous for raising glucose, uric acid, lipids, and calcium (while lowering potassium and sometimes sodium). Seeing this lab pattern should point you to a thiazide like hydrochlorothiazide.",
            objective: .adverseEffect,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "adverse effects", "labs"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_017",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Two common thiazide options for hypertension are hydrochlorothiazide and chlorthalidone. Which statement is MOST accurate for long-term BP control?",
            options: ["Chlorthalidone is longer-acting than hydrochlorothiazide", "Hydrochlorothiazide is longer-acting than chlorthalidone", "Both have identical half-lives and clinical duration", "Chlorthalidone is a loop diuretic used primarily for pulmonary edema", "Hydrochlorothiazide is potassium-sparing and causes hyperkalemia"],
            answer: "Chlorthalidone is longer-acting than hydrochlorothiazide",
            explanation: "Chlorthalidone is a long-acting thiazide-like diuretic often preferred for sustained BP lowering. Hydrochlorothiazide is widely used but is generally shorter-acting.",
            objective: .pearl,
            relatedDrugIds: ["d10", "d9"],
            tags: ["HTN", "chlorthalidone", "duration"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_018",
            subsectionId: "1b",
            difficulty: .medium,
            question: "When switching a heart failure patient from oral furosemide to another loop diuretic for more predictable oral absorption, which choice is most appropriate?",
            options: ["Torsemide", "Hydrochlorothiazide", "Chlorthalidone", "Bumetanide", "Furosemide"],
            answer: "Torsemide",
            explanation: "Torsemide is a loop diuretic with more reliable oral bioavailability than furosemide, making it a common choice when oral absorption is a concern in chronic heart failure.",
            objective: .pearl,
            relatedDrugIds: ["d13", "d11"],
            tags: ["Loop Diuretic", "bioavailability", "HF"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_019",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A clinician wants a loop diuretic that is very potent milligram-for-milligram. Which loop diuretic best fits this description?",
            options: ["Bumetanide", "Furosemide", "Torsemide", "Hydrochlorothiazide", "Chlorthalidone"],
            answer: "Bumetanide",
            explanation: "Bumetanide is a highly potent loop diuretic on a mg-for-mg basis. That potency is a classic comparison point among loop diuretics.",
            objective: .pearl,
            relatedDrugIds: ["d12"],
            tags: ["Loop Diuretic", "potency", "Bumetanide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_020",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient with acute pulmonary edema from decompensated heart failure needs rapid diuresis. Which medication from this subsection is classically used (often IV) for this situation?",
            options: ["Furosemide", "Hydrochlorothiazide", "Chlorthalidone", "Torsemide", "Bumetanide"],
            answer: "Furosemide",
            explanation: "Furosemide is a loop diuretic commonly used (often IV) in acute decompensated heart failure and pulmonary edema because it provides rapid, powerful diuresis.",
            objective: .indication,
            relatedDrugIds: ["d11"],
            tags: ["Acute pulmonary edema", "HF", "Loop Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_021",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A patient receiving high-dose IV diuresis reports tinnitus (ringing in the ears). This adverse effect is most strongly associated with which diuretic class?",
            options: ["Loop diuretics", "Thiazide diuretics", "Potassium-sparing diuretics", "Carbonic anhydrase inhibitors", "Osmotic diuretics"],
            answer: "Loop diuretics",
            explanation: "Ototoxicity (tinnitus/hearing changes) is a classic adverse effect of loop diuretics, especially with high doses or rapid IV administration.",
            objective: .adverseEffect,
            relatedDrugIds: ["d11", "d12", "d13"],
            tags: ["Loop Diuretic", "ototoxicity", "adverse effects"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_022",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A major interaction pearl: combining a loop diuretic like furosemide with which medication class increases the risk of ototoxicity (hearing damage)?",
            options: ["Aminoglycoside antibiotics", "Macrolide antibiotics", "Tetracycline antibiotics", "Penicillin antibiotics", "Azole antifungals"],
            answer: "Aminoglycoside antibiotics",
            explanation: "Loop diuretics can be ototoxic, and the risk increases when combined with other ototoxic drugs—classically aminoglycosides (e.g., gentamicin). This is a high-yield safety interaction.",
            objective: .interaction,
            relatedDrugIds: ["d11"],
            tags: ["interaction", "ototoxicity", "Loop Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_023",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient on digoxin for rate control starts furosemide for edema. Which electrolyte abnormality from diuretic therapy most increases the risk of digoxin toxicity and arrhythmias?",
            options: ["Hypokalemia", "Hyperkalemia", "Hypercalcemia", "Hypermagnesemia", "Hypernatremia"],
            answer: "Hypokalemia",
            explanation: "Loop (and thiazide) diuretics can cause hypokalemia. Low potassium sensitizes the myocardium to digoxin, increasing toxicity risk—so potassium monitoring and replacement are high-yield.",
            objective: .interaction,
            relatedDrugIds: ["d11"],
            tags: ["digoxin", "hypokalemia", "interaction"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_024",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient with bipolar disorder is stable on lithium. You start Microzide for hypertension and the lithium level rises. Microzide contains which generic medication?",
            options: ["Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Torsemide", "Bumetanide"],
            answer: "Hydrochlorothiazide",
            explanation: "Microzide is hydrochlorothiazide. Thiazides can reduce lithium clearance and raise lithium levels, increasing toxicity risk, so lithium monitoring is important if they're combined.",
            objective: .interaction,
            relatedDrugIds: ["d9"],
            tags: ["Lithium", "interaction", "Microzide", "Thiazide Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_025",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient with edema on furosemide begins taking high-dose NSAIDs daily and notices less diuresis. What is the best explanation?",
            options: ["NSAIDs reduce renal prostaglandins, lowering diuretic efficacy", "NSAIDs directly block NKCC2, causing diuretic resistance", "NSAIDs increase aldosterone, making furosemide more potent", "NSAIDs increase urinary sodium loss, amplifying diuresis", "NSAIDs prevent potassium loss, which stops furosemide from working"],
            answer: "NSAIDs reduce renal prostaglandins, lowering diuretic efficacy",
            explanation: "NSAIDs can blunt diuretic response by reducing renal prostaglandin synthesis, decreasing renal blood flow and natriuresis.",
            objective: .interaction,
            relatedDrugIds: ["d11"],
            tags: ["NSAIDs", "interaction", "diuretic resistance"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_026",
            subsectionId: "1b",
            difficulty: .medium,
            question: "After starting chlorthalidone for hypertension, which monitoring plan is most appropriate to catch the most testable early adverse effects?",
            options: ["Check a basic metabolic panel (especially Na+ and K+)", "Check INR weekly", "Check troponin daily", "Check TSH in 6 weeks", "Check HbA1c every 48 hours"],
            answer: "Check a basic metabolic panel (especially Na+ and K+)",
            explanation: "Thiazide(-like) diuretics can cause hyponatremia and hypokalemia. A BMP (Na+, K+, creatinine) soon after starting or increasing the dose is a high-yield monitoring step.",
            objective: .monitoring,
            relatedDrugIds: ["d10"],
            tags: ["monitoring", "electrolytes", "Chlorthalidone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_027",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A patient with chronic heart failure is titrating torsemide at home. Which patient-reported metric is most useful for day-to-day monitoring of diuretic effect?",
            options: ["Daily weight tracking", "Daily INR values", "Daily peak flow readings", "Daily finger-stick ketones", "Daily pupillary reflex checks"],
            answer: "Daily weight tracking",
            explanation: "For loop diuretics in heart failure, daily weights are one of the most practical ways to monitor volume status. Rapid weight changes often reflect fluid shifts before symptoms worsen.",
            objective: .monitoring,
            relatedDrugIds: ["d13"],
            tags: ["HF", "monitoring", "volume status"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_028",
            subsectionId: "1b",
            difficulty: .hard,
            question: "An older adult becomes confused a week after starting a long-acting thiazide-like diuretic for hypertension. Labs show low sodium. Which medication is the most likely cause?",
            options: ["Chlorthalidone", "Torsemide", "Bumetanide", "Furosemide", "Hydrochlorothiazide"],
            answer: "Chlorthalidone",
            explanation: "Thiazide(-like) diuretics can cause hyponatremia, and chlorthalidone's long duration can make this particularly clinically significant. Hyponatremia can present with confusion, falls, and seizures.",
            objective: .adverseEffect,
            relatedDrugIds: ["d10"],
            tags: ["hyponatremia", "adverse effects", "Thiazide-like Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_029",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient's serum calcium drifts upward after starting Microzide for hypertension. Which medication is Microzide?",
            options: ["Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Torsemide", "Bumetanide"],
            answer: "Hydrochlorothiazide",
            explanation: "Microzide is hydrochlorothiazide. Thiazides increase calcium reabsorption in the distal convoluted tubule, which can raise serum calcium slightly and lower urinary calcium.",
            objective: .brandGeneric,
            relatedDrugIds: ["d9"],
            tags: ["Microzide", "calcium", "Thiazide Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_030",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Chronic loop diuretic therapy can lower magnesium levels, which may predispose to arrhythmias. Which electrolyte is most important to replete if low during furosemide therapy?",
            options: ["Magnesium", "Calcium", "Phosphate", "Bicarbonate", "Chloride"],
            answer: "Magnesium",
            explanation: "Loop diuretics increase urinary magnesium excretion. Hypomagnesemia can contribute to arrhythmias and make potassium repletion harder.",
            objective: .monitoring,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "hypomagnesemia", "electrolytes"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_031",
            subsectionId: "1b",
            difficulty: .hard,
            question: "Both thiazide and loop diuretics can cause metabolic alkalosis. What is the most accurate mechanism behind this acid-base change?",
            options: ["Volume contraction increases aldosterone \u{2192} increased H+ secretion", "Direct inhibition of carbonic anhydrase in the proximal tubule", "Blocking ADH receptors causing bicarbonate retention", "Increasing lactic acid production in muscle", "Decreasing renal ammonia production causing acidosis"],
            answer: "Volume contraction increases aldosterone \u{2192} increased H+ secretion",
            explanation: "Diuretic-induced volume loss activates RAAS and increases distal Na+ delivery, which promotes H+ (and K+) secretion in the collecting duct—leading to metabolic alkalosis.",
            objective: .moa,
            relatedDrugIds: ["d9", "d11"],
            tags: ["acid-base", "metabolic alkalosis", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_032",
            subsectionId: "1b",
            difficulty: .hard,
            question: "Why do thiazide diuretics (like hydrochlorothiazide) decrease urinary calcium excretion?",
            options: ["Lower intracellular Na+ in the DCT drives the basolateral Na+/Ca2+ exchanger, increasing Ca2+ reabsorption", "Blocking NKCC2 eliminates the lumen-positive potential needed for Ca2+ reabsorption", "Blocking ENaC prevents calcium uptake in the collecting duct", "Inhibiting carbonic anhydrase directly increases calcium secretion", "Thiazides bind calcium in the tubular lumen, preventing reabsorption"],
            answer: "Lower intracellular Na+ in the DCT drives the basolateral Na+/Ca2+ exchanger, increasing Ca2+ reabsorption",
            explanation: "By blocking the Na+/Cl\u{2212} cotransporter in the DCT, thiazides lower intracellular Na+. This favors the basolateral Na+/Ca2+ exchanger and increases Ca2+ reabsorption.",
            objective: .moa,
            relatedDrugIds: ["d9"],
            tags: ["Thiazide Diuretic", "calcium", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_033",
            subsectionId: "1b",
            difficulty: .hard,
            question: "Loop diuretics (like furosemide) impair the kidney's ability to concentrate urine primarily by disrupting which physiologic process?",
            options: ["Countercurrent multiplication in the loop of Henle", "Glomerular filtration at the afferent arteriole", "Bicarbonate reclamation in the collecting duct", "Erythropoietin synthesis in the cortex", "Aldosterone secretion from the adrenal cortex"],
            answer: "Countercurrent multiplication in the loop of Henle",
            explanation: "The thick ascending limb is key to building the medullary gradient via countercurrent multiplication. Loop diuretics block NKCC2 there, reducing the gradient and impairing urine concentration.",
            objective: .moa,
            relatedDrugIds: ["d11"],
            tags: ["Loop Diuretic", "physiology", "MOA"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_034",
            subsectionId: "1b",
            difficulty: .hard,
            question: "Thalitone (chlorthalidone) is contraindicated in which scenario because the drug will not work and may cause harm?",
            options: ["Anuria (no urine output)", "Controlled essential hypertension", "Mild peripheral edema", "History of seasonal allergies", "Stable hyperlipidemia"],
            answer: "Anuria (no urine output)",
            explanation: "Chlorthalidone is contraindicated in anuria. If the kidneys are not producing urine, diuretics cannot promote diuresis and can worsen electrolyte/volume issues.",
            objective: .contraindication,
            relatedDrugIds: ["d10"],
            tags: ["contraindication", "anuria", "Chlorthalidone"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_035",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A clinician is cautious prescribing hydrochlorothiazide or chlorthalidone because both are sulfonamide-derived drugs. Which patient history is most relevant to this concern?",
            options: ["Severe sulfonamide allergy (e.g., rash/angioedema with sulfa antibiotics)", "History of penicillin allergy", "History of shellfish allergy", "History of lactose intolerance", "History of seasonal pollen allergies"],
            answer: "Severe sulfonamide allergy (e.g., rash/angioedema with sulfa antibiotics)",
            explanation: "Thiazide(-like) diuretics are sulfonamide-derived. A history of severe sulfonamide reactions is a key caution point worth remembering.",
            objective: .contraindication,
            relatedDrugIds: ["d9", "d10"],
            tags: ["sulfa", "hypersensitivity", "Thiazide Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_036",
            subsectionId: "1b",
            difficulty: .medium,
            question: "A student tries to identify a diuretic by name patterns. Which drug is thiazide-like for hypertension even though it does NOT contain the \"-thiazide\" suffix?",
            options: ["Chlorthalidone", "Hydrochlorothiazide", "Furosemide", "Torsemide", "Bumetanide"],
            answer: "Chlorthalidone",
            explanation: "Chlorthalidone is \"thiazide-like\" but doesn't carry the -thiazide suffix. It still works in the DCT and is longer-acting, which is why it's often emphasized in hypertension teaching.",
            objective: .classId,
            relatedDrugIds: ["d10"],
            tags: ["pattern recognition", "Thiazide-like Diuretic", "HTN"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_037",
            subsectionId: "1b",
            difficulty: .medium,
            question: "Name-pattern shortcut: only one drug in this subsection literally contains \"-thiazide\" in its generic name. Which one is it?",
            options: ["Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Bumetanide", "Torsemide"],
            answer: "Hydrochlorothiazide",
            explanation: "Hydrochlorothiazide contains \"-thiazide\" in the name and is the classic thiazide diuretic. Chlorthalidone is thiazide-like (same site/mechanism) but doesn't use the suffix.",
            objective: .suffixId,
            relatedDrugIds: ["d9", "d10"],
            tags: ["suffix", "pattern recognition", "Thiazide"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_038",
            subsectionId: "1b",
            difficulty: .hard,
            question: "A patient with heart failure has gut edema and responds poorly to oral furosemide. Which loop diuretic from this subsection is often chosen for more predictable oral absorption?",
            options: ["Torsemide", "Bumetanide", "Hydrochlorothiazide", "Chlorthalidone", "Furosemide"],
            answer: "Torsemide",
            explanation: "Torsemide has more reliable oral bioavailability than furosemide, so it's a common switch when oral response is inconsistent in heart failure or gut edema.",
            objective: .pearl,
            relatedDrugIds: ["d13", "d11"],
            tags: ["HF", "bioavailability", "Loop Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_039",
            subsectionId: "1b",
            difficulty: .expert,
            question: "A paradoxical pharmacology pearl: which diuretic can be used to reduce urine volume in nephrogenic diabetes insipidus?",
            options: ["Hydrochlorothiazide", "Furosemide", "Torsemide", "Bumetanide", "Chlorthalidone"],
            answer: "Hydrochlorothiazide",
            explanation: "Thiazides can paradoxically reduce polyuria in nephrogenic diabetes insipidus by causing mild volume depletion, increasing proximal sodium and water reabsorption so less water reaches the collecting duct.",
            objective: .pearl,
            relatedDrugIds: ["d9"],
            tags: ["nephrogenic DI", "pearl", "Thiazide Diuretic"],
            source: .curated
        ),
        .multipleChoice(
            id: "q1b_add_040",
            subsectionId: "1b",
            difficulty: .hard,
            question: "Furosemide carries a prominent warning as a potent diuretic. What is the key risk emphasized if excessive doses are given?",
            options: ["Profound diuresis with water and electrolyte depletion", "Life-threatening hyperkalemia from potassium retention", "Severe neutropenia requiring CBC monitoring", "Irreversible pulmonary fibrosis", "Teratogenicity requiring monthly pregnancy tests"],
            answer: "Profound diuresis with water and electrolyte depletion",
            explanation: "Furosemide is a potent diuretic; excessive dosing can cause profound diuresis leading to water/electrolyte depletion, so careful supervision and individualized dosing are essential.",
            objective: .contraindication,
            relatedDrugIds: ["d11"],
            tags: ["warning", "dehydration", "electrolytes"],
            source: .curated
        ),
    ]
}
