import Foundation

nonisolated enum UniversityData {
    static let schools: [String] = [
        "Abilene Christian University",
        "Adams State University",
        "Adelphi University",
        "Adrian College",
        "Agnes Scott College",
        "Alabama A&M University",
        "Alabama State University",
        "Albany College of Pharmacy and Health Sciences",
        "Albany State University",
        "Albertus Magnus College",
        "Albion College",
        "Albright College",
        "Alcorn State University",
        "Alderson Broaddus University",
        "Alfred University",
        "Allegheny College",
        "Allen University",
        "Alma College",
        "Alverno College",
        "American International College",
        "American University",
        "Amherst College",
        "Anderson University (IN)",
        "Anderson University (SC)",
        "Andrews University",
        "Angelo State University",
        "Anna Maria College",
        "Antioch University",
        "Appalachian State University",
        "Arcadia University",
        "Arizona State University",
        "Arkansas State University",
        "Arkansas Tech University",
        "Armstrong State University",
        "Asbury University",
        "Ashland University",
        "Assumption University",
        "Auburn University",
        "Auburn University Harrison College of Pharmacy",
        "Augsburg University",
        "Augustana College (IL)",
        "Augustana University (SD)",
        "Aurora University",
        "Austin College",
        "Austin Peay State University",
        "Averett University",
        "Avila University",
        "Azusa Pacific University",
        "Babson College",
        "Baker University",
        "Baldwin Wallace University",
        "Ball State University",
        "Bard College",
        "Barry University",
        "Barton College",
        "Bates College",
        "Baylor College of Medicine",
        "Baylor University",
        "Bellarmine University",
        "Bellevue University",
        "Belmont Abbey College",
        "Belmont University",
        "Belmont University College of Pharmacy",
        "Beloit College",
        "Bemidji State University",
        "Benedict College",
        "Benedictine College",
        "Benedictine University",
        "Bennett College",
        "Bennington College",
        "Bentley University",
        "Berea College",
        "Bergen Community College",
        "Berry College",
        "Bethany College (KS)",
        "Bethany College (WV)",
        "Bethel College (KS)",
        "Bethel University (MN)",
        "Bethel University (TN)",
        "Bethune-Cookman University",
        "Binghamton University (SUNY)",
        "Biola University",
        "Birmingham-Southern College",
        "Bismarck State College",
        "Black Hills State University",
        "Blackburn College",
        "Bloomfield College",
        "Bloomsburg University of Pennsylvania",
        "Blue Mountain College",
        "Bluefield State College",
        "Bluffton University",
        "Bob Jones University",
        "Boise State University",
        "Boston College",
        "Boston University",
        "Bowdoin College",
        "Bowie State University",
        "Bowling Green State University",
        "Bradley University",
        "Brandeis University",
        "Brenau University",
        "Brescia University",
        "Brevard College",
        "Briar Cliff University",
        "Bridgewater College",
        "Bridgewater State University",
        "Brigham Young University",
        "Brigham Young University–Idaho",
        "Brigham Young University–Hawaii",
        "Brown University",
        "Bryan College",
        "Bryant University",
        "Bryn Mawr College",
        "Bucknell University",
        "Buena Vista University",
        "Buffalo State College (SUNY)",
        "Butler University",
        "Butler University College of Pharmacy",
        "Cabrini University",
        "Caldwell University",
        "California Baptist University",
        "California Institute of Technology (Caltech)",
        "California Lutheran University",
        "California Northstate University",
        "California Polytechnic State University, San Luis Obispo",
        "California State Polytechnic University, Pomona",
        "California State University, Bakersfield",
        "California State University, Channel Islands",
        "California State University, Chico",
        "California State University, Dominguez Hills",
        "California State University, East Bay",
        "California State University, Fresno",
        "California State University, Fullerton",
        "California State University, Long Beach",
        "California State University, Los Angeles",
        "California State University, Monterey Bay",
        "California State University, Northridge",
        "California State University, Sacramento",
        "California State University, San Bernardino",
        "California State University, San Marcos",
        "California State University, Stanislaus",
        "California University of Pennsylvania",
        "Calvin University",
        "Cameron University",
        "Campbell University",
        "Campbell University College of Pharmacy",
        "Campbellsville University",
        "Canisius College",
        "Capital University",
        "Carleton College",
        "Carnegie Mellon University",
        "Carroll College (MT)",
        "Carroll University (WI)",
        "Carson-Newman University",
        "Carthage College",
        "Case Western Reserve University",
        "Castleton University",
        "Catawba College",
        "Catholic University of America",
        "Cedarville University",
        "Cedarville University School of Pharmacy",
        "Centenary College of Louisiana",
        "Central College (IA)",
        "Central Connecticut State University",
        "Central Methodist University",
        "Central Michigan University",
        "Central State University",
        "Central Washington University",
        "Centre College",
        "Chadron State College",
        "Champlain College",
        "Chapman University",
        "Chapman University School of Pharmacy",
        "Charleston Southern University",
        "Chatham University",
        "Chestnut Hill College",
        "Cheyney University of Pennsylvania",
        "Chicago State University",
        "Chicago State University College of Pharmacy",
        "Chowan University",
        "Christian Brothers University",
        "Christopher Newport University",
        "Citadel, The",
        "City College of New York (CUNY)",
        "Claflin University",
        "Claremont McKenna College",
        "Clarion University of Pennsylvania",
        "Clark Atlanta University",
        "Clark University",
        "Clarke University",
        "Clarkson University",
        "Clayton State University",
        "Clemson University",
        "Cleveland State University",
        "Coastal Carolina University",
        "Coe College",
        "Coker University",
        "Colby College",
        "Colgate University",
        "College of Charleston",
        "College of Idaho",
        "College of Mount Saint Vincent",
        "College of Saint Benedict",
        "College of Saint Rose",
        "College of the Holy Cross",
        "College of the Ozarks",
        "College of William & Mary",
        "College of Wooster",
        "Colorado Christian University",
        "Colorado College",
        "Colorado Mesa University",
        "Colorado School of Mines",
        "Colorado State University",
        "Colorado State University–Pueblo",
        "Columbia College (SC)",
        "Columbia University",
        "Columbus State University",
        "Concordia College (MN)",
        "Concordia University (NE)",
        "Concordia University (OR)",
        "Concordia University Chicago",
        "Concordia University Irvine",
        "Concordia University Wisconsin",
        "Connecticut College",
        "Converse University",
        "Cooper Union",
        "Coppin State University",
        "Cornell College (IA)",
        "Cornell University",
        "Cornerstone University",
        "Covenant College",
        "Creighton University",
        "Creighton University School of Pharmacy",
        "Culver-Stockton College",
        "Cumberland University",
        "Curry College",
        "D'Youville University",
        "D'Youville University School of Pharmacy",
        "Daemen University",
        "Dakota State University",
        "Dakota Wesleyan University",
        "Dallas Baptist University",
        "Dana College",
        "Dartmouth College",
        "Davidson College",
        "Davis & Elkins College",
        "Dayton, University of",
        "Dean College",
        "Defiance College",
        "Delaware State University",
        "Delaware Valley University",
        "Delta State University",
        "Denison University",
        "DePaul University",
        "DePauw University",
        "DeSales University",
        "Dickinson College",
        "Dickinson State University",
        "Dillard University",
        "Doane University",
        "Dominican University",
        "Dominican University of California",
        "Dordt University",
        "Drake University",
        "Drake University College of Pharmacy",
        "Drew University",
        "Drexel University",
        "Drexel University College of Medicine",
        "Drury University",
        "Duke University",
        "Duquesne University",
        "Duquesne University School of Pharmacy",
        "Earlham College",
        "East Carolina University",
        "East Central University",
        "East Stroudsburg University of Pennsylvania",
        "East Tennessee State University",
        "Eastern Connecticut State University",
        "Eastern Illinois University",
        "Eastern Kentucky University",
        "Eastern Mennonite University",
        "Eastern Michigan University",
        "Eastern Nazarene College",
        "Eastern New Mexico University",
        "Eastern Oregon University",
        "Eastern University",
        "Eastern Washington University",
        "Eckerd College",
        "Edinboro University of Pennsylvania",
        "Elon University",
        "Embry-Riddle Aeronautical University",
        "Emerson College",
        "Emmanuel College",
        "Emory & Henry College",
        "Emory University",
        "Emporia State University",
        "Endicott College",
        "Erskine College",
        "Evangel University",
        "Evansville, University of",
        "Evergreen State College",
        "Fairfield University",
        "Fairleigh Dickinson University",
        "Fairleigh Dickinson University School of Pharmacy",
        "Fairmont State University",
        "Farmingdale State College (SUNY)",
        "Faulkner University",
        "Fayetteville State University",
        "Felician University",
        "Ferris State University",
        "Ferris State University College of Pharmacy",
        "Ferrum College",
        "Fisk University",
        "Fitchburg State University",
        "Flagler College",
        "Florida A&M University",
        "Florida A&M University College of Pharmacy",
        "Florida Atlantic University",
        "Florida Gulf Coast University",
        "Florida Institute of Technology",
        "Florida International University",
        "Florida Memorial University",
        "Florida Polytechnic University",
        "Florida Southern College",
        "Florida State University",
        "Fontbonne University",
        "Fordham University",
        "Fort Hays State University",
        "Fort Lewis College",
        "Fort Valley State University",
        "Framingham State University",
        "Francis Marion University",
        "Franciscan University of Steubenville",
        "Franklin & Marshall College",
        "Franklin College",
        "Franklin Pierce University",
        "Freed-Hardeman University",
        "Fresno Pacific University",
        "Friends University",
        "Frostburg State University",
        "Furman University",
        "Gallaudet University",
        "Gannon University",
        "Gardner-Webb University",
        "Geneva College",
        "George Fox University",
        "George Mason University",
        "George Washington University",
        "Georgetown College",
        "Georgetown University",
        "Georgia College & State University",
        "Georgia Institute of Technology",
        "Georgia Southern University",
        "Georgia Southwestern State University",
        "Georgia State University",
        "Georgian Court University",
        "Gettysburg College",
        "Glenville State College",
        "Gonzaga University",
        "Gordon College",
        "Goshen College",
        "Goucher College",
        "Grace College",
        "Graceland University",
        "Grambling State University",
        "Grand Canyon University",
        "Grand Valley State University",
        "Grand View University",
        "Grinnell College",
        "Grove City College",
        "Guilford College",
        "Gustavus Adolphus College",
        "Gwynedd Mercy University",
        "Hamilton College",
        "Hamline University",
        "Hampden-Sydney College",
        "Hampshire College",
        "Hampton University",
        "Hampton University School of Pharmacy",
        "Hanover College",
        "Harding University",
        "Hardin-Simmons University",
        "Harris-Stowe State University",
        "Hartwick College",
        "Harvard University",
        "Harvey Mudd College",
        "Hastings College",
        "Haverford College",
        "Hawaii Pacific University",
        "Heidelberg University",
        "Henderson State University",
        "Hendrix College",
        "Heritage University",
        "High Point University",
        "High Point University Fred Wilson School of Pharmacy",
        "Hillsdale College",
        "Hiram College",
        "Hobart and William Smith Colleges",
        "Hofstra University",
        "Hollins University",
        "Holy Family University",
        "Hood College",
        "Hope College",
        "Houghton University",
        "Houston Baptist University",
        "Howard Payne University",
        "Howard University",
        "Howard University College of Pharmacy",
        "Humboldt State University",
        "Hunter College (CUNY)",
        "Huntingdon College",
        "Huntington University",
        "Husson University",
        "Husson University School of Pharmacy",
        "Huston-Tillotson University",
        "Idaho State University",
        "Idaho State University College of Pharmacy",
        "Illinois College",
        "Illinois Institute of Technology",
        "Illinois State University",
        "Illinois Wesleyan University",
        "Immaculata University",
        "Indiana State University",
        "Indiana University Bloomington",
        "Indiana University of Pennsylvania",
        "Indiana University–Purdue University Indianapolis (IUPUI)",
        "Indiana Wesleyan University",
        "Iona University",
        "Iowa State University",
        "Iowa Wesleyan University",
        "Ithaca College",
        "Jackson State University",
        "Jacksonville State University",
        "Jacksonville University",
        "James Madison University",
        "Jamestown University",
        "John Brown University",
        "John Carroll University",
        "Johns Hopkins University",
        "Johnson & Wales University",
        "Johnson C. Smith University",
        "Judson University",
        "Juniata College",
        "Kalamazoo College",
        "Kansas State University",
        "Kansas Wesleyan University",
        "Kean University",
        "Keene State College",
        "Keck Graduate Institute School of Pharmacy",
        "Kennesaw State University",
        "Kent State University",
        "Kentucky State University",
        "Kentucky Wesleyan College",
        "Kenyon College",
        "Kettering University",
        "Keuka College",
        "King University",
        "King's College (PA)",
        "Knox College",
        "Kutztown University of Pennsylvania",
        "La Roche University",
        "La Salle University",
        "La Sierra University",
        "Lafayette College",
        "LaGrange College",
        "Lake Erie College",
        "Lake Erie College of Osteopathic Medicine",
        "Lake Forest College",
        "Lake Superior State University",
        "Lamar University",
        "Lambuth University",
        "Lander University",
        "Lane College",
        "Langston University",
        "Larkin University College of Pharmacy",
        "Lawrence Technological University",
        "Lawrence University",
        "Le Moyne College",
        "Lebanon Valley College",
        "Lee University",
        "Lehigh University",
        "Lenoir-Rhyne University",
        "Lesley University",
        "LeTourneau University",
        "Lewis & Clark College",
        "Lewis University",
        "Liberty University",
        "Limestone University",
        "Lincoln Memorial University",
        "Lincoln University (MO)",
        "Lincoln University (PA)",
        "Lindenwood University",
        "Lindsey Wilson College",
        "Linfield University",
        "Lipscomb University",
        "Lipscomb University College of Pharmacy",
        "Livingstone College",
        "Lock Haven University of Pennsylvania",
        "Loma Linda University",
        "Loma Linda University School of Pharmacy",
        "Long Island University",
        "Longwood University",
        "Loras College",
        "Louisiana College",
        "Louisiana State University",
        "Louisiana Tech University",
        "Lourdes University",
        "Loyola Marymount University",
        "Loyola University Chicago",
        "Loyola University Maryland",
        "Loyola University New Orleans",
        "Lubbock Christian University",
        "Luther College",
        "Lycoming College",
        "Lynchburg University",
        "Lynn University",
        "Lyon College",
        "Macalester College",
        "MacMurray College",
        "Madonna University",
        "Malone University",
        "Manchester University",
        "Manchester University College of Pharmacy",
        "Manhattan College",
        "Manhattanville College",
        "Mansfield University of Pennsylvania",
        "Marian University (IN)",
        "Marian University (WI)",
        "Marietta College",
        "Marist College",
        "Marquette University",
        "Mars Hill University",
        "Marshall University",
        "Marshall University School of Pharmacy",
        "Martin Luther College",
        "Mary Baldwin University",
        "Maryland Institute College of Art",
        "Marymount Manhattan College",
        "Marymount University",
        "Maryville College",
        "Maryville University",
        "Marywood University",
        "Massachusetts College of Liberal Arts",
        "Massachusetts College of Pharmacy (MCPHS)",
        "Massachusetts Institute of Technology (MIT)",
        "Massachusetts Maritime Academy",
        "Mayo Clinic Alix School of Medicine",
        "McDaniel College",
        "McKendree University",
        "McNeese State University",
        "McPherson College",
        "Medaille University",
        "Medical University of South Carolina",
        "Mercer University",
        "Mercer University College of Pharmacy",
        "Mercy College",
        "Mercyhurst University",
        "Meredith College",
        "Merrimack College",
        "Mesa Community College",
        "Messiah University",
        "Methodist University",
        "Metropolitan State University",
        "Metropolitan State University of Denver",
        "Miami University (OH)",
        "Michigan State University",
        "Michigan Technological University",
        "MidAmerica Nazarene University",
        "Middle Tennessee State University",
        "Middlebury College",
        "Midland University",
        "Midwestern State University",
        "Midwestern University College of Pharmacy",
        "Miles College",
        "Millersville University of Pennsylvania",
        "Milligan University",
        "Millikin University",
        "Millsaps College",
        "Milwaukee School of Engineering",
        "Minnesota State University, Mankato",
        "Minnesota State University Moorhead",
        "Minot State University",
        "Misericordia University",
        "Mississippi College",
        "Mississippi State University",
        "Mississippi University for Women",
        "Mississippi Valley State University",
        "Missouri Southern State University",
        "Missouri State University",
        "Missouri University of Science and Technology",
        "Missouri Valley College",
        "Missouri Western State University",
        "Mitchell College",
        "Molloy University",
        "Monmouth College (IL)",
        "Monmouth University (NJ)",
        "Monroe College",
        "Montana State University",
        "Montana State University Billings",
        "Montana Tech",
        "Montclair State University",
        "Montevallo, University of",
        "Montreat College",
        "Moravian University",
        "Morehead State University",
        "Morehouse College",
        "Morgan State University",
        "Morningside University",
        "Morris College",
        "Mount Holyoke College",
        "Mount Marty University",
        "Mount Mercy University",
        "Mount Olive, University of",
        "Mount Saint Mary College",
        "Mount Saint Mary's University (CA)",
        "Mount St. Mary's University (MD)",
        "Mount Union, University of",
        "Mount Vernon Nazarene University",
        "Muhlenberg College",
        "Murray State University",
        "Muskingum University",
        "Naropa University",
        "National Louis University",
        "National University",
        "Nazareth University",
        "Nebraska Wesleyan University",
        "Neumann University",
        "New College of Florida",
        "New England College",
        "New Jersey City University",
        "New Jersey Institute of Technology",
        "New Mexico Highlands University",
        "New Mexico Institute of Mining and Technology",
        "New Mexico State University",
        "New School, The",
        "New York Institute of Technology",
        "New York University",
        "Newberry College",
        "Newman University",
        "Niagara University",
        "Nicholls State University",
        "Nichols College",
        "Norfolk State University",
        "North Carolina A&T State University",
        "North Carolina Central University",
        "North Carolina State University",
        "North Carolina Wesleyan University",
        "North Central College",
        "North Dakota State University",
        "North Dakota State University College of Pharmacy",
        "North Greenville University",
        "North Park University",
        "Northeastern Illinois University",
        "Northeastern State University",
        "Northeastern University",
        "Northeastern University School of Pharmacy",
        "Northern Arizona University",
        "Northern Illinois University",
        "Northern Iowa, University of",
        "Northern Kentucky University",
        "Northern Michigan University",
        "Northern State University",
        "Northland College",
        "Northwest Missouri State University",
        "Northwest Nazarene University",
        "Northwest University",
        "Northwestern College (IA)",
        "Northwestern Oklahoma State University",
        "Northwestern State University",
        "Northwestern University",
        "Northwood University",
        "Norwich University",
        "Notre Dame College",
        "Notre Dame of Maryland University",
        "Nova Southeastern University",
        "Nova Southeastern University College of Pharmacy",
        "Nyack College",
        "Oakland City University",
        "Oakland University",
        "Oberlin College",
        "Occidental College",
        "Oglethorpe University",
        "Ohio Dominican University",
        "Ohio Northern University",
        "Ohio Northern University College of Pharmacy",
        "Ohio State University",
        "Ohio State University College of Pharmacy",
        "Ohio University",
        "Ohio Wesleyan University",
        "Oklahoma Baptist University",
        "Oklahoma Christian University",
        "Oklahoma City University",
        "Oklahoma Panhandle State University",
        "Oklahoma State University",
        "Old Dominion University",
        "Olivet College",
        "Olivet Nazarene University",
        "Oral Roberts University",
        "Oregon Health & Science University",
        "Oregon Institute of Technology",
        "Oregon State University",
        "Oregon State University College of Pharmacy",
        "Otterbein University",
        "Ouachita Baptist University",
        "Our Lady of the Lake University",
        "Pace University",
        "Pacific Lutheran University",
        "Pacific University",
        "Pacific University School of Pharmacy",
        "Palm Beach Atlantic University",
        "Park University",
        "Paul Quinn College",
        "Paul Smith's College",
        "Peirce College",
        "Pennsylvania State University",
        "Pepperdine University",
        "Peru State College",
        "Pfeiffer University",
        "Philadelphia College of Osteopathic Medicine",
        "Philander Smith College",
        "Piedmont University",
        "Pittsburg State University",
        "Pitzer College",
        "Plymouth State University",
        "Point Loma Nazarene University",
        "Point Park University",
        "Pomona College",
        "Portland State University",
        "Post University",
        "Prairie View A&M University",
        "Pratt Institute",
        "Presbyterian College",
        "Presbyterian College School of Pharmacy",
        "Princeton University",
        "Providence College",
        "Purdue University",
        "Purdue University College of Pharmacy",
        "Purdue University Fort Wayne",
        "Purdue University Northwest",
        "Queens University of Charlotte",
        "Quincy University",
        "Quinnipiac University",
        "Radford University",
        "Ramapo College of New Jersey",
        "Randolph College",
        "Randolph-Macon College",
        "Regis College (MA)",
        "Regis University",
        "Regis University School of Pharmacy",
        "Reinhardt University",
        "Rensselaer Polytechnic Institute",
        "Rhode Island College",
        "Rhodes College",
        "Rice University",
        "Rider University",
        "Ripon College",
        "Roanoke College",
        "Robert Morris University",
        "Roberts Wesleyan University",
        "Rochester Institute of Technology",
        "Rockhurst University",
        "Rocky Mountain College",
        "Rollins College",
        "Roosevelt University",
        "Roosevelt University College of Pharmacy",
        "Rosalind Franklin University",
        "Rose-Hulman Institute of Technology",
        "Roseman University College of Pharmacy",
        "Rowan University",
        "Rush University",
        "Russell Sage College",
        "Rust College",
        "Rutgers University",
        "Rutgers University Ernest Mario School of Pharmacy",
        "Sacred Heart University",
        "Saginaw Valley State University",
        "Saint Ambrose University",
        "Saint Anselm College",
        "Saint Augustine's University",
        "Saint Benedict, College of",
        "Saint Bonaventure University",
        "Saint Edward's University",
        "Saint Francis University",
        "Saint John Fisher University",
        "Saint John's University (MN)",
        "Saint Joseph's College (ME)",
        "Saint Joseph's University (PA)",
        "Saint Lawrence University",
        "Saint Leo University",
        "Saint Louis College of Pharmacy (UHSP)",
        "Saint Louis University",
        "Saint Martin's University",
        "Saint Mary-of-the-Woods College",
        "Saint Mary's College (IN)",
        "Saint Mary's College of California",
        "Saint Mary's University (TX)",
        "Saint Mary's University of Minnesota",
        "Saint Michael's College",
        "Saint Norbert College",
        "Saint Olaf College",
        "Saint Peter's University",
        "Saint Thomas Aquinas College",
        "Saint Vincent College",
        "Saint Xavier University",
        "Salem College",
        "Salem State University",
        "Salisbury University",
        "Salve Regina University",
        "Sam Houston State University",
        "Samford University",
        "Samford University McWhorter School of Pharmacy",
        "San Diego State University",
        "San Francisco State University",
        "San Jose State University",
        "Santa Clara University",
        "Sarah Lawrence College",
        "Savannah College of Art and Design",
        "Savannah State University",
        "Schreiner University",
        "Scripps College",
        "Seattle Pacific University",
        "Seattle University",
        "Seton Hall University",
        "Seton Hill University",
        "Sewanee: University of the South",
        "Shaw University",
        "Shenandoah University",
        "Shenandoah University School of Pharmacy",
        "Shepherd University",
        "Shippensburg University of Pennsylvania",
        "Shorter University",
        "Siena College",
        "Siena Heights University",
        "Simmons University",
        "Simpson College",
        "Skidmore College",
        "Slippery Rock University of Pennsylvania",
        "Smith College",
        "Sonoma State University",
        "South Alabama, University of",
        "South Carolina College of Pharmacy (USC)",
        "South Carolina State University",
        "South Dakota School of Mines and Technology",
        "South Dakota State University",
        "South Dakota State University College of Pharmacy",
        "South University School of Pharmacy",
        "Southeast Missouri State University",
        "Southeastern Louisiana University",
        "Southeastern Oklahoma State University",
        "Southeastern University (FL)",
        "Southern Adventist University",
        "Southern Arkansas University",
        "Southern Connecticut State University",
        "Southern Illinois University Carbondale",
        "Southern Illinois University Edwardsville",
        "Southern Indiana, University of",
        "Southern Methodist University",
        "Southern Mississippi, University of",
        "Southern Nazarene University",
        "Southern New Hampshire University",
        "Southern Oregon University",
        "Southern University and A&M College",
        "Southern Utah University",
        "Southern Virginia University",
        "Southern Wesleyan University",
        "Southwest Baptist University",
        "Southwest College of Naturopathic Medicine",
        "Southwest Minnesota State University",
        "Southwestern Adventist University",
        "Southwestern College (KS)",
        "Southwestern Oklahoma State University",
        "Southwestern University (TX)",
        "Spelman College",
        "Spring Arbor University",
        "Spring Hill College",
        "Springfield College",
        "St. Ambrose University",
        "St. Bonaventure University",
        "St. Cloud State University",
        "St. John's University (NY)",
        "St. John's University College of Pharmacy",
        "St. Thomas, University of (MN)",
        "St. Thomas, University of (TX)",
        "Stanford University",
        "Stephen F. Austin State University",
        "Sterling College",
        "Stetson University",
        "Stevens Institute of Technology",
        "Stevenson University",
        "Stillman College",
        "Stockton University",
        "Stonehill College",
        "Stony Brook University (SUNY)",
        "Suffolk University",
        "Sul Ross State University",
        "Sullivan University College of Pharmacy",
        "Susquehanna University",
        "Swarthmore College",
        "Sweet Briar College",
        "Syracuse University",
        "Tabor College",
        "Talladega College",
        "Tampa, University of",
        "Tarleton State University",
        "Taylor University",
        "Temple University",
        "Temple University School of Pharmacy",
        "Tennessee State University",
        "Tennessee Technological University",
        "Tennessee Wesleyan University",
        "Texas A&M University",
        "Texas A&M University–Commerce",
        "Texas A&M University–Corpus Christi",
        "Texas A&M University–Kingsville",
        "Texas Christian University",
        "Texas Lutheran University",
        "Texas Southern University",
        "Texas Southern University College of Pharmacy",
        "Texas State University",
        "Texas Tech University",
        "Texas Tech University Health Sciences Center",
        "Texas Wesleyan University",
        "Texas Woman's University",
        "Thomas College",
        "Thomas Jefferson University",
        "Thomas More University",
        "Tiffin University",
        "Toccoa Falls College",
        "Touro College of Pharmacy",
        "Touro University",
        "Towson University",
        "Transylvania University",
        "Trevecca Nazarene University",
        "Trine University",
        "Trinity Christian College",
        "Trinity College (CT)",
        "Trinity University (TX)",
        "Troy University",
        "Truman State University",
        "Tufts University",
        "Tulane University",
        "Tulsa, University of",
        "Tuskegee University",
        "UNC Eshelman School of Pharmacy",
        "Union College (KY)",
        "Union College (NY)",
        "Union University",
        "Union University School of Pharmacy",
        "United States Air Force Academy",
        "United States Military Academy (West Point)",
        "United States Naval Academy",
        "University at Albany (SUNY)",
        "University at Buffalo (SUNY)",
        "University of Akron",
        "University of Alabama",
        "University of Alabama at Birmingham",
        "University of Alabama in Huntsville",
        "University of Alaska Anchorage",
        "University of Alaska Fairbanks",
        "University of Arizona",
        "University of Arizona College of Pharmacy",
        "University of Arkansas",
        "University of Arkansas at Little Rock",
        "University of Arkansas at Pine Bluff",
        "University of Arkansas for Medical Sciences",
        "University of Baltimore",
        "University of Bridgeport",
        "University of Buffalo School of Pharmacy",
        "University of California, Berkeley",
        "University of California, Davis",
        "University of California, Irvine",
        "University of California, Los Angeles (UCLA)",
        "University of California, Merced",
        "University of California, Riverside",
        "University of California, San Diego (UCSD)",
        "University of California, San Francisco (UCSF)",
        "University of California, Santa Barbara",
        "University of California, Santa Cruz",
        "University of Central Arkansas",
        "University of Central Florida",
        "University of Central Missouri",
        "University of Central Oklahoma",
        "University of Charleston",
        "University of Chicago",
        "University of Cincinnati",
        "University of Cincinnati College of Pharmacy",
        "University of Colorado Boulder",
        "University of Colorado Colorado Springs",
        "University of Colorado Denver",
        "University of Connecticut",
        "University of Connecticut School of Pharmacy",
        "University of Dallas",
        "University of Dayton",
        "University of Delaware",
        "University of Denver",
        "University of Detroit Mercy",
        "University of Evansville",
        "University of Findlay",
        "University of Florida",
        "University of Florida College of Pharmacy",
        "University of Georgia",
        "University of Georgia College of Pharmacy",
        "University of Hartford",
        "University of Hawaii at Hilo",
        "University of Hawaii at Hilo College of Pharmacy",
        "University of Hawaii at Manoa",
        "University of Houston",
        "University of Houston College of Pharmacy",
        "University of Houston–Clear Lake",
        "University of Houston–Downtown",
        "University of Idaho",
        "University of Illinois Chicago",
        "University of Illinois Chicago College of Pharmacy",
        "University of Illinois Urbana-Champaign",
        "University of Indianapolis",
        "University of Iowa",
        "University of Iowa College of Pharmacy",
        "University of Kansas",
        "University of Kansas School of Pharmacy",
        "University of Kentucky",
        "University of Kentucky College of Pharmacy",
        "University of Louisiana at Lafayette",
        "University of Louisiana at Monroe",
        "University of Louisiana at Monroe College of Pharmacy",
        "University of Louisville",
        "University of Lynchburg",
        "University of Maine",
        "University of Maine at Farmington",
        "University of Maine at Machias",
        "University of Mary",
        "University of Mary Hardin-Baylor",
        "University of Mary Washington",
        "University of Maryland, Baltimore County",
        "University of Maryland, College Park",
        "University of Maryland School of Pharmacy",
        "University of Massachusetts Amherst",
        "University of Massachusetts Boston",
        "University of Massachusetts Dartmouth",
        "University of Massachusetts Lowell",
        "University of Memphis",
        "University of Miami",
        "University of Michigan",
        "University of Michigan College of Pharmacy",
        "University of Minnesota Duluth",
        "University of Minnesota Twin Cities",
        "University of Minnesota College of Pharmacy",
        "University of Mississippi",
        "University of Mississippi School of Pharmacy",
        "University of Missouri",
        "University of Missouri-Kansas City",
        "University of Missouri-Kansas City School of Pharmacy",
        "University of Missouri-St. Louis",
        "University of Mobile",
        "University of Montana",
        "University of Montevallo",
        "University of Mount Union",
        "University of Nebraska at Kearney",
        "University of Nebraska at Omaha",
        "University of Nebraska–Lincoln",
        "University of Nebraska Medical Center",
        "University of Nebraska Medical Center College of Pharmacy",
        "University of Nevada, Las Vegas",
        "University of Nevada, Reno",
        "University of New England",
        "University of New England College of Pharmacy",
        "University of New Hampshire",
        "University of New Haven",
        "University of New Mexico",
        "University of New Mexico College of Pharmacy",
        "University of New Orleans",
        "University of North Alabama",
        "University of North Carolina at Asheville",
        "University of North Carolina at Chapel Hill",
        "University of North Carolina at Charlotte",
        "University of North Carolina at Greensboro",
        "University of North Carolina at Pembroke",
        "University of North Carolina Wilmington",
        "University of North Dakota",
        "University of North Florida",
        "University of North Georgia",
        "University of North Texas",
        "University of North Texas Health Science Center",
        "University of Northern Colorado",
        "University of Northern Iowa",
        "University of Northwestern Ohio",
        "University of Notre Dame",
        "University of Oklahoma",
        "University of Oklahoma College of Pharmacy",
        "University of Oregon",
        "University of the Ozarks",
        "University of the Pacific",
        "University of the Pacific Thomas J. Long School of Pharmacy",
        "University of Pennsylvania",
        "University of Pittsburgh",
        "University of Pittsburgh School of Pharmacy",
        "University of Portland",
        "University of Providence",
        "University of Puget Sound",
        "University of Redlands",
        "University of Rhode Island",
        "University of Rhode Island College of Pharmacy",
        "University of Richmond",
        "University of Rio Grande",
        "University of Rochester",
        "University of San Diego",
        "University of San Francisco",
        "University of the Sciences (Saint Joseph's)",
        "University of Scranton",
        "University of Sioux Falls",
        "University of South Alabama",
        "University of South Carolina",
        "University of South Dakota",
        "University of South Florida",
        "University of Southern California",
        "University of Southern California School of Pharmacy",
        "University of Southern Indiana",
        "University of Southern Maine",
        "University of Southern Mississippi",
        "University of St. Francis",
        "University of Tampa",
        "University of Tennessee at Chattanooga",
        "University of Tennessee at Martin",
        "University of Tennessee, Knoxville",
        "University of Tennessee College of Pharmacy",
        "University of Texas at Arlington",
        "University of Texas at Austin",
        "University of Texas at Austin College of Pharmacy",
        "University of Texas at Dallas",
        "University of Texas at El Paso",
        "University of Texas at San Antonio",
        "University of Texas at Tyler",
        "University of Texas Health Science Center at Houston",
        "University of Texas Health Science Center at San Antonio",
        "University of Texas Rio Grande Valley",
        "University of the Cumberlands",
        "University of the Incarnate Word",
        "University of Toledo",
        "University of Toledo College of Pharmacy",
        "University of Tulsa",
        "University of Utah",
        "University of Utah College of Pharmacy",
        "University of Vermont",
        "University of Virginia",
        "University of Washington",
        "University of Washington School of Pharmacy",
        "University of West Alabama",
        "University of West Florida",
        "University of West Georgia",
        "University of Western States",
        "University of Wisconsin–Eau Claire",
        "University of Wisconsin–Green Bay",
        "University of Wisconsin–La Crosse",
        "University of Wisconsin–Madison",
        "University of Wisconsin–Madison School of Pharmacy",
        "University of Wisconsin–Milwaukee",
        "University of Wisconsin–Oshkosh",
        "University of Wisconsin–Parkside",
        "University of Wisconsin–Platteville",
        "University of Wisconsin–River Falls",
        "University of Wisconsin–Stevens Point",
        "University of Wisconsin–Stout",
        "University of Wisconsin–Superior",
        "University of Wisconsin–Whitewater",
        "University of Wyoming",
        "University of Wyoming School of Pharmacy",
        "Upper Iowa University",
        "Ursinus College",
        "Ursuline College",
        "Utah State University",
        "Utah Tech University",
        "Utah Valley University",
        "Utica University",
        "Valdosta State University",
        "Valley City State University",
        "Valparaiso University",
        "Vanderbilt University",
        "Vassar College",
        "Vaughn College",
        "Vermont, University of",
        "Villanova University",
        "Virginia Commonwealth University",
        "Virginia Commonwealth University School of Pharmacy",
        "Virginia Military Institute",
        "Virginia Polytechnic Institute and State University (Virginia Tech)",
        "Virginia State University",
        "Virginia Union University",
        "Virginia Wesleyan University",
        "Viterbo University",
        "Wabash College",
        "Wagner College",
        "Wake Forest University",
        "Walla Walla University",
        "Walsh University",
        "Warner University",
        "Warren Wilson College",
        "Wartburg College",
        "Washburn University",
        "Washington & Jefferson College",
        "Washington & Lee University",
        "Washington College",
        "Washington State University",
        "Washington State University College of Pharmacy",
        "Washington University in St. Louis",
        "Wayland Baptist University",
        "Wayne State College (NE)",
        "Wayne State University",
        "Waynesburg University",
        "Webb Institute",
        "Weber State University",
        "Webster University",
        "Wellesley College",
        "Wells College",
        "Wentworth Institute of Technology",
        "Wesley College",
        "Wesleyan College (GA)",
        "Wesleyan University (CT)",
        "West Chester University of Pennsylvania",
        "West Liberty University",
        "West Texas A&M University",
        "West Virginia State University",
        "West Virginia University",
        "West Virginia University School of Pharmacy",
        "West Virginia Wesleyan College",
        "Western Carolina University",
        "Western Colorado, University of",
        "Western Connecticut State University",
        "Western Illinois University",
        "Western Kentucky University",
        "Western Michigan University",
        "Western New England University",
        "Western New England University College of Pharmacy",
        "Western New Mexico University",
        "Western Oregon University",
        "Western State Colorado University",
        "Western University of Health Sciences",
        "Western Washington University",
        "Westfield State University",
        "Westminster College (MO)",
        "Westminster College (PA)",
        "Westminster College (UT)",
        "Westmont College",
        "Wheaton College (IL)",
        "Wheaton College (MA)",
        "Wheeling University",
        "Whitman College",
        "Whittier College",
        "Whitworth University",
        "Wichita State University",
        "Widener University",
        "Wilberforce University",
        "Wiley College",
        "Wilkes University",
        "Wilkes University School of Pharmacy",
        "Willamette University",
        "William Carey University",
        "William Carey University School of Pharmacy",
        "William Jewell College",
        "William Paterson University",
        "William Peace University",
        "William Woods University",
        "Williams College",
        "Wilmington College",
        "Wilmington University",
        "Wilson College",
        "Wingate University",
        "Wingate University School of Pharmacy",
        "Winona State University",
        "Winston-Salem State University",
        "Winthrop University",
        "Wittenberg University",
        "Wofford College",
        "Woodbury University",
        "Worcester Polytechnic Institute",
        "Worcester State University",
        "Wright State University",
        "Xavier University (OH)",
        "Xavier University of Louisiana",
        "Xavier University of Louisiana College of Pharmacy",
        "Yale University",
        "York College of Pennsylvania",
        "Young Harris College",
        "Youngstown State University",

        // CANADA
        "Acadia University (Canada)",
        "Algoma University (Canada)",
        "Athabasca University (Canada)",
        "Bishop's University (Canada)",
        "Brandon University (Canada)",
        "Brock University (Canada)",
        "Cape Breton University (Canada)",
        "Carleton University (Canada)",
        "Concordia University (Canada)",
        "Concordia University of Edmonton (Canada)",
        "Dalhousie University (Canada)",
        "Emily Carr University of Art + Design (Canada)",
        "Kwantlen Polytechnic University (Canada)",
        "Lakehead University (Canada)",
        "Laurentian University (Canada)",
        "Laval University (Canada)",
        "MacEwan University (Canada)",
        "McGill University (Canada)",
        "McMaster University (Canada)",
        "Memorial University of Newfoundland (Canada)",
        "Mount Allison University (Canada)",
        "Mount Royal University (Canada)",
        "Mount Saint Vincent University (Canada)",
        "Nipissing University (Canada)",
        "OCAD University (Canada)",
        "Ontario Tech University (Canada)",
        "Queen's University (Canada)",
        "Royal Roads University (Canada)",
        "Ryerson University / Toronto Metropolitan University (Canada)",
        "Saint Francis Xavier University (Canada)",
        "Saint Mary's University (Canada)",
        "Simon Fraser University (Canada)",
        "St. Thomas University (Canada)",
        "Thompson Rivers University (Canada)",
        "Trent University (Canada)",
        "Trinity Western University (Canada)",
        "University of Alberta (Canada)",
        "University of British Columbia (Canada)",
        "University of Calgary (Canada)",
        "University of Guelph (Canada)",
        "University of King's College (Canada)",
        "University of Lethbridge (Canada)",
        "University of Manitoba (Canada)",
        "University of Montreal (Canada)",
        "University of New Brunswick (Canada)",
        "University of Northern British Columbia (Canada)",
        "University of Ontario Institute of Technology (Canada)",
        "University of Ottawa (Canada)",
        "University of Prince Edward Island (Canada)",
        "University of Regina (Canada)",
        "University of Saskatchewan (Canada)",
        "University of Sherbrooke (Canada)",
        "University of the Fraser Valley (Canada)",
        "University of Toronto (Canada)",
        "University of Victoria (Canada)",
        "University of Waterloo (Canada)",
        "University of Western Ontario (Canada)",
        "University of Windsor (Canada)",
        "University of Winnipeg (Canada)",
        "Vancouver Island University (Canada)",
        "Wilfrid Laurier University (Canada)",
        "York University (Canada)",
    ]
}
