import Foundation

nonisolated enum UniversityData {
    static let schools: [String] = [
        "Albany College of Pharmacy and Health Sciences",
        "Auburn University Harrison College of Pharmacy",
        "Baylor College of Medicine",
        "Belmont University College of Pharmacy",
        "Boston University",
        "Brigham Young University",
        "Brown University",
        "Butler University College of Pharmacy",
        "California Northstate University",
        "Campbell University College of Pharmacy",
        "Cedarville University School of Pharmacy",
        "Chapman University School of Pharmacy",
        "Chicago State University College of Pharmacy",
        "Clemson University",
        "Columbia University",
        "Concordia University Wisconsin",
        "Cornell University",
        "Creighton University School of Pharmacy",
        "D'Youville University School of Pharmacy",
        "Drake University College of Pharmacy",
        "Drexel University College of Medicine",
        "Duke University",
        "Duquesne University School of Pharmacy",
        "East Tennessee State University",
        "Emory University",
        "Fairleigh Dickinson University School of Pharmacy",
        "Ferris State University College of Pharmacy",
        "Florida A&M University College of Pharmacy",
        "Georgetown University",
        "George Washington University",
        "Hampton University School of Pharmacy",
        "Harvard University",
        "High Point University Fred Wilson School of Pharmacy",
        "Howard University College of Pharmacy",
        "Husson University School of Pharmacy",
        "Idaho State University College of Pharmacy",
        "Indiana University",
        "Johns Hopkins University",
        "Keck Graduate Institute School of Pharmacy",
        "Lake Erie College of Osteopathic Medicine",
        "Larkin University College of Pharmacy",
        "Lipscomb University College of Pharmacy",
        "Loma Linda University School of Pharmacy",
        "Long Island University",
        "Louisiana State University",
        "Manchester University College of Pharmacy",
        "Marshall University School of Pharmacy",
        "Massachusetts College of Pharmacy (MCPHS)",
        "Mayo Clinic Alix School of Medicine",
        "Medical University of South Carolina",
        "Mercer University College of Pharmacy",
        "Midwestern University College of Pharmacy",
        "Mississippi State University",
        "New York University",
        "North Dakota State University College of Pharmacy",
        "Northeastern University School of Pharmacy",
        "Northwestern University",
        "Nova Southeastern University College of Pharmacy",
        "Ohio Northern University College of Pharmacy",
        "Ohio State University College of Pharmacy",
        "Oregon State University College of Pharmacy",
        "Pacific University School of Pharmacy",
        "Palm Beach Atlantic University",
        "Philadelphia College of Osteopathic Medicine",
        "Presbyterian College School of Pharmacy",
        "Purdue University College of Pharmacy",
        "Regis University School of Pharmacy",
        "Roosevelt University College of Pharmacy",
        "Rosalind Franklin University",
        "Roseman University College of Pharmacy",
        "Rush University",
        "Rutgers University Ernest Mario School of Pharmacy",
        "Saint John Fisher University",
        "Saint Joseph's University",
        "Saint Louis College of Pharmacy (UHSP)",
        "Samford University McWhorter School of Pharmacy",
        "Shenandoah University School of Pharmacy",
        "South Carolina College of Pharmacy (USC)",
        "South Dakota State University College of Pharmacy",
        "South University School of Pharmacy",
        "Southern Illinois University Edwardsville",
        "Southwest College of Naturopathic Medicine",
        "Stanford University",
        "St. John's University College of Pharmacy",
        "Sullivan University College of Pharmacy",
        "Temple University School of Pharmacy",
        "Texas A&M University",
        "Texas Southern University College of Pharmacy",
        "Texas Tech University Health Sciences Center",
        "Thomas Jefferson University",
        "Touro College of Pharmacy",
        "Tulane University",
        "UNC Eshelman School of Pharmacy",
        "Union University School of Pharmacy",
        "University of Alabama at Birmingham",
        "University of Arizona College of Pharmacy",
        "University of Arkansas for Medical Sciences",
        "University of Buffalo School of Pharmacy",
        "University of California, Davis",
        "University of California, Irvine",
        "University of California, Los Angeles (UCLA)",
        "University of California, San Diego (UCSD)",
        "University of California, San Francisco (UCSF)",
        "University of Central Florida",
        "University of Chicago",
        "University of Cincinnati College of Pharmacy",
        "University of Colorado",
        "University of Connecticut School of Pharmacy",
        "University of Florida College of Pharmacy",
        "University of Georgia College of Pharmacy",
        "University of Hawaii at Hilo College of Pharmacy",
        "University of Houston College of Pharmacy",
        "University of Illinois Chicago College of Pharmacy",
        "University of Iowa College of Pharmacy",
        "University of Kansas School of Pharmacy",
        "University of Kentucky College of Pharmacy",
        "University of Louisiana at Monroe College of Pharmacy",
        "University of Louisville",
        "University of Maryland School of Pharmacy",
        "University of Michigan College of Pharmacy",
        "University of Minnesota College of Pharmacy",
        "University of Mississippi School of Pharmacy",
        "University of Missouri-Kansas City School of Pharmacy",
        "University of Montana",
        "University of Nebraska Medical Center College of Pharmacy",
        "University of New England College of Pharmacy",
        "University of New Mexico College of Pharmacy",
        "University of North Texas Health Science Center",
        "University of Oklahoma College of Pharmacy",
        "University of Oregon",
        "University of Pennsylvania",
        "University of Pittsburgh School of Pharmacy",
        "University of Rhode Island College of Pharmacy",
        "University of Rochester",
        "University of South Carolina",
        "University of South Florida",
        "University of Southern California School of Pharmacy",
        "University of Tennessee College of Pharmacy",
        "University of Texas at Austin College of Pharmacy",
        "University of Texas Health Science Center at San Antonio",
        "University of the Incarnate Word",
        "University of the Pacific Thomas J. Long School of Pharmacy",
        "University of the Sciences (Saint Joseph's)",
        "University of Toledo College of Pharmacy",
        "University of Utah College of Pharmacy",
        "University of Virginia",
        "University of Washington School of Pharmacy",
        "University of Wisconsin-Madison School of Pharmacy",
        "University of Wyoming School of Pharmacy",
        "Vanderbilt University",
        "Virginia Commonwealth University School of Pharmacy",
        "Washington State University College of Pharmacy",
        "Wayne State University",
        "West Virginia University School of Pharmacy",
        "Western New England University College of Pharmacy",
        "Western University of Health Sciences",
        "Wilkes University School of Pharmacy",
        "William Carey University School of Pharmacy",
        "Wingate University School of Pharmacy",
        "Xavier University of Louisiana College of Pharmacy",
        "Yale University",
        "Dalhousie University (Canada)",
        "Laval University (Canada)",
        "Memorial University of Newfoundland (Canada)",
        "University of Alberta (Canada)",
        "University of British Columbia (Canada)",
        "University of Manitoba (Canada)",
        "University of Montreal (Canada)",
        "University of Ottawa (Canada)",
        "University of Saskatchewan (Canada)",
        "University of Toronto (Canada)",
        "University of Waterloo (Canada)",
        "University of Western Ontario (Canada)",
        "McGill University (Canada)",
        "McMaster University (Canada)",
        "Queen's University (Canada)",
    ]
}
