// Config.swift - Auto-generated at build time
// Virtual read-only view of public environment variables available to Swift code

import Foundation

enum Config {
    static let EXPO_PUBLIC_ADMOB_APP_ID = ""
    static let EXPO_PUBLIC_ADMOB_REWARDED_AD_UNIT_ID = ""
    static let EXPO_PUBLIC_PROJECT_ID = ""
    static let EXPO_PUBLIC_REVENUECAT_IOS_API_KEY = ""
    static let EXPO_PUBLIC_REVENUECAT_TEST_API_KEY = ""
    static let EXPO_PUBLIC_RORK_API_BASE_URL = ""
    static let EXPO_PUBLIC_RORK_AUTH_URL = ""
    static let EXPO_PUBLIC_SUPABASE_ANON_KEY = ""
    static let EXPO_PUBLIC_SUPABASE_URL = ""
    static let EXPO_PUBLIC_TEAM_ID = ""
    static let EXPO_PUBLIC_TOOLKIT_URL = ""

    static let allValues: [String: String] = [
        "EXPO_PUBLIC_ADMOB_APP_ID": EXPO_PUBLIC_ADMOB_APP_ID,
        "EXPO_PUBLIC_ADMOB_REWARDED_AD_UNIT_ID": EXPO_PUBLIC_ADMOB_REWARDED_AD_UNIT_ID,
        "EXPO_PUBLIC_PROJECT_ID": EXPO_PUBLIC_PROJECT_ID,
        "EXPO_PUBLIC_REVENUECAT_IOS_API_KEY": EXPO_PUBLIC_REVENUECAT_IOS_API_KEY,
        "EXPO_PUBLIC_REVENUECAT_TEST_API_KEY": EXPO_PUBLIC_REVENUECAT_TEST_API_KEY,
        "EXPO_PUBLIC_RORK_API_BASE_URL": EXPO_PUBLIC_RORK_API_BASE_URL,
        "EXPO_PUBLIC_RORK_AUTH_URL": EXPO_PUBLIC_RORK_AUTH_URL,
        "EXPO_PUBLIC_SUPABASE_ANON_KEY": EXPO_PUBLIC_SUPABASE_ANON_KEY,
        "EXPO_PUBLIC_SUPABASE_URL": EXPO_PUBLIC_SUPABASE_URL,
        "EXPO_PUBLIC_TEAM_ID": EXPO_PUBLIC_TEAM_ID,
        "EXPO_PUBLIC_TOOLKIT_URL": EXPO_PUBLIC_TOOLKIT_URL,
    ]
}
